### PR TITLE
fix(client): runtime browser-build

### LINKED ISSUE #4465: Export Decimal in Browser Build

### PR DESCRIPTION
**Pull request by williamluke4**
fixes #4465

### CODE REVIEW

**Review by timsuchanek — APPROVED** [review]

**Comment by timsuchanek** [comment]
Please link to the issue this is fixing :)

File: src/packages/client/fixtures/generate.ts [hunk 1]
```diff
@@ -10,9 +10,6 @@ async function main() {
       '--skip-transpile': Boolean,
       '--built-runtime': Boolean,
     },
```
Comment (williamluke4) [inline src/packages/client/fixtures/generate.ts:12]: Should I revert this?

File: src/packages/engine-core/src/NodeEngine.ts [hunk 2]
```diff
@@ -9,6 +9,7 @@ import execa from 'execa'
 import fs from 'fs'
 import net from 'net'
 import pRetry from 'p-retry'
+import fetch from 'cross-fetch'
```
Comment (williamluke4) [inline src/packages/engine-core/src/NodeEngine.ts:12]: This had to be added as `new URL`(on L221) fails as the `BrowserEngine` was removed. I'm pretty sure this could also be achieved by adding "DOM" to tsconfig.

File: src/packages/client/fixtures/generate.ts (hunk 1 above)
Comment (timsuchanek) [reply src/packages/client/fixtures/generate.ts:12]: Nope, that's ok
