### PR TITLE
fix(client): use correct $-names in error messages

### LINKED ISSUE #9388: Missing `$` from `executeRaw` in error message "Invalid \`prisma.executeRaw()\` invocation:"
Take this example from https://github.com/prisma/prisma/blob/2b6319588bd384a1ca37d0022879ca589d974bd9/packages/client/src/__tests__/integration/happy/interactive-transactions/test.ts#L325

```ts
      await prisma.$executeRaw`INSERT INTO User (id, email) VALUES ("1", "user_1@website.com")`,
      await prisma.$executeRaw`INSERT INTO User (id, email) VALUES ("1", "user_1@website.com")`,
```

It will throw:

```
Invalid \`prisma.executeRaw()\` invocation:


  Raw query failed. Code: \`2067\`. Message: \`UNIQUE constraint failed: User.email\`
`)
```

The $ is required now in front of `executeRaw` (we used to support without the $ at some point)

Here the small fix would be to add the $ like `prisma.$executeRaw()` in the error message.

This probably also applies to `queryRaw`.

### PR DESCRIPTION
**Pull request by SevInf**
In error messages, `$queryRaw` and `$executeRaw` methods used to be
reported without leading $

Fixes #9388

### CODE REVIEW

File: packages/client/src/__tests__/integration/happy/interactive-transactions-postgres/test.ts [hunk 1]
```diff
@@ -192,15 +192,15 @@ describe('interactive transactions', () => {
 
     await expect(result).rejects.toThrowErrorMatchingInlineSnapshot(`
 
-                                    Invalid \`prisma.user.create()\` invocation in
-                                    /client/src/__tests__/integration/happy/interactive-transactions-postgres/test.ts:0:0
+                                                Invalid \`prisma.user.create()\` invocation in
```
Comment (SevInf) [inline packages/client/src/__tests__/integration/happy/interactive-transactions-postgres/test.ts:195]: I am not quite sure why those snapshots were updated, tbh. Should it be like that?

Comment (janpio) [reply packages/client/src/__tests__/integration/happy/interactive-transactions-postgres/test.ts:195]: Long standing problem with the snapshots generation: https://github.com/prisma/prisma/issues/8031

We should probably rename and expand that.

**Review by janpio — APPROVED** [review]

**Review by millsp — APPROVED** [review]

**Review by aqrln — APPROVED** [review]

File: packages/client/src/__tests__/integration/happy/interactive-transactions-postgres/test.ts (hunk 1 above)
Comment (aqrln) [reply packages/client/src/__tests__/integration/happy/interactive-transactions-postgres/test.ts:195]: It's a known issue, yes. You may revert unrelated changes if you want to minimize churn, or you may leave it as is, either way is fine.
