### PR TITLE
fix(client): Allow to use `Check`, `Has` and `Promise` as model names

### LINKED ISSUE #9669: Duplicate identifier 'CheckSelect'
### Bug description

I have a model in my prisma schema called `Check` which looks like it causes prisma to generate conflicting types.

In `.prisma/client/index.ts` I am getting a typescript warning as there are 2 `CheckSelect` types:
```typescript
  type CheckSelect<T, S, U> = T extends SelectAndInclude
    ? 'Please either choose `select` or `include`'
    : T extends HasSelect
    ? U
    : T extends HasInclude
    ? U
    : S
  export type CheckSelect = {
    id?: boolean
    name?: boolean
    checkType?: boolean
  }
```
image

### How to reproduce

1. Add a `Check` model to prisma.schema
2. run `prisma generate`
3. See error

I dont think there is anything complicated going on here.

### Expected behavior

I would expect prisma to either warn me that I cannot create a model called `Check` or handle the conflict in another way.

### Prisma information

I think this can be replicated with something as simple as this:
```
model Check {
  id          String        @id @default(uuid())
}
```

### Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js version: 14

### Prisma Version

```
prisma                  : 3.0.2
@prisma/client          : 3.0.2
Current platform        : windows
Query Engine (Node-API) : libquery-engine 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 2452cc6313d52b8b9a96999ac0e974d0aedf88db
Studio                  : 0.423.0
```

### LINKED ISSUE #12469: Certain `model` names cause clashes in generated types
### Bug description

**existing issues**
- #12332 
- #10490
- #9773
- #9669
- #9568, #7518

The following are all exported types from the `index.d.ts` and will cause clashes if they have corresponding `models` in the Prisma schema.

- PrismaPromise
- PrismaVersion
- JsonObject
- JsonValue
- InputJsonObject
- InputJsonValue
- PromiseType
- PromiseReturnType
- Enumerable
- RequiredKeys
- TruthyKeys
- TrueKeys
- Subset
- SelectSubset
- SubsetIntersection
- UnEnumerate
- Union 
- IntersectOf
- Overwrite
- At
- ComputeRaw
- OptionalFlat
- Strict
- Merge
- Boolean 
- True 
- False 
- Not
- Extends
- Has
- Or
- Keys
- GetScalarType
- ModelName 
- Datasources
- RejectOnNotFound 
- RejectPerModel
- RejectPerOperation 
- HasReject
- ErrorFormat 
- Hooks
- LogLevel 
- LogDefinition
- GetLogType
- GetEvents
- QueryEvent
- LogEvent
- PrismaAction 
- MiddlewareParams
- Middleware
- Datasource
- SortOrder 
- QueryMode 
- IntFilter
- StringFilter
- IntWithAggregatesFilter
- StringWithAggregatesFilter
- StringFieldUpdateOperationsInput
- IntFieldUpdateOperationsInput
- NestedIntFilter
- NestedStringFilter
- NestedIntWithAggregatesFilter
- NestedFloatFilter
- NestedStringWithAggregatesFilter
- BatchPayload

### How to reproduce

1. Generate a schema with one of the model names listed above
2. Write Prisma query
3. Observe return type is incorrect

### Expected behavior

_No response_

### Prisma information

n/a

### Environment & setup

- OS: macOS
- Node.js version: 17.7.1

### Prisma Version

```
3.11
```

### LINKED ISSUE #17542: Naming a model `Promise` breaks types for `PrismaPromise`
### Bug description

This started happening since Prisma 4.9.0, seemingly since https://github.com/prisma/prisma/pull/17265.

### How to reproduce

Clone the linked reproduction repository, generate the Prisma schema, and open `index.ts` in VSCode. `await` will not work on the `findMany` query and trying to call `map` on the expected awaited array of `customers` will give an error.

### Expected behavior

_No response_

### Prisma information

[Reproduction repository](https://github.com/Tenrys/prisma-4.9.0-await-prismapromise-repro)

### Environment & setup

- OS: Manjaro Linux
- Database: PostgreSQL
- Node.js version: v16.17.0

### Prisma Version

```
4.9.0
```

### PR DESCRIPTION
**Pull request by SevInf**
After looking through the issues, we had a couple of more clashes that
needed additional work:

1. `Check` and `Has` collide with built-in `CheckSelect`/`HasSelect`
   types. Those types are not public and not used since prisma 4.16.0,
   so I just removed them from generated file.
2. `Promise` is more complicated and required aliasing built-in type.

Fix #17542
Fix #9669
Close #12469

### CODE REVIEW

File: packages/client/tests/functional/naming-conflict/_builtInNames.ts [hunk 1]
```diff
@@ -56,4 +56,8 @@ export const builtInNames = [
   'IntFilter',
   'NestedIntFilter',
   'BatchPayload',
+  'Fetcher',
+  // 'Query', TODO: still broken
```
Comment (SevInf) [inline packages/client/tests/functional/naming-conflict/_builtInNames.ts:60]: I think this might need fix on the engine side, but not 100% sure.

**Review by Jolg42 — COMMENTED** [review]
It's a bit "weird" as a user to not have "Promise" anymore in the types? (and `JsPromise`, instead)
Screenshot 2023-07-17 at 15 23 27

**Comment by SevInf** [comment]
@Jolg42 I brought back `Promise` name

**Review by Jolg42 — APPROVED** [review]
