### PR TITLE
test(client): add coverage for invalid and missing env, remove useless test

### LINKED ISSUE #8613: test(client): happy blog-env test has no assertion
This test has no assertion. [adding "expect.assertions(1)" at the beginning makes the test fail.](https://github.com/prisma/prisma/pull/6225)

https://github.com/prisma/prisma/blob/main/packages/client/src/__tests__/integration/happy/blog-env/test.ts  

On first look, it looks like it's trying to test `PrismaClientInitializationError` but the code never errors.

We should check and properly test `PrismaClientInitializationError`

Context https://prisma-company.slack.com/archives/C016KUHB1R6/p1616400507047100

### PR DESCRIPTION
**Pull request by danstarns**
Closes: https://github.com/prisma/prisma/issues/8613

This PR removes the old test that wasn't working, didn't make any sense, and wasn't testing anything, and then it adds coverage, in the new functional test suite, to cover an env that is missing plus an env that is invalid.

### CODE REVIEW

File: packages/client/tests/functional/invalid-env/tests.ts [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+declare let prisma: import('@prisma/client').PrismaClient
+
+testMatrix.setupTestSuite(
+  () => {
+    beforeAll(() => {
+      const env = require('./prisma/env.json')
+      Object.assign(process.env, env)
+    })
+
+    test('test should throw PrismaClientInitializationError because invalid env', async () => {
```
Comment (millsp) [inline packages/client/tests/functional/invalid-env/tests.ts:13]:
```suggestion
    test('PrismaClientInitializationError for invalid env', async () => {
```

File: packages/client/tests/functional/missing-env/tests.ts [hunk 2]
```diff
@@ -0,0 +1,21 @@
+import testMatrix from './_matrix'
+
+// @ts-ignore this is just for type checks
+declare let prisma: import('@prisma/client').PrismaClient
+
+testMatrix.setupTestSuite(
+  () => {
+    test('test should throw PrismaClientInitializationError because missing env', async () => {
```
Comment (millsp) [inline packages/client/tests/functional/missing-env/tests.ts:8]:
```suggestion
    test('PrismaClientInitializationError for missing env', async () => {
```

**Review by millsp — APPROVED** [review]
