### PR TITLE
fix(client): Allow to use non-bundled Decimal.js versions

### LINKED ISSUE #6021: Prisma throws type mismatch error using Decimal type from from 'decimal.js' package
## Bug description

Prisma generates a namespace for Decimal.js that does not match the type from the import of Decimal.js from npm. This makes it annoying to use when third party code gives you "decimal.js Decimal's" and not "prisma Decimal's".

```
Type 'Decimal[]' is not assignable to type 'string | number | Decimal | Decimal[] | TestCreatefooInput | number[] | string[]'
```

## How to reproduce

```

model Test {
  id  Int       @id @default(autoincrement())
  foo Decimal[]
}
```

```
iimport { PrismaClient } from '@prisma/client'

import {Decimal as PrismaDecimal} from '@prisma/client/runtime'
import {Decimal as DecimalActual} from 'Decimal.js'

const prisma = new PrismaClient()

const actualDecimals = [new DecimalActual(1), new DecimalActual(2), new DecimalActual(3)]
const prismaDecimals = [new PrismaDecimal(1), new PrismaDecimal(2), new PrismaDecimal(3)]

prisma.test.create({
	data: {
		foo: actualDecimals
	  // ^ Type 'Decimal[]' is not assignable to type 'string | number | Decimal | Decimal[] | TestCreatefooInput | number[] | string[]'
	}
})

prisma.test.create({
	data: {
		foo: prismaDecimals
	}
})

```

## Expected behavior

Doesn't complain about mismatched types

## Prisma information

{
  "@prisma/client": "^2.18.0",
  "decimal.js": "^10.2.1"
}

## Environment & setup

```
Environment variables loaded from .env
prisma               : 2.18.0
@prisma/client       : 2.18.0
Current platform     : darwin
Query Engine         : query-engine da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at ../../.config/yarn/global/node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at ../../.config/yarn/global/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at ../../.config/yarn/global/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at ../../.config/yarn/global/node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.356.0
```

### PR DESCRIPTION
**Pull request by SevInf**
Since we bundle Decimal.js types, if the user has their own copy of the
library, our type will be incompatible with their. Introduce
`DecimalJSLike` interface. which includes public properties of decimal
instances and no methods and use this interface as input type. This
allows us to accept following things:

1. `Prisma.Decimal`
2. User-provided decimal instance, even if it is does not match
   our bundled version of the library.
3. Some compatible libraries, like decimal.js-light (not tested yet)
4. Manuallly constructed object with matching properties

Because of the last item, in some cases we have to do serialization
manually. `Decimal.isDecimal` returns true for items 1-3, but in case it
returns `false` we manually construct the instance from provided
properties.

Also adds a couple of functional tests for decimal.js handling.

Fix #6021

### CODE REVIEW

File: packages/client/tests/functional/_utils/idForProvider.ts [hunk 1]
```diff
@@ -0,0 +1,6 @@
+const sqlId = 'Int @id @default(autoincrement())'
+const mongoDbId = 'String @id @default(auto()) @map("_id") @db.ObjectId'
+
+export function idForProvider(provider: string): string {
```
Comment (SevInf) [inline packages/client/tests/functional/_utils/idForProvider.ts:4]: Thought this might be a useful helper for the cases, where we don't care about specifics of the id. Which, I assume will be most of the tests. What do you think?

File: packages/client/tests/functional/_utils/idForProvider.ts [hunk 2]
```diff
@@ -0,0 +1,6 @@
+const sqlId = 'Int @id @default(autoincrement())'
```
Comment (aqrln) [inline packages/client/tests/functional/_utils/idForProvider.ts:1]: Maybe 

```suggestion
const sqlId = 'String @id @default(uuid())'
```

so that the type will be the same regardless of the provider

File: packages/client/src/runtime/query.ts [hunk 3]
```diff
@@ -2,6 +2,7 @@ import chalk from 'chalk'
 import Decimal from 'decimal.js'
 import indent from 'indent-string'
 import stripAnsi from 'strip-ansi'
+import { P } from 'ts-toolbelt/out/Object/_api'
```
Comment (aqrln) [inline packages/client/src/runtime/query.ts:5]: Doesn't seem to be used

File: packages/client/src/runtime/utils/decimalJsLike.ts [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+export function stringifyDecimalJsLike(value: DecimalJsLike): string {
+  if (Decimal.isDecimal(value)) {
+    return String(value)
+  }
+
+  const tmpDecimal = new Decimal(0) as DecimalJsLike
+  tmpDecimal.d = value.d
+  tmpDecimal.e = value.e
+  tmpDecimal.s = value.s
+  return String(tmpDecimal)
```
Comment (aqrln) [inline packages/client/src/runtime/utils/decimalJsLike.ts:35]: clever trick!

**Review by aqrln — APPROVED** [review]
LGTM with one small comment (https://github.com/prisma/prisma/pull/13253#discussion_r869087100).

**Comment by SevInf** [comment]
Thanks @aqrln!
I fixed unused import. I still have no merge rights, so I'd be grateful if somebody could merge it after CI passes.

**Review by millsp — COMMENTED** [review]
Nice work 👏

**Comment by jessmorecroft** [comment]
Hi, I was going to try to get this working with decimal.js-light but can't see how it would. Those members in the DecimalJsLike interface simply don't exist in the light Decimal.

See here: https://github.com/MikeMcl/decimal.js-light/blob/master/decimal.d.ts

Hopefully I'm missing something?

**Comment by SimonCockx** [comment]
Not solved in `3.15.2`. I get a type error when doing this:
```ts
new PrismaClient().test.findUnique({ where: { id: 0 } }).then((t) => {
    const foo: Decimal = t!.foo;
    //    ^^^
});
```
`Type 'import("[...]/node_modules/@prisma/client/runtime/index").Decimal' is not assignable to type 'import("[...]/node_modules/decimal.js/decimal").default'.
  Types have separate declarations of a private property 'toStringTag'.`

given a model
```prisma
model Test {
  id  Int       @id @default(autoincrement())
  foo Decimal
}
```

**Comment by Jolg42** [comment]
@SimonCockx Hi! Could you [create a separate bug issue here](https://github.com/prisma/prisma/issues/new?assignees=&labels=kind%2Fbug&template=bug_report.yml)? We would need to reproduce this first.
