### PR TITLE
fix(client): revamp ClientEngine initialization and shutdown

### LINKED ISSUE #27157: PrismaPG: prismaClient unusable after calling $disconnect since 6.6.0
### Bug description

Since the new driver adapter interface from `6.6.0`, calling `$disconnect` calls `end()` on the underlying `pg.Pool`, and doesn't construct a fresh pool when new queries are issued.

This causes any subsequent queries to fail with an obtuse exception.

### Severity

🔹 Minor: Unexpected behavior, but does not block development

### Reproduction

```typescript
import {PrismaPg} from "@prisma/adapter-pg";
import {PrismaClient} from "@prisma/client";
import {Pool} from "pg";

async function main() {
  // const pool = new Pool({
  //   connectionString: process.env.CONNECTION_STRING,
  //   max: 10,
  //   allowExitOnIdle: true,
  // });

  const pgAdapter = new PrismaPg({
    connectionString: process.env.CONNECTION_STRING,
    max: 10,
    allowExitOnIdle: true,
  });
  const prismaClient = new PrismaClient({
    log: [
      {
        emit: 'event',
        level: 'query',
      },
    ],
    adapter: pgAdapter,
  });

  console.info(await prismaClient.$executeRaw`SELECT 1`)
  await prismaClient.$disconnect()
  // on 6.5.0 this works, 6.6.0 and up it doesn't.
  console.info(await prismaClient.$executeRaw`SELECT 1`)
}

main()

```

### Expected vs. Actual Behavior

**Expected**
The client should reconnect next time a query is issued.

**Actual**
An obtuse error is thrown, which if you add logging to https://github.com/prisma/prisma/blob/18e17cc0f6dfea6a4de44342f47f7a59ddd7a3ba/packages/adapter-pg/src/errors.ts#L6 you'll find it's a error from `pg` saying the `pool` has already been ended.

```
PrismaClientKnownRequestError: 
Invalid `prisma.$executeRaw()` invocation:


Error in external connector (id 0)
    at zn.handleRequestError (/Users/michaelnahkies/projects/node-libs/node_modules/@prisma/client/runtime/library.js:121:7459)
    at zn.handleAndLogRequestError (/Users/michaelnahkies/projects/node-libs/node_modules/@prisma/client/runtime/library.js:121:6784)
    at zn.request (/Users/michaelnahkies/projects/node-libs/node_modules/@prisma/client/runtime/library.js:121:6491)
    at async l (/Users/michaelnahkies/projects/node-libs/node_modules/@prisma/client/runtime/library.js:130:9778)
    at async main (/Users/michaelnahkies/projects/node-libs/libs/database/build/junk.js:28:18) {
  code: 'P2036',
  meta: { id: 0 },
  clientVersion: '6.7.0'
}
```

### Frequency

Consistently reproducible

### Does this occur in development or production?

Only in production (e.g., query engine, generated client)

### Is this a regression?

Yes, since 6.6.0

### Workaround

Re-construct `PrismaClient` after any `$disconnect`.

### Prisma Schema & Queries

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["views", "relationJoins", "prismaSchemaFolder", "driverAdapters"]
}

datasource db {
  provider = "postgresql"
  url      = "postgresql://..."
}
```

### Prisma Config

```ts
  "prisma": {
    "schema": "./prisma"
  },

```

### Logs & Debug Info

_No response_

### Environment & Setup

- **OS:** MacOS / Linux
- **Database:** PostgresSQL
- **Node.js version:** v22.13.1

### Prisma Version

```
Prisma schema loaded from prisma
prisma                  : 6.7.0
@prisma/client          : 6.7.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v22.13.1
TypeScript              : 5.7.3
Query Engine (Node-API) : libquery-engine 3cff47a7f5d65c3ea74883f1d736e41d68ce91ed (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 3cff47a7f5d65c3ea74883f1d736e41d68ce91ed (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 6.7.0-36.3cff47a7f5d65c3ea74883f1d736e41d68ce91ed
Default Engines Hash    : 3cff47a7f5d65c3ea74883f1d736e41d68ce91ed
Studio                  : 0.511.0
Preview Features        : driverAdapters, prismaSchemaFolder, relationJoins, views
```

### PR DESCRIPTION
**Pull request by aqrln**
Refactor the initialization and shutdown logic in the `ClientEngine`:

* Get rid of messy interdependent `Promise`s stored as class fields and introduce an explicit state machine with a discrete number of states and clearly defined transitions between them. All methods are safely callable concurrently and in any sequence because they know how to handle each of the four possible states. `ClientEngine` now starts disconnected and connects lazily on the first query, just like `LibraryEngine`.
	```mermaid
	stateDiagram-v2
	    [*] --> disconnected
	
	    disconnected --> connecting: #ensureStarted called
	    connecting --> connected: Connection promise resolved
	    connecting --> disconnected: Connection promise rejected
	    connected --> disconnecting: stop called
	    disconnecting --> disconnected: Disconnect promise settled
	```
* Make sure we discard the query compiler on panic and never use the same instance again to avoid memory leaks.
* Immediately drop the query compiler instance on WASM side on disconnect instead of relying on `FinalizationRegistry` to maybe free it some time later. Previously we would have a guaranteed memory leak on Cloudflare Workers here but they [shipped `FinalizationRegistry` support a couple of weeks ago](https://blog.cloudflare.com/we-shipped-finalizationregistry-in-workers-why-you-should-never-use-it/). However, just like the linked article says, the cleanup callbacks are not guaranteed to run, and we should call `free` directly if possible and only rely on GC hooks as a safety net.
* Fix `getErrorMessageWithLink` being passed a random query that happened to be started last instead of the query that actually failed, when multiple queries are in flight.

Refs: https://github.com/prisma/prisma/pull/27493
Fixes: https://github.com/prisma/prisma/issues/27157
Closes: https://linear.app/prisma-company/issue/ORM-972/bug-regression-driver-adapter-disconnect-issues

### CODE REVIEW

File: packages/client/src/runtime/core/engines/client/ClientEngine.ts [hunk 1]
```diff
@@ -138,46 +159,91 @@ export class ClientEngine implements Engine<undefined> {
...
+              driverAdapter,
+              transactionManager,
+              queryCompiler,
+            }
+
+            this.#state = { type: 'connected', engine }
+
+            return engine
+          } catch (error) {
+            this.#state = { type: 'disconnected' }
```
Comment (jacek-prisma) [inline packages/client/src/runtime/core/engines/client/ClientEngine.ts:181]: probably would not be a problem in practice, but if `await this.#instantiateQueryCompiler` fails, the `driverAdapter` gets leaked here

**Review by jacek-prisma — APPROVED** [review]
left 1 minor comment, but looks very good

File: packages/client/src/runtime/core/engines/client/ClientEngine.ts (hunk 1 above)
Comment (aqrln) [reply packages/client/src/runtime/core/engines/client/ClientEngine.ts:181]: done in [`abbb2ea` (#27528)](https://github.com/prisma/prisma/pull/27528/commits/abbb2ea2e8d0c63265283cc16b099715e130b383)

Comment (jacek-prisma) [reply packages/client/src/runtime/core/engines/client/ClientEngine.ts:181]: 👍

**Review by jacek-prisma — APPROVED** [review]
