### PR TITLE
fix(build): cleanup intermediary esm files

### LINKED ISSUE #11683: Avoid shipping unused intermediary ESM files
We have ESM builds to achieve tree-shaking. However, this is not proper ESM (still has requires, __dirnames, etc...) and it will fail at runtime. So for now, there is no actual reason to expose this.

https://prisma.github.io/prisma/dev/bench/

### PR DESCRIPTION
**Pull request by millsp**
Fixes https://github.com/prisma/prisma/issues/11683

### CODE REVIEW

File: helpers/compile/plugins/cleanupPlugin.ts [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+const unlink = promisify(fs.unlink)
+
+/**
+ * Removes the esm output files after cjs compile.
+ * @param build the esbuild build object
+ * @returns
+ */
+function removeIntermediaryEsmFiles(build: esbuild.PluginBuild) {
+  const files = Object.values(build.initialOptions.entryPoints ?? {})
+  const rms = files.map((file) => file.endsWith('.mjs') && unlink(file))
```
Comment (Jolg42) [inline helpers/compile/plugins/cleanupPlugin.ts:14]:
```suggestion
  const rms = files
  	.filter((file) => file.endsWith('.mjs'))
  	.map((file) => unlink(file))
```

That's probably fewer promises created like this

**Review by Jolg42 — APPROVED** [review]
See comment for minor improvement
