### PR TITLE
fix(engine-core): make event objects match their static types

### LINKED ISSUE #10217: Incorrect Typescript type for QueryEvent.timestamp
### Bug description

`QueryEvent.timestamp`'s Typescript type is `Date`, but it is actually a number

### How to reproduce

Check the type of `QueryEvent.timestamp`; see that it is `Date`
Log a query event, e.g.
```
prismaClient.$on('query', event => {
  console.log(event);
};
```
and see that the `timestamp` field is actually a number

### Expected behavior

Either `QueryEvent.timestamp` should have its type set to `number`, or it should contain a `Date` not a number

### Prisma information

n/a

### Environment & setup

- OS: Windows, Linux
- Database: PostgreSQL
- Node.js version: 16.8.0

### Prisma Version

```
prisma                  : 3.2.1
@prisma/client          : 3.2.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c
Studio                  : 0.435.0
Preview Features        : interactiveTransactions
```

### PR DESCRIPTION
**Pull request by aqrln**
* Make `timestamp`, `target` and `duration` match their advertised types in `LibraryEngine` and make them consistent with the logs that the `BinaryEngine` produces
* Fix broken `Date` objects in `BinaryEngine` logs

See specific commits for the changes in snapshots.

Closes https://github.com/prisma/prisma/issues/10217

### CODE REVIEW

**Review by millsp — APPROVED** [review]

File: packages/engine-core/src/common/errors/utils/log.ts [hunk 1]
```diff
@@ -119,7 +119,7 @@ export function convertLog(rustLog: RawRustLog): RustLog {
   return {
     ...rustLog,
     level,
-    timestamp: new Date(new Date().getFullYear() + ' ' + rustLog.timestamp),
+    timestamp: new Date(rustLog.timestamp),
```
Comment (Jolg42) [inline packages/engine-core/src/common/errors/utils/log.ts:122]: 🧹 Nice!

**Review by Jolg42 — APPROVED** [review]
