### PR TITLE
fix: disconnect race condition

### LINKED ISSUE #839: node script hanging after disconnect
## Bug description

We observed this with some internal testing. The error log is like the following: 

```
prisma-client TypeError: Cannot read property 'signalCode' of undefined
  prisma-client     at NodeEngine.handleRequestError (/Users/divyendusingh/Documents/prisma/system-behavior/pgbouncer-connection/node_modules/@prisma/client/runtime/index.js:1:111388)
  prisma-client     at /Users/divyendusingh/Documents/prisma/system-behavior/pgbouncer-connection/node_modules/@prisma/client/runtime/index.js:1:125748
  prisma-client     at runMicrotasks (<anonymous>)
  prisma-client     at processTicksAndRejections (internal/process/task_queues.js:97:5)
  prisma-client     at async PrismaClientFetcher.request (/Users/divyendusingh/Documents/prisma/system-behavior/pgbouncer-connection/node_modules/@prisma/client/runtime/index.js:1:222501)
  prisma-client     at async Promise.all (index 8) +1ms
  engine {
  engine   error: SocketError: other side closed
  engine       at Socket.onSocketEnd (/Users/divyendusingh/Documents/prisma/system-behavior/pgbouncer-connection/node_modules/@prisma/client/runtime/index.js:1:203556)
  engine       at Socket.emit (events.js:327:22)
  engine       at endReadableNT (_stream_readable.js:1221:12)
  engine       at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  engine     code: 'UND_ERR_SOCKET'
  engine   }
  engine } +1ms
```

## How to reproduce

Hunch: It happens when a lot of requests are running in parallel and a disconnect happens. While Prisma can reconnect if the connection is not available, it can happen that a certain request is already past that check and the async disconnect happens. In this case Prisma client gets stuck and these are the logs.

It thinks QE has crashed but that var is null. This can be reproduced by running many queries parallen and in loop and disconnecting async.

https://github.com/prisma/system-behavior/pull/6 (internal)

## Expected behavior

It shouldn't hang. 

## Prisma information

Prisma CLI: `2.5.0-dev.61`

Maybe related: https://github.com/prisma/prisma/issues/2917

### PR DESCRIPTION
**Pull request by timsuchanek**
Closes prisma/prisma-client-js#839

### CODE REVIEW

**Comment by timsuchanek** [comment]
Still needs more tests

File: src/packages/client/src/__tests__/runtime-tests/disconnect-finally/index.js [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+const prisma = new PrismaClient()
+async function main() {
+  res = prisma.user.findMany()
+}
+
+module.exports = () => {
+  return new Promise((r) => {
+    main().finally(async () => {
+      await prisma.$disconnect()
+      r(await res)
```
Comment (Jolg42) [inline src/packages/client/src/__tests__/runtime-tests/disconnect-finally/index.js:14]: for readability resolve would be better, I was surprised to see this `r` 😄 looked like a typo at first sight

File: src/packages/engine-core/src/NodeEngine.ts [hunk 2]
```diff
@@ -781,32 +802,63 @@ ${this.lastErrorLog.fields.file}:${this.lastErrorLog.fields.line}:${this.lastErr
...
+      stopPromise = new Promise((resolve, reject) => {
+        this.engineStopDeferred = { resolve, reject }
+      })
       this.queryEngineKilled = true
       this.undici?.close()
       this.child?.kill()
       delete this.child
     }
+    this.startPromise = undefined
+    await stopPromise
```
Comment (Jolg42) [inline src/packages/engine-core/src/NodeEngine.ts:860]: When `this.child` is truthy that means that stopPromise is a Promise but if it's falsy it would be `undefined` meaning it does `await undefined` which is a bit weird but works I guess?

**Comment by Jolg42** [comment]
One potentially interesting test would be to do multiple calls to `$disconnect` or `$connect` maybe.

File: src/packages/client/src/__tests__/runtime-tests/disconnect-finally/index.js (hunk 1 above)
Comment (timsuchanek) [reply src/packages/client/src/__tests__/runtime-tests/disconnect-finally/index.js:14]: Good point, will rename.

File: src/packages/engine-core/src/NodeEngine.ts (hunk 2 above)
Comment (timsuchanek) [reply src/packages/engine-core/src/NodeEngine.ts:860]: Good point, added an `if(stopPromise)` in there!

**Comment by timsuchanek** [comment]
> One potentially interesting test would be to do multiple calls to `$disconnect` or `$connect` maybe.

https://github.com/prisma/prisma/commit/1487e8017260b0443bbd31c7d6030d896cefda0e
