### PR TITLE
fix(client-generator-ts): fix "prisma generate" when no model is defined

### LINKED ISSUE #27926: Cannot read properties of undefined (reading 'filter') with prisma.config.ts
### Bug description

When using new prisma.config.ts got this issue. when generating `prisma generate`
but when i change provider as `prisma-client-js` prisma is generating the client file but cannot access model using prisma like prisma.user.findmany

### Severity

⚠️ Major: Breaks core functionality (e.g., migrations fail)

### Reproduction

Use the config same as above. Use prisma 6.14.0

### Expected vs. Actual Behavior

this will generate all the models file as ts extention also genrated client.ts file. refer below image.

Image

### Frequency

Consistently reproducible

### Does this occur in development or production?

Only in development (e.g., CLI tools, migrations, Prisma Studio)

### Is this a regression?

it works when i use prisma block in package.json

### Workaround

I dont know any work around for this 

### Prisma Schema & Queries

```prisma
generator client {
  provider               = "prisma-client"
  previewFeatures        = ["queryCompiler", "driverAdapters"]
  output                 = "../app/generated/prisma"
  runtime                = "bun"
  moduleFormat           = "esm"
  generatedFileExtension = "ts"
  importFileExtension    = "ts"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

### Prisma Config

```ts
import path from "node:path";
import type { PrismaConfig } from "prisma";

export default {
  experimental: {
    adapter: true,
  },
  schema: path.join("prisma", "schema.prisma"),
  migrations: {
    path: path.join("prisma", "migrations"),
  },
  views: {
    path: path.join("prisma", "views"),
  },
  typedSql: {
    path: path.join("prisma", "queries"),
  },
} satisfies PrismaConfig;

```

### Logs & Debug Info

_No response_

### Environment & Setup

- **OS:** Windows
- **Database:** PostgreSQL
- **Node.js version:** v23.4.0

### Prisma Version

```
6.14.0
```

### PR DESCRIPTION
**Pull request by jkomyno**
This PR:
- closes [ORM-1175](https://linear.app/prisma-company/issue/ORM-1175/prisma-client-support-prisma-generate-with-no-models)
- fixes https://github.com/prisma/prisma/issues/27926

It allows `prisma generate` to work with a `schema.prisma` file with the `prisma-client` generator and no model:

```prisma
generator client {
  provider = "prisma-client"
  output   = "../generated/client"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

### CODE REVIEW

File: packages/client-generator-ts/src/generateClient.ts [hunk 1]
```diff
@@ -78,6 +78,7 @@ export interface BuildClientResult {
   prismaClientDmmf: DMMF.Document
 }
 
+// Note: this breaks
```
Comment (FGoessler) [inline packages/client-generator-ts/src/generateClient.ts]: Left over comment or what is its purpose? 🤔

File: packages/client-generator-ts/src/dmmf.ts [hunk 2]
```diff
@@ -127,7 +127,7 @@ export class DMMFHelper implements DMMF.Document {
 
   private buildInputTypesMap() {
     const result = new Map<FullyQualifiedName, DMMF.InputType>()
-    for (const type of this.inputObjectTypes.prisma) {
+    for (const type of this.inputObjectTypes.prisma || []) {
```
Comment (FGoessler) [inline packages/client-generator-ts/src/dmmf.ts]: Nit for consistency:
```suggestion
    for (const type of this.inputObjectTypes.prisma ?? []) {
```

**Review by FGoessler — APPROVED** [review]
Two minor nits only. ;)

File: packages/client-generator-ts/src/generateClient.ts (hunk 1 above)
Comment (jkomyno) [reply packages/client-generator-ts/src/generateClient.ts]: Removed
