### PR TITLE
fix(engine-core): connect to QE binary by IPv4 loopback address

### LINKED ISSUE #9903: Prisma Client: Query Engine `engineType=binary` incompatible with Node.js v17?
Note: Node.js v17 is an intermediary release and won't become an LTS version and should not be used for production workloads.

I created a PR in our e2e tests suite here https://github.com/prisma/e2e-tests/pull/2137 to add a minimal test for v17 which succeeds on engineType "library" but fails on "binary" with 
https://github.com/prisma/e2e-tests/runs/3973259270?check_suite_focus=true#step:6:375
```
$ ts-node ./script.ts
PrismaClientKnownRequestError: 
Invalid `client.user.deleteMany()` invocation in
/home/runner/work/e2e-tests/e2e-tests/generic/basic/script.ts:7:21

   4 
   5 // A `main` function so that we can use async/await
   6 async function main() {
→  7   await client.user.deleteMany(
  connect ECONNREFUSED ::1:43951
    at cb (/home/runner/work/e2e-tests/e2e-tests/generic/basic/node_modules/@prisma/client/runtime/index.js:38537:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ECONNREFUSED',
  clientVersion: '3.4.0-dev.10',
  meta: undefined
}
```

Rerunning the test results in the same error.
We should reproduce locally and see what's happening here, looks like something about IPv6 maybe? `ECONNREFUSED ::1:43951`

Node.js v17 changelog here (didn't find anything related) https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V17.md

### PR DESCRIPTION
**Pull request by aqrln**
Unless a different IP or hostname is specified using the `--host`
command-line option, the query engine server binds to `127.0.0.1`:

* https://github.com/prisma/prisma-engines/blob/af993bb6d5c28f94e4ab70f68ff69364b628af97/query-engine/query-engine/src/opt.rs#L44-L46
* https://github.com/prisma/prisma-engines/blob/af993bb6d5c28f94e4ab70f68ff69364b628af97/query-engine/query-engine/src/server/mod.rs#L93

The BinaryEngine client tried to connect to the query engine server
using the `localhost` hostname, which normally resolves to either
`127.0.0.1` or `::1` (and in exotic cases might even resolve to
something completely different). When `localhost` resolved to the IPv6
loopback address (which seems to be usually the case with Node.js 17),
the client couldn't connect because the query engine server doesn't bind
to it.  This commit changes `localhost` to `127.0.0.1` to avoid this
error.

Fixes https://github.com/prisma/prisma/issues/9903

### CODE REVIEW

File: packages/engine-core/src/binary/BinaryEngine.ts [hunk 1]
```diff
@@ -602,11 +602,11 @@ ${chalk.dim("In case we're mistaken, please report this to us 🙏.")}`)
               json.fields?.message?.startsWith('Started http server')
             ) {
               if (this.useUds) {
-                this.connection.open('http://localhost', {
+                this.connection.open('http://127.0.0.1', {
```
Comment (aqrln) [inline packages/engine-core/src/binary/BinaryEngine.ts:605]: FWIW, I don't think it means anything in the context of Unix Domain Sockets, but I changed it as well for consistency.

**Review by millsp — APPROVED** [review]

**Comment by Jolg42** [comment]
@aqrln looks good!

Harshit was unable to reproduce though https://github.com/prisma/prisma/issues/9903#issuecomment-966177844

Did you get to a reproduction?

**Comment by aqrln** [comment]
@Jolg42 on my machine it's reproducible, yes

**Comment by aqrln** [comment]
Minimal reproduction:


```
prisma/packages/client on  aqrln/use-ipv4-loopback-address [$!?] is 📦 v0.0.0 via  v17.1.0 took 10s
❯ nvm use 16
Now using node v16.5.0 (npm v7.19.1)

prisma/packages/client on  aqrln/use-ipv4-loopback-address [$!?] is 📦 v0.0.0 via  v16.5.0
❯ node
Welcome to Node.js v16.5.0.
Type ".help" for more information.
> dns.lookup('localhost', console.log)
GetAddrInfoReqWrap {
  callback: [Function: log],
  family: 0,
  hostname: 'localhost',
  oncomplete: [Function: onlookup]
}
> null 127.0.0.1 4

>

prisma/packages/client on  aqrln/use-ipv4-loopback-address [$!?] is 📦 v0.0.0 via  v16.5.0 took 41s
❯ node --version
v16.5.0

prisma/packages/client on  aqrln/use-ipv4-loopback-address [$!?] is 📦 v0.0.0 via  v16.5.0
❯ nvm use 16
Now using node v16.5.0 (npm v7.19.1)

prisma/packages/client on  aqrln/use-ipv4-loopback-address [$!?] is 📦 v0.0.0 via  v16.5.0
❯ node
Welcome to Node.js v16.5.0.
Type ".help" for more information.
> dns.lookup('localhost', console.log)
GetAddrInfoReqWrap {
  callback: [Function: log],
  family: 0,
  hostname: 'localhost',
  oncomplete: [Function: onlookup]
}
> null 127.0.0.1 4

>

prisma/packages/client on  aqrln/use-ipv4-loopback-address [$!?] is 📦 v0.0.0 via  v16.5.0 took 19s
❯ nvm use 17
Now using node v17.1.0 (npm v8.1.3)

prisma/packages/client on  aqrln/use-ipv4-loopback-address [$!?] is 📦 v0.0.0 via  v17.1.0
❯ node
Welcome to Node.js v17.1.0.
Type ".help" for more information.
> dns.lookup('localhost', console.log)
GetAddrInfoReqWrap {
  callback: [Function: log],
  family: 0,
  hostname: 'localhost',
  oncomplete: [Function: onlookup]
}
> null ::1 6

>

```

**Review by Jolg42 — APPROVED** [review]
