### PR TITLE
fix(*): env var parsing for generator binaryTargets

### LINKED ISSUE #7295: 2.23.0 can not recognize `binaryTargets: env("..")` inside `generator client` section
### Bug description

`prisma [format|generate]` is not working with `env("BINARY_TARGETS")` in latest prisma (2.23.0) 😢

**ERROR** 👇
```
Error: Schema Parsing P1012

Get config
error: Expected a String value, but received functional value "env".
  -->  schema.prisma:8
   |
 7 |   provider      = "prisma-client-js"
 8 |   binaryTargets = env("BINARY_TARGETS")
   |
```

@janpio 

### How to reproduce

just run `prisma format` or `prisma generate` with schema below

### Expected behavior

should works

### Prisma information

```prisma
datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = env("BINARY_TARGETS")
}

model User {
  id Int @id
}
```

### Environment & setup

- OS: Mac OS
- Database: all
- Node.js version: v14.16.0

### Prisma Version

```
prisma               : 2.23.0
@prisma/client       : 2.23.0
Current platform     : darwin
Query Engine         : query-engine adf5e8cba3daf12d456d911d72b6e9418681b28b
Migration Engine     : migration-engine-cli adf5e8cba3daf12d456d911d72b6e9418681b28b
Introspection Engine : introspection-core adf5e8cba3daf12d456d911d72b6e9418681b28b
Format Binary        : prisma-fmt adf5e8cba3daf12d456d911d72b6e9418681b28b
Default Engines Hash : adf5e8cba3daf12d456d911d72b6e9418681b28b
Studio               : 0.393.0
```
--- 
parent https://github.com/prisma/prisma/issues/6830

### PR DESCRIPTION
**Pull request by Jolg42**
Needs merge of engine first https://github.com/prisma/prisma-engines/pull/1981

closes  #7295

### CODE REVIEW

**Comment by Jolg42** [comment]
When this is ready, we need to merge https://github.com/prisma/prisma-engines/pull/1981

**Comment by Jolg42** [comment]
We can review next week, could be great to have a chat here too with Pierre next week.

File: src/packages/sdk/src/utils/parseEnvValue.ts [hunk 1]
```diff
@@ -1,26 +1,55 @@
...
+ * - If there is an env var is present but can't be resolved an error will be thrown
+ */
+export function parseBinaryTargetsEnvValue(object: BinaryTargetsEnvValue) {
+  if (object.fromEnvVar && object.fromEnvVar !== null) {
+    const value = process.env[object.fromEnvVar]
+    if (!value) {
+      throw new Error(
+        `Attempted to load binaryTargets value using \`env(${
+          object.fromEnvVar
+        })\` but it was not present. Please insure that ${chalk.dim(
```
Comment (millsp) [inline src/packages/sdk/src/utils/parseEnvValue.ts:44]: "ensure" instead of "insure", you probably ctrl-c/v from above

File: src/packages/sdk/src/utils/parseEnvValue.ts [hunk 2]
```diff
@@ -1,26 +1,55 @@
...
+          object.fromEnvVar,
+        )} is present in your Environment Variables`,
+      )
+    }
+
+    // value is a string because it's from env var but need to be parsed as an array
+    return JSON.parse(value)
```
Comment (millsp) [inline src/packages/sdk/src/utils/parseEnvValue.ts:51]: So the value can be an `Array` stored in the env var, but can we have an array of env vars?

**Review by millsp — CHANGES_REQUESTED** [review]

**Comment by millsp** [comment]
Not able to review `src/packages/sdk/src/getGenerators.ts`, I lack too much context

**Review by millsp — APPROVED** [review]

File: src/packages/sdk/src/utils/parseEnvValue.ts (hunk 2 above)
Comment (millsp) [reply src/packages/sdk/src/utils/parseEnvValue.ts:51]: No

File: src/packages/sdk/src/utils/parseEnvValue.ts (hunk 1 above)
Comment (Jolg42) [reply src/packages/sdk/src/utils/parseEnvValue.ts:44]: Good point!

**Review by williamluke4 — APPROVED** [review]

File: src/packages/sdk/src/__tests__/getGenerators/getGenerators.test.ts [hunk 3]
```diff
@@ -101,7 +101,7 @@ describe('getGenerators', () => {
     generators.forEach((g) => g.stop())
   })
 
-  test('basic - binaryTargets as env var - native', async () => {
```
Comment (janpio) [inline src/packages/sdk/src/__tests__/getGenerators/getGenerators.test.ts]: Can we skip these for Node-API only?

File: src/packages/client/src/__tests__/integration/errors/missing-binary-native/test.ts [hunk 4]
```diff
@@ -35,31 +35,31 @@ test('missing-binary-native', async () => {
...
-            in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
-            but something went wrong. That's suboptimal.
+                                    You already added the platform "native" to the "generator" block
+                                    in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
+                                    but something went wrong. That's suboptimal.
 
-            Please create an issue at TEST_GITHUB_LINK
-          `)
+                                    Please create an issue at TEST_GITHUB_LINK
+                              `)
```
Comment (janpio) [inline src/packages/client/src/__tests__/integration/errors/missing-binary-native/test.ts:62]: What is going on here? That this changed is weird.

Comment (Jolg42) [reply src/packages/client/src/__tests__/integration/errors/missing-binary-native/test.ts:62]: inline snapshots are weird sometimes 🤷‍♂️

File: src/packages/sdk/src/__tests__/getGenerators/getGenerators.test.ts (hunk 3 above)
Comment (Jolg42) [reply src/packages/sdk/src/__tests__/getGenerators/getGenerators.test.ts]: Yes

File: src/packages/sdk/src/__tests__/getGenerators/getGenerators.test.ts [hunk 5]
```diff
@@ -101,25 +101,28 @@ describe('getGenerators', () => {
...
-    process.env.BINARY_TARGETS_ENV_VAR_TEST = '["native"]'
-
-    const aliases = {
-      'predefined-generator': {
-        generatorPath: path.join(__dirname, 'generator'),
-        outputPath: __dirname,
-      },
-    }
+  /* eslint-disable jest/no-standalone-expect */
+  const it = (condition: boolean) => (condition ? test : test.skip)
```
Comment (janpio) [inline src/packages/sdk/src/__tests__/getGenerators/getGenerators.test.ts:105]: Hack alarm :p `conditionalTest` maybe instead? And put in some helper file we hoepfully have?

File: src/packages/sdk/src/__tests__/getGenerators/getGenerators.test.ts [hunk 6]
```diff
@@ -150,7 +153,7 @@ describe('getGenerators', () => {
 
       generator gen_env {
         provider      = \\"predefined-generator\\"
-        binaryTargets = env(\\"BINARY_TARGETS_ENV_VAR_TEST\\")
+        binaryTargets = \\"native\\"
```
Comment (janpio) [inline src/packages/sdk/src/__tests__/getGenerators/getGenerators.test.ts:156]: Good catch that this case was missing!

File: src/packages/sdk/src/__tests__/getGenerators/getGenerators.test.ts [hunk 7]
```diff
@@ -301,8 +298,219 @@ describe('getGenerators', () => {
...
     `)
 
-    generators.forEach((g) => g.stop())
-  })
+      generators.forEach((g) => g.stop())
+    },
+  )
+
+  it(process.env.PRISMA_FORCE_NAPI !== 'true')(
+    'basic - binaryTargets as env var - native',
```
Comment (janpio) [inline src/packages/sdk/src/__tests__/getGenerators/getGenerators.test.ts:306]: ... in array

File: src/packages/cli/fixtures/custom generator/prisma/schema.prisma [hunk 8]
```diff
@@ -5,11 +5,11 @@ generator min {
 
 datasource db {
   provider = "sqlite"
-  url      = env("DATABASE_URL")
```
Comment (janpio) [inline src/packages/cli/fixtures/custom generator/prisma/schema.prisma:8]: Should we have a test where the env var is actually not set?

File: src/packages/sdk/src/__tests__/getGenerators/getGenerators.test.ts (hunk 7 above)
Comment (janpio) [reply src/packages/sdk/src/__tests__/getGenerators/getGenerators.test.ts:306]:
```suggestion
    'basic - binaryTargets as env var - native (in array)',
```

**Review by millsp — APPROVED** [review]

File: src/packages/sdk/src/__tests__/getGenerators/getGenerators.test.ts (hunk 5 above)
Comment (Jolg42) [reply src/packages/sdk/src/__tests__/getGenerators/getGenerators.test.ts:105]: Removed in https://github.com/prisma/prisma/pull/7792

File: src/packages/cli/fixtures/custom generator/prisma/schema.prisma (hunk 8 above)
Comment (Jolg42) [reply src/packages/cli/fixtures/custom generator/prisma/schema.prisma:8]: Revert in https://github.com/prisma/prisma/pull/7793
