### PR TITLE
fix(client): Correctly handle error reports with invalid line numbers

### LINKED ISSUE #15180: Bug with throwing formatted errors
### Bug description

I was running a query like this:

```prisma
const res: any = await prisma.role.deleteMany({
      where: {
         organizationDomain: context.userDomain,
         name: role.name,
      },
 });
```

Now, this query violates a foreign constraint (since I have not enabled cascade delete in related model) and prisma is trying to throw an error for this which is valid.

But the issue is that, it fails in formatting the error thrown. I was getting `TypeError: Cannot read properties of undefined (reading 'length')` and when I was trying to debug, I noticed that it came from `node_modules/@prisma/client/runtime/index.js`

And I added some logs to the file and noticed that `invocationLine` was undefined

Just to confirm if this was fixed in latest version, I upgraded to `4.3.1` and I see it there as well.

Stack trace and logs below:
```
nvint-psql           | 2022-09-05 06:38:50.300 UTC [37] ERROR:  update or delete on table "Role" violates foreign key constraint "Assessment_roleOrganizationDomain_roleName_fkey" on table "Assessment"
convint-psql           | 2022-09-05 06:38:50.300 UTC [37] DETAIL:  Key (organizationDomain, name)=(convint.ai, React Test Role) is still referenced from table "Assessment".
convint-psql           | 2022-09-05 06:38:50.300 UTC [37] STATEMENT:  DELETE FROM "public"."Role" WHERE "public"."Role"."id" IN ($1) /* traceparent=00-00-00-00 */
 ---errr:: PrismaClientKnownRequestError: Foreign key constraint failed on the field: `Assessment_roleOrganizationDomain_roleName_fkey (index)`
     at prismaGraphQLToJSError (/app/node_modules/@prisma/client/runtime/index.js:20426:12)
     at LibraryEngine.buildQueryError (/app/node_modules/@prisma/client/runtime/index.js:26373:12)
     at LibraryEngine.request (/app/node_modules/@prisma/client/runtime/index.js:26307:22)
     at async RequestHandler.request (/app/node_modules/@prisma/client/runtime/index.js:29888:24)
     at async PrismaClient._request (/app/node_modules/@prisma/client/runtime/index.js:30880:16)
     at async deleteRole (/app/src/modules/role/index.ts:689:23)
     at async field.resolve (/app/node_modules/@envelop/core/cjs/traced-schema.js:36:42)
     at async /app/node_modules/@envelop/core/cjs/orchestrator.js:380:27
     at async /app/node_modules/@pablosz/graphql-helix/process-request.js:161:27
     at async Object.processRequest (/app/node_modules/@pablosz/graphql-helix/process-request.js:66:18) {
   code: 'P2003',
   clientVersion: '4.3.1',
   meta: {
     field_name: 'Assessment_roleOrganizationDomain_roleName_fkey (index)'
   }
 } role.delete EnabledCallSite {
   _error: Error
       at new EnabledCallSite (/app/node_modules/@prisma/client/runtime/index.js:26893:19)
       at getCallSite (/app/node_modules/@prisma/client/runtime/index.js:26919:10)
       at Proxy.<anonymous> (/app/node_modules/@prisma/client/runtime/index.js:29505:22)
       at deleteRole (/app/src/modules/role/index.ts:689:47)
       at /app/node_modules/graphql-modules/index.cjs.js:1634:38
       at dispatch (/app/node_modules/graphql-modules/index.cjs.js:1457:40)
       at composed (/app/node_modules/graphql-modules/index.cjs.js:1463:16)
       at wrappedResolver (/app/node_modules/graphql-modules/index.cjs.js:1634:16)
       at field.resolve (/app/node_modules/@envelop/core/cjs/traced-schema.js:36:48)
       at async /app/node_modules/@envelop/core/cjs/orchestrator.js:380:27
 }
 ---invocationLine undefined
 --err:::: TypeError: Cannot read properties of undefined (reading 'length')
     at getIndent (/app/node_modules/@prisma/client/runtime/index.js:27625:28)
     at getTemplateParameters (/app/node_modules/@prisma/client/runtime/index.js:27588:34)
     at createErrorMessageWithContext (/app/node_modules/@prisma/client/runtime/index.js:27681:30)
     at RequestHandler.handleRequestError (/app/node_modules/@prisma/client/runtime/index.js:29915:17)
     at RequestHandler.request (/app/node_modules/@prisma/client/runtime/index.js:29907:12)
     at async PrismaClient._request (/app/node_modules/@prisma/client/runtime/index.js:30880:16)
     at async deleteRole (/app/src/modules/role/index.ts:689:23)
     at async field.resolve (/app/node_modules/@envelop/core/cjs/traced-schema.js:36:42)
     at async /app/node_modules/@envelop/core/cjs/orchestrator.js:380:27
     at async /app/node_modules/@pablosz/graphql-helix/process-request.js:161:27 {
   clientVersion: '4.3.1'
```

Because of this, I am not able to use `if (err instanceof Prisma.PrismaClientKnownRequestError)` to catch the error as well

### How to reproduce

- Just try violating a foreign constraint
- Use a query like above
- Try to catch and throw the error

### Expected behavior

Prisma throws a valid error

### Prisma information

```prisma
model Role {
  id              String       @id @default(uuid())
  organization    Organization @relation(fields: [organizationDomain], references: [domain])
  name            String
  description     String?
  skills          Json
  creator         User?        @relation(name: "createdRoles", fields: [creatorUsername], references: [username])
  createdDate     DateTime     @default(now())
  creatorUsername String?      @default("vignesh@convint.ai")
  isActive        Boolean      @default(true)
  assessments     Assessment[]
  metadata        Metadata[]

  organizationDomain String @default("convint.ai")

  @@unique([organizationDomain, name], name: "key")
}
```

```ts
const res: any = await prisma.role.deleteMany({
      where: {
         organizationDomain: context.userDomain,
         name: role.name,
      },
 });
```

### Environment & setup

- OS: Ubuntu 20.04
- Database: PostgresSQL
- Node.js version: 18.5.0

### Prisma Version

```
prisma                  : 4.3.1
@prisma/client          : 4.3.1
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/migration-engine-debian-openssl-3.0.x)
Introspection Engine    : introspection-core c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/introspection-engine-debian-openssl-3.0.x)
Format Binary           : prisma-fmt c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-3.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.3.0-32.c875e43600dfe042452e0b868f7a48b817b9640b
Default Engines Hash    : c875e43600dfe042452e0b868f7a48b817b9640b
Studio                  : 0.473.0
Preview Features        : interactiveTransactions, fullTextSearch
Done in 2.09s.
```

### PR DESCRIPTION
**Pull request by SevInf**
Could happen if source map is off, for example.

Fix #15180

### CODE REVIEW

File: packages/client/src/runtime/utils/createErrorMessageWithContext.ts [hunk 1]
```diff
@@ -76,8 +76,8 @@ function getTemplateParameters(
 
   const contextFirstLine = Math.max(1, callLocation.lineNumber - 3)
   let source = SourceFileSlice.read(callLocation.fileName)?.slice(contextFirstLine, callLocation.lineNumber)
-  if (source) {
-    const invocationLine = source.lineAt(callLocation.lineNumber)
+  const invocationLine = source?.lineAt(callLocation.lineNumber)
```
Comment (aqrln) [inline packages/client/src/runtime/utils/createErrorMessageWithContext.ts:79]: Let's also update the signature of `lineAt` to explicitly specify `string | undefined` as the return type. Otherwise the issue may be accidentally introduced back when moving the code around.

Comment (SevInf) [reply packages/client/src/runtime/utils/createErrorMessageWithContext.ts:79]: Good point, done.

**Review by aqrln — APPROVED** [review]
Thank you!

**Review by RodrigoRVSN — APPROVED** [review]
