### PR TITLE
fix(client): safe and unsafe raw queries

### LINKED ISSUE #7142: Revisit prisma.$queryRaw("...") vs. prisma.$queryRaw template literal
## Problem

Right now it's really easy to write a raw query that's susceptible to SQL injections

```js
// Raw query. Susceptible to SQL injections! 
prisma.$queryRaw(`SELECT \* FROM User WHERE email = ${email}`);

// Prepared query. Not susceptible to SQL injections.
prisma.$queryRaw`SELECT \* FROM User WHERE email = ${email}`;
```

The difference is in the `(` and `)`. This is far too subtle and there's no warning about which is which.

## Suggested solution

- [x] Investigate: Can we differentiate between `prisma.$queryRaw("...")` and the prisma.$queryRaw template literal?

If so, 

- [x] Rename `prisma.$queryRaw("...")` to something else. Perhaps `$queryDangerouslyRaw`.
    
    I think there are since there are places where you can't use a prepared statement (e.g. CREATE TABLE "${table}"). If so, I don't think we want to disallow the capability entirely.

- [ ] Consider writing a codemod for `npx @prisma/codemods` to rename function calls (not template literals) to the new method

If not,

- Consider other alternatives for clearly separating these two behaviors

## Other Ideas

- Maybe it's possible for our VS Code extension to detect it and return a warning.
- Or maybe it's possible at runtime to detect that it's used the wrong way and throw an error?

### LINKED ISSUE #8189: `$queryRaw` availability isn't derived from the DMMF
Blocks/depends on: https://github.com/prisma/prisma-engines/pull/2087

If raw operations are not available for a connector, they are not rendered in the DMMF:
```js
// ...
"mappings": {
    "modelOperations": [
      {
        "model": "Parent",
        // ...
      },
      {
        "model": "Child",
        // ...
      }
    ],
    "otherOperations": {
      "read": [],
      "write": []
    }
  }
// ...
```

However, the generated client still allows `$queryRaw` without complaining. This should be based on the available queries of the engine.

This is the object for a connector with raw query availability:
```js
  "otherOperations": {
      "read": [],
      "write": [
        "executeRaw",
        "queryRaw"
      ]
    }
```

### LINKED ISSUE #8808: Add runtime check to `$queryRaw("...")` to throw for JS calls
Right now there's a type error for `$queryRaw("...")` in Typescript, but nothing stopping people from using the function form in Javascript. We should throw a runtime error instructing people to use either the tagged template or $queryRawUnsafe.

### PR DESCRIPTION
**Pull request by millsp**
Fixes https://github.com/prisma/prisma/issues/7142
Fixes https://github.com/prisma/prisma/issues/8189
Fixes https://github.com/prisma/prisma/issues/8808

BREAKING CHANGE

### CODE REVIEW

File: packages/client/src/__tests__/types/deprecation/test.ts [hunk 1]
```diff
@@ -30,7 +30,7 @@ async function main() {
 
   const queryRaw1 = await prisma.$queryRaw`SELECT * FROM User WHERE id = 1`
   const queryRaw2 = await prisma.$queryRaw`SELECT * FROM User WHERE id = ${1}`
-  const queryRaw3 = await prisma.$queryRaw(
+  const queryRaw3 = await prisma.$queryRawUnsafe(
```
Comment (matthewmueller) [inline packages/client/src/__tests__/types/deprecation/test.ts:33]: Interesting. I think with the new API, we'd just do:

```js
const queryRaw3 = await prisma.$queryRawUnsafe(`SELECT * FROM User WHERE id = ${2}`)
```

Instead of the prepared queries with variables. It's literally just sending this raw query string to the database.

Comment (matthewmueller) [reply packages/client/src/__tests__/types/deprecation/test.ts:33]: And of course:

```ts
await prisma.$queryRaw(`SELECT * FROM User WHERE id = ${1}`)
```

Would no longer be possible, since that's the point of this change.

Comment (matthewmueller) [reply packages/client/src/__tests__/types/deprecation/test.ts:33]: I like the word Unsafe btw :-)

File: packages/client/src/__tests__/types/deprecation/test.ts [hunk 2]
```diff
@@ -44,7 +44,7 @@ async function main() {
   const executeRaw1 = await prisma.$executeRaw`SELECT * FROM User WHERE id = 1`
   const executeRaw2 =
     await prisma.$executeRaw`SELECT * FROM User WHERE id = ${1}`
-  const executeRaw3 = await prisma.$executeRaw(
+  const executeRaw3 = await prisma.$executeRawUnsafe(
```
Comment (matthewmueller) [inline packages/client/src/__tests__/types/deprecation/test.ts:47]: Same here, I'm not sure of a reason to support more parameters since JS supports template strings.

File: packages/client/src/generation/TSClient/PrismaClient.ts [hunk 3]
```diff
@@ -103,32 +103,50 @@ export class PrismaClient<
...
+   * Executes a raw query and returns the number of affected rows.
+   * Susceptible to SQL injections, see documentation.
+   * @example
+   * \`\`\`
+   * const result = await prisma.$executeRawUnsafe('UPDATE User SET cool = $1 WHERE id = $2 ;', true, 1)
+   * \`\`\`
+   * 
+   * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/raw-database-access).
+   */
+  $executeRawUnsafe<T = unknown>(query: string, ...values: any[]): PrismaPromise<T>;
```
Comment (matthewmueller) [inline packages/client/src/generation/TSClient/PrismaClient.ts:126]: Love these comments

File: packages/client/src/__tests__/integration/errors/executeRaw-alter-postgres/test.ts [hunk 4]
```diff
@@ -33,22 +33,25 @@ test('executeRaw-alter-postgres', async () => {
       Using the example below you can still execute your query with Prisma, but please note that it is vulnerable to SQL injection attacks and requires you to take care of input sanitization.
```
Comment (Jolg42) [inline packages/client/src/__tests__/integration/errors/executeRaw-alter-postgres/test.ts:33]: This file and test are still called `executeRaw-alter-postgres` maybe we can rename them?

**Review by williamluke4 — APPROVED** [review]

**Review by Jolg42 — APPROVED** [review]

**Review by Jolg42 — CHANGES_REQUESTED** [review]
Looks good! (didn't review everything in detail yet though)

See comment

and what's the state of 
```
TODO:

    add runtime checks (exceptions)
```

Do not merge now I guess, only for next release?

**Comment by millsp** [comment]
@Jolg42 the current changes are TS-only changes, we'd like to add an error for JS users too (runtime).

**Comment by janpio** [comment]
Tracked in https://github.com/prisma/prisma/issues/8808 now

File: packages/client/src/__tests__/integration/happy/blog-env-mssql/test.ts [hunk 5]
```diff
@@ -179,13 +179,13 @@ describe('blog-env-mssql', () => {
   describe('$queryRaw', () => {
     test('$queryRaw(string)', async () => {
       await prisma.user.create({ data: { email: 'a@a.de', name: 'A' } })
-      const users = await prisma.$queryRaw('SELECT * FROM [dbo].[User]')
+      const users = await prisma.$queryRawUnsafe('SELECT * FROM [dbo].[User]')
       expect(users).not.toHaveLength(0)
     })
 
     test('$queryRaw(string) with params', async () => {
```
Comment (Jolg42) [inline packages/client/src/__tests__/integration/happy/blog-env-mssql/test.ts:186]:
```suggestion
    test('$queryRawUnsafe(string) with params', async () => {
```

File: packages/client/src/__tests__/integration/happy/blog-env-mssql/test.ts [hunk 6]
```diff
@@ -179,13 +179,13 @@ describe('blog-env-mssql', () => {
   describe('$queryRaw', () => {
     test('$queryRaw(string)', async () => {
```
Comment (Jolg42) [inline packages/client/src/__tests__/integration/happy/blog-env-mssql/test.ts:180]:
```suggestion
    test('$queryRawUnsafe(string)', async () => {
```

File: packages/client/src/__tests__/integration/happy/blog-env-mssql/test.ts [hunk 7]
```diff
@@ -229,13 +229,13 @@ describe('blog-env-mssql', () => {
   })
 
   describe('$executeRawUnsafe', () => {
```
Comment (Jolg42) [inline packages/client/src/__tests__/integration/happy/blog-env-mssql/test.ts:231]: describe says it's about executeRawUnsafe but I see there are tests about executeRaw also

File: packages/client/src/__tests__/integration/happy/blog-env-mssql/test.ts [hunk 8]
```diff
@@ -179,13 +179,13 @@ describe('blog-env-mssql', () => {
   describe('$queryRaw', () => {
```
Comment (Jolg42) [inline packages/client/src/__tests__/integration/happy/blog-env-mssql/test.ts:179]: describe says it's about queryRaw but I see there are tests about queryRawUnsafe also

Maybe split into another describe?

File: packages/client/src/runtime/getPrismaClient.ts [hunk 9]
```diff
@@ -691,7 +690,37 @@ export function getPrismaClient(config: GetPrismaClientOptions) {
...
+      ...values: any[]
+    ) {
+      if (
+        (query as TemplateStringsArray).raw ||
+        (query as sqlTemplateTag.Sql).sql
+      ) {
+        return this.$executeRawRequest(query, ...values)
       }
+
+      throw new PrismaClientValidationError(`\`$executeRaw\` is a tagged function, please use it like the following:
```
Comment (Jolg42) [inline packages/client/src/runtime/getPrismaClient.ts:717]:
```suggestion
      throw new PrismaClientValidationError(`\`$executeRaw\` is a tag function, please use it like the following:
```

Looks like it's either a tag function or a tagged template from search online?

**Review by Jolg42 — CHANGES_REQUESTED** [review]
Looks great! Added a few comments

And need to check the failing tests

```
FAIL src/__tests__/integration/happy/raw-transactions/test.ts (5.761 s)
  ● transaction › queryRaw

    All elements of the array need to be Prisma Client promises. Hint: Please make sure you are not awaiting the Prisma client calls you intended to pass in the $transaction function.

      977 |           !p?.isExecuteRaw
      978 |         ) {
    > 979 |           throw new Error(
          |                 ^
      980 |             `All elements of the array need to be Prisma Client promises. Hint: Please make sure you are not awaiting the Prisma client calls you intended to pass in the $transaction function.`,
      981 |           )
      982 |         }

      at PrismaClient.$___transactionInternal (src/runtime/getPrismaClient.ts:979:17)
      at PrismaClient.$___transaction (src/runtime/getPrismaClient.ts:1015:21)
      at PrismaClient.$transaction (src/runtime/getPrismaClient.ts:1031:21)
      at Object.<anonymous> (src/__tests__/integration/happy/raw-transactions/test.ts:21:30)
...
...
```

File: packages/client/src/__tests__/integration/happy/blog-env-mssql/test.ts [hunk 10]
```diff
@@ -270,5 +270,17 @@ describe('blog-env-mssql', () => {
         await prisma.$executeRaw`SELECT * FROM [dbo].[User] WHERE name = ${'F'}`
       expect(users).not.toBe(0)
     })
+
```
Comment (janpio) [inline packages/client/src/__tests__/integration/happy/blog-env-mssql/test.ts:273]:
```suggestion
})

describe('$*Raw errors', () => {
```

File: packages/client/src/__tests__/integration/happy/blog-env-mssql/test.ts (hunk 7 above)
Comment (janpio) [reply packages/client/src/__tests__/integration/happy/blog-env-mssql/test.ts:231]: https://github.com/prisma/prisma/pull/8728/files/4fcd61119798c5b5a91237b9a05b8dc3ab3f1baa..abcd6293b8d105b41251d8fdef26ea296db355e8#r702831558

File: packages/client/src/__tests__/integration/happy/blog-env-mssql/test.ts (hunk 8 above)
Comment (janpio) [reply packages/client/src/__tests__/integration/happy/blog-env-mssql/test.ts:179]: I think all tests actually are about `queryRawUnsafe` now, so:
```suggestion
  describe('$queryRawUnsafe', () => {
```

File: packages/client/src/__tests__/integration/happy/blog-env-mssql/test.ts (hunk 10 above)
Comment (Jolg42) [reply packages/client/src/__tests__/integration/happy/blog-env-mssql/test.ts:273]: i don't like it 😄 it's not great for doing a search

File: packages/client/src/runtime/getPrismaClient.ts (hunk 9 above)
Comment (Jolg42) [reply packages/client/src/runtime/getPrismaClient.ts:717]: If so needs to be done in other places as well

File: packages/client/src/__tests__/integration/happy/blog-env-mssql/test.ts (hunk 10 above)
Comment (janpio) [reply packages/client/src/__tests__/integration/happy/blog-env-mssql/test.ts:266]: You can spell it both out of course

**Review by Jolg42 — APPROVED** [review]
Pre-approval, for the small changes in progress

File: packages/client/src/runtime/getPrismaClient.ts (hunk 9 above)
Comment (millsp) [reply packages/client/src/runtime/getPrismaClient.ts]: Thanks!

**Review by Jolg42 — APPROVED** [review]
Nice documentation! 💚
