### PR TITLE
fix(client): middleware not being passed unpacker

### LINKED ISSUE #4948: Response of `count` queries changes when you have a middleware
## Bug description

When you use a middleware (even an "empty" one), it changes the response of `prisma.model.count()` queries.

## How to reproduce

Here are two scripts that should produce the same output, but don't:

```
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const main = async () => {
  console.log(await prisma.user.count());
};

main()
```

Output: `20` (expected)

vs.
```
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();
prisma.$use((params, next) => next(params));

const main = async () => {
  console.log(await prisma.user.count());
};

main()
```

Output: `{ _all: 20 }` (unexpected)

## Expected behavior

The output of both scripts should be `20`

## Prisma information

The schema is not relevant, I can observe this with multiple schemas

## Environment & setup

- OS: macOS
- Database: Postgres (but the issue does not depend on this)
- Node.js version: 14.15.1
- Prisma version:

```
@prisma/cli          : 2.15.0-dev.19
@prisma/client       : 2.15.0-dev.19
Current platform     : darwin
Query Engine         : query-engine 6b6ad7413a6b0c825e89eeac9adeb28830b1babb (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 6b6ad7413a6b0c825e89eeac9adeb28830b1babb (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 6b6ad7413a6b0c825e89eeac9adeb28830b1babb (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 6b6ad7413a6b0c825e89eeac9adeb28830b1babb (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.332.0
```

### PR DESCRIPTION
**Pull request by williamluke4**
fixes https://github.com/prisma/prisma/issues/4948

### CODE REVIEW

File: src/packages/client/src/runtime/getPrismaClient.ts [hunk 1]
```diff
@@ -989,6 +991,7 @@ new PrismaClient({
       transactionId,
       unpacker,
     }: InternalRequestParams) {
+      console.log(unpacker);
```
Comment (timsuchanek) [inline src/packages/client/src/runtime/getPrismaClient.ts:994]: Please cleanup and also add a test

**Review by timsuchanek — DISMISSED** [review]
Please cleanup and add a test
