### PR TITLE
fix(internals): avoid crash in prisma version, rename 'getVersion' -> 'getEngineVersion'

### LINKED ISSUE #14014: `prisma --version` crashes if `openssl` isn't properly installed
Compare `prisma --version` on a system where `openssl` is properly installed, with the same command on another system where `openssl` isn't available.

## With proper `openssl` installation

`prisma --version`

image

## Without `openssl` support

`prisma --version`

image

## Proposed Solution

Regardless of the errors that might arise while reading the versions and hashes of every internal package and engine `prisma` depends on, we should still try to display a table of all the versions we retrieved to `stdout`, and the list of possible errors we accumulated into `stderr`. If at least one error arises, let the process terminate with exit code `1`, but only after displaying a version table as complete as possible.

### PR DESCRIPTION
**Pull request by jkomyno**
Closes https://github.com/prisma/prisma/issues/14014.

### CODE REVIEW

**Comment by jkomyno** [comment]
Integration PR: https://github.com/prisma/prisma/pull/13739

**Comment by jkomyno** [comment]
Example `prisma --version` output in a machine without a proper `openssl` installation:

```
Error: Unable to require(`/home/prisma/.nvm/versions/node/v16.15.1/lib/node_modules/prisma/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node`)
 libssl.so.1.1: cannot open shared object file: No such file or directory
    at load (/home/prisma/.nvm/versions/node/v16.15.1/lib/node_modules/prisma/build/index.js:89433:11)
    at getBinaryVersion (/home/prisma/.nvm/versions/node/v16.15.1/lib/node_modules/prisma/build/index.js:89448:16)
Error: Command failed with exit code 127: /home/prisma/.nvm/versions/node/v16.15.1/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x --version
/home/prisma/.nvm/versions/node/v16.15.1/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
    at makeError (/home/prisma/.nvm/versions/node/v16.15.1/lib/node_modules/prisma/build/index.js:3673:18)
    at handlePromise (/home/prisma/.nvm/versions/node/v16.15.1/lib/node_modules/prisma/build/index.js:4426:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getBinaryVersion (/home/prisma/.nvm/versions/node/v16.15.1/lib/node_modules/prisma/build/index.js:89451:20) {
  shortMessage: 'Command failed with exit code 127: /home/prisma/.nvm/versions/node/v16.15.1/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x --version',
  command: '/home/prisma/.nvm/versions/node/v16.15.1/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x --version',
  escapedCommand: '"/home/prisma/.nvm/versions/node/v16.15.1/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x" --version',
  exitCode: 127,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '/home/prisma/.nvm/versions/node/v16.15.1/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Error: Command failed with exit code 127: /home/prisma/.nvm/versions/node/v16.15.1/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x --version
/home/prisma/.nvm/versions/node/v16.15.1/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
    at makeError (/home/prisma/.nvm/versions/node/v16.15.1/lib/node_modules/prisma/build/index.js:3673:18)
    at handlePromise (/home/prisma/.nvm/versions/node/v16.15.1/lib/node_modules/prisma/build/index.js:4426:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getBinaryVersion (/home/prisma/.nvm/versions/node/v16.15.1/lib/node_modules/prisma/build/index.js:89451:20) {
  shortMessage: 'Command failed with exit code 127: /home/prisma/.nvm/versions/node/v16.15.1/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x --version',
  command: '/home/prisma/.nvm/versions/node/v16.15.1/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x --version',
  escapedCommand: '"/home/prisma/.nvm/versions/node/v16.15.1/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x" --version',
  exitCode: 127,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '/home/prisma/.nvm/versions/node/v16.15.1/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
prisma                  : 3.16.0-integration-avoid-crash-in-prisma-version.1
@prisma/client          : Not found
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : E_CANNOT_RESOLVE_VERSION (at ../.nvm/versions/node/v16.15.1/lib/node_modules/prisma/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Introspection Engine    : E_CANNOT_RESOLVE_VERSION (at ../.nvm/versions/node/v16.15.1/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Migration Engine        : E_CANNOT_RESOLVE_VERSION (at ../.nvm/versions/node/v16.15.1/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 21b5f322ad1c14a1b28b18e805330f02df46f643 (at ../.nvm/versions/node/v16.15.1/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 21b5f322ad1c14a1b28b18e805330f02df46f643
Studio                  : 0.462.0

```

File: packages/cli/src/Version.ts [hunk 1]
```diff
@@ -74,29 +76,47 @@ export class Version implements Command {
 
     const platform = await getPlatform()
     const cliQueryEngineBinaryType = getCliQueryEngineBinaryType()
-    const introspectionEngine = await this.resolveEngine(BinaryType.introspectionEngine)
-    const migrationEngine = await this.resolveEngine(BinaryType.migrationEngine)
-    // TODO This conditional does not really belong here, CLI should be able to tell you which engine it is _actually_ using
```
Comment (Jolg42) [inline packages/cli/src/Version.ts:79]: Unsure what it was about

File: packages/cli/src/Version.ts [hunk 2]
```diff
@@ -74,29 +76,47 @@ export class Version implements Command {
...
+      ...enginesRows,
+
       ['Default Engines Hash', packageJson.dependencies['@prisma/engines'].split('.').pop()],
       ['Studio', packageJson.devDependencies['@prisma/studio-server']],
     ]
 
+    if (enginesMetaInfoErrors.length > 0) {
+      process.exitCode = 1
+      enginesMetaInfoErrors.forEach((e) => console.error(e))
+    }
```
Comment (Jolg42) [inline packages/cli/src/Version.ts:118]: Add a comment here? it's a bit obscure if one doesn't know

File: packages/sdk/src/engine-commands/getEnginesMetaInfo.ts [hunk 3]
```diff
@@ -0,0 +1,177 @@
...
+            (versionError) => ({ version: E.left(versionError), ...rest }),
+            (version) => ({ version: E.right(version), ...rest }),
+          ),
+        )
+        return result as T.Task<EngineInfoBinaryPathSuccess>
+      },
+    ),
+  )
+  return engineInfoBinaryTask
+}
```
Comment (Jolg42) [inline packages/sdk/src/engine-commands/getEnginesMetaInfo.ts:177]: Using `fp-ts` here, makes this code cryptic, it's hard to review and maintain. (the one letter "things" don't help and it's not obvious what `matchW` vs `matchEW` actually is without looking for documentation).

Is there a way to rewrite these cryptic parts, so we don't introduce too much complexity here?

File: packages/sdk/src/engine-commands/getEnginesMetaInfo.ts [hunk 4]
```diff
@@ -0,0 +1,177 @@
+import { getCliQueryEngineBinaryType } from '@prisma/engines'
+import { BinaryType } from '@prisma/fetch-engine'
+import * as E from 'fp-ts/Either'
+import { pipe } from 'fp-ts/lib/function'
+import * as O from 'fp-ts/Option'
+import * as T from 'fp-ts/Task'
+import * as TE from 'fp-ts/TaskEither'
+import fs from 'fs'
+import path from 'path'
+import { match, P } from 'ts-pattern'
```
Comment (Jolg42) [inline packages/sdk/src/engine-commands/getEnginesMetaInfo.ts:10]: ts-pattern `match` is nice

File: packages/sdk/src/engine-commands/getEnginesMetaInfo.ts (hunk 3 above)
Comment (jkomyno) [reply packages/sdk/src/engine-commands/getEnginesMetaInfo.ts:177]: This is a "wide" pattern matching of what's inside `safeResolveBinary`, which is a lazy promise that cannot throw any error at runtime. It acts as a destructor, doing a similar work as what `reduce` does for lists.
The `W` in `matchEW` and `matchW` stands for `Widen`: https://gcanti.github.io/fp-ts/guides/code-conventions.html#what-a-w-suffix-means-eg-chainw-or-chaineitherkw. This is needed to have proper type inference when a destructor returns two different types from its code paths (usually one for the "error" branch, another one for the "success" branch), and these types are part of the same union type.

The `E` in `matchEW` stands for `Effect`: https://gcanti.github.io/fp-ts/guides/code-conventions.html#what-an-e-suffix-means-eg-matche.

I'll see to improve the readability of this, though

File: packages/cli/src/Version.ts (hunk 2 above)
Comment (jkomyno) [reply packages/cli/src/Version.ts:118]:
```suggestion
    /**
     * If reading Rust engines metainfo (like their git hash) failed, display the errors to stderr,
     * and let Node.js exit naturally, but with error code 1.
     */
    if (enginesMetaInfoErrors.length > 0) {
      process.exitCode = 1
      enginesMetaInfoErrors.forEach((e) => console.error(e))
    }
```

File: packages/cli/src/Version.ts (hunk 1 above)
Comment (jkomyno) [reply packages/cli/src/Version.ts:79]: Found it, it was old: https://github.com/prisma/prisma/pull/7813/files#diff-10c45fc842f5a53e6a551a6103dfd55323d64393bd4fbbcc7ddcea546417d7e0

File: packages/internals/src/engine-commands/getBinaryVersion.ts [hunk 5]
```diff
@@ -0,0 +1,37 @@
...
+  }
+  enginePath = await resolveBinary(binaryName, enginePath)
+  if (binaryName === BinaryType.libqueryEngine) {
+    await isNodeAPISupported()
+
+    const QE = load<NodeAPILibraryTypes.Library>(enginePath)
+    return `libquery-engine ${QE.version().commit}`
+  } else {
+    const result = await execa(enginePath, ['--version'], {
+      maxBuffer: MAX_BUFFER,
```
Comment (Jolg42) [inline packages/internals/src/engine-commands/getBinaryVersion.ts:25]: `MAX_BUFFER` should not be needed here, the engine output will be small (for getDMMF it can be very large and then it's needed there)
The default is `Default: 100_000_000 (100 MB)` https://github.com/sindresorhus/execa#maxbuffer

File: packages/internals/src/engine-commands/getVersion.ts [hunk 6]
```diff
@@ -1,18 +1,16 @@
...
 
 import { resolveBinary } from '../resolveBinary'
 import { load } from '../utils/load'
 
-const debug = Debug('prisma:getVersion')
-
 const MAX_BUFFER = 1_000_000_000
 
-export async function getVersion(enginePath?: string, binaryName?: BinaryType): Promise<string> {
+export async function getBinaryVersion(enginePath?: string, binaryName?: BinaryType): Promise<string> {
```
Comment (Jolg42) [inline packages/internals/src/engine-commands/getVersion.ts:13]: I'm confused here, maybe you forgot to delete this file?
Since `packages/internals/src/engine-commands/getBinaryVersion.ts` exists now, it's a duplicate?

Comment (jkomyno) [reply packages/internals/src/engine-commands/getVersion.ts:13]: I think this is the result of `git merge main`. Since this file didn't get signaled as a merge conflict, git simply created a duplicate. Thanks for spotting it

File: packages/internals/src/engine-commands/getBinaryVersion.ts (hunk 5 above)
Comment (jkomyno) [reply packages/internals/src/engine-commands/getBinaryVersion.ts:25]: Thank you, please notice I didn't add `MAX_BUFFER` here. Should we change this in another PR, after this gets merged?

Comment (jkomyno) [reply packages/internals/src/engine-commands/getBinaryVersion.ts:25]: Actually, this is small enough we can do it in this PR

File: packages/internals/src/engine-commands/getEnginesMetaInfo.ts [hunk 7]
```diff
@@ -0,0 +1,178 @@
...
+    /**
+     * Extract EngineInfo from a library engine
+     */
+    const engineInfoLibrary: EngineInfoLibrary = {
+      ...resolvedVersion,
+      libraryPath: O.fromNullable(pathFromEnv),
+      fromEnvVar: O.fromNullable(envVar),
+    }
+    return engineInfoLibrary
+  }
```
[the remark this answers is not in the document]
Comment (jkomyno) [reply packages/internals/src/engine-commands/getEnginesMetaInfo.ts:163]: Ok, that was on me because I didn't read this line in `resolveBinary.ts`:

```ts
export const engineEnvVarMap = {
  [BinaryType.queryEngine]: 'PRISMA_QUERY_ENGINE_BINARY',
  [BinaryType.libqueryEngine]: 'PRISMA_QUERY_ENGINE_LIBRARY', // <----
  [BinaryType.migrationEngine]: 'PRISMA_MIGRATION_ENGINE_BINARY',
  [BinaryType.introspectionEngine]: 'PRISMA_INTROSPECTION_ENGINE_BINARY',
  [BinaryType.prismaFmt]: 'PRISMA_FMT_BINARY',
}
```

However, I did test [the most up to date code](https://github.com/prisma/prisma/pull/13737/commits/444b647945ac24b64ae96162026c44c7aed109b7) of this PR, and it still manages env vars for resolving the `library` and the `binary` (as shown in the private chat).
I will rephrase some vars and comments I have introduced in this PR to reflect this fact.

[the remark this answers is not in the document]
Comment (jkomyno) [reply packages/internals/src/engine-commands/getEnginesMetaInfo.ts]: In fact, this resulted in a bunch of simplifications 🎉

**Comment by jkomyno** [comment]
@janpio [your comment](https://github.com/prisma/prisma/pull/13973#discussion_r906272468) should be moved to this PR.

**Review by Jolg42 — APPROVED** [review]
👍🏼 🚢

**Comment by jkomyno** [comment]
Closes https://github.com/prisma/prisma/issues/14014.

**Comment by Jolg42** [comment]
Was reverted in https://github.com/prisma/prisma/pull/14025 because of an unexpected problem with `pkg` test

[Slack thread](https://prisma-company.slack.com/archives/CRGDU19K6/p1656094859878089)
