### PR TITLE
fix(client): Correctly handle object enums within query extensions

### LINKED ISSUE #18854: Cannot create record with Prisma.DbNull when clientExtensions enabled
### Bug description

I can't use `Prisma.DbNull` as data for a `Json?` column if I have the following clientExtension in use:

```
  query: {
    $allModels: {
      $allOperations({ model, operation, args, query }) {
        return query(args);

       }
    }
   }
```

Please see the MRE below for full detail

https://github.com/awinograd/prisma-repro/tree/db-null

### How to reproduce

1. Clone https://github.com/awinograd/prisma-repro/tree/db-null
2. Run `yarn dev:database`
3. Run `yarn dev`
4. Observe error

> Argument config: Provided value new Prisma.NullTypes.DbNull() of type DbNull on prisma.createOneUser is not a NullableJsonNullValueInput.
→ Possible values: NullableJsonNullValueInput.DbNull, NullableJsonNullValueInput.JsonNull

### Expected behavior

Record inserts with `NULL` for config column

### Prisma information

https://github.com/awinograd/prisma-repro/tree/db-null

### Environment & setup

- OS: MacOS
- Database: PostgresQL
- Node.js version: 16.13.1

### Prisma Version

```
prisma                  : 4.13.0
@prisma/client          : 4.13.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.13.0-50.1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a
Default Engines Hash    : 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a
Studio                  : 0.484.0
Preview Features        : clientExtensions
```

### LINKED ISSUE #18875: Extended client raw queries fail when using the Prisma.sql helper
### Bug description

Raw queries ($queryRaw or $executeRaw) throw an error if they are extended in a client extension and use the Prisma.sql helper

This fails ``prisma.$queryRaw(Prisma.sql`SELECT 1`);``
This also fails ``prisma.$queryRaw`SELECT ${Prisma.sql`1`}`;``
But this doesn't ``prisma.$queryRaw`SELECT 1`;``

```
TypeError: Cannot read properties of undefined (reading 'length')
    at new Sql (/project/sandbox/node_modules/@prisma/client/runtime/library.js:169:6674)
    at klona (/project/sandbox/node_modules/@prisma/client/runtime/library.js:164:9168)
    at klona (/project/sandbox/node_modules/@prisma/client/runtime/library.js:164:9454)
    at /project/sandbox/node_modules/@prisma/client/runtime/library.js:164:10164
    at _callback (/project/sandbox/node_modules/@prisma/client/runtime/library.js:164:2796)
    at PrismaPromise.then (/project/sandbox/node_modules/@prisma/client/runtime/library.js:164:2887)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### How to reproduce

```typescript
import { PrismaClient, Prisma } from '@prisma/client';

const prisma = new PrismaClient().$extends({
  query: {
    $allModels: {
      $allOperations: ({ query, args }) => {
        return query(args);
      },
      // OR
      // $queryRaw: ({ query, args }) => {
      //   return query(args);
      // },
    },
  },
});

(async () => {
  await prisma.$queryRaw(Prisma.sql`SELECT 1`);
})();
```

### Expected behavior

_No response_

### Prisma information

```prisma
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["clientExtensions"]
}
```

```ts
import { PrismaClient, Prisma } from '@prisma/client';

const prisma = new PrismaClient().$extends({
  query: {
    $allModels: {
      $allOperations: ({ query, args }) => {
        return query(args);
      },
      // OR
      // $queryRaw: ({ query, args }) => {
      //   return query(args);
      // },
    },
  },
});

(async () => {
  await prisma.$queryRaw(Prisma.sql`SELECT 1`);
})();
```

### Environment & setup

- Database: MySQL
- Node.js version: 18.12.0

### Prisma Version

```
prisma                  : 4.13.0
@prisma/client          : 4.13.0
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a (at node_modules/prisma/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a (at node_modules/prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-3.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.13.0-50.1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a
Default Engines Hash    : 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a
Studio                  : 0.484.0
```

### PR DESCRIPTION
**Pull request by SevInf**
Object enum variants are meant to be singletons. When query extensions
are used, `klona` created new instances which were not accepted by the
validator. Fixed by forking `klona` code and adapting it to our built in
types - now we won't clone object enums.

Side-effect of this change: since we are not using `klona` anymore, #18875 would also be fixed.

Fix #18854
Fix #18875

### CODE REVIEW

File: packages/client/src/runtime/utils/deepCloneArgs.ts [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+}
+
+function cloneRaw(rawParam: RawQueryArgs[0]): RawQueryArgs[0] {
+  if (rawParam instanceof Sql) {
+    return new Sql(rawParam.strings, rawParam.values)
+  }
+  return klona(rawParam)
+}
+
+// based on https://raw.githubusercontent.com/lukeed/klona/master/src/index.js
```
Comment (Jolg42) [inline packages/client/src/runtime/utils/deepCloneArgs.ts:37]:
```suggestion
// based on https://github.com/lukeed/klona/blob/v2.0.6/src/index.js
```
I think that's a better link? (includes the tag)

**Review by millsp — APPROVED** [review]
