### PR TITLE
fix: serialize Windows paths in NFT annotations properly

### LINKED ISSUE #9322: Prisma generates incompatible path on Windows
### Bug description

`prisma generate` creates a client as expected, but `index.js` file has incorrectly implemented path on Windows, so it throws

```bash
SyntaxError: Invalid Unicode escape sequence
```

index.js

```javascript
/**
 * Build tool annotations
 * In order to make `ncc` and `@vercel/nft` happy.
 * The process.cwd() annotation is only needed for https://github.com/vercel/vercel/tree/master/packages/now-next
**/
path.join(__dirname, 'query_engine-windows.dll.node');
path.join(process.cwd(), './bazel-out\x64_windows-fastbuild\bin\common\updates-prisma\prisma\query_engine-windows.dll.node')
/**
 * Annotation for `@vercel/nft`
 * The process.cwd() annotation is only needed for https://github.com/vercel/vercel/tree/master/packages/now-next
**/
path.join(__dirname, 'schema.prisma');
path.join(process.cwd(), './bazel-out\x64_windows-fastbuild\bin\common\updates-prisma\prisma\schema.prisma');
```

### How to reproduce

Run `prisma generate` on Windows

### Expected behavior

It should insert paths like this:

```js
path.join(process.cwd(), './bazel-out/x64_windows-fastbuild/bin/common/updates-prisma/prisma/schema.prisma');
```

or

```js
path.join(process.cwd(), './bazel-out\\x64_windows-fastbuild\\bin\\common\\updates-prisma\\prisma\\schema.prisma');
```

### Environment & setup

- OS: Windows 11
- Database: Mysql
- Node.js version: 14.17

### Prisma Version

```
prisma                  : 3.0.2
@prisma/client          : 3.0.2
Current platform        : windows
Query Engine (Node-API) : libquery-engine 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 2452cc6313d52b8b9a96999ac0e974d0aedf88db
Studio                  : 0.423.0
```

### PR DESCRIPTION
**Pull request by xnerhu**
This PR includes a simple solution to #9322, which is to replace `\` with `/`.

### CODE REVIEW

**Comment by millsp** [comment]
You can use `JSON.stringify` (see where `findSync` is used) to escape windows paths properly. As for the `./`, that should be replaced with `path.sep` so that it's multi-platform.

File: packages/client/src/generation/utils.ts [hunk 1]
```diff
@@ -366,6 +366,14 @@ export function unique<T>(arr: T[]): T[] {
 
   return result
 }
+
+/**
+ * Replaces \ to /
+ */
+export const fixPath = (path: string) => {
+  return path.replace(/\\/g, '/')
```
Comment (aqrln) [inline packages/client/src/generation/utils.ts:374]: It's an edge case, but on Linux and macOS files and directories may intentionally have backslashes in their names, and it would be incorrect to replace those with path separators.

**Comment by aqrln** [comment]
@millsp I rebased this PR and changed the approach to use `JSON.stringify` and native path separators, as per [your comment](https://github.com/prisma/prisma/pull/9371#issuecomment-927981012)

**Comment by millsp** [comment]
Thanks, let's give it a spin on e2e-tests.

**Comment by Jolg42** [comment]
Created the branch https://github.com/prisma/prisma/tree/integration/path-generation-fix

Release in progress at https://buildkite.com/prisma/release-prisma-typescript/builds/6110

**Review by millsp — APPROVED** [review]

**Comment by aqrln** [comment]
I just realized this didn't fail any tests (ideally it should have: single quotes were replaced by double quote as a side effect, so I'd expect some snapshots to fail), which means this piece of functionality might not be fully tested.

**Comment by Jolg42** [comment]
Indeed, we should add a test for this then

Notes:

Integration version is `3.10.0-integration-path-generation-fix.1`

Corresponding e2e tests (all 🟢) https://github.com/prisma/e2e-tests/actions/runs/1864112142
