### PR TITLE
fix: fix byte upserts by removing legacy byte array representation

### LINKED ISSUE #28824: Prisma v7 breaks postgres Byte upserts
### Bug description

Prisma v7 breaks postgres Byte upserts.

### Severity

🚨 Critical: Data loss, app crash, security issue

### Reproduction

Schema:
```prisma
datasource db {
  provider     = "postgresql"
  relationMode = "foreignKeys"
  extensions   = [pgcrypto]
}

generator client {
  provider        = "prisma-client"
  previewFeatures = ["relationJoins", "typedSql", "postgresqlExtensions"]
  output          = "../__generated__/prisma"
  engineType      = "library"
}

generator pothos {
  provider = "prisma-pothos-types"
  output   = "../__generated__/pothos-types.ts"
}

model TestByteId {
  id    Bytes  @id
  value String
}

model TestStringId {
  id    String @id
  value String
}
```

script
```ts
await prisma.$executeRaw`DROP TABLE IF EXISTS "Test" CASCADE`;
await prisma.$executeRaw`DROP TABLE IF EXISTS "Test2" CASCADE`;

const stringId = 'hello world!';
const upsertStringRow = () =>
  prisma.testStringId.upsert({
    create: {
      id: stringId,
      value: 'hello world!',
    },
    where: {
      id: stringId,
    },
    update: {},
  });

await upsertStringRow();
console.log('created string row');
await upsertStringRow();
console.log('updated string row');

const byteId = new Uint8Array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);
const upsertByteRow = () =>
  prisma.testByteId.upsert({
    create: {
      id: byteId,
      value: 'hello world!',
    },
    where: {
      id: byteId,
    },
    update: {},
  });

await upsertByteRow();
console.log('created byte row');
await upsertByteRow();
console.log('updated byte row');

await prisma.$disconnect();
```

### Expected vs. Actual Behavior

Expected:
```
created string row
updated string row
created byte row
updated byte row
```

Actual:
```
created string row
updated string row
created byte row

[error]
An operation failed because it depends on one or more records that were required but not found. No record was found for an upsert.
```

### Frequency

Consistently reproducible

### Does this occur in development or production?

Both development and production

### Is this a regression?

Worked in 6.12.0
Broken in 7.0.1

### Workaround

Works in 6.12.0

### Prisma Schema & Queries

See repro

### Prisma Config

_No response_

### Logs & Debug Info

_No response_

### Environment & Setup

- **OS:** OSX 15.6.1
- **Database:** Postgres 17
- **Node.js version:** v22.14.0

### Prisma Version

```
prisma               : 7.0.1
@prisma/client       : 7.0.1
Operating System     : darwin
Architecture         : arm64
Node.js              : v22.14.0
TypeScript           : 5.8.3
Query Compiler       : enabled
PSL                  : @prisma/prisma-schema-wasm 7.1.0-2.f09f2815f091dbba658cdcd2264306d88bb5bda6
Schema Engine        : schema-engine-cli f09f2815f091dbba658cdcd2264306d88bb5bda6 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Default Engines Hash : f09f2815f091dbba658cdcd2264306d88bb5bda6
Studio               : 0.8.2
```

### PR DESCRIPTION
**Pull request by jacek-prisma**
[TML-1683](https://linear.app/prisma-company/issue/TML-1683/fix-byte-array-upsert-issue)

Removes the legacy byte representation that used arrays. The old representation used arrays to make query arguments JSON serializable, which is something we no longer need. It was inefficient and it was also causing an edge case in the query renderer where it would interpret byte arrays as parameter lists.

Fixes https://github.com/prisma/prisma/issues/28824.

## Summary by CodeRabbit

* **Improvements**
  * Binary values are preserved as native binary (Buffer/Uint8Array) across adapters; byte arrays are no longer auto-converted to number arrays or re-encoded.
  * Result value types now accept Uint8Array and runtime truthiness treats Uint8Array like arrays.
  * Bytes/BytesArray no longer receive special serialization/transformation and pass through raw binary.

* **Tests**
  * Added functional tests for upserting records using byte-array IDs (skipped on SQL Server).

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: packages/client/tests/functional/bytes-upsert/_matrix.ts [hunk 1]
```diff
@@ -0,0 +1,4 @@
+import { defineMatrix } from '../_utils/defineMatrix'
+import { allProviders, Providers } from '../_utils/providers'
+
+export default defineMatrix(() => [allProviders.filter(({ provider }) => provider !== Providers.SQLSERVER)])
```
[the remark this answers is not in the document]
Comment (jacek-prisma) [reply packages/client/tests/functional/bytes-upsert/_matrix.ts:4]: Both are necessary in our tests

File: packages/client/tests/functional/bytes-upsert/tests.ts [hunk 2]
```diff
@@ -0,0 +1,42 @@
+import { randomBytes } from 'crypto'
+
+import testMatrix from './_matrix'
+// @ts-ignore
+import type { PrismaClient } from './generated/prisma/client'
+
```
[the remark this answers is not in the document]
Comment (jacek-prisma) [reply packages/client/tests/functional/bytes-upsert/tests.ts:6]: It is needed in our tests

File: packages/client/tests/functional/bytes-upsert/tests.ts [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+      // This second call was failing in v7 with "No record was found for an upsert"
+      await upsertByteRow() // Should not throw
+
+      // Verify the record exists and has correct data
+      const result = await prisma.testByteId.findUnique({
+        where: { bytes: byteId },
+      })
+      expect(result).toBeTruthy()
+      expect(result?.bytes).toEqual(byteId)
+    })
```
[the remark this answers is not in the document]
Comment (jacek-prisma) [reply packages/client/tests/functional/bytes-upsert/tests.ts:34]: doesn't matter in our tests

File: packages/adapter-neon/src/conversion.ts [hunk 4]
```diff
@@ -370,18 +359,11 @@ const parsePgBytes = getTypeParser(ScalarColumnType.BYTEA) as (_: string) => Buf
 const parseBytesArray = getTypeParser(ArrayColumnType.BYTEA_ARRAY) as (_: string) => Buffer[]
 
 function normalizeByteaArray(serializedBytesArray) {
-  const buffers = parseBytesArray(serializedBytesArray)
-  return buffers.map((buf) => (buf ? encodeBuffer(buf) : null))
+  return parseBytesArray(serializedBytesArray)
 }
```
[the remark this answers is not in the document]
Comment (jacek-prisma) [reply packages/adapter-neon/src/conversion.ts]: this line was not touched in the PR

File: packages/adapter-pg/src/conversion.ts [hunk 5]
```diff
@@ -383,18 +372,11 @@ const parsePgBytes = getTypeParser(ScalarColumnType.BYTEA) as (_: string) => Buf
 const parseBytesArray = getTypeParser(ArrayColumnType.BYTEA_ARRAY) as (_: string) => Buffer[]
 
 function normalizeByteaArray(serializedBytesArray) {
-  const buffers = parseBytesArray(serializedBytesArray)
-  return buffers.map((buf) => (buf ? encodeBuffer(buf) : null))
+  return parseBytesArray(serializedBytesArray)
 }
```
[the remark this answers is not in the document]
Comment (jacek-prisma) [reply packages/adapter-pg/src/conversion.ts]: this line was not touched in the PR

File: packages/adapter-d1/src/conversion.ts [hunk 6]
```diff
@@ -107,7 +107,7 @@ export function mapRow<A>(result: (A | ResultValue)[], columnTypes: ColumnType[]
     const value = result[i]
 
     if (value instanceof ArrayBuffer) {
-      result[i] = Array.from(new Uint8Array(value))
+      result[i] = Buffer.from(value)
```
Comment (aqrln) [inline packages/adapter-d1/src/conversion.ts]: I think it should be `new Uint8Array(value)`, we try to not use `Buffer` much anymore and we have even changed the public API in Prisma 6 to accept and return `Uint8Array`s. Especially here, since it's an adapter for Cloudflare D1, I'd expect a standard JS type and not a Node.js specific one.

File: packages/adapter-libsql/src/conversion.ts [hunk 7]
```diff
@@ -139,7 +139,7 @@ export function mapRow(row: Row, columnTypes: ColumnType[]): ResultValue[] {
     // logic that treats string values of type Bytes as raw UTF-8 bytes that was
     // implemented for other adapters.
     if (value instanceof ArrayBuffer) {
```
Comment (aqrln) [inline packages/adapter-libsql/src/conversion.ts]: Outdated comment

File: packages/adapter-libsql/src/conversion.ts [hunk 8]
```diff
@@ -139,7 +139,7 @@ export function mapRow(row: Row, columnTypes: ColumnType[]): ResultValue[] {
...
-      result[i] = Array.from(new Uint8Array(value))
+      result[i] = Buffer.from(value)
```
Comment (aqrln) [inline packages/adapter-libsql/src/conversion.ts]: likewise, let's not use `Uint8Array` and not `Buffer` unless absolutely necessary.

Even better, maybe we shouldn't even handle this case on this level, it should be the `DataMapper` that converts arbitrary `ArrayBuffer`s to `Uint8Array`s if necessary at all.

File: packages/adapter-neon/src/conversion.ts [hunk 9]
```diff
@@ -370,18 +359,11 @@ const parsePgBytes = getTypeParser(ScalarColumnType.BYTEA) as (_: string) => Buf
...
-/**
- * Convert bytes to a JSON-encodable representation since we can't
- * currently send a parsed Buffer or ArrayBuffer across JS to Rust
- * boundary.
- */
-function convertBytes(serializedBytes: string): number[] {
-  const buffer = parsePgBytes(serializedBytes)
-  return encodeBuffer(buffer)
+function convertBytes(serializedBytes: string): Buffer {
+  return parsePgBytes(serializedBytes)
```
Comment (aqrln) [inline packages/adapter-neon/src/conversion.ts]: Do we still need these wrapper functions? Should we maybe just use the underlying functions directly?

File: packages/adapter-libsql/src/conversion.ts (hunk 8 above)
Comment (jacek-prisma) [reply packages/adapter-libsql/src/conversion.ts]: I think it's better to have one 'expected' type for byte arrays, we even enforce it a lot of the time via `ResultValue`, which right now does not permit `ArrayBuffer`

File: packages/adapter-d1/src/conversion.ts (hunk 6 above)
Comment (jacek-prisma) [reply packages/adapter-d1/src/conversion.ts]: updated all calls that used either an arraybuffer or a view to use `new Uint8Array`

File: packages/adapter-libsql/src/conversion.ts (hunk 7 above)
Comment (jacek-prisma) [reply packages/adapter-libsql/src/conversion.ts]: 👍 
removed it

File: packages/adapter-neon/src/conversion.ts (hunk 9 above)
Comment (jacek-prisma) [reply packages/adapter-neon/src/conversion.ts]: I don't think so, removed them

File: packages/adapter-mssql/src/conversion.ts [hunk 10]
```diff
@@ -125,12 +125,8 @@ export function mapArg<A>(arg: A | BigInt | Date, argType: ArgType): null | numb
...
   }
 
-  if (Array.isArray(arg) && argType.scalarType === 'bytes') {
-    return Buffer.from(arg)
-  }
-
   if (ArrayBuffer.isView(arg)) {
-    return Buffer.from(arg.buffer, arg.byteOffset, arg.byteLength)
+    return new Uint8Array(arg.buffer, arg.byteOffset, arg.byteLength)
   }
```
[the remark this answers is not in the document]
Comment (jacek-prisma) [reply packages/adapter-mssql/src/conversion.ts:130]: fixed

File: packages/adapter-neon/src/conversion.ts [hunk 11]
```diff
@@ -444,13 +422,9 @@ export function mapArg<A>(arg: A | Date, argType: ArgType): null | unknown[] | s
...
 
-  if (Array.isArray(arg) && argType.scalarType === 'bytes') {
-    return Buffer.from(arg)
-  }
-
   // https://github.com/brianc/node-postgres/pull/2930
   if (ArrayBuffer.isView(arg)) {
-    return Buffer.from(arg.buffer, arg.byteOffset, arg.byteLength)
+    return new Uint8Array(arg.buffer, arg.byteOffset, arg.byteLength)
   }
```
[the remark this answers is not in the document]
Comment (jacek-prisma) [reply packages/adapter-neon/src/conversion.ts:428]: I don't think this is accurate based on my search, and also the tests pass with `Uint8Array`

File: packages/adapter-better-sqlite3/src/conversion.ts [hunk 12]
```diff
@@ -150,12 +150,8 @@ export function mapRow(row: Row, columnTypes: ColumnType[]): ResultValue[] {
...
     const value = row[i]
 
-    // Convert array buffers to arrays of bytes.
-    // Base64 would've been more efficient but would collide with the existing
-    // logic that treats string values of type Bytes as raw UTF-8 bytes that was
-    // implemented for other adapters.
-    if (value instanceof ArrayBuffer || value instanceof Buffer) {
-      result[i] = Array.from(new Uint8Array(value))
+    if (value instanceof ArrayBuffer) {
+      result[i] = new Uint8Array(value)
```
Comment (igalklebanov) [inline packages/adapter-better-sqlite3/src/conversion.ts]: `better-sqlite3` returns `Buffer` for `BLOB` affinity according to https://github.com/WiseLibs/better-sqlite3/blob/6209be238d6a1b181f516e4e636986604b0f62e1/docs/api.md?plain=1#L663.

`Buffer` is a subclass of `Uint8Array`.
`ArrayBuffer` is not an ancestor of `Uint8Array`.

This code seems to be unreachable.

File: packages/adapter-libsql/src/conversion.ts [hunk 13]
```diff
@@ -134,12 +134,8 @@ export function mapRow(row: Row, columnTypes: ColumnType[]): ResultValue[] {
   for (let i = 0; i < row.length; i++) {
     const value = row[i]
 
-    // Convert array buffers to arrays of bytes.
-    // Base64 would've been more efficient but would collide with the existing
-    // logic that treats string values of type Bytes as raw UTF-8 bytes that was
-    // implemented for other adapters.
     if (value instanceof ArrayBuffer) {
```
Comment (igalklebanov) [inline packages/adapter-libsql/src/conversion.ts:137]: See https://github.com/prisma/prisma/pull/28913/changes#r2619173013, which might be relevant here as well.

File: packages/adapter-better-sqlite3/src/conversion.ts (hunk 12 above)
Comment (jacek-prisma) [reply packages/adapter-better-sqlite3/src/conversion.ts]: the `ArrayBuffer` check was already there, maybe it's not needed, I'll remove it and see if tests still pass

File: packages/adapter-libsql/src/conversion.ts (hunk 13 above)
Comment (jacek-prisma) [reply packages/adapter-libsql/src/conversion.ts:137]: `libsql` defines the type for column values as
```
export type Value = null | string | number | bigint | ArrayBuffer
```
which I think means that they can indeed return an ArrayBuffer (removing the check gives a type error)

Comment (igalklebanov) [reply packages/adapter-libsql/src/conversion.ts:137]: What you mentioned:

https://github.com/tursodatabase/libsql-client-ts/blob/45634442fb2e9c395daf49394839a64dd449aca9/packages/libsql-core/src/api.ts#L460-L478

You're right.

**Review by igalklebanov — APPROVED** [review]
