### PR TITLE
fix(init): support SqlServer and MongoDB Preview with flag

### LINKED ISSUE #7900: `prisma init` for datasource providers in Preview/EarlyAccess
## Problem

Providers in Preview, like SQL Server or in Early Access like MongoDB need an extra preview feature flag.

We should add that flag automatically when using `prisma init --datasource-provider sqlserver.

### PR DESCRIPTION
**Pull request by Jolg42**
Add the corresponding preview flag to the default schema automatically.

Changed step 2 for MongoDB from
```
2. Run prisma db pull to turn your database schema into a Prisma schema.
```
to
```
2. Define models in the prisma.schema file.
```

Also check if the default url is good.

Feel free to give feedback here if that makes sense.

Closes https://github.com/prisma/prisma/issues/7900

### CODE REVIEW

File: src/packages/cli/src/Init.ts [hunk 1]
```diff
@@ -76,7 +94,7 @@ export const defaultURL = (
     case 'sqlserver':
       return `sqlserver://localhost:${port};database=mydb;user=SA;password=randompassword;`
     case 'mongodb':
-      return `mongodb://johndoe:randompassword@localhost:${port}/mydb?authSource=admin`
+      return `mongodb+srv://root:randompassword@cluster0.ab1cd.mongodb.net/mydb?retryWrites=true&w=majority`
```
Comment (millsp) [inline src/packages/cli/src/Init.ts:97]: Is this intended?

**Review by millsp — APPROVED** [review]

File: src/packages/cli/src/__tests__/__snapshots__/init.test.ts.snap [hunk 2]
```diff
@@ -8,9 +8,9 @@ Environment variables loaded from .env
 
 Next steps:
 1. Set the DATABASE_URL in the .env file to point to your existing database. If your database has no tables yet, read https://pris.ly/d/getting-started
-2. Set the provider of the datasource block in schema.prisma to match your database: postgresql, mysql, sqlserver or sqlite.
-3. Run prisma db pull to turn your database schema into a Prisma data model.
-4. Run prisma generate to install Prisma Client. You can then start querying your database.
+2. Set the provider of the datasource block in schema.prisma to match your database: postgresql, mysql, sqlite, sqlserver (Preview) or mongodb (Preview).
+3. Run prisma db pull to turn your database schema into a Prisma schema.
```
Comment (janpio) [inline src/packages/cli/src/__tests__/__snapshots__/init.test.ts.snap:12]: Technically "data model" is correct - it is the part of the schema file with `model`s inside.

But probably fine.

**Review by janpio — APPROVED** [review]

File: src/packages/cli/src/Init.ts (hunk 1 above)
Comment (Jolg42) [reply src/packages/cli/src/Init.ts:97]: I copy paste from example in the (not yet merged) docs, I guess it's what we want.
