### PR TITLE
test(client): regression test for directUrl

### LINKED ISSUE #17810: Prisma Client falsely validates `directUrl` env var value, leading to validation error (Affects PDP/Data Proxy and normal Engine)
We introduced `directUrl` in 4.10.0. Unfortuantely there is a problem, which leads to the `directUrl` env var validation to lead to a validation error on production if your do not _also_ set the env var behind `directUrl` - which makes no sense.

### PR DESCRIPTION
**Pull request by millsp**
closes https://github.com/prisma/prisma/issues/17810

### CODE REVIEW

File: packages/client/tests/functional/17810-direct-url-missing/tests.ts [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+ */
+testMatrix.setupTestSuite(({ provider }) => {
+  beforeAll(() => {
+    delete process.env[`DIRECT_DATABASE_URI_${provider}`]
+  })
+
+  test('doing a query', async () => {
+    await prisma.user.findMany()
+  })
+})
```
Comment (aqrln) [inline packages/client/tests/functional/17810-direct-url-missing/tests.ts:18]:
```suggestion
import { NewPrismaClient } from '../_utils/types'
import testMatrix from './_matrix'
// @ts-ignore
import type { PrismaClient } from './node_modules/@prisma/client'

let prisma: PrismaClient
declare let newPrismaClient: NewPrismaClient<typeof PrismaClient>

/**
 * Regression test for https://github.com/prisma/prisma/issues/17810
 */
testMatrix.setupTestSuite(
  ({ provider }) => {
    beforeEach(() => {
      delete process.env[`DIRECT_DATABASE_URI_${provider}`]
      prisma = newPrismaClient()
    })

    test('doing a query', async () => {
      await prisma.user.findMany()
    })
  },
  {
    skipDefaultClientInstance: true,
  },
)
```

**Review by aqrln — CHANGES_REQUESTED** [review]
This test passes both with and without engine changes because the engine is initialised before the environment variable is unset.

With the following patch (ignoring whitespace for clarity, `git diff --ignore-space-change`):

```diff
diff --git a/packages/client/tests/functional/17810-direct-url-missing/tests.ts b/packages/client/tests/functional/17810-direct-url-missing/tests.ts
index 2dc03c00a..87e7e8e56 100644
--- a/packages/client/tests/functional/17810-direct-url-missing/tests.ts
+++ b/packages/client/tests/functional/17810-direct-url-missing/tests.ts
@@ -1,18 +1,26 @@
+import { NewPrismaClient } from '../_utils/types'
 import testMatrix from './_matrix'
 // @ts-ignore
 import type { PrismaClient } from './node_modules/@prisma/client'
 
-declare let prisma: PrismaClient
+let prisma: PrismaClient
+declare let newPrismaClient: NewPrismaClient<typeof PrismaClient>
 
 /**
  * Regression test for https://github.com/prisma/prisma/issues/17810
  */
-testMatrix.setupTestSuite(({ provider }) => {
-  beforeAll(() => {
+testMatrix.setupTestSuite(
+  ({ provider }) => {
+    beforeEach(() => {
       delete process.env[`DIRECT_DATABASE_URI_${provider}`]
+      prisma = newPrismaClient()
     })
 
     test('doing a query', async () => {
       await prisma.user.findMany()
     })
-})
+  },
+  {
+    skipDefaultClientInstance: true,
+  },
+)
```

the test fails without https://github.com/prisma/prisma-engines/pull/3688 with the following error:

```
    error: Environment variable not found: DIRECT_DATABASE_URI_postgresql.
      -->  schema.prisma:10
       | 
     9 |       url      = env("DATABASE_URI_postgresql")
    10 |       directUrl = env("DIRECT_DATABASE_URI_postgresql")
       | 

    Validation Error Count: 1
```

but passes with that engine commit.

**Comment by millsp** [comment]
> This test passes both with and without engine changes because the engine is initialised before the environment variable is unset.

Not really, here's this same PR but with the previous engine https://github.com/prisma/prisma/pull/17827

**Comment by millsp** [comment]
That said, I can see how this can be flaky and inconsistent so I added your change :+1:

**Review by janpio — APPROVED** [review]

**Comment by aqrln** [comment]
@millsp 

> Not really, here's this same PR but with the previous engine https://github.com/prisma/prisma/pull/17827

Huh, that's weird, maybe I accidentally used too old engine that didn't have the validation yet? Thank you for double checking and sorry if it was a false alarm!

**Review by aqrln — APPROVED** [review]
