### PR TITLE
fix(webpack5): schema file not found

### LINKED ISSUE #6328: Prisma is not compatible with Next.js webpack5 opt-in
## Bug description

Next.js recently announced the move to Webpack 5, which is supported by opting-in with `next.config.js`: https://nextjs.org/docs/messages/webpack5

Prisma fails to initialize when used with Next.js when `future.webpack5` is `true`:

```
 API error: PrismaClientInitializationError2 [PrismaClientInitializationError]: 
 Invalid `prisma.account.findUnique()` invocation:
 
 
   Query engine exited with code 101
 
 thread 'main' panicked at 'Could not open datamodel file "/app/.next/server/pages/api/Account/schema.prisma"', query-engine/query-engine/src/opt.rs:187:53
 stack backtrace:
    0: rust_begin_unwind
              at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
    1: std::panicking::begin_panic_fmt
              at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:435:5
    2: query_engine::opt::load_datamodel_file::{{closure}}
    3: structopt::StructOpt::from_args
    4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
    5: std::thread::local::LocalKey<T>::with
    6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
    7: async_io::driver::block_on
    8: async_global_executor::reactor::block_on
    9: std::thread::local::LocalKey<T>::with
   10: async_std::task::builder::Builder::blocking
   11: query_engine::main
 note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
     at cb (webpack-internal:///./prisma/client/runtime/index.js:410:539)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:93:5)
     at async GET (webpack-internal:///./src/pages/api/Account/[id].ts:44:19)
     at async eval (webpack-internal:///./src/server/api.ts:50:16)
     at async apiResolver (/app/.yarn/$$virtual/next-virtual-32fc5bd849/0/cache/next-npm-10.1.2-24c2718295-97ce484973.zip/node_modules/next/dist/next-server/server/api-utils.js:8:1)
     at async DevServer.handleApiRequest (/app/.yarn/$$virtual/next-virtual-32fc5bd849/0/cache/next-npm-10.1.2-24c2718295-97ce484973.zip/node_modules/next/dist/next-server/server/next-server.js:67:462)
     at async Object.fn (/app/.yarn/$$virtual/next-virtual-32fc5bd849/0/cache/next-npm-10.1.2-24c2718295-97ce484973.zip/node_modules/next/dist/next-server/server/next-server.js:59:492)
     at async Router.execute (/app/.yarn/$$virtual/next-virtual-32fc5bd849/0/cache/next-npm-10.1.2-24c2718295-97ce484973.zip/node_modules/next/dist/next-server/server/router.js:25:67)
     at async DevServer.run (/app/.yarn/$$virtual/next-virtual-32fc5bd849/0/cache/next-npm-10.1.2-24c2718295-97ce484973.zip/node_modules/next/dist/next-server/server/next-server.js:69:1042)
     at async DevServer.handleRequest (/app/.yarn/$$virtual/next-virtual-32fc5bd849/0/cache/next-npm-10.1.2-24c2718295-97ce484973.zip/node_modules/next/dist/next-server/server/next-server.js:34:504) {
   clientVersion: '2.20.0',
   errorCode: undefined
 }
```

Prisma appears to be attempting to read the schema file from the wrong place.

## How to reproduce

1. Create Next.js project
2. Opt-in to webpack5 (see https://nextjs.org/docs/messages/webpack5)
3. Initialize Prisma 2.20.0 in project
4. Query database using Prisma Client in Next.js page

## Expected behavior

Prisma should not catastrophically fail to initialize

## Environment & setup

- OS: Debian
- Database: Postgres 13.2
- Node.js version: 14.16.0
- Prisma version: 2.20.0

### PR DESCRIPTION
**Pull request by millsp**
With `webpack5`, the `__dirname` is no longer equal to `/`, but the path of the bundled page like we would expect it. It causes the client to look for the `prisma` schema in the wrong folder. I added a workaround to support both `webpack@4` and `5`

fixes #6328

### CODE REVIEW

**Review by williamluke4 — APPROVED** [review]

File: src/packages/client/src/generation/TSClient/TSClient.ts [hunk 1]
```diff
@@ -81,7 +81,7 @@ export class TSClient implements Generatable {
     const code = `${commonCodeJS({ ...this.options, browser: false })}
 
 const dirnamePolyfill = path.join(process.cwd(), ${JSON.stringify(cwdDirname)})
-const dirname = __dirname.length === 1 ? dirnamePolyfill : __dirname
+const dirname = (__dirname.includes('.next/serverless') || __dirname === '/') ? dirnamePolyfill : __dirname
```
Comment (Jolg42) [inline src/packages/client/src/generation/TSClient/TSClient.ts:84]:
```suggestion
const dirname = (__dirname === '/' || __dirname.includes('.next/serverless')) ? dirnamePolyfill : __dirname
```
Maybe more generic case first and special case in second for the condition?

Comment (Jolg42) [reply src/packages/client/src/generation/TSClient/TSClient.ts:84]: also matching `'/'` makes me think that it could be a problem on windows, maybe revert to length === 1?

Comment (janpio) [inline src/packages/client/src/generation/TSClient/TSClient.ts:84]: Do we usually have framework specific things in this file? 
This feels like a very specialized solution for a more generic problem.

Comment (matthewmueller) [reply src/packages/client/src/generation/TSClient/TSClient.ts:84]: There's also `require('path').sep` I believe.

Comment (matthewmueller) [reply src/packages/client/src/generation/TSClient/TSClient.ts:84]: Yes, it's quite common, unfortunately. We have `if (netlify)` checks in some places too.

Comment (millsp) [reply src/packages/client/src/generation/TSClient/TSClient.ts:84]: The `dirnamePolyfill` was specifically made for `next` I think, some comment seems to point into this direction. I agree with you that this is not generic. I wanted to generalize the fix by using `process.cwd()` instead but it breaks many of our existing tests.

Because we cannot predict the state of the client (bundled or not, or in a different folder, in a build step or prod), it makes it difficult to use `__dirname`. I get the feeling that it might be a bad idea in this case. It would be easier to look relatively to the process rather than relatively to the file (we write the relative paths in the `config` variable in the generated client. Once bundled and moved around, those paths aren't valid anymore).

Comment (millsp) [reply src/packages/client/src/generation/TSClient/TSClient.ts]: I would expect things to be searched (binaries, schemas) relatively to the process unless a custom `output` path has been provided.

Comment (Jolg42) [reply src/packages/client/src/generation/TSClient/TSClient.ts]: Was reverted to `__dirname.length === 1`
