### PR TITLE
fix(db seed): redesign of db seed

### LINKED ISSUE #8732: EPIC: re-design of `db seed` feature
`prisma db seed` is currently a Preview feature.

During this phase, we noticed [different issues](https://github.com/prisma/prisma/issues?q=is%3Aissue+label%3A%22topic%3A+db+seed%22) caused by the complexity of the current implementation.

The Migrations Team decided to remove the complexity and make it a lot easier to understand for users and to maintain.

The new implementation is in https://github.com/prisma/prisma/pull/8146

How it will work is that a `prisma.seed` property in the `package.json` of your project will be required if you want to use `prisma db seed`.

The CLI will give examples that can be copy-pasted.

If you are currently using the previous implementation of `prisma db seed` and upgrade to this new version then it will throw an error with an upgrade help message which should be easy to fix (add `prisma.seed` to the `package.json`)

`package.json` example for a JavaScript project
```js
  "prisma": {
    "seed": "node prisma/seed.js"
  } 
```

`package.json` example for a TypeScript project
```js
  "prisma": {
    "seed": "ts-node prisma/seed.ts"
  }
```

Example of a `prisma/seed.js`
```js
async function main() {
  await new Promise((resolve) => setTimeout(resolve, 100))
  console.log('Hello from seed.js')
}

main()
  .then(() => console.log('Goodbye from seed.js'))
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
```

What needs to done for releasing the "new" `db seed`:
- [x] Review and merge https://github.com/prisma/prisma/pull/8146
- [x] QA db seed
- [x] Update docs https://github.com/prisma/docs/pull/2161
- [x] https://github.com/prisma/prisma/issues/8033 
- [x] e2e https://github.com/prisma/e2e-tests/issues/1806
- [ ] Update https://github.com/prisma/prisma/issues/5161
- [ ] Close issues and let users know that they can use the new version https://github.com/prisma/prisma/issues?q=is%3Aissue+label%3A%22topic%3A+db+seed%22+is%3Aopen

### PR DESCRIPTION
**Pull request by Jolg42**
Internal: https://www.notion.so/prismaio/db-seed-workshop-2a104a37762e4fb7bf3100c0227569ff

`prisma db seed` is currently a Preview feature.

During this phase, we noticed [different issues](https://github.com/prisma/prisma/issues?q=is%3Aissue+label%3A%22topic%3A+db+seed%22) caused by the complexity of the current implementation.

The Migrations Team decided to remove the complexity and make it a lot easier to understand for users and to maintain.

The new implementation is in this PR.

How it will work is that a `prisma.seed` property in the `package.json` of your project will be required if you want to use `prisma db seed`.

The CLI will give examples that can be copy-pasted.

If you are currently using the previous implementation of `prisma db seed` and upgrade to this new version then it will throw an error with an upgrade help message which should be easy to fix (add `prisma.seed` to the `package.json`)

`package.json` example for a JavaScript project
```js
  "prisma": {
    "seed": "node prisma/seed.js"
  } 
```

`package.json` example for a TypeScript project
```js
  "prisma": {
    "seed": "ts-node prisma/seed.ts"
  }
```

Example of a `prisma/seed.js`
```js
async function main() {
  await new Promise((resolve) => setTimeout(resolve, 100))
  console.log('Hello from seed.js')
}

main()
  .then(() => console.log('Goodbye from seed.js'))
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
```

`npx prisma db seed --preview-feature` results in something like
Screen Shot 2021-07-08 at 13 19 39

### if file path is invalid
Screen Shot 2021-07-08 at 13 23 44
Screen Shot 2021-07-08 at 13 23 29

### if seed exits with error
Screen Shot 2021-07-08 at 13 34 16
Screen Shot 2021-07-08 at 13 33 53

### if command is not found
Screen Shot 2021-07-08 at 14 06 55

### if we detect a seed.ts file but no "prisma.seed" in package.json 
Screen Shot 2021-07-08 at 14 07 40

### if we detect a seed.js file but no "prisma.seed" in package.json 
Screen Shot 2021-07-08 at 14 09 20

### if we detect a seed.sh file but no "prisma.seed" in package.json 
Screen Shot 2021-07-08 at 14 16 53

### If we didn't detect a seed.ts/.js/.sh we error with 
Screen Shot 2021-07-08 at 14 16 09

### CODE REVIEW

**Comment by Jolg42** [comment]
Can be tried with `2.27.0-integration-db-seed-new-behavior.1`

File: src/packages/migrate/src/utils/seed.ts [hunk 1]
```diff
@@ -1,47 +1,144 @@
...
+    )
+  }
+
+  return seedCommandFromPkgJson
+}
+
+export async function executeSeedCommand(command: string): Promise<boolean> {
+  console.info(`Running seed command \`${chalk.italic(command)}\` ...`)
+  try {
+    const result = await execa.command(command)
```
Comment (tomhoule) [inline src/packages/migrate/src/utils/seed.ts:127]: I am wondering about two things on how we execute the commands:

- Are we doing like npm and adding `.npm/bin` to the `PATH`?
- I don't know if we want to, but do we redirect stderr/stdout of the script to the stdout of migrate? It could be useful for debugging seed scripts. At the same time, it could become noisy and messy.

**Review by tomhoule — APPROVED** [review]
Very nice! The new code is nice and easy to follow.

**Comment by Jolg42** [comment]
New changes: warning in migrate dev and migrate reset (we error in db seed)

Screen Shot 2021-07-09 at 09 45 36

Screen Shot 2021-07-09 at 09 46 50

**Comment by Jolg42** [comment]
Can be tried with 
```
npx prisma@2.27.0-integration-db-seed-new-behavior.4 db seed --preview-feature
```

File: src/packages/migrate/src/__tests__/DbSeed.test.ts [hunk 2]
```diff
@@ -106,8 +106,8 @@ Please provide the --preview-feature flag to use this command.
     const result = DbSeed.new().parse(['--preview-feature'])
     await expect(result).resolves.toMatchInlineSnapshot(`
 
-                                                🌱  The seed command has been executed.
-                                        `)
+                                                                        🌱  The seed command has been executed.
+                                                            `)
```
Comment (janpio) [inline src/packages/migrate/src/__tests__/DbSeed.test.ts]: Something is wrong about the snapshot indentation again. This will keep happening it seems :/

Comment (Jolg42) [reply src/packages/migrate/src/__tests__/DbSeed.test.ts]: Yes, it's a recurrent thing we don't know why, "Jest"...

Comment (janpio) [reply src/packages/migrate/src/__tests__/DbSeed.test.ts]: You can just ignore these change and revert the lines so that the snapshots keeps making sense. They still match just fine.

File: src/packages/migrate/src/utils/seed.ts [hunk 3]
```diff
@@ -1,47 +1,165 @@
...
+  if (prismaConfig && prismaConfig.data?.seed) {
+    return undefined
+  }
+
+  // If new "seed" config is not set, help user to set it
+  const packageManager = hasYarn() ? 'yarn add -D' : 'npm i -D'
+
+  // TODO link to docs
+  let message = `${chalk.red(
+    'To configure seeding in your project you need to add a "seed" property in your package.json with the command to execute it:',
```
Comment (janpio) [inline src/packages/migrate/src/utils/seed.ts:38]: The error message currently does not mention that this is a sub property of the `prisma` object. Might be as simple as:
```suggestion
    'To configure seeding in your project you need to add a "prisma.seed" property in your package.json with the command to execute it:',
```

File: src/packages/migrate/src/utils/seed.ts [hunk 4]
```diff
@@ -1,47 +1,165 @@
...
+  )}
+
+1. Open the package.json of your project
+`
+
+  if (detected.numberOfSeedFiles === 1) {
+    // Probably was using seed before 2.27.0 and need to add the seed property in package.json
+    message += `2. Add the following example to it:`
```
Comment (janpio) [inline src/packages/migrate/src/utils/seed.ts:46]: why "following example"? Isn't this the concrete thing the user needs to add? So maybe "Add the following object"? Or should it maybe explain to add a "seed: ..." entry to the "prisma" object if it already exists?

File: src/packages/migrate/src/utils/seed.ts [hunk 5]
```diff
@@ -1,47 +1,165 @@
...
+    } else if (detected.ts) {
+      message += `
+\`\`\`
+"prisma": {
+  "seed": "ts-node ${detected.ts}"
+}
+\`\`\`
+
+3. Install the required dependencies by running:
+${chalk.green(`${packageManager} ts-node typescript @types/node`)}
```
Comment (janpio) [inline src/packages/migrate/src/utils/seed.ts:65]: Is this always required or might they already be present?
(Is a fair simplification to always show this)

File: src/packages/migrate/src/utils/seed.ts [hunk 6]
```diff
@@ -1,47 +1,165 @@
...
+      message += `
+\`\`\`
+"prisma": {
+  "seed": "${detected.sh}"
+}
+\`\`\`
+And run \`chmod +x ${detected.sh}\` to make it executable.`
+    }
+  } else {
+    message += `2. Add one of the following example to your package.json:
```
Comment (janpio) [inline src/packages/migrate/src/utils/seed.ts:77]:
```suggestion
    message += `2. Add one of the following examples to your package.json:
```

But the same applies as commented before: https://github.com/prisma/prisma/pull/8146/files#r667486929

Comment (janpio) [reply src/packages/migrate/src/utils/seed.ts:77]: Shouldn't this also mention that the `seed.x` file actually needs to be created?

File: src/packages/migrate/src/__tests__/DbSeed.test.ts [hunk 7]
```diff
@@ -67,213 +103,156 @@ describe('seed', () => {
...
+      `prisma:warn The "--schema" parameter is not used anymore by "prisma db seed" since 2.27.0 and can now be removed.`,
+    )
     expect(
       ctx.mocked['console.error'].mock.calls.join('\n'),
     ).toMatchInlineSnapshot(``)
   })
 
-  it('Custom --schema from package.json', async () => {
-    ctx.fixture('seed-sqlite-schema-from-package-json')
+  it('custom --schema from package.json should enrich help setup', async () => {
```
Comment (janpio) [inline src/packages/migrate/src/__tests__/DbSeed.test.ts:203]: What does "should enrich help setup" mean? Should it influence the path that is output in the setup help output?

**Review by janpio — COMMENTED** [review]
Looking good.

Do the new tests confirm that the actual seed command was successfully executed and output made it to the executing terminal?

File: src/packages/migrate/src/utils/seed.ts (hunk 5 above)
Comment (Jolg42) [reply src/packages/migrate/src/utils/seed.ts:65]: required to run the example seed.ts but might already be there

File: src/packages/migrate/src/__tests__/DbSeed.test.ts (hunk 7 above)
Comment (Jolg42) [reply src/packages/migrate/src/__tests__/DbSeed.test.ts:203]: Yes!

**Comment by Jolg42** [comment]
>Do the new tests confirm that the actual seed command was successfully executed and output made it to the executing terminal?

With the inherit of stdout I tried many ways to capture the logs but didn't succeed, I guess we can try in e2e.

**Comment by Jolg42** [comment]
New integration version available: `2.29.0-integration-db-seed-new-behavior.1`

File: packages/migrate/src/__tests__/fixtures/seed-sqlite-js-ts-default-export/package.json [hunk 8]
```diff
@@ -1,11 +1,11 @@
 {
-  "name": "seed-sqlite-js-ts-default-export",
+  "name": "seed-sqlite-sh",
```
Comment (janpio) [inline packages/migrate/src/__tests__/fixtures/seed-sqlite-js-ts-default-export/package.json:2]: package name not matching folder name?

File: packages/migrate/src/__tests__/fixtures/seed-sqlite-js-ts-named-export/package.json [hunk 9]
```diff
@@ -1,11 +1,11 @@
 {
-  "name": "seed-sqlite-js-ts-named-export",
+  "name": "seed-sqlite-js",
```
Comment (janpio) [inline packages/migrate/src/__tests__/fixtures/seed-sqlite-js-ts-named-export/package.json:2]: package name not matching folder name?

**Comment by benbender** [comment]
@janpio just tried `2.29.0-integration-db-seed-new-behavior.1` in my `sveltekit`-app. This app has `"type": "module",` in `package.json` to notify node that this is an es-module-package (default in sveltekit, many vite-apps and upcoming default for node). Additionally I'm writing my seeds in `Typescript`. 

With the proposed ts-node-setup the seed is failing as before:
````
> prisma db seed --preview-feature

Environment variables loaded from .env
Prisma schema loaded from db/schema.prisma
Running seed: ts-node "db/seed.ts" ...
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for [redacted]/db/seed.ts
````

What works though, is to  setup ts-node with it's experimental esm-loader: `"ts-node": "node --loader ts-node/esm",`

I think that should be at least reflected in docs/help as this kind of setup will get more common and more users will struggle with the advised setup failing...

**Review by williamluke4 — APPROVED** [review]
Great work Joel! :partying_face:

File: packages/migrate/src/__tests__/DbSeed.test.ts [hunk 10]
```diff
@@ -145,8 +145,8 @@ And run \`chmod +x prisma/seed.sh\` to make it executable.
     const result = DbSeed.new().parse(['--preview-feature'])
     await expect(result).resolves.toMatchInlineSnapshot(`
 
-                                                                                                            🌱  The seed command has been executed.
-                                                                                          `)
+                                                                                                                                    🌱  The seed command has been executed.
+                                                                                                              `)
```
[the remark this answers is not in the document]
Comment (Jolg42) [reply packages/migrate/src/__tests__/DbSeed.test.ts:149]: Not for my system, it's Jest snapshot logic, looks like a recent update might help on this
