### PR TITLE
fix(client): raw transactions

### LINKED ISSUE #4269: Sequential $transaction with $executeRaw
## Problem

We wish to run a series of `$executeRaw` queries in sequence using `$transaction`. Using prisma client `2.11.0`, the following:
```ts
try {
  await prisma.$transaction([
    prisma.$executeRaw`
      CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    `,
    prisma.$executeRaw`
      CREATE TABLE "Users" ("id" uuid PRIMARY KEY DEFAULT uuid_generate_v4());
    `,
    prisma.$executeRaw`
      CREATE TABLE "Groups" (userId uuid NOT NULL REFERENCES "Users");
    `,
  ]);
} catch (error) {
  console.error(error);
} finally {
  await prisma.$disconnect();
}
```
throws
```
Invalid `prisma.executeRaw()` invocation:


  Raw query failed. Code: `42P01`. Message: `db error: ERROR: relation "Users" does not exist`
```

## Suggested solution

We would like to be able to recreate something like

```sql
BEGIN;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE "Users" ("id" uuid PRIMARY KEY DEFAULT uuid_generate_v4());
CREATE TABLE "Groups" (userId uuid NOT NULL REFERENCES "Users");
COMMIT;
```

## Alternatives

For us, the only alternative is still to keep `pg` client around for schema migrations.

## Additional context

As mentioned in #3828, we have a simple schema migration system and wish replace the current pg client with prisma (which we are using for the rest of the application). The most critical migrations usually require multiple queries so until we can run each migration (which is a set of sql statements) in a transaction we have to keep both PostgreSQL clients.

*EDIT: wrong error message, also use extension*

### LINKED ISSUE #4331: Transaction items run outside Postgres transaction (breaks) with random order
## Bug description

While using the `prisma.$transaction` feature in `2.11.0`, transaction items run outside the Postgres transaction. Also the items of the JS-Array run in totally random order instead of sequential.

## How to reproduce

**Sample code:**

```js
const rawQuery = prisma.$queryRaw`SELECT * FROM USER`;
const updateUsers = prisma.user.updateMany({
  where: { name: 'A' },
  data: { name: 'B' },
});

prisma.$transaction([rawQuery, updateUsers]).then(console.log).catch(console.error);
```

**Result on first run:**
The raw query is the last before commit, instead of the first after BEGIN.

```console
prisma:query BEGIN
prisma:query SELECT "public"."User"."id" FROM "public"."User" WHERE "public"."User"."name" = $1
prisma:query UPDATE "public"."User" SET "name" = $1 WHERE "public"."User"."id" IN ($2,$3,$4,$5,$6,$7,$8)
prisma:query SELECT * FROM USER
prisma:query COMMIT
```

**Result on next run:**
Now the raw query runs even before BEGIN, outside the Postgres transaction.

```console
prisma:query SELECT * FROM USER
prisma:query BEGIN
prisma:query SELECT "public"."User"."id" FROM "public"."User" WHERE "public"."User"."name" = $1
prisma:query UPDATE "public"."User" SET "name" = $1 WHERE "public"."User"."id" IN ($2,$3,$4,$5,$6,$7,$8)
prisma:query COMMIT
```

**Result on any next run:**

The order of the lines above appears to be totally random. Some queries even run after COMMIT.

## Expected behavior

- Maintain sequential order of transactions
- Keep transactions inside BEGIN / COMMIT block

## Prisma information

```console
model User {
  id        String  @id @default(uuid())
  name      String
}
```

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 15.2.0
- Prisma version: 

```
@prisma/cli          : 2.11.0
@prisma/client       : 2.11.0
Current platform     : darwin
Query Engine         : query-engine 58369335532e47bdcec77a2f1e7c1fb83a463918 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 58369335532e47bdcec77a2f1e7c1fb83a463918 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 58369335532e47bdcec77a2f1e7c1fb83a463918 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 58369335532e47bdcec77a2f1e7c1fb83a463918 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.311.0
```

### LINKED ISSUE #4649: Mapped transactions should not be grouped together
## Bug description
If you do something like:
```typescript
await Promise.all(
    calendars.map(calendar =>
      ctx.prisma.$transaction<any>([...])
))
```

It will actually batch all the operations of the different transactions together. It doesn't seem to matter if I add an await on each transaction request.

## How to reproduce

1. Take any schema
2. Create an array of values to operation on
3. Map that array to a a transaction with one or more operations
4. Check prisma logs, you will see one `BEGIN` and one `COMMIT`

## Expected behavior

Each transaction should be independant.

## Prisma information
```
@prisma/cli          : 2.13.0
@prisma/client       : 2.13.0
Current platform     : darwin
Query Engine         : query-engine 833ab05d2a20e822f6736a39a27de4fc8f6b3e49 (at ../node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 833ab05d2a20e822f6736a39a27de4fc8f6b3e49 (at ../node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 833ab05d2a20e822f6736a39a27de4fc8f6b3e49 (at ../node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 833ab05d2a20e822f6736a39a27de4fc8f6b3e49 (at ../node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.329.0
```

### PR DESCRIPTION
**Pull request by timsuchanek**
Closes https://github.com/prisma/prisma/issues/4331
Closes https://github.com/prisma/prisma/issues/4269
Closes https://github.com/prisma/prisma/issues/4649
Fixes flaky test https://github.com/prisma/prisma/runs/1590604348

### CODE REVIEW

File: src/packages/engine-core/src/NodeEngine.ts [hunk 1]
```diff
@@ -199,6 +199,9 @@ export class NodeEngine {
     this.generator = generator
     this.datasources = datasources
     this.logEmitter = new EventEmitter()
+    this.logEmitter.on('error', () => {
+      // to prevent unhandled error events
```
Comment (williamluke4) [inline src/packages/engine-core/src/NodeEngine.ts:203]: Are the unhandled error events logged somewhere or just completely ignored?

**Review by williamluke4 — APPROVED** [review]
Nice 👍

File: src/packages/engine-core/src/NodeEngine.ts (hunk 1 above)
Comment (timsuchanek) [reply src/packages/engine-core/src/NodeEngine.ts:203]: Yeah so that's to work around the default behavior of Node.js.
If you have this code:
```ts
const EventEmitter = require('events')

const emitter = new EventEmitter()

emitter.emit('error', new Error('blub'))
```
Node will always throw an unhandled error exception.
However, in our case that's not what we want, as we already handle errors through the promises that are bound to queries. Our error events are just an additional optional way to log them.
