### PR TITLE
fix(engine-core): allow overriding datasource in Data Proxy client

### LINKED ISSUE #11595: Allow `dataproxy` to have datasource overrides
### Bug description

https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#programmatically-override-a-datasource-url

This does not currently work with the client being generated with `dataproxy`.

### How to reproduce

Instantiate the Prisma Client with a datasource override as described in the docs. Generate, with `PRISMA_CLIENT_ENGINE_TYPE=dataproxy`

### Expected behavior

That should be handled by `DataProxyEngine`.

### Prisma Version

```
3.9.1
```

### LINKED ISSUE #13771: Prisma Edge Client + CF Worker `process not defined`
### Bug description

Getting `process not found error` when deploying the prisma Edge client to Cloudflare pages. Isn the Edge client supposed to prevent this error from happening? I am only using the client in SvelteKit Endpoints https://kit.svelte.dev/docs/routing#endpoints

NOTE: I am using dot-env package to run the local dev script in package.json as prisma cannot find my .env DATABASE_URL var without this command (Maybe this is related to the issue?)

Err Log: 

` {
        text: 'Uncaught ReferenceError: process is not defined\n' +
          '  at line 8755 in node_modules/.prisma/client/edge.js\n' +
          '  at line 16 in __require2\n' +
          '  at line 8768 in node_modules/@prisma/client/edge.js\n' +
          '  at line 16 in __require2\n' +
          '  at line 8774\n' +
          '  at line 8789\n' +
          ' [code: 10021]'
      }
`

### How to reproduce

1. Set up Prisma data-proxy in SvelteKit following this instructions https://www.prisma.io/docs/concepts/data-platform/data-proxy
2. Deploy to CF pages and see that it builds successfully, but when visiting a page it will have the process not found error

You should be using the Edge Client and --data-proxy option with npx prisma generate. And your database_url should start wit prisma://

### Expected behavior

I'm not executing code that is meant for the server on the client so I dont understand why this error is happening

### Prisma information

I have a demo of the issue here https://github.com/vidiabtc/sveltekit-test

### Environment & setup

- OS: MacOS-->
- Database: MySQL
- Node.js version: v16.7.0

### Prisma Version

```
		"prisma": "^3.15.1",
		"@prisma/client": "^3.15.1",

```

### PR DESCRIPTION
**Pull request by aqrln**
Epic: https://github.com/prisma/client-planning/issues/24
Closes: https://github.com/prisma/prisma/issues/11595
Closes: https://github.com/prisma/prisma/issues/13771

### CODE REVIEW

File: packages/engine-core/src/data-proxy/DataProxyEngine.ts [hunk 1]
```diff
@@ -242,6 +239,50 @@ export class DataProxyEngine extends Engine {
...
+    if (datasource.url.value) {
+      return datasource.url.value
+    }
+
+    if (datasource.url.fromEnvVar) {
+      const envVar = datasource.url.fromEnvVar
+      const loadedEnvURL = this.env[envVar]
+
+      if (loadedEnvURL === undefined) {
+        throw new Error(`Datasource "${name}" references an environment variable "${envVar}" that is not set`)
```
Comment (millsp) [inline packages/engine-core/src/data-proxy/DataProxyEngine.ts:277]: Should we make this an `InvalidDatasourceError` ?

File: packages/engine-core/src/data-proxy/DataProxyEngine.ts [hunk 2]
```diff
@@ -242,6 +239,50 @@ export class DataProxyEngine extends Engine {
...
+      }
+
+      return loadedEnvURL
+    }
+
+    throw new Error(`Datasource "${name}" specification is invalid: both value and fromEnvVar are null`)
```
Comment (millsp) [inline packages/engine-core/src/data-proxy/DataProxyEngine.ts:283]: Same question here.

File: packages/engine-core/src/data-proxy/DataProxyEngine.ts [hunk 3]
```diff
@@ -242,6 +239,50 @@ export class DataProxyEngine extends Engine {
...
   }
 
+  private mergeOverriddenDatasources(): Record<string, InlineDatasource> {
+    if (this.config.datasources === undefined) {
+      return this.inlineDatasources
+    }
+
+    const finalDatasources = klona(this.inlineDatasources)
+
+    for (const override of this.config.datasources) {
```
Comment (millsp) [inline packages/engine-core/src/data-proxy/DataProxyEngine.ts:249]: That's when I wish we made blaze a utility library for all the packages :crying_cat_face: 😄:
```ts
return { ....inlineDatasources, ....map(config.datasources ?? {}, (d) => ({ url: { value: d.url } })) }
```

File: packages/engine-core/src/data-proxy/DataProxyEngine.ts [hunk 4]
```diff
@@ -242,6 +239,50 @@ export class DataProxyEngine extends Engine {
     return [host, apiKey]
   }
 
+  private mergeOverriddenDatasources(): Record<string, InlineDatasource> {
+    if (this.config.datasources === undefined) {
+      return this.inlineDatasources
+    }
+
+    const finalDatasources = klona(this.inlineDatasources)
```
Comment (millsp) [inline packages/engine-core/src/data-proxy/DataProxyEngine.ts:247]: Can you please check how much this increases the size of the edge bundle (if anything)?

Comment (millsp) [reply packages/engine-core/src/data-proxy/DataProxyEngine.ts:247]: (something to keep watching because it can easily explode. It's 263KB as of 4.1.0)

**Review by millsp — APPROVED** [review]
Looks good, thanks for making this work (+ see comments)

File: packages/client/src/runtime/getPrismaClient.ts [hunk 5]
```diff
@@ -402,6 +402,7 @@ export function getPrismaClient(config: GetPrismaClientConfig) {
             url,
           }))
 
+        // TODO: isn't it equivalent to just `inputDatasources` if the first argument is `[]`?
```
Comment (danstarns) [inline packages/client/src/runtime/getPrismaClient.ts:405]: I agree!

File: packages/engine-core/src/data-proxy/DataProxyEngine.ts (hunk 4 above)
Comment (aqrln) [reply packages/engine-core/src/data-proxy/DataProxyEngine.ts]: I simplified code based on your other comment so that the deep copy is not necessary anymore.

File: packages/engine-core/src/data-proxy/DataProxyEngine.ts (hunk 3 above)
Comment (aqrln) [reply packages/engine-core/src/data-proxy/DataProxyEngine.ts:248]: This way of thinking is still helpful even without the actual utility, I simplified code based on this comment, thank you!

File: packages/client/src/runtime/getPrismaClient.ts (hunk 5 above)
Comment (aqrln) [reply packages/client/src/runtime/getPrismaClient.ts:412]: Could be a good candidate for a deep dive
