### PR TITLE
fix(client): Default selection for composite lists

### LINKED ISSUE #19880: 4.16: Generated types for list composites are incorrect
### Bug description

Reading the 4.16 patch notes I don't see any communication about changes on MongoDB types but we experienced them.

Model 

```
model LegacyInterfaceOperation {
  idOperation   String          @id @default(auto()) @map("_id") @db.ObjectId
  operationType OperationType
  fileType      FileType
  status        OperationStatus
  previous      OperationStatus?
  next          OperationStatus?
  fromDate      DateTime?
  idInstitution Int
  interfacing   Int
  fileName      String
  fileUrl       String?
  parentDir     String?
  recordCount   Int             @default(0)
  retries       Int             @default(0)
  error         String?
  report        Json?
  createdAt     DateTime?       @default(now())
  updatedAt     DateTime?       @updatedAt
  metadata      OperationMetadata?

  @@map("legacyInterfaceOperation")
  @@index(idInstitution)
}
```

Type generated using 4.15

```
export type LegacyInterfaceOperation = {
  idOperation: string
  operationType: OperationType
  fileType: FileType
  status: OperationStatus
  previous: OperationStatus | null
  next: OperationStatus | null
  fromDate: Date | null
  idInstitution: number
  interfacing: number
  fileName: string
  fileUrl: string | null
  parentDir: string | null
  recordCount: number
  retries: number
  error: string | null
  report: Prisma.JsonValue | null
  createdAt: Date | null
  updatedAt: Date | null
  metadata: OperationMetadata | null
}
```

### How to reproduce

1. Update to 4.16
2. Generate Prisma Client
3. Observe new types

```
export type LegacyInterfaceOperation = runtime.Types.DefaultSelection<LegacyInterfaceOperationPayload>

export type LegacyInterfaceOperationPayload<ExtArgs extends $Extensions.Args = $Extensions.DefaultArgs> = {
  objects: {}
  scalars: $Extensions.GetResult<{
    idOperation: string
    operationType: OperationType
    fileType: FileType
    status: OperationStatus
    previous: OperationStatus | null
    next: OperationStatus | null
    fromDate: Date | null
    idInstitution: number
    interfacing: number
    fileName: string
    fileUrl: string | null
    parentDir: string | null
    recordCount: number
    retries: number
    error: string | null
    report: Prisma.JsonValue | null
    createdAt: Date | null
    updatedAt: Date | null
  }, ExtArgs["result"]["legacyInterfaceOperation"]>
  composites: {
    metadata: OperationMetadataPayload | null
  }
}
```

### Expected behavior

Can we get any insights on the change, or a migration guide? We were using the convient types from Prisma in some place of our apps but now there are new fields and such and I'm not sure the underlying behavior changed.

### Prisma information

See the model at the start of the issue.

### Environment & setup

- OS: MacOs
- Database: MongoDB
- Node.js version: 18.16

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 4.16.0
@prisma/client          : 4.16.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine b20ead4d3ab9e78ac112966e242ded703f4a052c (at node_modules/.pnpm/@prisma+engines@4.16.0/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli b20ead4d3ab9e78ac112966e242ded703f4a052c (at node_modules/.pnpm/@prisma+engines@4.16.0/node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.16.0-66.b20ead4d3ab9e78ac112966e242ded703f4a052c
Default Engines Hash    : b20ead4d3ab9e78ac112966e242ded703f4a052c
Studio                  : 0.484.0
```

### PR DESCRIPTION
**Pull request by SevInf**
Fix #19880

### CODE REVIEW

**Review by aqrln — APPROVED** [review]

File: packages/client/tests/functional/composites/selection/prisma/_schema.ts [hunk 1]
```diff
@@ -20,11 +20,16 @@ export default testMatrix.setupSchema(({ provider }) => {
...
   }
   
   type Name {
     firstName String
     lastName String
   }
+
+  type Thing {
+    name String
+  }
```
Comment (Jolg42) [inline packages/client/tests/functional/composites/selection/prisma/_schema.ts:33]: I'm wondering if we should also test like in https://github.com/prisma/prisma/blob/c6982ebf3d860444370f4b835b604fda94b92089/packages/client/src/__tests__/integration/happy/exhaustive-schema-mongo/schema.prisma#L37
For a composite type in a composite type

Comment (SevInf) [reply packages/client/tests/functional/composites/selection/prisma/_schema.ts:34]: I think only optional composite was missing? Added tests for that too.

**Review by Jolg42 — APPROVED** [review]
