### PR TITLE
fix(client): stricter json filtering

### LINKED ISSUE #3364: JSON fields filtering stopped working in 2.5.0
## Bug description

Filtering on JSON field (equals, not) stopped working in 2.5.0.

## How to reproduce

Running this code:

```ts
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient({});

async function main() {
  await prisma.$connect();
  await prisma.post.deleteMany({});

  await prisma.post.create({
    data: {
      title: "Post title 1",
      metadata: {
        published: true,
      },
    },
  });
  await prisma.post.create({
    data: {
      title: "Post title 2",
      metadata: {
        published: false,
      },
    },
  });
  await prisma.post.create({
    data: {
      title: "Post title 3",
      metadata: {
        otherKey: "otherValue",
      },
    },
  });

  const allPosts = await prisma.post.findMany();
  const publishedPosts = await prisma.post.findMany({
    where: {
      metadata: {
        equals: {
          published: true,
        },
      },
    },
  });
  const notPublishedPosts = await prisma.post.findMany({
    where: {
      metadata: {
        equals: {
          published: false,
        },
      },
    },
  });
  const notEqualsPublishedPosts = await prisma.post.findMany({
    where: {
      metadata: {
        not: {
          equals: {
            published: true,
          },
        },
      },
    },
  });
  
  console.log(
    util.inspect(
      {
        allPosts,
        publishedPosts,
        notPublishedPosts,
        notEqualsPublishedPosts,
      },
      false,
      null
    )
  );
}

main()
  .catch((e) => console.error(e))
  .finally(async () => {
    await prisma.$disconnect();
  });
```

Results in this:
```
{
  allPosts: [
    { id: 9, title: 'Post title 1', metadata: { published: true } },
    { id: 10, title: 'Post title 2', metadata: { published: false } },
    {
      id: 11,
      title: 'Post title 3',
      metadata: { otherKey: 'otherValue' }
    }
  ],
  publishedPosts: [],
  notPublishedPosts: [],
  notEqualsPublishedPosts: []
}
```

## Expected behavior

It should return properly filtered data.

## Prisma information

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Post {
  id       Int    @id @default(autoincrement())
  title    String
  metadata Json
}
```

## Environment & setup

- OS:  Windows 10 (WSL2 Ubuntu 20.04)
- Database:  Postgres
- Node.js version:  14
- Prisma version:
 
```
@prisma/cli          : 2.5.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 9a670138b1db276001d785a2adcba1584c869d24 (at node_modules/@prisma/cli/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 9a670138b1db276001d785a2adcba1584c869d24 (at node_modules/@prisma/cli/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 9a670138b1db276001d785a2adcba1584c869d24 (at node_modules/@prisma/cli/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 9a670138b1db276001d785a2adcba1584c869d24 (at node_modules/@prisma/cli/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.259.0
```

### PR DESCRIPTION
**Pull request by timsuchanek**
Closes #3364

### CODE REVIEW

File: src/packages/fetch-engine/src/getLatestTag.ts [hunk 1]
```diff
@@ -26,6 +26,10 @@ export async function getLatestTag(): Promise<any> {
   const result = await fetch(url, {
     agent: getProxyAgent(url),
   } as any).then((res) => res.json())
+  if (!Array.isArray(result)) {
+    console.log(result)
```
Comment (Jolg42) [inline src/packages/fetch-engine/src/getLatestTag.ts:30]: Maybe remove the console.log later?
```suggestion
```

File: src/packages/client/src/runtime/query.ts [hunk 2]
```diff
@@ -1000,16 +1000,18 @@ export function transformDocument(document: Document): Document {
...
-          && ar.schemaArg?.inputType[0].kind === 'object' 
-          && ar.key !== 'is' 
+          && ar.schemaArg?.inputType[0].kind === 'object'
+          && ar.key !== 'is'
+          && ar.argType !== 'Json'
           // do not add `is` on ...ListRelationFilter 
           // https://github.com/prisma/prisma/issues/3342
           && !(typeof ar.schemaArg?.inputType[0].type === 'object' && ar.schemaArg?.inputType[0].type.name.includes('ListRelationFilter'))
-          ) {
+          && !(typeof ar.argType === 'object' && (ar.argType as DMMF.InputType)?.name?.startsWith('Json'))
```
Comment (Jolg42) [inline src/packages/client/src/runtime/query.ts:1013]: What about the `NestedJsonNullableFilter`? I'm not sure if we need to do something about it 🤷‍♂️

File: src/packages/client/src/runtime/transformDmmf.ts [hunk 3]
```diff
@@ -119,7 +119,10 @@ function transformInputTypes(document: DMMF.Document): DMMF.Document {
 
           // there might not be an equals field, if it's a relation filter
           if (equalsField) {
-            f.inputType.unshift(equalsField.inputType[0])
+            if (equalsField.inputType[0].type !== 'Json') {
```
Comment (Jolg42) [inline src/packages/client/src/runtime/transformDmmf.ts:122]: Maybe we could use a comment here as it's hard to process everything that's happening in this file 😄

File: src/packages/client/src/__tests__/runtime-tests/blog-env-postgresql/index.js [hunk 4]
```diff
@@ -219,17 +219,19 @@ module.exports = async () => {
...
-      ],
+      jsonData: {
+        equals: [
+          {
+            array1key: 'array1value',
+          },
+        ]
+      },
     },
   })
```
Comment (Jolg42) [inline src/packages/client/src/__tests__/runtime-tests/blog-env-postgresql/index.js:236]: So only one query is a valid query?

I thought it was possible to do both and both should work?

Because we should test for both and probably add that to the MySQL / PostgeSQL integration tests I think

File: src/packages/client/src/runtime/query.ts (hunk 2 above)
Comment (timsuchanek) [reply src/packages/client/src/runtime/query.ts:1013]: What is `NestedJsonNullableFilter`?

File: src/packages/client/src/runtime/transformDmmf.ts (hunk 3 above)
Comment (timsuchanek) [reply src/packages/client/src/runtime/transformDmmf.ts:122]: Ok, will add commments :)

File: src/packages/client/src/__tests__/runtime-tests/blog-env-postgresql/index.js (hunk 4 above)
Comment (timsuchanek) [reply src/packages/client/src/__tests__/runtime-tests/blog-env-postgresql/index.js:236]: No, we decided back when we fixed it, that only the `equals` version is valid, as you otherwise get into hells kitchen.
If you e.g. have a json with the content `equals: {}` you can't query it.

Comment (Jolg42) [reply src/packages/client/src/__tests__/runtime-tests/blog-env-postgresql/index.js:236]: Yes I remember now 😅 
So without the equals is producing an error now? I'm curious off its result.

File: src/packages/client/src/runtime/query.ts (hunk 2 above)
Comment (Jolg42) [reply src/packages/client/src/runtime/query.ts:1013]: I do not know exactly but it's in the DMMF

File: src/packages/client/src/__tests__/runtime-tests/blog-env-postgresql/index.js (hunk 4 above)
Comment (timsuchanek) [reply src/packages/client/src/__tests__/runtime-tests/blog-env-postgresql/index.js:236]: Yes without equals it's producing an error. I'll add a test case for that.
