### PR TITLE
fix(client): delete transactionId field in middleware

### LINKED ISSUE #7584: Middleware + $transactions do not play well together
### Bug description

If I use a middleware to Client, then call a `prisma.$transaction`, then the middleware blocks query execution.

### How to reproduce

Assume this schema:

```
model User {
  id Int @id
  name String
}
```

I have a middlware that modifies Client responses to also include some extra parameters with it:

```
const prisma = new PrismaClient();

prisma.$use(async (params, next) => {
  let response = await next(params);
  console.log("middleware", response);
  return {
    params,
    response,
  };
});

  await prisma.$transaction([
    prisma.user.create({
      data: {
        id: "1",
        name: "Sid",
      },
    }),
  ]);
```

However:

1. The query doesn't get executed. I don't see this record in my database.
2. Instead of logging the Client response, the variabke `response` seems to be an async function. If I log `response.toString()`, it looks like calling `next` returns the actual `next` function. If I call this returned value again, like so:

```
prisma.$use(async (params, next) => {
  let response = await next(params);
  response = await (response as any)(params);
  console.log("middleware", response);
  return {
    params,
    response,
  };
});

  await prisma.$transaction([
    prisma.user.create({
      data: {
        id: "1",
        name: "Sid",
        age: 0,
      },
    }),
  ])
```

then everything works as expected. I see the correct log and the query gets executed.

### Expected behavior

_No response_

### Prisma information

model User {
  id Int @id
  name String
}

### Environment & setup

- OS: macOS
- Database: Postgres
- Node.js version: v14.17.0

### Prisma Version

This seems to only be happening on `dev`. Prisma 2.24.1 behaves as expected.

I'm on:

```
prisma               : 2.25.0-dev.31
@prisma/client       : 2.25.0-dev.31
Current platform     : darwin
Query Engine         : query-engine 89926e7ecbebb89657ae2b56ab3454364ad7b5c5 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 89926e7ecbebb89657ae2b56ab3454364ad7b5c5 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 89926e7ecbebb89657ae2b56ab3454364ad7b5c5 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 89926e7ecbebb89657ae2b56ab3454364ad7b5c5 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 89926e7ecbebb89657ae2b56ab3454364ad7b5c5
Studio               : 0.399.0
```

Internal Slack https://prisma-company.slack.com/archives/C016KUHB1R6/p1623327462109600

### PR DESCRIPTION
**Pull request by millsp**
Fixes https://github.com/prisma/prisma/issues/7584

https://github.com/prisma/e2e-tests/actions/runs/937511350

### CODE REVIEW

**Comment by janpio** [comment]
Available as `2.25.0-integration-fix-mw-tx.1` @madebysid (to fix Studio)

File: src/packages/client/src/runtime/getPrismaClient.ts [hunk 1]
```diff
@@ -915,45 +915,42 @@ new PrismaClient({
      * @param middlewareIndex
      * @returns
      */
-    private _request(
+    private async _request(
```
Comment (Jolg42) [inline src/packages/client/src/runtime/getPrismaClient.ts:918]: Why this change here?

File: src/packages/client/src/runtime/getPrismaClient.ts [hunk 2]
```diff
@@ -915,45 +915,42 @@ new PrismaClient({
...
-                  ...changedParams,
-                },
-                ++middlewareIndex,
-              ) // recursion happens over here
-            })
-          })
+          const changedInternalParams = { ...internalParams, ...params }
+
+          // TODO remove this, because transactionId should be passed?
+          if (index > 0) delete changedInternalParams['transactionId']
```
Comment (Jolg42) [inline src/packages/client/src/runtime/getPrismaClient.ts:947]: TODO for now?

**Comment by madebysid** [comment]
Can confirm that the version Jan quoted fixes Studio!

File: src/packages/client/src/runtime/getPrismaClient.ts [hunk 3]
```diff
@@ -915,45 +915,42 @@ new PrismaClient({
      * @param middlewareIndex
      * @returns
      */
-    private _request(
+    private async _request(
       internalParams: InternalRequestParams,
-      middlewareIndex = 0,
```
Comment (williamluke4) [inline src/packages/client/src/runtime/getPrismaClient.ts:920]: Why was this removed

File: src/packages/client/src/runtime/getPrismaClient.ts (hunk 1 above)
Comment (Jolg42) [inline src/packages/client/src/runtime/getPrismaClient.ts:918]:
```suggestion
    private _request(
```

This has performance implications, it's not needed.

File: src/packages/client/src/runtime/getPrismaClient.ts (hunk 2 above)
Comment (millsp) [reply src/packages/client/src/runtime/getPrismaClient.ts:945]: Yes

**Review by Jolg42 — APPROVED** [review]

**Review by williamluke4 — APPROVED** [review]

File: src/packages/client/src/runtime/getPrismaClient.ts (hunk 2 above)
Comment (millsp) [reply src/packages/client/src/runtime/getPrismaClient.ts:945]: We will need to remove this, because middlewares with transactions makes it not to be executed as a regular transaction (removes `transactionId`)

Comment (janpio) [reply src/packages/client/src/runtime/getPrismaClient.ts:945]: Can we make an issue out of this so we can remember and prioritize? Thanks.

Comment (millsp) [reply src/packages/client/src/runtime/getPrismaClient.ts:945]: This is preventing the transactions from rolling back. If enabled, transactions do rollback, but introduce those bugs we've seen on studio. https://github.com/prisma/prisma/issues/6705#issuecomment-861055614

**Review by pg38scf8dc — COMMENTED** [review]
Норм
