### PR TITLE
fix(client): test itx deadlocks

### LINKED ISSUE #11750: Interactive Transaction concurrent writes cause Prisma to hang
### Bug description

Most likely related to https://github.com/prisma/prisma/issues/8707

Here is a minimal repo, using postgres DB and Prisma 3.9.1: https://github.com/danielwong2268/test-prisma

When running several concurrent transactions, under some conditions Prisma hangs. Some variables that were toggled was the number of concurrent transactions, whether locking through `SELECT FOR UPDATE` was used, and whether a delay was introduced to the transaction. A different combination of these three variables yielded different results.

Further description and observations in the readme.

### How to reproduce

Go to minimal repo in Bug description and run through steps. `CONCURRENCY`, `WITH_LOCK`, and `ADD_DELAY` variables can be changed within the script.

My observations are here: https://github.com/danielwong2268/test-prisma#current-behavior

### Expected behavior

Running with CONCURRENCY=10 and WITH_LOCK=true and ADD_DELAY=true should work, and the final id should be 1 + 10 = 11.

### Prisma information

```
datasource db {
  provider = "postgresql"
  url      = "postgresql://postgres:postgres@localhost:5432/test-db"
}

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["interactiveTransactions"]
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User?   @relation(fields: [authorId], references: [id])
  authorId  Int?
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}

```

### Environment & setup

- OS: Mac OS 11.5.2
- Database: Postgres 13.3
- Node.js version: v14.17.3

### Prisma Version

```
prisma                  : 3.9.1
@prisma/client          : 3.9.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : bcc2ff906db47790ee902e7bbc76d7ffb1893009
Studio                  : 0.457.0
Preview Features        : interactiveTransactions
```

### PR DESCRIPTION
**Pull request by garrensmith**
The interactive transactions can deadlock when a SELECT ... FOR UPDATE
is used in a transaction.
This test is to show that the fix resolves it and makes sure this
never occurs again.

See https://github.com/prisma/prisma-engines/pull/2811 for a full explanation of the issue. This will need the prisma-engines PR to be merged before this test passes. 

This resolves https://github.com/prisma/prisma/issues/11750

### CODE REVIEW

File: packages/client/src/__tests__/integration/happy/interactive-transactions-postgres/test.ts [hunk 1]
```diff
@@ -575,6 +575,62 @@ describe('interactive transactions', () => {
...
+          await transactionPrisma.$queryRaw`SELECT id from "User" where email = 'x' FOR UPDATE`
+
+          const user = await transactionPrisma.user.findUnique({
+            rejectOnNotFound: true,
+            where: {
+              email: 'x',
+            },
+          })
+
+          await new Promise((r) => setTimeout(r, 100))
```
Comment (millsp) [inline packages/client/src/__tests__/integration/happy/interactive-transactions-postgres/test.ts:606]: Worth adding a comment why this is necessary/useful.

File: packages/client/src/__tests__/integration/happy/interactive-transactions-postgres/test.ts [hunk 2]
```diff
@@ -575,6 +575,62 @@ describe('interactive transactions', () => {
 
     expect(users.length).toBe(0)
   })
+
+  /**
+   * Makes sure that the engine can process when the transaction has locks inside
```
Comment (millsp) [inline packages/client/src/__tests__/integration/happy/interactive-transactions-postgres/test.ts:580]: Can you please add a link to your original PR?

**Review by millsp — APPROVED** [review]
Awesome! Thank you for fixing this. Looks good (+see comments).
