### PR TITLE
fix(client): do not discard extra args

### LINKED ISSUE #11556: Count does not work with where
### Bug description

When passing the `where` to `prisma.relation.count`, the parameters are not considered, as if they had not been passed

## The code

```
console.log('query without where')

const c = await prisma.user.count()

console.log(`response: ${c}\n\n`)

console.log('query with where id = 1')

const d = await prisma.user.count({
  where: {
    id: 1
  }
})

console.log(`response: ${d}`)
```

## The result

```
query without where
prisma:info Starting a postgresql pool with 5 connections.
prisma:query SELECT COUNT(*) FROM (SELECT "public"."users"."id" FROM "public"."users" WHERE 1=1 OFFSET $1) AS "sub"
response: 24


query with where id = 1
prisma:query SELECT COUNT(*) FROM (SELECT "public"."users"."id" FROM "public"."users" WHERE 1=1 OFFSET $1) AS "sub"
response: 24
```

### Expected behavior

_No response_

### Prisma information

They are in "How to reproduce"

### Environment & setup

- OS: `KDE neon 5.23`
- Database:  `PostgreSQL 13.3`
- Node.js version: `v16.13.2`

### Prisma Version

```
prisma                  : 3.9.0
@prisma/client          : 3.9.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : bcc2ff906db47790ee902e7bbc76d7ffb1893009
Studio                  : 0.457.0
```

### PR DESCRIPTION
**Pull request by millsp**
We lacked tests on `count` and a regression was introduced. Added more tests and fixed the issue.

### CODE REVIEW

File: packages/client/src/__tests__/integration/happy/count/test.ts [hunk 1]
```diff
@@ -1,68 +1,165 @@
...
-      ?       id?: true
+  test('select all true', async () => {
+    const value = await prisma.user.count({
+      select: true,
+    })
+
+    expect(value).toMatchInlineSnapshot(`10`)
+  })
+
+  // TODO: this should happen but we always make selects to become true
```
Comment (aqrln) [inline packages/client/src/__tests__/integration/happy/count/test.ts:76]: We should create an issue for this 👍

Comment (millsp) [reply packages/client/src/__tests__/integration/happy/count/test.ts:76]: Definitely. The reason why I chose not to fix this is that it's been behaving like this before this regression even.

File: packages/client/src/runtime/core/model/aggregates/count.ts [hunk 2]
```diff
@@ -9,15 +10,17 @@ import { aggregate } from './aggregate'
  * @param modelAction a callback action that triggers request execution
  * @returns
  */
-export function count(client: Client, userArgs: object | undefined, modelAction: ModelAction) {
+export function count(client: Client, userArgs: UserArgs | undefined, modelAction: ModelAction) {
   // count is an aggregate, we reuse them but hijack their unpacker
 
+  const { select, ..._userArgs } = userArgs ?? {} // exclude select
   if (typeof userArgs?.['select'] === 'object') {
```
Comment (aqrln) [inline packages/client/src/runtime/core/model/aggregates/count.ts:17]: `userArgs?.['select']` can now be replaced with just `select` here and below

File: packages/client/src/runtime/core/model/aggregates/groupBy.ts [hunk 3]
```diff
@@ -10,13 +11,15 @@ import { desugarUserArgs as desugarUserArgsAggregate } from './aggregate'
...
+function desugarUserArgs(userArgs: UserArgs) {
   const _userArgs = desugarUserArgsAggregate(userArgs)
 
   // we desugar the array into { [key]: boolean }
-  if (Array.isArray(userArgs?.['by']) === true) {
-    for (const key of userArgs?.['by'] ?? []) {
-      _userArgs['select'][key] = true
+  if (Array.isArray(userArgs['by'])) {
+    for (const key of userArgs['by']) {
+      if (_userArgs['select'] && typeof key === 'string') {
```
Comment (aqrln) [inline packages/client/src/runtime/core/model/aggregates/groupBy.ts:20]: Is the first check here to make the type checker happy? As far as I understand, `_userArgs['select']` is always present since it's the result of `desugarUserArgsAggregate`.

File: packages/client/src/__tests__/integration/happy/count/test.ts (hunk 1 above)
Comment (aqrln) [reply packages/client/src/__tests__/integration/happy/count/test.ts:76]: yep, that would definitely be out of scope

File: packages/client/src/runtime/core/model/aggregates/groupBy.ts (hunk 3 above)
Comment (millsp) [reply packages/client/src/runtime/core/model/aggregates/groupBy.ts:20]: Yep, probably overkill, I adjusted the return type in the parent call instead.

File: packages/client/src/__tests__/integration/happy/count/test.ts (hunk 1 above)
Comment (millsp) [reply packages/client/src/__tests__/integration/happy/count/test.ts:76]: Actually, thinking about it, I don't think it's a problem. If a user does not want to make a selection with `select: false` that still means that he wants to count (but without any selection), hence `select: true` in any case.

Comment (millsp) [reply packages/client/src/__tests__/integration/happy/count/test.ts:76]: (it's confusing from a code logic point of view, but makes sense from a user point of view)

**Review by aqrln — APPROVED** [review]

File: packages/client/src/runtime/core/model/aggregates/groupBy.ts [hunk 4]
```diff
@@ -10,13 +11,15 @@ import { desugarUserArgs as desugarUserArgsAggregate } from './aggregate'
...
 
   // we desugar the array into { [key]: boolean }
-  if (Array.isArray(userArgs?.['by']) === true) {
-    for (const key of userArgs?.['by'] ?? []) {
-      _userArgs['select'][key] = true
+  if (Array.isArray(userArgs['by'])) {
+    for (const key of userArgs['by']) {
+      if (typeof key === 'string') {
+        _userArgs['select'][key] = true
+      }
```
Comment (Jolg42) [inline packages/client/src/runtime/core/model/aggregates/groupBy.ts:22]: Seems that `if (typeof key === 'string') {` is new here, what is its purpose in this context? (add a comment maybe?)

Comment (millsp) [reply packages/client/src/runtime/core/model/aggregates/groupBy.ts:22]: It's to keep the checker happy (it was `any` before).

File: packages/client/src/__tests__/integration/happy/count/test.ts (hunk 1 above)
Comment (Jolg42) [reply packages/client/src/__tests__/integration/happy/count/test.ts:76]: It would be nice to have a test case with `select all false` that is passing so it changes the test will catch it right away.
With a comment for the test

File: packages/client/src/runtime/core/model/aggregates/aggregate.ts [hunk 5]
```diff
@@ -65,7 +66,7 @@ export function createUnpacker(userArgs: object) {
  * @param modelAction a callback action that triggers request execution
  * @returns
  */
-export function aggregate(client: Client, userArgs: object | undefined, modelAction: ModelAction) {
+export function aggregate(client: Client, userArgs: UserArgs | undefined, modelAction: ModelAction) {
```
Comment (Jolg42) [inline packages/client/src/runtime/core/model/aggregates/aggregate.ts:69]:
```suggestion
export function aggregate(client: Client, userArgs: UserArgs, modelAction: ModelAction) {
```

UserArgs type can be undefined I see, so undefined again here is no necessary I think

Comment (Jolg42) [reply packages/client/src/runtime/core/model/aggregates/aggregate.ts:69]: This change might be needed in other places

File: packages/client/src/runtime/core/model/UserArgs.ts [hunk 6]
```diff
@@ -0,0 +1,8 @@
+/**
+ * Input that flows from the user into the Client.
+ */
+export type UserArgs = {
+  [K in string]: UserArgsProp | UserArgsProp[]
+}
+
+type UserArgsProp = UserArgs | string | number | boolean | bigint | object | null | undefined
```
Comment (Jolg42) [inline packages/client/src/runtime/core/model/UserArgs.ts:8]: The original type I could see previous code is `object | undefined`, here it expands the possibilities a lot, and I'm unsure if all are needed? (trying to think about it, but a quick chat would help probably)

File: packages/client/src/runtime/core/model/aggregates/aggregate.ts (hunk 5 above)
Comment (millsp) [reply packages/client/src/runtime/core/model/aggregates/aggregate.ts:69]: `UserArgs` is not undefined but its properties can.

Comment (Jolg42) [reply packages/client/src/runtime/core/model/aggregates/aggregate.ts:69]: Ok I'm definitely not at my best these 2 days 😅

**Review by Jolg42 — APPROVED** [review]
Let's get this into a patch release now 🚢
