### PR TITLE
fix(client): allow prisma.empty to $executeRaw & $queryRaw

### LINKED ISSUE #11233: Cannot pass Prisma.empty to $executeRaw function
### Bug description

We have a function which generates raw queries based on its input. then the generated query will be passed to `$executeRaw` to run it. in some conditions, the function may return `Prisma.empty`. In this case Prisma throws a PrismaClientValidationError 

we had no problems in version 2.30.3, This happened after upgrading "prisma" & "@prisma/client" version  to 3.8.1 

### How to reproduce

`await db.$executeRaw(Prisma.empty);`

throws this error: 
```
    PrismaClientValidationError: `$executeRaw` is a tag function, please use it like the following:
    const result = await prisma.$executeRaw`UPDATE User SET cool = ${true} WHERE email = ${'user@email.com'};`
    
    Or read our docs at https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#executeraw
```

### Expected behavior

to run it without any errors. preferably don't issue any queries if the input is `Prisma.empty`

### Prisma information

N/A

### Environment & setup

- OS: Debian
- Database: PostgreSQL
- Node.js version: 14.17.6

### Prisma Version

```
10.1.0
```

### PR DESCRIPTION
**Pull request by danstarns**
Closes: https://github.com/prisma/prisma/issues/11233

Having issues passing an empty sql stmt to the db and so return null when its empty.

### CODE REVIEW

File: packages/client/src/runtime/getPrismaClient.ts [hunk 1]
```diff
@@ -680,7 +680,12 @@ export function getPrismaClient(config: GetPrismaClientConfig) {
      * @returns
      */
     $executeRaw(query: TemplateStringsArray | sqlTemplateTag.Sql, ...values: any[]) {
-      return createPrismaPromise((txId, lock, otelCtx) => {
+      return createPrismaPromise(async (txId, lock, otelCtx): Promise<unknown> => {
+        const isInstanceOfSQL = query.constructor.name === 'Sql'
+        if (isInstanceOfSQL && (query as { sql: string }).sql === '') {
+          return null
+        }
```
Comment (aqrln) [inline packages/client/src/runtime/getPrismaClient.ts:687]: Should we maybe make `isInstanceOfSQL` a type guard?

Something like

```ts
function isSql(value: unknown): value is sqlTemplateTag.Sql {
  return value.constructor.name === 'Sql'
}
```

and then, here

```ts
if (isSql(query) && query.sql === '') {
  return null
}
```

No strong opinion though, if you don't find it more readable, then  it's also fine as it is.

**Review by aqrln — COMMENTED** [review]
Looks good overall, just a couple of comments

File: packages/client/src/runtime/getPrismaClient.ts [hunk 2]
```diff
@@ -680,7 +680,12 @@ export function getPrismaClient(config: GetPrismaClientConfig) {
...
+
         if ((query as TemplateStringsArray).raw || (query as sqlTemplateTag.Sql).sql) {
```
Comment (millsp) [inline packages/client/src/runtime/getPrismaClient.ts:689]:
```suggestion
        if ((query as TemplateStringsArray).raw !== undefined || (query as sqlTemplateTag.Sql).sql !== undefined) {
```

This should be enough.

**Review by millsp — CHANGES_REQUESTED** [review]
The same problem applies to `$queryRaw`, I believe.

File: packages/client/src/runtime/getPrismaClient.ts (hunk 1 above)
Comment (danstarns) [reply packages/client/src/runtime/getPrismaClient.ts]: Sure I added it!

File: packages/client/src/runtime/getPrismaClient.ts [hunk 3]
```diff
@@ -680,8 +681,12 @@ export function getPrismaClient(config: GetPrismaClientConfig) {
...
      */
     $executeRaw(query: TemplateStringsArray | sqlTemplateTag.Sql, ...values: any[]) {
-      return createPrismaPromise((txId, lock, otelCtx) => {
-        if ((query as TemplateStringsArray).raw || (query as sqlTemplateTag.Sql).sql) {
+      return createPrismaPromise(async (txId, lock, otelCtx): Promise<unknown> => {
+        if (isSql(query) && query.sql === '') {
+          return null
+        }
+
+        if ((query as TemplateStringsArray).raw !== undefined || (query as sqlTemplateTag.Sql).sql !== undefined) {
```
Comment (aqrln) [inline packages/client/src/runtime/getPrismaClient.ts:689]: I wonder if the previous (the newly added) check is now necessary or just adding `!== undefined` here is enough to fix the bug.

File: packages/client/src/runtime/getPrismaClient.ts [hunk 4]
```diff
@@ -856,7 +861,11 @@ Or read our docs at https://www.prisma.io/docs/concepts/components/prisma-client
      * @returns
      */
     $queryRaw(query: TemplateStringsArray | sqlTemplateTag.Sql, ...values: any[]) {
-      return createPrismaPromise((txId, lock, otelCtx) => {
+      return createPrismaPromise(async (txId, lock, otelCtx): Promise<unknown> => {
+        if (isSql(query) && query.sql === '') {
+          return null
+        }
+
         if ((query as TemplateStringsArray).raw || (query as sqlTemplateTag.Sql).sql) {
```
Comment (aqrln) [inline packages/client/src/runtime/getPrismaClient.ts:869]: This should also probably be changed the same way

```suggestion
        if ((query as TemplateStringsArray).raw !== undefined || (query as sqlTemplateTag.Sql).sql !== undefined) {
```

File: packages/client/src/runtime/getPrismaClient.ts (hunk 3 above)
Comment (millsp) [reply packages/client/src/runtime/getPrismaClient.ts:689]: I think the check can now be removed

Comment (danstarns) [reply packages/client/src/runtime/getPrismaClient.ts:689]: This check needs to be here because we cannot send an empty string to the DB. So the newly added check returns null if the string is empty.

```
Invalid `prisma.$executeRaw()` invocation:


      Raw query failed. Code: `1065`. Message: `Query was empty`

      48980 |       message = this.sanitizeMessage(message);
      48981 |       if (e.code) {
    > 48982 |         throw new PrismaClientKnownRequestError(message, e.code, this.client._clientVersion, e.meta);
            |               ^
      48983 |       } else if (e.isPanic) {
      48984 |         throw new PrismaClientRustPanicError(message, this.client._clientVersion);
      48985 |       } else if (e instanceof PrismaClientUnknownRequestError) {

      at RequestHandler.request (../../runtime/index.js:48982:15)
      at Proxy._request (../../runtime/index.js:49888:18)
      at Object.<anonymous> (empty-to-raw/tests.ts:11:22)
```

**Review by millsp — CHANGES_REQUESTED** [review]
Let's fix https://github.com/prisma/prisma/pull/13656/files#r902878957 and merge 🚀

File: packages/client/src/runtime/getPrismaClient.ts (hunk 3 above)
Comment (danstarns) [reply packages/client/src/runtime/getPrismaClient.ts:697]: Sure it could be seen as breaking! I have reverted the changes I made and instead now assert the error could be thrown or the `0` or the `[]`. My reason for adding the null return is because it's deterministic, easier to reason about/document plus the issue expected 'to run it without any errors. preferably don't issue any queries if the input is Prisma.empty'.

File: packages/client/tests/functional/empty-to-raw/tests.ts [hunk 5]
```diff
@@ -0,0 +1,90 @@
...
+        case 'sqlserver':
+          expect(result).toEqual([])
+          break
+
+        case 'mysql':
+          expect((result as Error).message).toContain('Raw query failed. Code: `1065`. Message: `Query was empty`')
+          break
+
+        default:
+          throw new Error('invalid prodiver')
```
Comment (millsp) [inline packages/client/tests/functional/empty-to-raw/tests.ts:80]:
```suggestion
          throw new Error('invalid provider')
```

Comment (danstarns) [reply packages/client/tests/functional/empty-to-raw/tests.ts:80]: good catch!

File: packages/client/src/runtime/getPrismaClient.ts [hunk 6]
```diff
@@ -693,8 +693,8 @@ export function getPrismaClient(config: GetPrismaClientConfig) {
      * @returns
      */
     $executeRaw(query: TemplateStringsArray | sqlTemplateTag.Sql, ...values: any[]) {
-      return createPrismaPromise((txId, lock, otelCtx) => {
-        if ((query as TemplateStringsArray).raw || (query as sqlTemplateTag.Sql).sql) {
+      return createPrismaPromise(async (txId, lock, otelCtx): Promise<unknown> => {
```
Comment (danstarns) [inline packages/client/src/runtime/getPrismaClient.ts:696]:
```suggestion
      return createPrismaPromise(async (txId, lock, otelCtx) => {
```

File: packages/client/src/runtime/getPrismaClient.ts [hunk 7]
```diff
@@ -693,8 +693,8 @@ export function getPrismaClient(config: GetPrismaClientConfig) {
      * @returns
      */
     $executeRaw(query: TemplateStringsArray | sqlTemplateTag.Sql, ...values: any[]) {
-      return createPrismaPromise((txId, lock, otelCtx) => {
-        if ((query as TemplateStringsArray).raw || (query as sqlTemplateTag.Sql).sql) {
+      return createPrismaPromise(async (txId, lock, otelCtx) => {
```
Comment (danstarns) [inline packages/client/src/runtime/getPrismaClient.ts:696]:
```suggestion
      return createPrismaPromise((txId, lock, otelCtx) => {
```

File: packages/client/tests/functional/empty-to-raw/tests.ts [hunk 8]
```diff
@@ -0,0 +1,90 @@
...
+          expect(result).toEqual([])
+          break
+
+        case 'cockroachdb':
+          expect(result).toEqual([])
+          break
+
+        case 'sqlserver':
+          expect(result).toEqual([])
+          break
```
Comment (Jolg42) [inline packages/client/tests/functional/empty-to-raw/tests.ts:73]:
```suggestion
        case 'postgresql':
        case 'cockroachdb':
        case 'sqlserver':
          expect(result).toEqual([])
          break
```
Can be simplified

File: packages/client/tests/functional/empty-to-raw/tests.ts [hunk 9]
```diff
@@ -0,0 +1,90 @@
...
+          expect(result).toEqual(0)
+          break
+
+        case 'cockroachdb':
+          expect(result).toEqual(0)
+          break
+
+        case 'sqlserver':
+          expect(result).toEqual(0)
+          break
```
Comment (Jolg42) [inline packages/client/tests/functional/empty-to-raw/tests.ts:36]:
```suggestion
        case 'postgresql':
        case 'cockroachdb':
        case 'sqlserver':
          expect(result).toEqual(0)
          break
```

**Review by millsp — APPROVED** [review]
