### PR TITLE
fix(client): improve error links

### LINKED ISSUE #865: Generated Github issue creation links do often not include helpful information
This repo reproduces a problem and causes 3 errors: https://github.com/divyendu-test/prisma-client-js-797

These are the links created automatically by Prisma Client for these errors:
https://github.com/prisma/prisma-client-js/issues/862
https://github.com/prisma/prisma-client-js/issues/863
https://github.com/prisma/prisma-client-js/issues/864

On first look the "Logs" of these issues do not look very helpful. As we have a clear reproduction here, we can double check what _would_ be helpful and possibly improve our logic that collects the information included in the issue.

Many more issues from real users can be found via https://github.com/prisma/prisma-client-js/labels/topic%3A%20basic%20reporting%20issue

### PR DESCRIPTION
**Pull request by timsuchanek**
Closes prisma/prisma-client-js#865

### CODE REVIEW

File: src/packages/engine-core/src/NodeEngine.ts [hunk 1]
```diff
@@ -839,9 +845,11 @@ ${this.lastErrorLog.fields.file}:${this.lastErrorLog.fields.line}:${this.lastErr
 
         // don't wait for this
         void (async () => {
-          const engineVersion = await this.version()
-          debug(`Client Version ${this.clientVersion}`)
-          debug(`Engine Version ${engineVersion}`)
+          const engineVersion = await this.version(true)
+          debug(`Client Version: ${this.clientVersion}`)
+          debug(`Engine Version: ${engineVersion}`)
+          const activeProvider = await this.getActiveProvider()
```
Comment (timsuchanek) [inline src/packages/engine-core/src/NodeEngine.ts:851]: Potentially related to test failure

File: src/packages/engine-core/src/NodeEngine.ts [hunk 2]
```diff
@@ -938,6 +946,12 @@ ${this.lastErrorLog.fields.file}:${this.lastErrorLog.fields.line}:${this.lastErr
     return this.getConfigPromise
   }
 
+  async getActiveProvider(): Promise<ConnectorType> {
+    const config = await this.getConfig()
+    this.lastActiveProvider = config.datasources[0].activeProvider
```
Comment (timsuchanek) [inline src/packages/engine-core/src/NodeEngine.ts:955]: Potentially related to test failure

File: src/packages/engine-core/src/NodeEngine.ts [hunk 3]
```diff
@@ -1039,7 +1065,11 @@ ${this.lastErrorLog.fields.file}:${this.lastErrorLog.fields.line}:${this.lastErr
       transaction,
     }
 
-    this.currentRequestPromise = this.undici.request(JSON.stringify(body))
+    const stringifiedQuery = JSON.stringify(body)
+
+    this.currentRequestPromise = this.undici!.request(stringifiedQuery)
```
Comment (timsuchanek) [inline src/packages/engine-core/src/NodeEngine.ts:1074]: Potentially related to test failure

File: src/packages/engine-core/src/NodeEngine.ts [hunk 4]
```diff
@@ -1123,6 +1145,17 @@ ${this.lastErrorLog.fields.file}:${this.lastErrorLog.fields.line}:${this.lastErr
     }
   }
 
+  private getErrorMessageWithLink(title: string) {
+    return getErrorMessageWithLink({
```
Comment (timsuchanek) [inline src/packages/engine-core/src/NodeEngine.ts:1153]: Potentially related to test failure

File: src/packages/engine-core/src/byline.ts [hunk 5]
```diff
@@ -65,7 +65,7 @@ function LineStream(options) {
   this._lastChunkEndedWithCR = false
 
   // take the source's encoding if we don't have one
-  this.on('pipe', function (src) {
+  this.on('pipe', function (this, src) {
```
Comment (timsuchanek) [inline src/packages/engine-core/src/byline.ts:68]: Potentially related to test failure
