### PR TITLE
fix(client, mssql): multi param for prepared statements

### LINKED ISSUE #6276: Error when using `join` raw query helper with SQL Server
## Bug description

Hello, this is most likely MS SQL Server specific.

I'm trying to run a raw query with an `IN` clause for which I'm using the `Prisma.join()` helper, as shown [here](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#tagged-template-helpers).

I get the following error:
```
PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]:
Invalid `prisma.queryRaw()` invocation:


  Raw query failed. Code: `245`. Message: `Conversion failed when converting the nvarchar value '{"values":[1,2,3],"strings":["",",",",",""],"text":"$1,$2,$3","sql":"?,?,?"}' to data type int.`
```

## How to reproduce

1. Connect to an sql server database
2. Run a raw query with the following bit in the `where` clause: `IN (${Prisma.join(ids)})` - where `ids` is an array of numbers.

## Expected behavior

Expected the query to return results.

## Environment & setup

- OS: Windows 10
- Database: Microsoft SQL Server
- Node.js version: 14.16.0
- Prisma version: 2.18.0

### PR DESCRIPTION
**Pull request by millsp**
Fixes https://github.com/prisma/prisma/issues/6276

E2E https://github.com/prisma/e2e-tests/actions/runs/973308128

### CODE REVIEW

File: src/packages/client/src/__tests__/integration/happy/blog-env-mssql/test.ts [hunk 1]
```diff
@@ -18,8 +19,9 @@ describe('blog-env-mssql', () => {
     await setupMSSQL(setupParams)
 
     await generateTestClient()
-    const { PrismaClient } = require('./node_modules/@prisma/client')
+    const { PrismaClient, Prisma } = require('./node_modules/@prisma/client')
 
+    PrismaHelpers = Prisma
```
Comment (janpio) [inline src/packages/client/src/__tests__/integration/happy/blog-env-mssql/test.ts:24]: Why?

File: src/packages/client/src/__tests__/integration/happy/blog-env-mssql/test.ts [hunk 2]
```diff
@@ -206,8 +208,11 @@ describe('blog-env-mssql', () => {
 
     test('$queryRaw`<SQL>`', async () => {
       await prisma.user.create({ data: { email: 'e@a.de', name: 'E' } })
-      const users = await prisma.$queryRaw`SELECT * FROM [dbo].[User]`
-      expect(users).not.toHaveLength(0)
+      const users =
+        await prisma.$queryRaw`SELECT * FROM [dbo].[User] WHERE id IN (${PrismaHelpers.join(
+          ['42', '333', '2048'],
+        )})`
+      expect(users).toHaveLength(0)
```
Comment (janpio) [inline src/packages/client/src/__tests__/integration/happy/blog-env-mssql/test.ts:215]: We probably want to keep the old test around as well?

**Review by janpio — APPROVED** [review]
Looks good to me, but I am not sure if all cases are covered (as I never fully understood the raw Client API with its different variations)

File: src/packages/client/src/__tests__/integration/happy/blog-env-mssql/test.ts (hunk 1 above)
Comment (millsp) [reply src/packages/client/src/__tests__/integration/happy/blog-env-mssql/test.ts:24]: Because the import of prisma is done in `beforeAll`. I'd like to improve that in our tests.

**Review by Jolg42 — APPROVED** [review]
Looks good
