### PR TITLE
fix(engine-core): don't log the whole package.json in data proxy logs

### LINKED ISSUE #14660: Large package.json log output in prisma:client:dataproxyEngine
The whole fetched body of `package.json` is printed in logs:

```
2022-08-04T16:06:37.112Z prisma:client:dataproxyEngine  body fetched from unpkg.com:  {
  "version": "4.1.1",
  "name": "prisma",
  "description": "Prisma is an open-source database toolkit. It includes a JavaScript/TypeScript ORM for Node.js, migrations and a modern GUI to view and edit the data in your database. You can use Prisma in new projects or add it to an existing one.",
  "keywords": [
    "orm",
    "prisma2",
    "prisma",
    "cli",
    "database",
    "sql",
    "postgresql",
    "mysql",
    "sqlite",
    "mariadb",
    "mssql",
    "typescript",
    "query-builder"
  ],
  "main": "build/index.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/prisma/prisma.git",
    "directory": "packages/cli"
  },
  "homepage": "https://www.prisma.io",
  "author": "Tim Suchanek <suchanek@prisma.io>",
  "bugs": "https://github.com/prisma/prisma/issues",
  "license": "Apache-2.0",
  "engines": {
    "node": ">=14.17"
  },
  "prisma": {
    "prismaCommit": "fda72be967f13c0e1214149d7988cf8881f9f3d9"
  },
  "files": [
    "README.md",
    "build",
    "install",
    "runtime/*.js",
    "runtime/*.d.ts",
    "runtime/utils",
    "runtime/dist",
    "runtime/llhttp",
    "prisma-client",
    "preinstall",
    "scripts/preinstall-entry.js",
    "scripts/install-entry.js"
  ],
  "pkg": {
    "assets": [
      "build/**/*",
      "runtime/**/*",
      "prisma-client/**/*",
      "node_modules/@prisma/engines/**/*",
      "node_modules/@prisma/engines/*"
    ]
  },
  "bin": {
    "prisma": "build/index.js",
    "prisma2": "build/index.js"
  },
  "devDependencies": {
    "@prisma/client": "4.1.1",
    "@prisma/debug": "4.1.1",
    "@prisma/fetch-engine": "4.1.1",
    "@prisma/generator-helper": "4.1.1",
    "@prisma/get-platform": "4.1.1",
    "@prisma/internals": "4.1.1",
    "@prisma/migrate": "4.1.1",
    "@prisma/studio": "0.469.0",
    "@prisma/studio-server": "0.469.0",
    "@swc/core": "1.2.204",
    "@swc/jest": "0.2.21",
    "@types/debug": "4.1.7",
    "@types/fs-extra": "9.0.13",
    "@types/jest": "28.1.5",
    "@types/rimraf": "3.0.2",
    "@types/ws": "8.5.3",
    "chalk": "4.1.2",
    "checkpoint-client": "1.1.21",
    "debug": "4.3.4",
    "dotenv": "16.0.1",
    "esbuild": "0.14.47",
    "execa": "5.1.1",
    "fast-deep-equal": "3.1.3",
    "fs-extra": "10.1.0",
    "fs-jetpack": "4.3.1",
    "get-port": "5.1.1",
    "global-dirs": "3.0.0",
    "is-installed-globally": "0.4.0",
    "jest": "28.1.2",
    "jest-junit": "14.0.0",
    "line-replace": "2.0.1",
    "log-update": "4.0.0",
    "make-dir": "3.1.0",
    "node-fetch": "2.6.7",
    "open": "7.4.2",
    "pkg-up": "3.1.0",
    "replace-string": "3.1.0",
    "resolve-pkg": "2.0.0",
    "rimraf": "3.0.2",
    "strip-ansi": "6.0.1",
    "tempy": "1.0.1",
    "ts-pattern": "4.0.3",
    "typescript": "4.7.4"
  },
  "dependencies": {
    "@prisma/engines": "4.1.1"
  },
  "sideEffects": false,
  "scripts": {
    "dev": "DEV=true node -r esbuild-register helpers/build.ts",
    "build": "node -r esbuild-register helpers/build.ts",
    "test": "jest --maxConcurrency=1 --verbose",
    "install": "node scripts/install-entry.js",
    "tsc": "tsc -d -p tsconfig.build.json",
    "preinstall": "node scripts/preinstall-entry.js"
  }
}
2022-08-04T16:06:37.113Z prisma:client:dataproxyEngine  version 4.1.1
```

This makes it hard to read the log and makes it necessary to scroll a lot to the top.

Initially this log was added to aid with debugging when parsing the JSON fails, but it should only be logged when the failure actually occurs. Otherwise, just printing the size in bytes or JS characters is more than enough.

### PR DESCRIPTION
**Pull request by aqrln**
Log the size in JS characters instead.

The body is logged in the case of a JSON parsing error below in the code
(i.e., previously it would have been logged twice in case of an error).

Closes https://github.com/prisma/prisma/issues/14660

### CODE REVIEW

File: packages/engine-core/src/data-proxy/utils/getClientVersion.ts [hunk 1]
```diff
@@ -40,7 +40,7 @@ async function _getClientVersion(config: EngineConfig) {
     // because it's using the global "fetch"
     // eslint-disable-next-line @typescript-eslint/await-thenable
     const bodyAsText = await res.text()
-    debug('body fetched from unpkg.com: ', bodyAsText)
+    debug('length of body fetched from unpkg.com:', bodyAsText.length)
```
Comment (millsp) [inline packages/engine-core/src/data-proxy/utils/getClientVersion.ts:43]:
```suggestion
    debug('length of body fetched from unpkg.com', bodyAsText.length)
```

**Review by millsp — APPROVED** [review]

**Review by millsp — APPROVED** [review]
