### PR TITLE
fix(client): make engine events type safe internally

### LINKED ISSUE #9039: Log output of Node-API library engine is different
When starting a Prisma Client, you get an info log about the starting of the pool with x connections. This log is different when you consume it as an event:

`library`:
```
      Array [
        Object {
          message: Starting a sqlite pool with 5 connections.,
          target: undefined,
        },
      ]
```

`binary`:
```
      Array [
        Object {
          message: Starting a sqlite pool with 5 connections.,
          target: target: quaint::pooled,
        },
      ]
```

I assume similar differences exist across the board.

Related: https://github.com/prisma/prisma/issues/7605 + https://github.com/prisma/prisma/pull/9037

### LINKED ISSUE #18479: `target` and `timestamp` are undefined in `info` events in Data Proxy client
### Bug description

`info` event objects with Data Proxy client look like this:

```js
{
  timestamp: undefined,
  message: 'Calling https://aws-us-east-1.prisma-data.com/4.11.0/59ffd609948c3da558b850dda9948fe631888e7b9ad36d54dbd73a50b90e0b10/graphql (n=0)',
  target: undefined
}

{
  timestamp: undefined,
  message: 'Schema (re)uploaded (hash: 59ffd609948c3da558b850dda9948fe631888e7b9ad36d54dbd73a50b90e0b10)',
  target: undefined
}

{
  timestamp: undefined,
  message: 'Calling https://aws-us-east-1.prisma-data.com/4.11.0/59ffd609948c3da558b850dda9948fe631888e7b9ad36d54dbd73a50b90e0b10/graphql (n=1)',
  target: undefined
}
```

### How to reproduce

1. Use Data Proxy client
2. Enable info events: `const prisma = new PrismaClient({ log: [{ emit: 'event', level: 'info' }] })`
3. Add event handlers: `prisma.$on('info', console.log)`
4. Do some queries so that events are emitted

### Expected behavior

`timestamp` must be a date and target must be a string (at least an empty string if it's not applicable since it's required by the types which are part of public API).

### Environment & setup

- OS: macOS
- Database: PostgreSQL + Data Proxy
- Node.js version: v19.8.1

### Prisma Version

```
prisma                  : 4.12.0-dev.26
@prisma/client          : 4.12.0-dev.26
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 8db80a4b8f3db0e9a578b9559ce46792063d2446 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 8db80a4b8f3db0e9a578b9559ce46792063d2446 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.12.0-57.8db80a4b8f3db0e9a578b9559ce46792063d2446
Default Engines Hash    : 8db80a4b8f3db0e9a578b9559ce46792063d2446
Studio                  : 0.483.0
```

### LINKED ISSUE #18482: Wrong types of `timestamp` and `duration` in query events with Data Proxy
### Bug description

Query events with Data Proxy client have `timestamp` field that doesn't conform to the `Prisma.QueryEvent` interface and inconsistent with what is emitted by the regular client. It must be a `Date`, but it's a pair of integers instead. Also the `duration` field is wrong: it must be a number and not a string.

```json
        {
          "duration": "3",
          "params": "[0]",
          "query": "SELECT \"public\".\"User\".\"user_id\", \"public\".\"User\".\"email\", \"public\".\"User\".\"name\" FROM \"public\".\"User\" WHERE 1=1 OFFSET $1 ",
          "target": "quaint::connector::metrics",
          "timestamp": [
            1679675013,
            611480810,
          ]
        }
```

### How to reproduce

1.  Use Data Proxy client
2.  Enable query logs: `const prisma = new PrismaClient({ log: [{ emit: 'event', level: 'query' }] })`
3.  Add event handler: `prisma.$on('query', console.log)`
4.  Do some queries so that events are emitted

### Expected behavior

TS type:

```ts
  export type QueryEvent = {
    timestamp: Date
    query: string
    params: string
    duration: number
    target: string
  }
```

Same event with regular client:

```json
        {
          "duration": 219,
          "params": "[0]",
          "query": "SELECT \"public\".\"User\".\"user_id\", \"public\".\"User\".\"email\", \"public\".\"User\".\"name\" FROM \"public\".\"User\" WHERE 1=1 OFFSET $1",
          "target": "quaint::connector::metrics",
          "timestamp": "2023-03-24T16:26:32.999Z"
        }
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL + Data Proxy
- Node.js version: v19.8.1

### Prisma Version

```
prisma                  : 4.12.0-dev.26
@prisma/client          : 4.12.0-dev.26
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 8db80a4b8f3db0e9a578b9559ce46792063d2446 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 8db80a4b8f3db0e9a578b9559ce46792063d2446 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.12.0-57.8db80a4b8f3db0e9a578b9559ce46792063d2446
Default Engines Hash    : 8db80a4b8f3db0e9a578b9559ce46792063d2446
Studio                  : 0.483.0
```

### PR DESCRIPTION
**Pull request by aqrln**
* Separate log events and `beforeExit` hook, make them different APIs internally (keeping the user-facing facade that is part of public API as is).
* Emit engine events directly on the `logEmitter` passed in the constructor eliminating one level of indirection.
* Require the events to conform to the expected types on engine level and unify them, don't leak the implementation details of different event object shapes in different engine types all the way up to `PrismaClient` class.
* Make `LogEmitter` a specialized type rather than using a generic `EventEmitter`, `EventEmitter` is just a possible implementation of that interface.
* Fix the bugs in `LibraryEngine` and `DataProxyEngine` log events (all of which actually did become type errors with these changes).

Closes: https://github.com/prisma/team-orm/issues/365
Fixes: https://github.com/prisma/prisma/issues/18479
Fixes: https://github.com/prisma/prisma/issues/18482
Fixes: https://github.com/prisma/prisma/issues/9039

### CODE REVIEW

File: packages/client/src/runtime/core/engines/common/types/Events.ts [hunk 1]
```diff
@@ -1,5 +1,32 @@
...
+
+export type EngineEventType = QueryEventType | LogEventType
+
+export type EngineEvent<E extends EngineEventType> = E extends QueryEventType ? QueryEvent : LogEvent
+
+type EngineEventContravariant<E extends EngineEventType> = [E & QueryEventType] extends [never]
+  ? LogEvent
+  : [E & LogEventType] extends [never]
+  ? QueryEvent
+  : QueryEvent & LogEvent
```
Comment (millsp) [inline packages/client/src/runtime/core/engines/common/types/Events.ts:13]: Could this have been implemented with overloads?

Comment (aqrln) [reply packages/client/src/runtime/core/engines/common/types/Events.ts:13]: Good point, it could've been. We could even make it more strict and only allow `LogEventType` XOR `QueryEventType` by only declaring

```ts
  emit(event: QueryEventType, payload: QueryEvent): boolean
  emit(event: LogEventType, payload: LogEvent): boolean
```

Also, unrelated but we could replace `boolean` with `void` in the return signature since we don't actually need it, it came from the original `EventEmitter` type declaration.

File: packages/client/src/runtime/core/engines/binary/BinaryEngine.ts [hunk 2]
```diff
@@ -17,16 +17,10 @@ import { PrismaClientRustError } from '../../errors/PrismaClientRustError'
...
-  EngineConfig,
-  EngineEventType,
-  RequestBatchOptions,
-  RequestOptions,
-} from '../common/Engine'
+import type { BatchQueryEngineResult, EngineConfig, RequestBatchOptions, RequestOptions } from '../common/Engine'
 import { Engine } from '../common/Engine'
 import { resolveEnginePath } from '../common/resolveEnginePath'
-import { EventEmitter } from '../common/types/Events'
+import { LogEmitter, LogEventType } from '../common/types/Events'
```
Comment (jkomyno) [inline packages/client/src/runtime/core/engines/binary/BinaryEngine.ts:23]:
```suggestion
import type { LogEmitter, LogEventType } from '../common/types/Events'
```

File: packages/client/src/runtime/core/engines/common/Engine.ts [hunk 3]
```diff
@@ -4,7 +4,7 @@ import { TracingHelper } from '@prisma/internals'
 
 import { Datasources, GetPrismaClientConfig } from '../../../getPrismaClient'
 import { Fetch } from '../data-proxy/utils/request'
-import { EventEmitter } from './types/Events'
+import { LogEmitter } from './types/Events'
```
Comment (jkomyno) [inline packages/client/src/runtime/core/engines/common/Engine.ts:7]:
```suggestion
import type { LogEmitter } from './types/Events'
```

File: packages/client/src/runtime/core/engines/data-proxy/DataProxyEngine.ts [hunk 4]
```diff
@@ -242,8 +241,9 @@ export class DataProxyEngine extends Engine<DataProxyTxInfoPayload> {
 
             this.logEmitter.emit('query', {
               query: dbQuery,
-              timestamp: log.timestamp,
-              duration: log.attributes.duration_ms,
+              // first part is in seconds, second is in nanoseconds, we need to convert both to milliseconds
+              timestamp: new Date(log.timestamp[0] * 1e3 + log.timestamp[1] / 1e6),
```
Comment (jkomyno) [inline packages/client/src/runtime/core/engines/data-proxy/DataProxyEngine.ts:245]: Can you please add a test that explicitly tests the timestamp conversion logic?

File: packages/client/tests/functional/logging-types/tests.ts [hunk 5]
```diff
@@ -0,0 +1,64 @@
...
+        expect(typeof log.target).toBe('string')
+      }
+
+      for (const log of infoLogs) {
+        expect(log.timestamp).toBeInstanceOf(Date)
+        expect(typeof log.target).toBe('string')
+        expect(typeof log.message).toBe('string')
+      }
+    })
+  },
```
Comment (Jolg42) [inline packages/client/tests/functional/logging-types/tests.ts:60]: Can you check (after this PR is ok too) if this tests covers all cases from the older tests in `packages/client/src/__tests__/integration/happy/logging`. 
It would be nice to remove these old ones.

**Review by Jolg42 — APPROVED** [review]
"Finally" some good cleanup for these different things, I like it a lot ✨
Good job! 🙌🏼

File: packages/client/tests/functional/logging-types/tests.ts [hunk 6]
```diff
@@ -0,0 +1,64 @@
...
+import { NewPrismaClient } from '../_utils/types'
+import testMatrix from './_matrix'
+// @ts-ignore
+import type { Prisma, PrismaClient } from './node_modules/@prisma/client'
+
+declare let newPrismaClient: NewPrismaClient<typeof PrismaClient>
+
+testMatrix.setupTestSuite(
+  ({ provider }, _suiteMeta, clientMeta) => {
+    test('check that query and info logs match their declared types', async () => {
```
[the remark this answers is not in the document]
Comment (aqrln) [reply packages/client/tests/functional/logging-types/tests.ts:12]: From the quick look, it also checks that query logs work with iTX. I'll merge this as is, we can port everything into the new test in a follow-up PR.
