### PR TITLE
fix(generate): remove misleading "breaking changes" message for 3.0+

### LINKED ISSUE #9171: `prisma 3.0.1` warns about breaking changes.
### Bug description

It probably should warn about breaking changes, but this check:
https://github.com/prisma/prisma/blob/40783e17b07d24c3576e863abe6344b6d9d7a9a7/packages/cli/src/Generate.ts#L219

Is not correct since the switch to semver.

### How to reproduce

Install `prisma`@`3.0.1` and re-run `prisma generate`.

### Expected behavior

_No response_

### Prisma information

```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Something {
  id        String @id @default(cuid())
  name      String
}
```

### Environment & setup

- OS: MacOS
- Database: PostgreSQL
- Node.js version: v14.17.1

### Prisma Version

```
prisma                  : 3.0.1
@prisma/client          : 3.0.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 2452cc6313d52b8b9a96999ac0e974d0aedf88db
Studio                  : 0.423.0
```

### PR DESCRIPTION
**Pull request by janpio**
close #9171

- This functionality is missing tests (obviously)
- We could also add a warning to review breaking changes and release notes when going from 2.x to 3.x using this functionality

### CODE REVIEW

File: packages/cli/src/Generate.ts [hunk 1]
```diff
@@ -215,8 +215,10 @@ Please run \`${getCommandWithExecutor('prisma generate')}\` to see the errors.`)
           clientVersionBeforeGenerate &&
           typeof clientVersionBeforeGenerate === 'string'
         ) {
+          const major = clientVersionBeforeGenerate.split('.')[0]
```
Comment (Zn4rK) [inline packages/cli/src/Generate.ts:218]:
```ts
const [major, minor] = clientVersionBeforeGenerate.split('.')
```

File: packages/cli/src/Generate.ts [hunk 2]
```diff
@@ -215,8 +215,10 @@ Please run \`${getCommandWithExecutor('prisma generate')}\` to see the errors.`)
...
           const minor = clientVersionBeforeGenerate.split('.')[1]
-          if (parseInt(minor, 10) < 12) {
+          
+          if (parseInt(minor, 10) == 2 && parseInt(minor, 10) < 12) {
```
Comment (frovere) [inline packages/cli/src/Generate.ts:221]: const `major` is unused
```js
if (parseInt(mayor, 10) == 2 && parseInt(minor, 10) < 12) {
```

File: packages/cli/src/Generate.ts (hunk 1 above)
Comment (janpio) [reply packages/cli/src/Generate.ts]: No, this was just the Engineering Manager writing code - @millsp fixed it properly.

File: packages/cli/src/Generate.ts (hunk 2 above)
Comment (janpio) [reply packages/cli/src/Generate.ts]: https://github.com/prisma/prisma/pull/9177#discussion_r704744459

**Review by millsp — APPROVED** [review]
