### PR TITLE
fix(client): `runtimeDescription` is not defined #23153

### LINKED ISSUE #23430: `runtimeDescription` is not defined error
### Bug description

Found in https://github.com/prisma/prisma/issues/23153

`runtimeDescription` is not defined error after upgrading to 5.9.1 (from 5.8.1)

### PR DESCRIPTION
**Pull request by Jolg42**
This fixes the state introduced by myself in 5.2.0 in
https://github.com/prisma/prisma/pull/20683

I took this opportunity to add tests for `Prisma.sql` & co.

Contributes to #23153

### CODE REVIEW

**Comment by Jolg42** [comment]
Note: I'll update the snapshots after we reviewed the text

File: packages/client/src/generation/TSClient/common.ts [hunk 1]
```diff
@@ -126,7 +126,9 @@ Prisma.NullTypes = {
 export const notSupportOnBrowser = (fnc: string, browser?: boolean) => {
   if (browser)
     return `() => {
-  throw new Error(\`${fnc} is unable to be run \${runtimeDescription}.
+  throw new Error(\`${fnc} was imported from @prisma/client/index-browser.
```
Comment (SevInf) [inline packages/client/src/generation/TSClient/common.ts:129]: I am a little bit confused about the new message.

Bundlers wold route `@prisma/client` imports to `@prisma/client/index-browser` automatically if they are building frontend build. So, from users standpoint, they already do what the error message suggesting and would probably be confused even more.

**Review by SevInf — APPROVED** [review]
