### PR TITLE
fix(client): jsdoc for undefined vs null

### LINKED ISSUE #5149: findFirst with `undefined` value shouldn't return data
## Bug description

Calling `findFirst` with an `undefined` in where filter still returns data. This is not intuitive. 

## How to reproduce

1. Deploy this schema with `yarn prisma db push --preview-feature`

```prisma
datasource ds {
    provider = "sqlite"
    url      = "file:./dev.db"
}

generator pc {
    provider = "prisma-client-js"
}

model User {
    id   String @id
    name String
}
```

2. Ensure it has some rows
3. Run the following script

```ts
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()
async function main() {
  const data = await prisma.user.findFirst({
    where: {
      id: null
    },
  })
  console.log({ data })
}

main()
```

4. It returns

```
{ data: { id: '1', name: 'Alice' } }
```

5. The where ID doesn't match anything, it shouldn't return

## Expected behaviour

IMO, this should be a runtime error. 

## Prisma information

```
(base) divyendusingh [p2-ff]$ yarn prisma --version                                                                                                                                  130 ↵
yarn run v1.22.4
$ /Users/divyendusingh/Documents/prisma/triage/p2-ff/node_modules/.bin/prisma --version
@prisma/cli          : 2.15.0-dev.57
@prisma/client       : 2.15.0-dev.57
Current platform     : darwin
Query Engine         : query-engine 6cece221de1da7dd83b9a158db5147e36f802cb1 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 6cece221de1da7dd83b9a158db5147e36f802cb1 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 6cece221de1da7dd83b9a158db5147e36f802cb1 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 6cece221de1da7dd83b9a158db5147e36f802cb1 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.333.0
```

### PR DESCRIPTION
**Pull request by timsuchanek**
Closes #5149

### CODE REVIEW

File: src/packages/client/src/generation/TSClient/jsdoc.ts [hunk 1]
```diff
@@ -0,0 +1,374 @@
...
+  model: DMMF.Model
+  action: DMMF.ModelAction
+  mapping: DMMF.ModelMapping
+}
+
+const Docs = {
+  cursor: `{@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}`,
+  pagination: `{@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}`,
+  aggregations: `{@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}`,
+  distinct: `@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs`,
```
Comment (williamluke4) [inline src/packages/client/src/generation/TSClient/jsdoc.ts:19]:
```suggestion
  distinct: `{@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}`,
```

File: src/packages/client/src/generation/TSClient/jsdoc.ts [hunk 2]
```diff
@@ -0,0 +1,374 @@
...
+  sorting: `@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs`,
```
Comment (williamluke4) [inline src/packages/client/src/generation/TSClient/jsdoc.ts:20]:
```suggestion
  sorting: `{@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}`,
```

**Review by williamluke4 — APPROVED** [review]
