### PR TITLE
fix(client): Fix naming conflict in types args

### LINKED ISSUE #17005: Prisma 4.8 produces conflicting typescript types for custom many to many relations
### Bug description

prisma 4.8 is producing multiple typescript type definitions with the same name for a fairly common naming pattern for a custom many to many relation

### How to reproduce

1. clone https://github.com/hayes/prisma-4.8-generator-bug
2. run npm install
3. run npm geneate
4. run npm type

### Expected behavior

Type checking the client should not cause errors, types should all have unique names

### Prisma information

```prisma
datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

generator client {
  provider = "prisma-client-js"
  output   = "../client"
}

/// Model for Posts!
model Post {
  id Int @id @default(autoincrement())
  media PostMedia[]
}

model Media {
  id Int @id @default(autoincrement())
  posts PostMedia[]
}

model PostMedia {
  id      Int   @id @default(autoincrement())
  post    Post  @relation(fields: [postId], references: [id])
  media   Media @relation(fields: [mediaId], references: [id])
  postId  Int
  mediaId Int
  @@unique([postId, mediaId])
}
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: macOS
- Database: sqlite
- Node.js version: 16.17

### Prisma Version

```
prisma                  : 4.8.0
@prisma/client          : 4.8.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/.pnpm/@prisma+engines@4.8.0/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/.pnpm/@prisma+engines@4.8.0/node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/.pnpm/@prisma+engines@4.8.0/node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/.pnpm/@prisma+engines@4.8.0/node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.8.0-61.d6e67a83f971b175a593ccc12e15c4a757f93ffe
Default Engines Hash    : d6e67a83f971b175a593ccc12e15c4a757f93ffe
Studio                  : 0.479.0
```

### LINKED ISSUE #17030: Using findUnique on 4.8.0 with nested `where` and `include` produces an object that doesn't include entities you specify in `include`
### Bug description

When I use `findUnique` and specify `where` condition values for a multi column unique constraint and specify data to `include`, the resulting object will produce all the data but the types are going to be wrong and typescript will not show the data I specified in my `include`. If anyone could come up with a better wording, please, let me know! :D

This issue was not present in 4.7.1 but was introduced in 4.8.0

### How to reproduce

Use findUnique() and provide it with `where` and `include`, `where` must depend on multi column unique constraint.

### Expected behavior

The resulting object must contain data I specified in `include`

### Prisma information

Schema can be found [here](https://github.com/TenkoSpirit/genshin.academy/blob/78ea9a42b8618a1ac668ec8ba24b536924768fc6/prisma/schema.prisma)

Using Prisma 4.8.0
```ts
const info = await prisma.characterInfo.findUnique({
  where: {
    entryLanguage_characterId: {
      entryLanguage: "en",
      characterId: params.id,
    },
  },
  include: {
    details: {
      include: {
        assets: true,
      },
    },
  },
});

console.log(info?.details);  // Property 'details' does not exist on type 'CharacterInfo'.
```

Using Prisma 4.7.1 this is not happening.

### Environment & setup

- OS: Arch Linux x86_64, kernel 6.1.1-zen1-1-zen
- Database: PostgreSQL 14.6
- Node.js version: v18.12.1

### Prisma Version

```
prisma                  : 4.8.0
@prisma/client          : 4.8.0
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/migration-engine-debian-openssl-3.0.x)
Introspection Engine    : introspection-core d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/introspection-engine-debian-openssl-3.0.x)
Format Binary           : prisma-fmt d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-3.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.8.0-61.d6e67a83f971b175a593ccc12e15c4a757f93ffe
Default Engines Hash    : d6e67a83f971b175a593ccc12e15c4a757f93ffe
Studio                  : 0.479.0
Preview Features        : fullTextSearch, postgresqlExtensions
Done in 0.42s.
```

### PR DESCRIPTION
**Pull request by SevInf**
Since 4.8.0, we generate explicit types for model fields args, not only
for top level queries. Naming we choose for it, `ModelFieldArgs` can
clash with existing types if `ModelField` type also exists in the
schema. To fix it, this PR changes naming scheme to `Model$fieldArgs`.
Since `$` can not be used in field name, this new naming scheme is
guaranteed not to clash with anything.

Bug introduced in #16844

Fix #17005 
Fix #17030

### CODE REVIEW

File: packages/client/src/generation/utils.ts [hunk 1]
```diff
@@ -99,7 +99,7 @@ export function getFieldArgName(field: DMMF.SchemaField, modelName: string): str
 }
 
 export function getModelFieldArgsName(field: DMMF.SchemaField, modelName: string) {
-  return `${modelName}${capitalize(field.name)}Args`
+  return `${modelName}$${field.name}Args`
```
Comment (Jolg42) [inline packages/client/src/generation/utils.ts:102]:
```suggestion
  // Example: User$postsArgs
  // So it doesn't conflict with the generated type, like UserPostsArgs
  return `${modelName}$${field.name}Args`
```

**Review by Jolg42 — APPROVED** [review]
This looks good to me 👍🏼 
maybe someone else could have a look too

File: packages/client/tests/functional/issues/17005-args-type-conflict/_matrix.ts [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+      provider: 'mongodb',
+    },
+    {
+      provider: 'cockroachdb',
+    },
+    {
+      provider: 'sqlserver',
+    },
+  ],
+])
```
Comment (danstarns) [inline packages/client/tests/functional/issues/17005-args-type-conflict/_matrix.ts:24]:
```suggestion
import { defineMatrix } from '../../_utils/defineMatrix'
import { allProviders } from '../../_utils/providers'

export default defineMatrix(() => [allProviders])
```

**Review by danstarns — APPROVED** [review]
