### PR TITLE
fix(cli): add CockroachDB to the providers list

### LINKED ISSUE #11633: `prisma init` needs CockroachDB in the providers list
### Bug description

  Currently the output of `prisma init` has the following line:

```
2. Set the provider of the datasource block in schema.prisma to match your database: postgresql, mysql, sqlite, sqlserver or mongodb (Preview).
```

This now needs `cockroachdb` added to the list.

### How to reproduce

1. run `npx prisma init`

### Expected behavior

Should include CockroachDB.

### Prisma information

N/A

### Environment & setup

N/A

### Prisma Version

```
3.9.1
```

### PR DESCRIPTION
**Pull request by jkomyno**
fix(cli): add CockroachDB to the providers list

Closes #11633

### CODE REVIEW

File: packages/cli/src/Init.ts [hunk 1]
```diff
@@ -211,9 +211,9 @@ export class Init implements Command {
       url = args['--url']
     } else if (args['--datasource-provider']) {
       const providerLowercase = args['--datasource-provider'].toLowerCase()
-      if (!['postgresql', 'mysql', 'sqlserver', 'sqlite', 'mongodb'].includes(providerLowercase)) {
+      if (!['postgresql', 'mysql', 'sqlserver', 'sqlite', 'mongodb', 'cockroachdb'].includes(providerLowercase)) {
         throw new Error(
-          `Provider "${args['--datasource-provider']}" is invalid or not supported. Try again with "postgresql", "mysql", "sqlite", "sqlserver" or "mongodb".`,
+          `Provider "${args['--datasource-provider']}" is invalid or not supported. Try again with "postgresql", "mysql", "sqlite", "sqlserver", "mongodb", or "cockroachdb".`,
```
Comment (jkomyno) [inline packages/cli/src/Init.ts:216]: It may be worth creating a small utility that transforms the array of supported datasource providers to a stringified version to append after the "Try again with " string.

Comment (janpio) [reply packages/cli/src/Init.ts:216]: I think that would be an ok optimization to do along the way, on the other hand another stacking PR (towards this one, that will be change to `main` automatically when this here is merged) might be clearer.

**Comment by jkomyno** [comment]
Note: the CI error seems to be triggered by code outside the scope of this PR, as verified by @janpio

File: packages/cli/src/__tests__/commands/Init.test.ts [hunk 2]
```diff
@@ -58,6 +58,26 @@ test('works with provider param - postgresql', async () => {
   `)
 })
 
+test('works with provider param - cockroachdb', async () => {
+  ctx.fixture('init')
+  const result = await ctx.cli('init', '--datasource-provider', 'cockroachdb')
+  expect(stripAnsi(result.stdout)).toMatchSnapshot()
+
+  const schema = fs.readFileSync(join(ctx.tmpDir, 'prisma', 'schema.prisma'), 'utf-8')
+  expect(schema).toMatch(defaultSchema('cockroachdb'))
```
Comment (Jolg42) [inline packages/cli/src/__tests__/commands/Init.test.ts:67]: The default schema needs an extra line for the generator like 
```
previewFeatures = ["cockroachdb"]
```

I can suggest doing it like we did for mongodb and removed here
https://github.com/prisma/prisma/pull/12660/files#diff-3a2fd0c2f24931daa62a694bc42215135099cded6cc9da76ef7c64db4fb6f10fL21-L39

**Review by Jolg42 — CHANGES_REQUESTED** [review]
Looks great! See comment about missing `previewFeatures` for cockroachdb

**Review by Jolg42 — APPROVED** [review]
Nice one!

File: packages/cli/src/Init.ts [hunk 3]
```diff
@@ -19,6 +19,23 @@ import { isError } from 'util'
...
+    
+    generator client {
+      provider        = "prisma-client-js"
+      previewFeatures = ["${provider}"]
+    }
+    
+    datasource db {
+      provider = "${provider}"
+      url      = env("DATABASE_URL")
+    }
```
Comment (aqrln) [inline packages/cli/src/Init.ts:35]: I believe this will result in extra spacing starting from the second line in the generated schema file.

Comment (janpio) [reply packages/cli/src/Init.ts:35]: I think we previously had similar for for MongoDB which was _just_ removed a few days ago. Might also be worth to just quickly go back and check how we did this before.

(Also might be worth to extract the list of providers that should get a preview feature flag to a constant, then we can just keep this around next time - although no provider might be in preview at that time)

Comment (jkomyno) [reply packages/cli/src/Init.ts:35]: I believe @aqrln is right, the `generator` and `datasource` blocks are shifted compared to [how you folks did for MongoDB](https://github.com/prisma/prisma/pull/12660/files#diff-3a2fd0c2f24931daa62a694bc42215135099cded6cc9da76ef7c64db4fb6f10f). New PR incoming to fix it
