### PR TITLE
fix(client-generator-ts): fix dynamic import on Webpack 5 (default bundler on Next.js 15)

### LINKED ISSUE #27049: queryCompiler: “TypeError: createRequire is not a function”
### Bug description

Enabling `queryCompiler` in my next.js app results in an error during initailization:
```
TypeError: createRequire is not a function
    at Object.getQueryCompilerWasmModule (prisma/dist/internal/class.js:75:24)
  73 |         const { readFile } = await import('node:fs/promises');
  74 |         const { createRequire } = await import('node:module');
> 75 |         const require = createRequire(import.meta.url);
     |                        ^
  76 |         const wasmModulePath = require.resolve("@prisma/client/runtime/query_compiler_bg.postgresql.wasm");
  77 |         const wasmModuleBytes = await readFile(wasmModulePath);
  78 |         return new globalThis.WebAssembly.Module(wasmModuleBytes);
```
despite that I’m on the most recent Node version (v22.15.0)

### Severity

⚠️ Major: Breaks core functionality (e.g., migrations fail)

### Reproduction

1. Scaffold next.js app: `bunx create-next-app@latest -e reproduction-template .`
2. Create `prisma/schema.prisma` from the schema provided below (minimal schema using prisma-client generator)
3. `bunx prisma generate`
4. Compile the prisma client to be able to import it, running `tsc` inside the `prisma` folder with the following:
    <details><summary><code>prisma/tsconfig.json</code></summary>

    ```json
    {
      "compilerOptions": {
        "target": "es2023",
    
        "lib": ["esnext", "dom", "dom.iterable"],
        "libReplacement": false,
    
        "module": "esnext",
        "moduleResolution": "bundler",
        "moduleDetection": "force",
        "isolatedModules": true,
        "esModuleInterop": true,
        "skipLibCheck": true,
        "strict": true,
    
        "noEmit": false,
        "declaration": true,
        "outDir": "dist",
      },
      "include": ["**/*.ts"],
      "exclude": ["dist/**/*"],
    }
    ```

    </details>
5. Instantiate Prisma in the default `app/page.tsx`:   
    ```
    import { PrismaClient } from '../prisma/dist/client';
    import { PrismaNeon } from '@prisma/adapter-neon';
    
    const connectionString = process.env.DATABASE_URL;
    const adapter = new PrismaNeon({ connectionString });
    const db = new PrismaClient({ adapter });
    console.log(db);
    
    export default function Home() {
      return null;
    }
    ```
6. Start the dev server and load `localhost:3000`

### Expected vs. Actual Behavior

Expected: The database client initializes without error

Actual:
```
TypeError: createRequire is not a function
    at Object.getQueryCompilerWasmModule (prisma/dist/internal/class.js:75:24)
  73 |         const { readFile } = await import('node:fs/promises');
  74 |         const { createRequire } = await import('node:module');
> 75 |         const require = createRequire(import.meta.url);
     |                        ^
  76 |         const wasmModulePath = require.resolve("@prisma/client/runtime/query_compiler_bg.postgresql.wasm");
  77 |         const wasmModuleBytes = await readFile(wasmModulePath);
  78 |         return new globalThis.WebAssembly.Module(wasmModuleBytes);
```

from `../prisma/dist/internal/class.js:76:24`

### Frequency

Consistently reproducible

### Does this occur in development or production?

Both development and production

### Is this a regression?

Not sure

### Workaround

Not using the `queryCompiler` feature

### Prisma Schema & Queries

```prisma
generator client {
  provider = "prisma-client"
  output = "generated/client"
  moduleFormat = "esm"
  previewFeatures = ["driverAdapters", "relationJoins", "queryCompiler"]
}

datasource db {
  provider = "postgresql"
  url = env("DATABASE_URL")
}

model MyModel {
  id String @id @default(uuid())
}
```

Reproduces without running any query

### Prisma Config

N/A

### Logs & Debug Info

No query needs to be run to reproduce

### Environment & Setup

- **OS:** macOS; Darwin 24.5.0 arm64 arm
- **Database:** any
- **Node.js version:** v22.15.0

### Prisma Version

```
prisma                  : 6.7.0
@prisma/client          : 6.7.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v22.15.0
TypeScript              : 5.8.3
Query Engine (Node-API) : libquery-engine 3cff47a7f5d65c3ea74883f1d736e41d68ce91ed (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 3cff47a7f5d65c3ea74883f1d736e41d68ce91ed (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 6.7.0-36.3cff47a7f5d65c3ea74883f1d736e41d68ce91ed
Default Engines Hash    : 3cff47a7f5d65c3ea74883f1d736e41d68ce91ed
Studio                  : 0.511.0
```

### PR DESCRIPTION
**Pull request by jkomyno**
This PR modifies the `prisma-client` generator by introducing

```typescript
const dynamicRequireFn = async <const T extends string>(name: T) =>
  typeof __non_webpack_require__ === 'function'
    ? Promise.resolve(__non_webpack_require__(name))
    : await import(/* webpackIgnore: true */ name)
```

This function evaluates to:
- `import(name)` for all bundler targets, except Webpack, but including Turbopack.
- `__non_webpack_require__(name)` for Webpack targets.

This is used to dynamically import a module at runtime, while also excluding it from Webpack's bundle.
 It allows to mitigate https://github.com/webpack/webpack/issues/19607 and
 - fix https://github.com/prisma/prisma/issues/27049
 - fix https://github.com/prisma/prisma/issues/27343

In practice, it's used to import `node:fs/promises` and `node:module`.

---

At the present state, this PR seems to do the trick with Next.js 15 / Webpack 5 without causing regressions in other frameworks or environments. E.g., since `__non_webpack_require__` is only defined on Webpack, it doesn't affect Turbopack, which will still use the native `await import`.

We can also decide to introduce a new top-level `runtime = "webpack"` configuration option for the `prisma-client` generator, and remove the build-time conditionality in `dynamicRequireFn`. However, that would introduce additional friction, and would need to be deprecated once Turbopack (Webpack's replacement) becomes generally available, so I'd advise against it.

### CODE REVIEW

**Comment by jkomyno** [comment]
I'll use [an integration version](https://github.com/prisma/prisma/actions/runs/15865175271/job/44730579612) in [prisma/prisma-examples](https://github.com/prisma/prisma-examples/pull/8162).

**Review by aqrln — APPROVED** [review]
Nice job investigating this!

File: packages/client-generator-ts/src/utils/buildGetWasmModule.ts [hunk 1]
```diff
@@ -43,9 +61,12 @@ export function buildGetWasmModule({
...
 
   getQuery${capitalizedComponent}WasmModule: async () => {
-    const { readFile } = await import('node:fs/promises')
+    ${buildDynamicRequireFn()}
+  
+    // Note: we must use dynamic imports here to avoid bundling errors like \`Module parse failed: Unexpected character '' (1:0)\`.
+    const { readFile } = await dynamicRequireFn('node:fs/promises')
     ${buildRequire(moduleFormat)}
-    const wasmModulePath = require.resolve(${JSON.stringify(wasmModulePath)})
+    const wasmModulePath = _require.resolve(${JSON.stringify(wasmModulePath)})
```
Comment (CHC383) [inline packages/client-generator-ts/src/utils/buildGetWasmModule.ts:69]: Where is `_require` defined for cjs?

Comment (JAD3N) [reply packages/client-generator-ts/src/utils/buildGetWasmModule.ts:69]: ~~@CHC383 The `_require` is defined by the `buildRequire` call. I imagine it's renamed to prevent conflicts.~~

Edit: Nevermind, I can't see it either for CJS. Surely it's supposed to return something like `const _require = require;` for CJS?
