### PR TITLE
fix(client): field references via extensions

### LINKED ISSUE #19892: Field references are not available on extended clients
### Bug description

When using `$extends`, field references are not available on the type-level.

### How to reproduce

```ts
const xprisma = prisma.$extends({})

await xprisma.product.createMany({
  data: [
    {
      title: 'Potato',
      properties1: {
        kind: 'root vegetable',
      },
      properties2: {
        kind: 'root vegetable',
      },
    },
  ],
})

const products = await xprisma.product.findMany({
  where: { properties1: { equals: xprisma.product.fields.properties2 } },
})

expect(products).toEqual([expect.objectContaining({ title: 'Potato' })])
```

### Expected behavior

Field references should work when `fieldReference` is enabled.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["fieldReference"]
}

datasource db {
  provider = "${provider}"
  url      = env("DATABASE_URI_${provider}")
}

model Product {
  id ${idForProvider(provider)}
  title String
  properties1 Json
  properties2 Json?
}
```

### Environment & setup

n/a

### Prisma Version

```
4.16.0
```

### PR DESCRIPTION
**Pull request by millsp**
closes https://github.com/prisma/prisma/issues/19892

### CODE REVIEW

File: packages/client/src/runtime/core/types/Extensions.ts [hunk 1]
```diff
@@ -120,12 +120,15 @@ export type DynamicModelExtensionThis<TypeMap extends TypeMapDef, M extends Prop
...
     ? <A extends TypeMap['model'][M][P]['args']>(args?: A) =>
-        PrismaPromise<GetOperationResult<TypeMap['model'][M][P]['payload'], A, P & Operation>>
-    : <A extends TypeMap['model'][M][P]['args']>(args: A) =>
-        PrismaPromise<GetOperationResult<TypeMap['model'][M][P]['payload'], A, P & Operation>>
+        PrismaPromise<GetOperationResult<TypeMap['model'][M]['operations'][P]['payload'], A, P & Operation>>
+    : <A extends TypeMap['model'][M]['operations'][P]['args']>(args: A) =>
+        PrismaPromise<GetOperationResult<TypeMap['model'][M]['operations'][P]['payload'], A, P & Operation>>
+} & {
+  [P in Exclude<'fields' & keyof TypeMap['model'][M], keyof ExtArgs['model'][Uncapitalize<M & string>]>]:
+    TypeMap['model'][M]['fields'] // TODO remove & keyof TypeMap['model'][M] once fieldRefs is GA
```
Comment (Jolg42) [inline packages/client/src/runtime/core/types/Extensions.ts:131]:
```suggestion
    TypeMap['model'][M]['fields'] // TODO remove & keyof TypeMap['model'][M] once fieldReference is GA
```
So we can find this later easily via a search

**Review by Jolg42 — APPROVED** [review]

**Review by SevInf — APPROVED** [review]
