### PR TITLE
fix: add missing deserialization for JSON values

### LINKED ISSUE #29174: postgres date field in JSONB serialization regression in 7.4.0
### Bug description

in version 7.2.0 and before, given a schema of:

```
model ModelWithJson {
  id String @id
  properties Json
}
```

using:
```
await this.prisma.modelWithJson.create({
      data: {
        id: '1',
        properties: {
          dateField: new Date(),
        },
      },
    });
```

would produce a properties field with an iso string:

```
{"dateField": "2026-02-12T13:32:20.594Z"}
```

but now we get:

{"dateField": {"$type": "DateTime", "value": "2026-02-12T13:32:20.594Z"}}

which is a corruption of the json of course

### Severity

🚨 Critical: Data loss, app crash, security issue

### Expected vs. Actual Behavior

expected json field:

```
{"dateField": "2026-02-12T13:32:20.594Z"}
```

actual json field:

```
{"dateField": {"$type": "DateTime", "value": "2026-02-12T13:32:20.594Z"}}
```

### Frequency

Consistently reproducible

### Does this occur in development or production?

Both development and production

### Is this a regression?

Yes, last worked in Prisma 7.2.0, broke in 7.4.0

### Workaround

downgrading fixes it

### Prisma Schema & Queries

```prisma
model ModelWithJson {
  id String @id
  properties Json
}
```
```ts
await this.prisma.modelWithJson.create({
      data: {
        id: '1',
        properties: {
          dateField: new Date(),
        },
      },
    });
```

### Prisma Config

```ts
// Add your `prisma.config.ts`
```

### Logs & Debug Info

```
// Debug logs here
```

### Environment & Setup

- **OS:** macOS
- **Database:** PostgreSQL
- **Node.js version:** v24.12.0

### Prisma Version

```
7.4.0
```

### PR DESCRIPTION
**Pull request by jacek-prisma**
[TML-1901](https://linear.app/prisma-company/issue/TML-1901/investigate-and-fix-jsonb-regression-in-74)
Fixes https://github.com/prisma/prisma/issues/29174

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed JSON date deserialization in JSONB parameter fields to preserve date formatting and custom type info.

* **Refactor**
  * Renamed exported deserialization function for clearer naming.
  * Raw JSON values are now preserved during deserialization.
  * Changed default behavior to wrap raw values during JSON serialization when option unspecified.

* **Tests**
  * Added functional tests covering JSON date deserialization and related scenarios.

### CODE REVIEW

File: packages/client/src/runtime/core/engines/client/parameterization/parameterize.ts [hunk 1]
```diff
@@ -323,7 +324,7 @@ class Parameterizer {
 
     const mask = getScalarMask(edge)
     if (mask & ScalarMask.Json) {
-      const jsonValue = JSON.stringify(obj)
+      const jsonValue = JSON.stringify(deserializeJsonObject(obj))
       const type: PlaceholderType = { type: 'Json' }
       return this.#getOrCreatePlaceholder(jsonValue, type)
     }
```
[the remark this answers is not in the document]
Comment (jacek-prisma) [reply packages/client/src/runtime/core/engines/client/parameterization/parameterize.ts:330]: updated

File: packages/client-engine-runtime/src/json-protocol.ts [hunk 2]
```diff
@@ -18,13 +19,15 @@ export type JsonInputTaggedValue =
...
   | EnumTaggedValue
+  | RawTaggedValue
 
 export type JsonOutputTaggedValue =
   | DateTaggedValue
   | DecimalTaggedValue
   | BytesTaggedValue
   | BigIntTaggedValue
   | JsonTaggedValue
+  | RawTaggedValue
```
Comment (aqrln) [inline packages/client-engine-runtime/src/json-protocol.ts]: I don't think `Raw` can appear in output values, can it?

Comment (jacek-prisma) [reply packages/client-engine-runtime/src/json-protocol.ts]: You're right, it can't. The way the code is currently structured `deserializeTaggedValue` is used against both input and output values but is typed `JsonOutputTaggedValue`, it might need a type of its own

Comment (jacek-prisma) [reply packages/client-engine-runtime/src/json-protocol.ts]: updated

File: packages/client-engine-runtime/src/json-protocol.ts [hunk 3]
```diff
@@ -83,7 +85,10 @@ function isTaggedValue(value: unknown): value is JsonOutputTaggedValue {
  * patch and normalize them here to ensure they are consistent with the snapshots
  * in the query engine tests.
  */
-function normalizeTaggedValue({ $type, value }: JsonOutputTaggedValue): JsonOutputTaggedValue {
+function normalizeTaggedValue({
+  $type,
+  value,
+}: JsonInputTaggedValue | JsonOutputTaggedValue): JsonInputTaggedValue | JsonOutputTaggedValue {
```
Comment (aqrln) [inline packages/client-engine-runtime/src/json-protocol.ts:91]: Should this be something like this instead?
```suggestion
function normalizeTaggedValue<T extends JsonInputTaggedValue | JsonOutputTaggedValue>({
  $type,
  value,
}: T): T {
```

Comment (jacek-prisma) [reply packages/client-engine-runtime/src/json-protocol.ts:91]: yep 👍

Comment (jacek-prisma) [reply packages/client-engine-runtime/src/json-protocol.ts:91]: the signature you suggest is correct, but I am not sure if it's possible to implement safely in Typescript, the current implementation gives a type error

Comment (jacek-prisma) [reply packages/client-engine-runtime/src/json-protocol.ts:91]: also I don't think we particularly need the more precise signature

**Review by aqrln — APPROVED** [review]

File: packages/client-engine-runtime/src/json-protocol.ts (hunk 3 above)
Comment (aqrln) [reply packages/client-engine-runtime/src/json-protocol.ts:91]: lgtm as is in that case
