### PR TITLE
fix(cli, client): deletion of engines when `--no-engine` is passed

### LINKED ISSUE #17685: .prisma/client: Name can't start with a dot
### Bug description

When prima client is generated with custom output path, it throws error `.prisma/client: Name can't start with a dot`
Screenshot 2023-02-02 at 12 29 24 AM

### Expected behavior

I want to run yarn normally after manually generating the client.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  output   = "../src/generated/client"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v16.13.2

### Prisma Version

```
prisma                  : 4.9.0
@prisma/client          : 4.9.0
```

### PR DESCRIPTION
**Pull request by millsp**
We knew we introduced a small regression when we fixed https://github.com/prisma/prisma/issues/17685, this fixes it.

### CODE REVIEW

File: packages/client/tests/e2e/_utils/run.ts [hunk 1]
```diff
@@ -14,9 +14,6 @@ const args = arg(
     // like run jest in band, useful for debugging and CI
     '--runInBand': Boolean,
     '--run-in-band': '--runInBand',
-    // do not fully build cli and client packages before packing
-    '--skipBuild': Boolean,
-    '--skip-build': '--skipBuild',
```
Comment (millsp) [inline packages/client/tests/e2e/_utils/run.ts:19]: Not needed. Everyone builds their repo before running tests.

File: packages/client/src/generation/generateClient.ts [hunk 2]
```diff
@@ -604,11 +604,11 @@ async function copyRuntimeFiles({ from, to, runtimeName, sourceMaps }: CopyRunti
  * Attempts to delete the output directory.
  * @param finalOutputDir
  */
-async function deleteOutputDir(finalOutputDir: string) {
+async function deleteOutputDir(finalOutputDir: string, datamodel: string) {
   try {
     debug(`attempting to delete ${finalOutputDir} recursively`)
     // we want to make sure that if we delete, we delete the right directory
-    if (require(`${finalOutputDir}/package.json`).name === GENERATED_PACKAGE_NAME) {
+    if (require(`${finalOutputDir}/package.json`).name === getUniquePackageName(datamodel)) {
```
Comment (millsp) [inline packages/client/src/generation/generateClient.ts:611]: The fix.

**Review by Jolg42 — APPROVED** [review]

File: packages/client/src/generation/generateClient.ts (hunk 2 above)
Comment (SevInf) [reply packages/client/src/generation/generateClient.ts:610]: Does not necessary needs changing right now, just food for thought. Would it make sense to change it to something like this?

```suggestion
    if (require(`${finalOutputDir}/package.json`).startsWith(GENERATED_PACKAGE_NAME)) {
```

Otherwise, if schema changed at the same time `--no-engine` flag was added to invocation, engine won't be deleted.

Comment (millsp) [reply packages/client/src/generation/generateClient.ts:610]: Good catch, I'll add a test for that
