### PR TITLE
fix(generators): Do not force install of package manager when using ni

### LINKED ISSUE #19945: Prisma requires to install bun when generating client library
### Bug description

When running `npx prisma generate` it outputs:

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
[ni] Detected bun but it doesn't seem to be installed.

✔ Would you like to globally install bun (​https://bun.sh​)? … no

Than the execution will terminates

### Expected behavior

Generate the client libraries

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  binaryTargets   = ["native", "darwin-arm64", "linux-musl", "linux-arm64-openssl-1.1.x"]
  previewFeatures = ["extendedWhereUnique"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

...
```

### Environment & setup

- OS: macOS Ventura
- Database: PostgreSQL
- Node.js version: v16.18.0

### Prisma Version

```
prisma                  : 4.16.1
@prisma/client          : Not found
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine b20ead4d3ab9e78ac112966e242ded703f4a052c (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli b20ead4d3ab9e78ac112966e242ded703f4a052c (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.16.0-66.b20ead4d3ab9e78ac112966e242ded703f4a052c
Default Engines Hash    : b20ead4d3ab9e78ac112966e242ded703f4a052c
Studio                  : 0.484.0
Preview Features        : extendedWhereUnique
```

### PR DESCRIPTION
**Pull request by timarnoldev**
Fixes #19945

When having a .lock file from a different package manager `ni` forces the installation or terminates the task if the user declines.

To overcome this issue when `ni` is used in cli tools like `prisma cl` `programmatic` should be set to true.

### CODE REVIEW

File: packages/internals/src/get-generators/generatorResolvers/prisma-client-js/auto-installation/getPackageCmd.ts [hunk 1]
```diff
@@ -8,7 +8,7 @@ import { Command, detect, getCommand } from '@antfu/ni'
  * @returns
  */
 export async function getPackageCmd(cwd: string, cmd: Command, ...args: string[]) {
-  const agent = await detect({ autoInstall: false, cwd })
+  const agent = await detect({ autoInstall: false, cwd:cwd, programmatic: true })
```
Comment (Jolg42) [inline packages/internals/src/get-generators/generatorResolvers/prisma-client-js/auto-installation/getPackageCmd.ts:11]:
```suggestion
  const agent = await detect({ autoInstall: false, cwd, programmatic: true })
```
Small fix

**Comment by Jolg42** [comment]
Note: the `programmatic` option was added to `ni` by @millsp in https://github.com/antfu/ni/pull/151

**Comment by Jolg42** [comment]
@millsp is there any reason why this option it was not set to `true` like done in this PR?

**Comment by millsp** [comment]
No I don't think there's any reason, it should always be marked as programmatic.

**Review by Jolg42 — APPROVED** [review]

**Review by Jolg42 — APPROVED** [review]
Nice, I just reproduced and it works like expected, thanks for the PR!

```
npx prisma generate
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
bun add v0.6.13 (3a93ddfa)

 installed @prisma/client@4.17.0-dev.86


 2 packages installed [343.00ms]
  Removed: 1

✔ Installed the @prisma/client and prisma packages in your project

✔ Generated Prisma Client (4.17.0-dev.86 | library) to ./node_modules/@prisma/client in 45ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
...
```
