### PR TITLE
test(client): fix db isolation and run tests in parallel

### LINKED ISSUE #13186: Database isolation in the new test setup doesn't work properly
The regular expression in `setupTestSuiteDbURI()` doesn't seem to work (at least for the PostgreSQL connection string), so tests are using the same database, and, if run concurrently, cause constraint violations, "database does not exist" errors (when the `afterAll` hook of one test suite runs in parallel with the tests from another test suite) etc.

### PR DESCRIPTION
**Pull request by SevInf**
- Introduce separate set of env variables for functional tests DBs
urls. During test execution, `PRISMA_DB_NAME` substring in those URLs
will be replaced with unique name.
- Workaround for iTx performance issues with library engine
- Workaround for jest BigInt serialization issues

Fix #13186

### CODE REVIEW

**Comment by SevInf** [comment]
Before:
image


After:
image

**Comment by danstarns** [comment]
This doesn't work on windows! :O I can't figure out why but the process.env is not preserved. I'm using direnv, and on main, the test suite runs fine, however, when switching to this branch I get: 

```
danie@danielspc MINGW64 /c/code/prisma/packages/client (test/db-isolation)
$ pnpm run test:functional:code

> @prisma/client@0.0.0 test:functional:code C:\code\prisma\packages\client
> node -r esbuild-register helpers/functional-test/run-tests.ts --no-types

{
  column: 27,
  file: 'C:\\code\\prisma\\packages\\engines\\dist\\index.js',
  length: 2,
  line: 9061,
  lineText: '          } else if (x === -0) {',
  namespace: '',
  suggestion: ''
}
Comparison with -0 using the "===" operator will also match 0
 FAIL  tests/functional/reuse-binary-engine/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  tests/functional/queryRaw-send-type-hints/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  tests/functional/missing-env/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  tests/functional/queryRaw-typed-results/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  tests/functional/metrics-disabled/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  tests/functional/queryRaw-typed-results-advanced-and-native-types/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  tests/functional/_example/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  tests/functional/metrics/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  tests/functional/interactive-transactions/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  tests/functional/json-null-types/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  tests/functional/handle-int-overflow/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  tests/functional/too-many-instances-of-prisma-client/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  tests/functional/empty-to-raw/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  tests/functional/invalid-env/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  tests/functional/init-error/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  tests/functional/decimal-list/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  tests/functional/count/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  tests/functional/decimal/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  tests/functional/restart/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  tests/functional/findFirstOrThrow/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  tests/functional/findUniqueOrThrow/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  tests/functional/blog-update/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  tests/functional/create-many/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

Summary of all failing tests
 FAIL  reuse-binary-engine/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  queryRaw-send-type-hints/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  missing-env/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  queryRaw-typed-results/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  metrics-disabled/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  queryRaw-typed-results-advanced-and-native-types/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  _example/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  metrics/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  interactive-transactions/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  json-null-types/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  handle-int-overflow/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  too-many-instances-of-prisma-client/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  empty-to-raw/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  invalid-env/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  init-error/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  decimal-list/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  count/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  decimal/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  restart/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  findFirstOrThrow/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  findUniqueOrThrow/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  blog-update/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)

 FAIL  create-many/tests.ts
  ● Test suite failed to run

    Required env variable TEST_FUNCTIONAL_MONGO_URI is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions

      30 |   const value = process.env[varName]
      31 |   if (!value) {
    > 32 |     throw new Error(
         |           ^
      33 |       `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
      34 |     )
      35 |   }

      at requireEnvVariable (_utils/setupTestSuiteEnv.ts:32:11)
      at Object.<anonymous> (_utils/setupTestSuiteEnv.ts:17:12)
      at Object.<anonymous> (_utils/setupTestSuiteClient.ts:14:104)


Test Suites: 23 failed, 23 total
Tests:       0 total
Snapshots:   0 total
Time:        7.036 s
Ran all test suites.
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by danstarns** [comment]
> @danstarns if you use `direnv` with a `.envrc` file, you will need to run `direnv allow .`

I have & branch `main` works fine with direnv.

**Review by danstarns — APPROVED** [review]
This works! My previous comments is because I forgot/did not realize to add the new env vars. **If you are using docker in local development please add the following to your .envrc file:** 

```
export TEST_FUNCTIONAL_POSTGRES_URI="postgres://prisma:prisma@localhost:5432/PRISMA_DB_NAME"
export TEST_FUNCTIONAL_MYSQL_URI="mysql://root:root@localhost:3306/PRISMA_DB_NAME"
export TEST_FUNCTIONAL_MSSQL_URI="sqlserver://localhost:1433;database=PRISMA_DB_NAME-migrate;user=SA;password=Pr1sm4_Pr1sm4;trustServerCertificate=true;"
export TEST_FUNCTIONAL_MONGO_URI="mongodb://root:prisma@localhost:27018/PRISMA_DB_NAME?authSource=admin"
export TEST_FUNCTIONAL_COCKROACH_URI="postgresql://prisma@localhost:26257/PRISMA_DB_NAME"
```

File: packages/client/tests/functional/_utils/setupTestSuiteEnv.ts [hunk 1]
```diff
@@ -1,14 +1,40 @@
...
+ */
+function requireEnvVariable(varName: string): string {
+  const value = process.env[varName]
+  if (!value) {
+    throw new Error(
+      `Required env variable ${varName} is not set. See https://github.com/prisma/prisma/blob/main/TESTING.md for instructions`,
+    )
+  }
+  return value
+}
```
Comment (aqrln) [inline packages/client/tests/functional/_utils/setupTestSuiteEnv.ts:37]:
```suggestion
}

```

File: packages/client/tests/functional/_utils/setupTestSuiteEnv.ts [hunk 2]
```diff
@@ -1,14 +1,40 @@
-import crypto from 'crypto'
+import cuid from 'cuid'
 import fs from 'fs-extra'
 import path from 'path'
+import { performance } from 'perf_hooks'
```
Comment (aqrln) [inline packages/client/tests/functional/_utils/setupTestSuiteEnv.ts:4]: I believe it's not used currently

```suggestion
```

**Review by aqrln — APPROVED** [review]

File: .buildkite/test/run.sh [hunk 3]
```diff
@@ -42,11 +42,4 @@ pnpm run test
 
 # New client test suite
 # 
-# TODO make make side effect free and isolated since it can right now, only be ran after `pnpm run test`
-# because it drops the postgresql `tests` database which result in the following error during `pnpm run test` if `test:functional` are run before
-# FAIL  src/__tests__/integration/postgresql/runtime.test.ts
-# FAIL  src/__tests__/integration/postgresql/introspection.test.ts
-#  error: database "tests" does not exist
-# Test Suites: 2 failed, 8 passed, 10 total
-# https://buildkite.com/prisma/release-prisma-typescript/builds/6514
```
Comment (Jolg42) [inline .buildkite/test/run.sh:51]: Then you can now move `pnpm run --filter "@prisma/client" test:functional` to be before `pnpm run test`
