### PR TITLE
fix(sdk): unable to build when no yarn is installed globally

### LINKED ISSUE #4179: CONTRIBUTING.md missing YARN dependency
## Bug description

When i was copying repo to contribute i encountered that in order to build "client" package i had to install YARN globally, although in the CONTRIBUTING.md it is not mentioned.
Here's the usage place that was failing for me before i installed YARN:
https://github.com/prisma/prisma/blob/284891a1d04a1d98f358b5cd141c79c0106ed0c3/src/packages/sdk/src/getPackedPackage.ts#L48

## How to reproduce

1. Consider clean npm install (no yarn is installed)
2. Follow CONTRIBUTING.md guide for "client"

## Expected behavior

1) YARN is mentioned in CONTRIBUTING.md
or
2) YARN is not mentioned in CONTRIBUTING.md, but then "client" should be able to build and i can contribute without having YARN

## Environment & setup

- OS: Ubuntu 20.04.1 LTS
- Node.js version: v15.1.0
- NPM version: 7.0.9
- Prisma version: git master branch

### PR DESCRIPTION
**Pull request by muxahuk**
fixes https://github.com/prisma/prisma/issues/4179

### CODE REVIEW

**Comment by Jolg42** [comment]
Thanks for your contribution 😃 @muxahuk 

@timsuchanek could you review?

It's about the dev setup that needs yarn for `yarn pack`, this PR makes it possible to use `npm pack`.

File: src/packages/sdk/src/getPackedPackage.ts [hunk 1]
```diff
@@ -44,12 +47,24 @@ export async function getPackedPackage(
...
-  await execa.command(`yarn pack -f ${archivePath}`, {
+  await execa.command(packCMD, {
     shell: true,
-    cwd: packageDir,
+    cwd: isYarn ? packageDir : tmpDir, // for npm pack it outputs a file to the cwd
   })
 
+  if (!isYarn) { // since npm pack does not have option to specify a filename we change it here
+    // find single tgz in temp folder
+    const filename = (await readdir(tmpDir))[0]
```
Comment (timsuchanek) [inline src/packages/sdk/src/getPackedPackage.ts:63]: From just reading this, can't it be, that `npm pack` will create a `.tgz` in a folder that already has files? If there would be a file that would be read first, we would have the wrong file here

**Review by timsuchanek — CHANGES_REQUESTED** [review]

File: src/packages/sdk/src/getPackedPackage.ts (hunk 1 above)
Comment (muxahuk) [reply src/packages/sdk/src/getPackedPackage.ts:63]: if we assume that tmp directory is the same - yes,
but as it is stated in docs. of tempy library, that is being used to create a tmp dir.:
```
tempy.directory(options?)
Get a temporary directory path. **The directory is created for you.**
```
it will create a unique directory every time, leading to the empty directory, so practically this cannot happen.

Comment (timsuchanek) [reply src/packages/sdk/src/getPackedPackage.ts:63]: Ok, but isn't `npm pack` generating to `packageDir` here, which is not the `tmp` dir, but the actual directory of the package?

Comment (muxahuk) [reply src/packages/sdk/src/getPackedPackage.ts:63]: no it is not. `npm pack` is generating tgz to the `cwd` of the process and on line 58
```
cwd: isYarn ? packageDir : tmpDir, // for npm pack it outputs a file to the cwd
```
i'm setting `cwd` to be `tmpDir`.
Meaning if u do something like: `cd /tmp/ && npm pack /abs/path/to/package/` it will output tgz into the `tmp` directory.

Comment (timsuchanek) [reply src/packages/sdk/src/getPackedPackage.ts:63]: Ok now I get it. Thanks for clarifying!

**Review by timsuchanek — APPROVED** [review]
