### PR TITLE
test(client): Regression test for gh-13766

### LINKED ISSUE #13766: Update Restrict failed on prisma referentialIntegrity
### Bug description

If you enable the previewFeatures referentialIntegrity, and you have a relation i.e., 1-many and you try to update a column(a non primary key) from the parent table, prisma gives an error.

```
The change you are trying to make would violate the required relation 'OrderToOrderStatusHistory' between the `Order` and `OrderStatusHistory` models.
```

With the default referentialIntegrity from the database the update succeed. Or if you change the onUpdate: Cascade

### How to reproduce

I have create a public project that you can clone if you like:
https://github.com/ManolisPap/prisma-playground

- Create an empty database with mysql or PlaneScale
- create the .env file with an envirome variable DATABASE_URL='...'
- create the prisma.schema file (with the attached code)
- npx prisma db push
- create the index2.ts file (with the attached code)
- run the index2.ts file npx ts-node index2.ts
- The typescript code will run successfully and we will create a new Order and a new OrderStatusHistory but then it will fail to update the paid column of the order with id 1.
- Or just follows the step from prisma.io:
[https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/relational-databases-typescript-postgres](Initial Setup)

### Expected behavior

Update the paid field to true(1).

### Prisma information

**prisma.schema**

```prisma
datasource db {
  provider             = "mysql"
  url                  = env("DATABASE_URL")
  referentialIntegrity = "prisma"
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
}

enum OrderStatus {
  NEW
  PICKED
  STORED
  DELIVERED
}

model Order {
  orderId          Int                  @id @default(autoincrement())
  paid             Boolean?
  statusMilestones OrderStatusHistory[]

  @@index([orderId])
}

model OrderStatusHistory {
  orderStatusHistoryId Int         @id @default(autoincrement())
  orderId              Int
  status               OrderStatus
  createdAt            DateTime    @default(now())
  order                Order       @relation(fields: [orderId], references: [orderId], onUpdate: Restrict, onDelete: Cascade)

  @@index([orderId])
}

```

**Dummy Typescript usage**
```ts
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient({
  log: ["query", "info", "warn", "error"],
  errorFormat: "pretty",
});

async function main() {
  const ordersNum = await prisma.order.count();
  console.log("Orders into database: " + ordersNum);

  if (ordersNum == 0) {
    console.log("Create a new order");
    const order = await prisma.order.create({
      data: {
        orderId: 1,
        paid: false,
        statusMilestones: {
          create: {
            status: "NEW",
          },
        },
      },
    });
    console.log(order);
  }

  console.log("Update Order with id 1");
  const updatedOrder = await prisma.order.update({
    where: {
      orderId: 1,
    },
    data: {
      paid: true,
    },
  });
  console.log(updatedOrder);
}

main()
  .catch((e) => {
    throw e;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
```

### Environment & setup

OS: Windows
Database: mySQL or Planetscale
Node.js version: v16.13.0

### Prisma Version

prisma: "^3.15.1"

### PR DESCRIPTION
**Pull request by danstarns**
Closes: [Update Restrict failed on prisma referentialIntegrity](https://github.com/prisma/prisma/issues/13766)

Integrates Engines: https://github.com/prisma/prisma-engines/pull/3194

### CODE REVIEW

File: packages/client/tests/functional/issues/13766/tests.ts [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+      await expect(() =>
+        prisma.order.update({
+          where: {
+            orderId: orderId1,
+          },
+          data: {
+            orderId: orderId2,
+          },
+        }),
+      ).toThrowError()
```
Comment (danstarns) [inline packages/client/tests/functional/issues/13766/tests.ts:76]: **This assertion is currently failing in CI.**

According to the solution here: https://www.notion.so/prismaio/emulated-onUpdate-Restrict-is-broken-e0e5109e23a64398896a748afdd8ddcd this should throw.

Screenshot 2022-09-21 at 19 42 34

File: packages/client/tests/functional/issues/13766/tests.ts [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+import type { PrismaClient } from '@prisma/client'
+
+import testMatrix from './_matrix'
+
+declare let prisma: PrismaClient
+
+// https://github.com/prisma/prisma/issues/13766
+testMatrix.setupTestSuite(
+  ({ provider }) => {
+    test('should not prevent any updates on a model when updating a field', async () => {
```
Comment (danstarns) [inline packages/client/tests/functional/issues/13766/tests.ts:12]: This works.

File: packages/client/tests/functional/issues/13766/tests.ts [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+        },
+        data: {
+          paid: true,
+        },
+      })
+
+      expect(updatedOrder).toMatchObject({ orderId, paid: true })
+    })
+
+    test('should prevent updates on a model if any other relation references an field', async () => {
```
Comment (danstarns) [inline packages/client/tests/functional/issues/13766/tests.ts:39]: This fails.

File: packages/client/tests/functional/issues/13766/tests.ts (hunk 1 above)
Comment (Jolg42) [reply packages/client/tests/functional/issues/13766/tests.ts]: @danstarns Note that this was incorrect 
```
      await expect(() =>
        prisma.order.update({
          where: {
            orderId: orderId1,
          },
          data: {
            orderId: orderId2,
          },
        }),
      ).toThrowError()
```
and this is the correct version
```
      await expect(
        prisma.order.update({
          where: {
            orderId: orderId1,
          },
          data: {
            orderId: orderId2,
          },
        }),
      ).rejects.toThrowError()
```

File: packages/client/tests/functional/issues/13766/prisma/_schema.ts [hunk 4]
```diff
@@ -11,25 +11,21 @@ export default testMatrix.setupSchema(({ provider }) => {
     datasource db {
       provider = "${provider}"
       url      = env("DATABASE_URI_${provider}")
-    }
-
-    enum OrderStatus {
-      NEW
-      PICKED
-      STORED
-      DELIVERED
```
Comment (janpio) [inline packages/client/tests/functional/issues/13766/prisma/_schema.ts]: Just cleanup because irrelevant or did this cause trouble @Jolg42?

File: packages/client/tests/functional/issues/13766/prisma/_schema.ts [hunk 5]
```diff
@@ -11,25 +11,21 @@ export default testMatrix.setupSchema(({ provider }) => {
...
+      id               ${idForProvider(provider)}
+      orderId          String @unique
       paid             Boolean?
       statusMilestones OrderStatusHistory[]
     }
 
     model OrderStatusHistory {
-      orderStatusHistoryId ${idForProvider(provider)}
+      id                   ${idForProvider(provider)}
+      orderStatusHistoryId String
```
Comment (janpio) [inline packages/client/tests/functional/issues/13766/prisma/_schema.ts:26]: Why do we need 2 IDs here @Jolg42? Workaround for test setup limitation?

File: packages/client/tests/functional/issues/13766/prisma/_schema.ts (hunk 4 above)
Comment (Jolg42) [reply packages/client/tests/functional/issues/13766/prisma/_schema.ts]: To make it possible to run SQLite and SQL Server
https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#enum
>Not supported by SQLite and Microsoft SQL Server
The [SQLite connector](https://www.prisma.io/docs/concepts/database-connectors/sqlite) and the The [Microsoft SQL Server connector](https://www.prisma.io/docs/concepts/database-connectors/sql-server) do not support the enum type.

File: packages/client/tests/functional/issues/13766/prisma/_schema.ts (hunk 5 above)
Comment (Jolg42) [reply packages/client/tests/functional/issues/13766/prisma/_schema.ts:26]: Workaround for testing MongoDB since the _id is immutable

Comment (janpio) [reply packages/client/tests/functional/issues/13766/prisma/_schema.ts:26]: Maybe worth separating into two different tess then? One for Mongo with this setup, and one that really reproduces the original issue? I am not sure what different behavior this could trigger. Or are you sure enough it does not?

Comment (Jolg42) [reply packages/client/tests/functional/issues/13766/prisma/_schema.ts]: see new commit and README, I split into 2 schemas.

Comment (janpio) [reply packages/client/tests/functional/issues/13766/prisma/_schema.ts]: Nice!

**Comment by Jolg42** [comment]
Waiting for pipeline to be unblocked before merging
