### PR TITLE
fix(adapter-pg): add conversion mapping for timestamptz arrays

### LINKED ISSUE #27248: Creating a row with pg timestamptz array with Prisma throws error
### Bug description

When using Prisma with a PostgreSQL `timestamptz` array column, the `create()` operation fails with the following error:

```log
PrismaClientKnownRequestError: 
Invalid `prisma.metadata.create()` invocation:


Inconsistent column data: Column type 'Unknown' could not be deserialized from the database.
    at Zn.handleRequestError (/Users/nakul/Documents/Codes/others/pg-timestamptz-arrays-error/node_modules/prisma-client-autogen/runtime/library.js:124:7459)
    at Zn.handleAndLogRequestError (/Users/nakul/Documents/Codes/others/pg-timestamptz-arrays-error/node_modules/prisma-client-autogen/runtime/library.js:124:6784)
    at Zn.request (/Users/nakul/Documents/Codes/others/pg-timestamptz-arrays-error/node_modules/prisma-client-autogen/runtime/library.js:124:6491)
    at async l (/Users/nakul/Documents/Codes/others/pg-timestamptz-arrays-error/node_modules/prisma-client-autogen/runtime/library.js:133:9778)
    at async main (file:///Users/nakul/Documents/Codes/others/pg-timestamptz-arrays-error/src/main.js:31:25) {
  code: 'P2023',
  meta: {
    modelName: 'Metadata',
    message: "Column type 'Unknown' could not be deserialized from the database."
  },
  clientVersion: '6.8.2'
}
```

The `INSERT` SQL command inserts a record into the table without any issues.

### Severity

🔹 Minor: Unexpected behavior, but does not block development

### Reproduction

Public GitHub repo with the reproducible example can be found [here](https://github.com/nakul-bigpi/pg-timestamptz-arrays-error).

### Expected vs. Actual Behavior

**Actual:** Got error `Inconsistent column data: Column type 'Unknown' could not be deserialized from the database.` while creating a row with timestamptz array column.

**Expected:** This operation should go through without any errors.

### Frequency

Consistently reproducible

### Does this occur in development or production?

Both development and production

### Is this a regression?

Not sure, I tried it with `5.17.0` and then with `6.8.2` - the issue happened in both versions. I have included `6.8.2` in my reproducible example above.

### Workaround

No workaround, I had to patch the package with pnpm.

### Prisma Schema & Queries

**Prisma schema:**
```prisma
generator client {
  provider        = "prisma-client-js"
  output          = "../node_modules/prisma-client-autogen"
  previewFeatures = ["driverAdapters"]
  binaryTargets   = ["native", "linux-musl", "linux-musl-openssl-3.0.x", "darwin-arm64", "linux-arm64-openssl-1.1.x"]
}

generator json {
  provider = "prisma-json-types-generator"
}

datasource db {
  provider = "postgres"
  url      = env("POSTGRES_URL")
}

model Metadata {
  id             String     @id @default(uuid()) @db.Uuid
  fieldName      String
  dateListValues DateTime[] @default([]) @db.Timestamptz(0)
}
```

**Prisma query:**
```ts
const newMetadata = await prisma.metadata.create({
  data: {
    fieldName: "inductionDates",
    dateListValues: [new Date(), new Date()],
  },
});
```

### Prisma Config

```ts
// Add your `prisma.config.ts`
```

### Logs & Debug Info

```log
PrismaClientKnownRequestError: 
Invalid `prisma.metadata.create()` invocation:


Inconsistent column data: Column type 'Unknown' could not be deserialized from the database.
    at Zn.handleRequestError (/Users/nakul/Documents/Codes/others/pg-timestamptz-arrays-error/node_modules/prisma-client-autogen/runtime/library.js:124:7459)
    at Zn.handleAndLogRequestError (/Users/nakul/Documents/Codes/others/pg-timestamptz-arrays-error/node_modules/prisma-client-autogen/runtime/library.js:124:6784)
    at Zn.request (/Users/nakul/Documents/Codes/others/pg-timestamptz-arrays-error/node_modules/prisma-client-autogen/runtime/library.js:124:6491)
    at async l (/Users/nakul/Documents/Codes/others/pg-timestamptz-arrays-error/node_modules/prisma-client-autogen/runtime/library.js:133:9778)
    at async main (file:///Users/nakul/Documents/Codes/others/pg-timestamptz-arrays-error/src/main.js:31:25) {
  code: 'P2023',
  meta: {
    modelName: 'Metadata',
    message: "Column type 'Unknown' could not be deserialized from the database."
  },
  clientVersion: '6.8.2'
}
```

### Environment & Setup

- **OS:** macOS
- **Database:** PostgreSQL
- **Node.js version:** v20.11.1

### Prisma Version

```log
prisma                  : 6.8.2
@prisma/client          : 6.8.2
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.11.1
TypeScript              : 5.8.3
Query Engine (Node-API) : libquery-engine 2060c79ba17c6bb9f5823312b6f6b7f4a845738e (at node_modules/.pnpm/@prisma+engines@6.8.2/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 2060c79ba17c6bb9f5823312b6f6b7f4a845738e (at node_modules/.pnpm/@prisma+engines@6.8.2/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 6.8.0-43.2060c79ba17c6bb9f5823312b6f6b7f4a845738e
Default Engines Hash    : 2060c79ba17c6bb9f5823312b6f6b7f4a845738e
Studio                  : 0.511.0
```

### PR DESCRIPTION
**Pull request by nakul-bigpi**
Fixes #27248.

### CODE REVIEW

File: packages/adapter-pg/src/conversion.ts [hunk 1]
```diff
@@ -33,6 +33,7 @@ const ArrayColumnType = {
   OID_ARRAY: 1028,
   TEXT_ARRAY: 1009,
   TIMESTAMP_ARRAY: 1115,
+  TIMESTAMPTZ_ARRAY: 1185,
```
Comment (nakul-bigpi) [inline packages/adapter-pg/src/conversion.ts:36]: oid `1185` comes from - https://github.com/postgres/postgres/blob/master/src/include/catalog/pg_type.dat#L306

**Review by jacek-prisma — APPROVED** [review]
LGTM, thanks for the contribution!
