### PR TITLE
fix(client): Ensure empty array argument is not turned into object

### LINKED ISSUE #18846: GraphQL protocol encoder incorrectly turns empty array into empty object.
Schema:

```prisma
generator client {
  provider = "prisma-client-js"
  output   = "../node_modules/.prisma/client"
}

datasource db {
  provider = "postgresql"
  url      = env("TEST_POSTGRES_URI")
}

model User {
  id     String  @id @map("_id")
  active Boolean
}
```

TS:

```ts
  await prisma.user.findMany({
    where: {
      // @ts-ignore
      AND: [[], undefined],
    },
  })
```

This input is invalid: arrays are not valid values for individual elements of `AND` filter. It is correctly rejected by generated TS types. Yet, if we are using it with GraphQL protocol and `@ts-ignore` from a snippet above, the following GraphQL query is produced:

```graphql
query {
  findManyUser(where: {
    AND: [{}]
  }) {
    id
    active
  }
}
```

So, empty array element got turned into an empty object, making the query valid. As soon as we add at least one element to the array, this correctly throws validation error again. 

We believe this is not intentional and validation error should be thrown for empty array case as well. Error is present when JSON protocol is used.

### PR DESCRIPTION
**Pull request by SevInf**
Fix #18846

### CODE REVIEW

File: packages/client/src/runtime/query.ts [hunk 1]
```diff
@@ -1507,12 +1533,12 @@ function tryInferArgs(
...
   return new Arg({
     key,
-    value: value.map((v) => {
+    value: value.map((v, i) => {
       if (inputType.isList && typeof v !== 'object') {
         return v
       }
-      if (typeof v !== 'object' || !value) {
-        return getInvalidTypeArg(key, v, arg, inputType)
+      if (typeof v !== 'object' || !value || Array.isArray(v)) {
```
Comment (SevInf) [inline packages/client/src/runtime/query.ts:1540]: This line is an actual fix, the rest is just ensuring that the error renders correctly.

Comment (Jolg42) [reply packages/client/src/runtime/query.ts:1540]: Maybe add some comments? Because it's hard to understand what's happening in general in `query.ts` 😅

File: packages/client/tests/functional/issues/18846-empty-array/_matrix.ts [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+      provider: 'mongodb',
+    },
+    {
+      provider: 'cockroachdb',
+    },
+    {
+      provider: 'sqlserver',
+    },
+  ],
+])
```
Comment (Jolg42) [inline packages/client/tests/functional/issues/18846-empty-array/_matrix.ts:24]: Technically, we could only test on 1 database? (Is there something interesting to test on different databases for this?)

Comment (SevInf) [reply packages/client/tests/functional/issues/18846-empty-array/_matrix.ts:24]: I think generally our approach for functional tests have always been "test on all providers unless you have really good reasons not too", because we had suprirsing failures on selected providers where we were absolutely sure provider makes no difference

File: packages/client/helpers/functional-test/run-tests.ts [hunk 3]
```diff
@@ -53,7 +53,7 @@ const args = arg(
 )
 
 async function main(): Promise<number | void> {
-  let jestCli = new JestCli(['--silent', '--config', 'tests/functional/jest.config.js'])
+  let jestCli = new JestCli(['--config', 'tests/functional/jest.config.js'])
```
[the remark this answers is not in the document]
Comment (SevInf) [reply packages/client/helpers/functional-test/run-tests.ts]: Was not meant to be commited, reverted

File: packages/client/src/runtime/query.ts (hunk 1 above)
Comment (SevInf) [reply packages/client/src/runtime/query.ts:1551]: Added. Not sure how much they help in a grand scheme of things though.

**Review by Jolg42 — APPROVED** [review]

**Review by aqrln — APPROVED** [review]
