### PR TITLE
fix(client): Fix $Enums namespace in browser build

### LINKED ISSUE #20480: Unhandled Runtime Error when upgrading to 5.1.0 from 5.0.0
### Bug description

I just upgraded to 5.1.0 and getting an `Unhandled Runtime Error`, don't really know how to debug. `Category` is one of my enum tables in schema.

```
Unhandled Runtime Error
TypeError: Cannot set properties of undefined (setting 'Category')

Call Stack
eval
node_modules/.prisma/client/index-browser.js (430:42)
./node_modules/.prisma/client/index-browser.js
file:///Users/lipis/work/lim-expenses/.next/static/chunks/pages/index.js (17:1)
options.factory
/_next/static/chunks/webpack.js (707:31)
__webpack_require__
file:///Users/lipis/work/lim-expenses/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (362:21)
eval
node_modules/@prisma/client/index-browser.js (1:15)
./node_modules/@prisma/client/index-browser.js
file:///Users/lipis/work/lim-expenses/.next/static/chunks/pages/index.js (27:1)
options.factory
/_next/static/chunks/webpack.js (707:31)
__webpack_require__
file:///Users/lipis/work/lim-expenses/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (362:21)
eval
webpack-internal:///./lib/date-utils.ts (27:72)
./lib/date-utils.ts
file:///Users/lipis/work/lim-expenses/.next/static/chunks/pages/index.js (9363:1)
options.factory
/_next/static/chunks/webpack.js (707:31)
__webpack_require__
file:///Users/lipis/work/lim-expenses/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (362:21)
eval
webpack-internal:///./components/branches/BranchItem.tsx (4:73)
./components/branches/BranchItem.tsx
file:///Users/lipis/work/lim-expenses/.next/static/chunks/pages/index.js (9198:1)
options.factory
/_next/static/chunks/webpack.js (707:31)
__webpack_require__
file:///Users/lipis/work/lim-expenses/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (362:21)
eval
webpack-internal:///./pages/index.tsx (8:89)
./pages/index.tsx
file:///Users/lipis/work/lim-expenses/.next/static/chunks/pages/index.js (9493:1)
options.factory
/_next/static/chunks/webpack.js (707:31)
__webpack_require__
file:///Users/lipis/work/lim-expenses/.next/static/chunks/webpack.js (37:33)
fn
/_next/static/chunks/webpack.js (362:21)
eval
node_modules/next/dist/build/webpack/loaders/next-client-pages-loader.js?absolutePagePath=%2FUsers%2Flipis%2Fwork%2Flim-expenses%2Fpages%2Findex.tsx&page=%2F! (5:15)
execute
node_modules/next/dist/client/route-loader.js (233:50)
```

### Expected behavior

_No response_

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

generator erd {
  provider  = "prisma-erd-generator"
  output    = "../prisma/ERD.svg"
  tableOnly = true
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

enum Method {
  bank
  cash
  check
  credit
  delivery
}

enum Category {
  expense
  recurrent
  report
  revenue
  salary
  share
  vendor
}

enum Duration {
  day
  week
  month
  quarter
  semester
  year
  all
}

model Config {
  id           Int    @id @default(0)
  trialDays    Int    @default(60)
  priceMonth   Int    @default(29)
  priceYear    Int    @default(299)
  priceTax     Float  @default(0)
}

...

```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v18.17.0

### Prisma Version

```
5.1.0
```

### PR DESCRIPTION
**Pull request by SevInf**
$Enums namespace was correctly created for server-side clients, but not
for browser.

Fix #20480

/integration

### CODE REVIEW

**Review by aqrln — APPROVED** [review]

**Review by Jolg42 — APPROVED** [review]
Nice! 🚀

File: packages/client/tests/e2e/browser-enum/_steps.ts [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+
+import { executeSteps } from '../_utils/executeSteps'
+
+void executeSteps({
+  setup: async () => {
+    await $`pnpm install`
+    await $`pnpm exec prisma generate`
+  },
+  test: async () => {
+    await $`pnpm exec jest`
```
Comment (millsp) [inline packages/client/tests/e2e/browser-enum/_steps.ts:11]: I think we could also typecheck?

**Review by millsp — APPROVED** [review]

File: packages/client/tests/e2e/browser-enum/_steps.ts (hunk 1 above)
Comment (SevInf) [reply packages/client/tests/e2e/browser-enum/_steps.ts:11]: We don't actually have `.d.ts` file for `index-browser`, so `tsc` fails with direct import. I think better test for this would be importing `@prisma/client`,  bundling it and running it in proper browser-like environment (jsdom? pupeeteer?), but for the sake of getting the fix faster, i'd suggest we do afterwards.

Comment (millsp) [reply packages/client/tests/e2e/browser-enum/_steps.ts:11]: :+1:
