### PR TITLE
fix(client,internals,migrate,generator-helper): handle multibyte UTF-8 characters split across chunk boundaries in byline

### LINKED ISSUE #27695: DMMF Generation Causes UTF-8 Character Corruption for Japanese Characters
### Bug description

Prisma's DMMF (Data Model Meta Format) generation corrupts Japanese UTF-8 characters before they reach custom generators.
Specifically, 3-byte UTF-8 characters like "者" (U+8005) and "時" (U+6642) are replaced with Unicode replacement characters (U+FFFD) during the DMMF generation process within Prisma engines, not in the custom generator code itself.

### Severity

⚠️ Major: Breaks core functionality (e.g., migrations fail)

### Minimal Repository
This issue can be reproduced with this repository: [problem-prisma-dmmf-garbled](https://github.com/example/problem-prisma-dmmf-garbled)

### Steps to Reproduce

**Option A: VS Code DevContainer**
1. Open this repository in VS Code DevContainer
2. Run `pnpm i` to install dependencies
3. Run `npx prisma generate` to generate DMMF
4. Check `prisma/migrations/dmmf.json` for character corruption

**Option B: GitHub Codespaces**
1. Open this repository in GitHub Codespaces
2. Run `pnpm i` to install dependencies
3. Run `npx prisma generate` to generate DMMF
4. Check `prisma/migrations/dmmf.json` for character corruption

**Note:** Different environments will show different corruption patterns. Testing in multiple environments is recommended to observe the platform-dependent nature of this issue.

### Quick Reproduction Command
```bash
rm -rf prisma/migrations/ && npx prisma generate && grep -n -P '\xEF\xBF\xBD' prisma/migrations/dmmf.json
```

### Important Note on Reproducibility
**The corruption is probabilistic and platform-dependent** - running the same command multiple times may produce different results, and different environments corrupt different characters:

**WSL2 Environment:**
- "最終更新者" corruption: **Always occurs** (100% reproduction rate - 5/5 runs)
- "承認日時" corruption: **Sometimes occurs** (60% reproduction rate - 3/5 runs)
- Both corruptions simultaneously: 60% of the time

**GitHub Codespaces Environment:**
- "分析実行日時" corruption: **Occurs 80% of the time** (4/5 runs in testing)
- Single corruption point (vs. WSL2's dual corruption pattern)
- Different line numbers and characters affected compared to WSL2

Run the command multiple times to observe the varying behavior:
```bash
# Run this several times to see different corruption patterns
for i in {1..5}; do
  echo "=== Run $i ==="
  rm -rf prisma/migrations/ && npx prisma generate >/dev/null 2>&1
  echo "Corrupted lines found:"
  grep -n -P '\xEF\xBF\xBD' prisma/migrations/dmmf.json || echo "No corruption detected"
  echo
done
```

### Key Requirements for Reproduction

**Important:** This issue only occurs with **large schema.prisma files** containing Japanese characters at specific byte positions. A minimal schema will NOT reproduce the issue.

The reproduction repository contains:
- **Large schema.prisma** (~69KB with extensive Japanese documentation)
- **Custom generator** that outputs DMMF as JSON
- **Environment-dependent corruption patterns** at different positions in the file

**Example of affected lines in the repository's schema.prisma:**
```prisma
/// 最終更新者 - 最後に更新した担当者  # ← Gets corrupted to "最終更新�� - ..."
lastUpdatedBy String? @map("last_updated_by")

/// 承認日時 - 検査結果が承認された日時  # ← Gets corrupted to "承���日時 - ..."
approvedAt DateTime? @map("approved_at") @db.Timestamptz()
```

**Custom generator (generator.ts):**
```typescript
#!/usr/bin/env node
import generatorHelper from "@prisma/generator-helper";
import type { GeneratorOptions } from "@prisma/generator-helper";
import fs from "fs";
import path from "path";

const generate = async (options: GeneratorOptions) => {
  const { dmmf } = options;
  const outputDir = options.generator.output?.value!;
  fs.mkdirSync(outputDir, { recursive: true });
  
  const dmmfFilePath = path.join(outputDir, "dmmf.json");
  fs.writeFileSync(dmmfFilePath, JSON.stringify(dmmf, null, 2), "utf-8");
};

generatorHelper.generatorHandler({
  onManifest: () => ({
    defaultOutput: "migrations",
    prettyName: "Prisma Database Comments",
  }),
  onGenerate: generate,
});
```

**Why a minimal example won't work:**
- The issue is **position-dependent** (specific byte offsets in large files)
- **Different environments corrupt different positions:**
  - WSL2: schema.prisma bytes 41,557 and 63,915 → DMMF lines 6776, 10389
  - Codespaces: different schema position → DMMF line 11235
- Adding/removing content changes byte positions and prevents reproduction

### Expected vs. Actual Behavior

**Expected:** Japanese characters should be preserved exactly as written in schema comments
```json
"documentation": "最終更新者 - 最後に更新した担当者"
"documentation": "承認日時 - 検査結果が承認された日時"
```

**Actual:** Characters get corrupted with Unicode replacement characters
```json
"documentation": "最終更新�� - 最後に更新した担当者"
"documentation": "承���日時 - 検査結果が承認された日時"
```

### Frequency

Intermittent / Random

### Does this occur in development or production?

Only in development (e.g., CLI tools, migrations, Prisma Studio)

### Is this a regression?

**Unknown** - Not confirmed if this is a regression or existing issue

### Workaround

**No viable workaround available.** 

While adding content before the problematic byte positions can prevent corruption in testing, this is not a practical solution as:
- It requires modifying the schema content artificially
- It's unpredictable which positions will be affected in different environments
- It doesn't address the underlying memory corruption issue

### Prisma Schema & Queries

See minimal reproduction example above. The issue occurs with any Japanese 3-byte UTF-8 characters in schema documentation comments.

### Prisma Config

```ts
// Add your `prisma.config.ts`
```

### Logs & Debug Info

**WSL2 Environment:**
```bash
$ rm -rf prisma/migrations/ && npx prisma generate && grep -n -P '\xEF\xBF\xBD' prisma/migrations/dmmf.json
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (v6.12.0) to ./node_modules/.pnpm/@prisma+client@6.12.0_prisma@6.12.0_typescript@5.8.3__typescript@5.8.3/node_modules/@prisma/client in 367ms

✔ Generated Prisma Database Comments to ./prisma/migrations in 336ms

6776:            "documentation": "最終更新�� - 最後に更新した担当者"
10389:            "documentation": "承���日時 - 検査結果が承認された日時"
```

**GitHub Codespaces Environment:**
```bash
$ rm -rf prisma/migrations/ && npx prisma generate && grep -n -P '\xEF\xBF\xBD' prisma/migrations/dmmf.json
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (v6.12.0) to ./node_modules/.pnpm/@prisma+client@6.12.0_prisma@6.12.0_typescript@5.8.3__typescript@5.8.3/node_modules/@prisma/client in 345ms

✔ Generated Prisma Database Comments to ./prisma/migrations in 229ms

11235:            "documentation": "分析実行日時 - 分���を実行した日時"
```

**Probabilistic Behavior in WSL2 (5 consecutive runs):**
```bash
=== Run 1 ===
6776:            "documentation": "最終更新�� - 最後に更新した担当者"
=== Run 2 ===
6776:            "documentation": "最終更新�� - 最後に更新した担当者"
10389:            "documentation": "承���日時 - 検査結果が承認された日時"
=== Run 3 ===
6776:            "documentation": "最終更新�� - 最後に更新した担当者"
=== Run 4 ===
6776:            "documentation": "最終更新�� - 最後に更新した担当者"
10389:            "documentation": "承���日時 - 検査結果が承認された日時"
=== Run 5 ===
6776:            "documentation": "最終更新�� - 最後に更新した担当者"
10389:            "documentation": "承���日時 - 検査結果が承認された日時"
```

**Probabilistic Behavior in Codespaces (5 consecutive runs):**
```bash
=== Run 1 ===
11235:            "documentation": "分析実行日時 - 分���を実行した日時"
=== Run 2 ===
11235:            "documentation": "分析実行日時 - 分���を実行した日時"
=== Run 3 ===
No corruption detected
=== Run 4 ===
11235:            "documentation": "分析実行日時 - 分���を実行した日時"
=== Run 5 ===
11235:            "documentation": "分析実行日時 - 分���を実行した日時"
```

### Environment & Setup

**Environment 1: WSL2 (Where dual corruption occurs)**
- **OS**: Linux (WSL2) - Linux 6.6.87.1-microsoft-standard-WSL2
- **Node.js Version**: v22.12.0
- **Package Manager**: pnpm@10.12.1
- **Corruption Pattern**: Lines 6776, 10389 (100%/60% rates)

**Environment 2: GitHub Codespaces (Where single corruption occurs)**
- **OS**: Linux (Codespaces container) - Linux codespaces-a15200 6.8.0-1027-azure
- **Node.js Version**: v22.12.0
- **Package Manager**: pnpm@10.12.1
- **Corruption Pattern**: Line 11235 (80% rate)

**Common to both environments:**
- **Database**: PostgreSQL (using connection string, issue occurs during generation not DB operations)
- **Container Runtime**: Both use containerized Linux environments
- **Same codebase**: Identical schema.prisma and generator.ts files

### Prisma Version

```bash
$ npx prisma version
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
prisma                  : 6.12.0
@prisma/client          : 6.12.0
Computed binaryTarget   : debian-openssl-3.0.x
Operating System        : linux
Architecture            : x64
Node.js                 : v22.12.0
TypeScript              : 5.8.3
Query Engine (Node-API) : libquery-engine 8047c96bbd92db98a2abc7c9323ce77c02c89dbc (at node_modules/.pnpm/@prisma+engines@6.12.0/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
PSL                     : @prisma/prisma-schema-wasm 6.12.0-15.8047c96bbd92db98a2abc7c9323ce77c02c89dbc
Schema Engine           : schema-engine-cli 8047c96bbd92db98a2abc7c9323ce77c02c89dbc (at node_modules/.pnpm/@prisma+engines@6.12.0/node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x)
Default Engines Hash    : 8047c96bbd92db98a2abc7c9323ce77c02c89dbc
Studio                  : 0.511.0
```

### PR DESCRIPTION
**Pull request by onozaty**
## Summary

Fixes #27695 

This PR fixes a bug where multibyte UTF-8 characters (e.g., Japanese text, emojis) were corrupted when split across stream chunk boundaries in the `byline` module used for parsing generator output.

## Problem

The original implementation used `chunk.toString(encoding)` which does not handle incomplete multibyte sequences correctly. When a multibyte character is split across chunk boundaries, the incomplete bytes are replaced with the Unicode replacement character (�), causing corruption of DMMF output containing non-ASCII characters.

## Solution

- Replace `chunk.toString(encoding)` with Node.js `StringDecoder` which properly buffers incomplete multibyte sequences
- Use `decoder.write()` in `_transform` to handle partial sequences
- Use `decoder.end()` in `_flush` to finalize any remaining buffered bytes
- Add `node:` prefix to built-in module imports for consistency

## Changes

**Modified packages**: `generator-helper`, `client`, `internals`, `migrate`

**Implementation:**
- **Fixed** `_transform` method to use `StringDecoder.write()`
- **Fixed** `_flush` method to append remaining bytes from `StringDecoder.end()`
- **Added** Comprehensive test coverage for multibyte character handling

## Test Coverage

Added 5 tests per package (20 total) covering:
- ✅ Single-byte ASCII characters
- ✅ Multibyte characters (Japanese, emoji) in complete chunks
- ✅ Multibyte characters split across chunk boundaries
- ✅ Truncated incomplete UTF-8 sequences at stream end

All tests pass in affected packages (`generator-helper`, `client`, `internals`, `migrate`).

### CODE REVIEW

File: packages/migrate/src/utils/byline.ts [hunk 1]
```diff
@@ -83,11 +87,16 @@ LineStream.prototype._transform = function (chunk, encoding, done) {
...
-      chunk = chunk.toString() // utf8
       encoding = 'utf8'
-    } else {
-      chunk = chunk.toString(encoding)
     }
+
+    // Create decoder on first use
+    if (!this._decoder) {
+      this._decoder = new StringDecoder(encoding)
+    }
```
[the remark this answers is not in the document]
Comment (onozaty) [reply packages/migrate/src/utils/byline.ts]: I've addressed this in commit 43986d0 (fix: handle encoding changes in byline StringDecoder)

File: packages/migrate/src/__tests__/byline.test.ts [hunk 2]
```diff
@@ -0,0 +1,131 @@
...
+
+      const stream = createReadableFromChunks([chunk])
+      const lineStream = byline(stream)
+
+      const lines = await collectLines(lineStream)
+      // Should get single replacement character (�) for incomplete UTF-8 sequence
+      expect(lines).toEqual(['Complete line', 'Incomplete�'])
+    })
+
+    it('handles encoding change between chunks', async () => {
```
[the remark this answers is not in the document]
Comment (onozaty) [reply packages/migrate/src/__tests__/byline.test.ts]: I've already fixed this inconsistency in commit ad65a2d (test: use consistent `test()` function naming in byline tests). All test files now consistently use `test()` instead of mixing `test()` and `it()`.

File: packages/migrate/src/utils/byline.ts [hunk 3]
```diff
@@ -128,6 +139,17 @@ LineStream.prototype._pushBuffer = function (encoding, keep, done) {
...
 
 LineStream.prototype._flush = function (done) {
+  // Finalize decoder and get any remaining buffered bytes
+  if (this._decoder) {
+    const remaining = this._decoder.end()
+    if (remaining && this._lineBuffer.length > 0) {
+      // Append remaining bytes to last line in buffer
+      // Note: _lineBuffer always has at least one element (even if empty string)
+      // because split() always returns an array with at least one element
+      this._lineBuffer[this._lineBuffer.length - 1] += remaining
```
[the remark this answers is not in the document]
Comment (onozaty) [reply packages/migrate/src/utils/byline.ts]: Thank you for the careful review! Let me explain why `_lineBuffer` is guaranteed to have at least one element when we reach the `remaining` append logic:

**Analysis:**

1. `_lineBuffer` is initialized as an empty array: `this._lineBuffer = []` (line 64)
2. `_decoder` is also initialized as `null`: `this._decoder = null` (line 69)
3. The decoder is only created inside `_transform` when processing a buffer chunk (lines 90-92):
   ```typescript
   if (!this._decoder || this._decoderEncoding !== encoding) {
     this._decoder = new StringDecoder(encoding)
     this._decoderEncoding = encoding
   }
4. In the same `_transform` call, the chunk is split and concatenated to `_lineBuffer` (lines 100, 118):
   ```
   const lines = chunk.split(/\r\n|\r|\n/g)
   // ...
   this._lineBuffer = this._lineBuffer.concat(lines)
   ```
5. `String.prototype.split()` always returns an array with at least one element, even for empty strings:
    - `''.split(/\n/g)` → `['']`
    - `'text'.split(/\n/g)` → `['text']`
    - `'a\nb'.split(/\n/g)` → `['a', 'b']`

**Therefore:** If `this._decoder` exists (is not `null`), it means `_transform` was called at least once, which means `_lineBuffer` has at least one element from the `split()` operation. The condition `if (this._decoder)` (line 132) implicitly guarantees that `this._lineBuffer.length > 0`, making the explicit length check technically redundant but kept for defensive programming and code clarity. Edge case that cannot occur: The scenario where `_decoder` exists but `_lineBuffer` is empty would require the decoder to be created without going through `_transform`, which doesn't happen in this implementation. The current implementation correctly handles all cases.

**Comment by aqrln** [comment]
Thanks so much for this! Could we also deduplicate this and put it in a single place while we're here? Even better, any chance we could use the built-in `node:readline` module instead?

**Comment by onozaty** [comment]
Thank you for the feedback about deduplication!

I've replaced the custom byline implementation with Node.js's built-in `node:readline` module across all packages. This eliminates the duplicate code entirely.

## Changes Made

- Replaced byline with `readline.createInterface()` in:
  - `@prisma/generator-helper` (GeneratorProcess, generatorHandler)
  - `@prisma/client` (BinaryEngine)
  - `@prisma/migrate` (SchemaEngineCLI)
  - `@prisma/internals` (removed export)
- Removed 4 duplicate `byline.ts` implementations and their tests
- Removed `byline.ts` from eslint ignore patterns

Commits:
- d37f11781 - refactor(client,internals,migrate,generator-helper): replace byline with node:readline
- 84fca2c70 - chore: remove byline.ts from eslint ignore patterns
- b5c98f1ab - test(generator-helper): add readline multibyte UTF-8 handling tests

## Multibyte UTF-8 Character Handling

The original issue this PR addresses (multibyte UTF-8 character corruption) is resolved by using `node:readline`, which correctly handles multibyte characters split across chunk boundaries.

While it's difficult to write integration tests that reliably reproduce the original corruption issue (we cannot control exactly where child process buffers split), I've added unit tests in `packages/generator-helper/src/__tests__/readline-utf8-split.test.ts` that verify `readline.createInterface()` with `crlfDelay: Infinity` correctly handles multibyte UTF-8 characters split across chunks.

File: packages/client/src/runtime/core/engines/binary/BinaryEngine.ts
Comment (aqrln) [inline packages/client/src/runtime/core/engines/binary/BinaryEngine.ts:1]: This file is gone on `main` so this is causing conflicts, please rebase

File: packages/generator-helper/src/__tests__/readline-utf8-split.test.ts [hunk 4]
```diff
@@ -0,0 +1,82 @@
...
+import { Readable } from 'node:stream'
+
+import { describe, expect, test } from 'vitest'
+
+/**
+ * Verify node:readline correctly handles multibyte UTF-8 characters split across chunks.
+ *
+ * The custom byline implementation we replaced had StringDecoder logic for this.
+ * These tests confirm readline.createInterface() handles it correctly.
+ *
```
Comment (aqrln) [inline packages/generator-helper/src/__tests__/readline-utf8-split.test.ts]: This context won't make sense outside the PR
```suggestion
```

File: packages/generator-helper/src/__tests__/readline-utf8-split.test.ts [hunk 5]
```diff
@@ -0,0 +1,82 @@
+import readline from 'node:readline'
+import { Readable } from 'node:stream'
+
+import { describe, expect, test } from 'vitest'
+
+/**
+ * Verify node:readline correctly handles multibyte UTF-8 characters split across chunks.
```
Comment (aqrln) [inline packages/generator-helper/src/__tests__/readline-utf8-split.test.ts:7]: Probably a good idea to include a link to the issue since it's basically a regression test

File: packages/client/src/runtime/core/engines/binary/BinaryEngine.ts
Comment (onozaty) [reply packages/client/src/runtime/core/engines/binary/BinaryEngine.ts:1]: Rebased onto main. The BinaryEngine.ts conflict has been resolved (file was removed in main).

File: packages/generator-helper/src/__tests__/readline-utf8-split.test.ts (hunk 4 above)
Comment (onozaty) [reply packages/generator-helper/src/__tests__/readline-utf8-split.test.ts]: Removed.

File: packages/generator-helper/src/__tests__/readline-utf8-split.test.ts (hunk 5 above)
Comment (onozaty) [reply packages/generator-helper/src/__tests__/readline-utf8-split.test.ts:7]: Added issue reference.

**Review by aqrln — APPROVED** [review]
This is very nice, thank you for working on this and sorry for the delay!
