### PR TITLE
fix(client): negative decimal

### LINKED ISSUE #5508: Negative number cannot be entered as string to Decimal input
## Bug description

I'm trying to create a new record in an SQLite table where one of the fields is of type `Decimal`. If I pass a negative number as `string` to create function, I get the following error from Prisma:

```
Argument initialBalance: Got invalid value '-65.7' on prisma.createOneCashBox. Provided String, expected Decimal.
```

It works if I pass it the same value as `number` or `Decimal`. Positive `string` values also work without any problems.

## How to reproduce

1. Define a table with `Decimal` field.
2. Try to pass a negative `string` value when creating a new record in this table (e.g. `-65.7`).
3. See error in the output.

## Expected behavior

The input type looks like this:

```typescript
export interface CashBoxCreateInput {
  ...
  initialBalance: Decimal | number | string
  ...
}
```

So I would assume Prisma should be able to process any numeric value entered as either `string`, `number` or `Decimal` when creating a new record with `Decimal` field.

## Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["nativeTypes"]
}

datasource db {
  provider = "sqlite"
  url      = "file:../myfile.db"
}

model CashBox {
  id                  Int      @default(autoincrement()) @id
  ...
  initialBalance      Decimal 
  ...
}
```

## Environment & setup

- OS: Manjaro Linux 
- Database: SQLite 
- Node.js version: 15.6.0 
- Prisma version: 2.16.0

### PR DESCRIPTION
**Pull request by timsuchanek**
Closes #5508

### CODE REVIEW

File: src/packages/client/src/runtime/query.ts [hunk 1]
```diff
@@ -1369,7 +1369,7 @@ function hasCorrectScalarType(
   // from https://github.com/MikeMcl/decimal.js/blob/master/decimal.js#L115
   if (
     graphQLType === 'String' &&
-    /^(\d+(\.\d*)?|\.\d+)(e[+-]?\d+)?$/i.test(value) &&
+    /^\-?(\d+(\.\d*)?|\.\d+)(e[+-]?\d+)?$/i.test(value) &&
```
Comment (williamluke4) [inline src/packages/client/src/runtime/query.ts:1372]: Would it not be better to have the regex after `expectedType === 'Decimal'` Thus we can skip the regex test if the expected type is not Decimal

Comment (timsuchanek) [reply src/packages/client/src/runtime/query.ts:1372]: That is very true!!

**Review by williamluke4 — APPROVED** [review]
