### PR TITLE
fix(client): typescript 4.8 

### LINKED ISSUE #15041: Prisma Client is incompatible with TypeScript 4.8
### Bug description

When trying to build prisma-using project with TS 4.8, following errors are thrown:

```

node_modules/.prisma/client/index.d.ts:1144:45 - error TS2344: Type 'S["include"][P]' does not satisfy the constraint 'boolean | UserArgs | null | undefined'.
  Type 'S["include"]["author"]' is not assignable to type 'boolean | UserArgs | null | undefined'.
    Type 'S["include"]["author"]' is not assignable to type 'boolean | UserArgs | null | undefined'.
      Type 'S["include"]["author"]' is not assignable to type 'UserArgs'.
        Type 'S["include"]["author"]' is not assignable to type 'UserArgs'.
          Type 'S["include"][P]' is not assignable to type 'UserArgs'.
            Type 'S["include"]["author"]' is not assignable to type 'UserArgs'.
              Type 'S["include"]["author"]' is not assignable to type 'UserArgs'.

1144         P extends 'author' ? UserGetPayload<S['include'][P]> :  never
                                                 ~~~~~~~~~~~~~~~

node_modules/.prisma/client/index.d.ts:1175:18 - error TS2344: Type 'GlobalRejectSettings' does not satisfy the constraint 'RejectOnNotFound | RejectPerOperation | undefined'.
  Type 'GlobalRejectSettings' is not assignable to type 'RejectPerOperation'.

1175     ): HasReject<GlobalRejectSettings, LocalRejectSettings, 'findUnique', 'Post'> extends True ? CheckSelect<T, Prisma__PostClient<Post>, Prisma__PostClient<PostGetPayload<T>>> : CheckSelect<T, Prisma__PostClient<Post | null >, Prisma__PostClient<PostGetPayload<T> | null >>
                      ~~~~~~~~~~~~~~~~~~~~

  node_modules/.prisma/client/index.d.ts:1161:33
    1161   export interface PostDelegate<GlobalRejectSettings> {
                                         ~~~~~~~~~~~~~~~~~~~~
    This type parameter might need an `extends RejectPerOperation` constraint.
  node_modules/.prisma/client/index.d.ts:1161:33
    1161   export interface PostDelegate<GlobalRejectSettings> {
                                         ~~~~~~~~~~~~~~~~~~~~
    This type parameter might need an `extends RejectOnNotFound | RejectPerOperation | undefined` constraint.

node_modules/.prisma/client/index.d.ts:1192:18 - error TS2344: Type 'GlobalRejectSettings' does not satisfy the constraint 'RejectOnNotFound | RejectPerOperation | undefined'.

1192     ): HasReject<GlobalRejectSettings, LocalRejectSettings, 'findFirst', 'Post'> extends True ? CheckSelect<T, Prisma__PostClient<Post>, Prisma__PostClient<PostGetPayload<T>>> : CheckSelect<T, Prisma__PostClient<Post | null >, Prisma__PostClient<PostGetPayload<T> | null >>
                      ~~~~~~~~~~~~~~~~~~~~

  node_modules/.prisma/client/index.d.ts:1161:33
    1161   export interface PostDelegate<GlobalRejectSettings> {
                                         ~~~~~~~~~~~~~~~~~~~~
    This type parameter might need an `extends RejectOnNotFound | RejectPerOperation | undefined` constraint.

node_modules/.prisma/client/index.d.ts:2119:18 - error TS2344: Type 'GlobalRejectSettings' does not satisfy the constraint 'RejectOnNotFound | RejectPerOperation | undefined'.
  Type 'GlobalRejectSettings' is not assignable to type 'RejectPerOperation'.

2119     ): HasReject<GlobalRejectSettings, LocalRejectSettings, 'findUnique', 'Profile'> extends True ? CheckSelect<T, Prisma__ProfileClient<Profile>, Prisma__ProfileClient<ProfileGetPayload<T>>> : CheckSelect<T, Prisma__ProfileClient<Profile | null >, Prisma__ProfileClient<ProfileGetPayload<T> | null >>
                      ~~~~~~~~~~~~~~~~~~~~

  node_modules/.prisma/client/index.d.ts:2105:36
    2105   export interface ProfileDelegate<GlobalRejectSettings> {
                                            ~~~~~~~~~~~~~~~~~~~~
    This type parameter might need an `extends RejectPerOperation` constraint.
  node_modules/.prisma/client/index.d.ts:2105:36
    2105   export interface ProfileDelegate<GlobalRejectSettings> {
                                            ~~~~~~~~~~~~~~~~~~~~
    This type parameter might need an `extends RejectOnNotFound | RejectPerOperation | undefined` constraint.

node_modules/.prisma/client/index.d.ts:2136:18 - error TS2344: Type 'GlobalRejectSettings' does not satisfy the constraint 'RejectOnNotFound | RejectPerOperation | undefined'.

2136     ): HasReject<GlobalRejectSettings, LocalRejectSettings, 'findFirst', 'Profile'> extends True ? CheckSelect<T, Prisma__ProfileClient<Profile>, Prisma__ProfileClient<ProfileGetPayload<T>>> : CheckSelect<T, Prisma__ProfileClient<Profile | null >, Prisma__ProfileClient<ProfileGetPayload<T> | null >>
                      ~~~~~~~~~~~~~~~~~~~~

  node_modules/.prisma/client/index.d.ts:2105:36
    2105   export interface ProfileDelegate<GlobalRejectSettings> {
                                            ~~~~~~~~~~~~~~~~~~~~
    This type parameter might need an `extends RejectOnNotFound | RejectPerOperation | undefined` constraint.

node_modules/.prisma/client/index.d.ts:3032:52 - error TS2344: Type 'S["include"][P]' does not satisfy the constraint 'boolean | PostArgs | null | undefined'.
  Type 'S["include"]["posts"]' is not assignable to type 'boolean | PostArgs | null | undefined'.
    Type 'S["include"]["posts"]' is not assignable to type 'boolean | PostArgs | null | undefined'.
      Type 'S["include"]["posts"]' is not assignable to type 'PostArgs'.
        Type 'S["include"]["posts"]' is not assignable to type 'PostArgs'.
          Type 'S["include"][P]' is not assignable to type 'PostArgs'.
            Type 'S["include"]["posts"]' is not assignable to type 'PostArgs'.
              Type 'S["include"]["posts"]' is not assignable to type 'PostArgs'.

3032         P extends 'posts' ? Array < PostGetPayload<S['include'][P]>>  :
                                                        ~~~~~~~~~~~~~~~

node_modules/.prisma/client/index.d.ts:3033:49 - error TS2344: Type 'S["include"][P]' does not satisfy the constraint 'boolean | ProfileArgs | null | undefined'.
  Type 'S["include"]["profile"]' is not assignable to type 'boolean | ProfileArgs | null | undefined'.
    Type 'S["include"]["profile"]' is not assignable to type 'boolean | ProfileArgs | null | undefined'.
      Type 'S["include"]["profile"]' is not assignable to type 'ProfileArgs'.
        Type 'S["include"]["profile"]' is not assignable to type 'ProfileArgs'.
          Type 'S["include"][P]' is not assignable to type 'ProfileArgs'.
            Type 'S["include"]["profile"]' is not assignable to type 'ProfileArgs'.
              Type 'S["include"]["profile"]' is not assignable to type 'ProfileArgs'.

3033         P extends 'profile' ? ProfileGetPayload<S['include'][P]> | null :
                                                     ~~~~~~~~~~~~~~~

node_modules/.prisma/client/index.d.ts:3034:60 - error TS2344: Type 'S["include"][P]' does not satisfy the constraint 'boolean | UserCountOutputTypeArgs | null | undefined'.
  Type 'S["include"]["_count"]' is not assignable to type 'boolean | UserCountOutputTypeArgs | null | undefined'.
    Type 'S["include"]["_count"]' is not assignable to type 'boolean | UserCountOutputTypeArgs | null | undefined'.

3034         P extends '_count' ? UserCountOutputTypeGetPayload<S['include'][P]> :  never
                                                     ~~~~~~~~~~~~~~

node_modules/.prisma/client/index.d.ts:3041:60 - error TS2344: Type 'S["select"][P]' does not satisfy the constraint 'boolean | UserCountOutputTypeArgs | null | undefined'.
  Type 'S["select"]["_count"]' is not assignable to type 'boolean | UserCountOutputTypeArgs | null | undefined'.
    Type 'S["select"]["_count"]' is not assignable to type 'boolean | UserCountOutputTypeArgs | null | undefined'.

3041         P extends '_count' ? UserCountOutputTypeGetPayload<S['select'][P]> :  P extends keyof User ? User[P] : never
                                                                ~~~~~~~~~~~~~~

node_modules/.prisma/client/index.d.ts:3067:18 - error TS2344: Type 'GlobalRejectSettings' does not satisfy the constraint 'RejectOnNotFound | RejectPerOperation | undefined'.
  Type 'GlobalRejectSettings' is not assignable to type 'RejectPerOperation'.
```

### How to reproduce

Try running `tsc` on a Prisma project with TypeScript 4.8

### Expected behavior

`tsc` successfully compiles project

### Prisma information

Schema:

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Post {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  title     String   @db.VarChar(255)
  content   String?
  published Boolean  @default(false)
  author    User     @relation(fields: [authorId], references: [id])
  authorId  Int
}

model Profile {
  id     Int     @id @default(autoincrement())
  bio    String?
  user   User    @relation(fields: [userId], references: [id])
  userId Int     @unique
}

model User {
  id      Int      @id @default(autoincrement())
  email   String   @unique
  name    String?
  posts   Post[]
  profile Profile?
}

```

Repository:

```ts
import type { PrismaClient, User } from '@prisma/client'

export type CreateUserRow = Omit<User, 'id'>

export class UserRepository {
  private readonly prisma: PrismaClient

  constructor(prisma: PrismaClient) {
    this.prisma = prisma
  }

  async getUser(id: number): Promise<User | null> {
    const user = await this.prisma.user.findUnique({
      where: {
        id,
      },
    })

    return user
  }

  async createUser(user: CreateUserRow): Promise<User> {
    const createdUser = await this.prisma.user.create({
      data: user,
    })
    return createdUser
  }
}
```

### Environment & setup

TypeScript 4.8.2

### Prisma Version

Prisma 4.2.1

### PR DESCRIPTION
**Pull request by millsp**
Currently, TS 4.8 fails in our ecosystem-tests https://github.com/prisma/ecosystem-tests/pull/3052#issuecomment-1229955024 and in https://github.com/prisma/prisma/issues/15041.

### CODE REVIEW

File: packages/client/src/__tests__/integration/happy/exhaustive-schema/__snapshots__/test.ts.snap [hunk 1]
```diff
@@ -1122,7 +1122,7 @@ export namespace Prisma {
   ? False
   : T extends Date
   ? False
-  : T extends Buffer
+  : T extends Uint8Array
```
Comment (jkomyno) [inline packages/client/src/__tests__/integration/happy/exhaustive-schema/__snapshots__/test.ts.snap:1125]: Does `TS 4.8.0` remove typing support for `Buffer` in favor of `Uint8Array`?

File: packages/client/src/generation/TSClient/Model.ts [hunk 2]
```diff
@@ -570,3 +570,5 @@ ${f.name}<T extends ${getFieldArgName(f, !this.dmmf.typeMap[fieldTypeName])} = {
 }`
   }
 }
+
+type t = Buffer
```
Comment (Jolg42) [inline packages/client/src/generation/TSClient/Model.ts:574]: What does this do?
Looks like it's not needed to me 👀

File: packages/client/src/generation/TSClient/Payload.ts [hunk 3]
```diff
@@ -1,12 +1,18 @@
 import indent from 'indent-string'
+import { freemem } from 'os'
```
Comment (Jolg42) [inline packages/client/src/generation/TSClient/Payload.ts:2]:
```suggestion
```
Looks unused, so better removing it?

File: packages/client/src/generation/TSClient/Payload.ts [hunk 4]
```diff
@@ -38,11 +45,34 @@ export type ${getPayloadName(name)}<
...
+          typeof f.outputType.type === 'object' &&
+          !this.dmmf.typeMap[f.outputType.type.name]
+        )
+      })
+
+      if (nonCompositeRelations.length === 0) {
+        return ''
+      } else {
+        relations = nonCompositeRelations
+      }
```
Comment (Jolg42) [inline packages/client/src/generation/TSClient/Payload.ts:73]: This looks like the main change about Prisma's composite types

Comment (jkomyno) [inline packages/client/src/generation/TSClient/Payload.ts:73]: I'd suggest using `ts-pattern` and its exhaustiveness check for this purpose, but even the following could do:

```suggestion
    const self = this

    const relations: DMMF.SchemaField[] = (() => {
      switch (projection) {
        case Projection.select:
          // For select, a "relation" can be a model or a composite type
          return type.fields.filter((f) => f.outputType.location === 'outputObjectTypes')
  
        case Projection.include:
          // For include, a "relation" can only be a model
          return type.fields.filter((f) => (
              f.outputType.location === 'outputObjectTypes'
              && typeof f.outputType.type === 'object'
              && !self.dmmf.typeMap[f.outputType.type.name]
            )
          )
        default:
          // I'd rather use `ts-pattern`'s `.exhaustive()` compile-time check here
          throw new Error(`Unknown projection ${projection}`)
        }
      })()

    if (relations.length === 0 && projection === Projection.include) {
      return ''
    }
```

In general, I'd advice against having free `let` declarations around, as well as missing `else` statements in enumeration checks

Comment (SevInf) [reply packages/client/src/generation/TSClient/Payload.ts:73]: One more thing you can use to ensure exhaustiveness with if/switch `assertNever` from `@prisma/internals`. [Example in TS playground](https://www.typescriptlang.org/play?#code/LAKApgHgDg9gTgFwAQDMCuA7AxggljDJAQwGcSxEA5MANwoAoi4BzALiQ1ooBokK54AWTBkizMOxII4uDMwCU7TnThIA3qCRIEACwEB3DmEMBROALj1+QkSTFh5oAL6hQAEzBYANkzBIsBFKocGi4COwA5ACCUFBeYBFIAD5IEQDycERyCcmpAApgTBGuICT6YVg6SPQoIWHy6pr+pH7RsfERrE1aAEZwhQDWANxNWC2pGVnind1IfYMjIFoeKERoXuGzpORUXJa1oQi8EQCqGAMYMPqEB2ER8otOQA). Notice compile-time error in default branch.

Comment (jkomyno) [reply packages/client/src/generation/TSClient/Payload.ts:73]: Right, that's a viable alternative in this scenario

File: packages/client/src/__tests__/integration/happy/exhaustive-schema/__snapshots__/test.ts.snap (hunk 1 above)
Comment (millsp) [reply packages/client/src/__tests__/integration/happy/exhaustive-schema/__snapshots__/test.ts.snap:1125]: Buffer is not included in the types (no type reference to node types), so it will be there only if you use node. However, since we are planning to also support Deno, I thought it would be better to check `Uint8Array` in `IsObject` instead.

File: packages/client/src/generation/TSClient/Model.ts (hunk 2 above)
Comment (millsp) [reply packages/client/src/generation/TSClient/Model.ts:574]: Yep, indeed. Thanks!

File: packages/client/src/generation/TSClient/Payload.ts (hunk 4 above)
Comment (millsp) [reply packages/client/src/generation/TSClient/Payload.ts:73]: I ended up with a hybrid between both suggestions.

**Review by danstarns — APPROVED** [review]
Could we also bump the reproductions typescript versions, please? Otherwise looks good to me.

File: packages/client/src/generation/TSClient/Payload.ts [hunk 5]
```diff
@@ -38,11 +45,33 @@ export type ${getPayloadName(name)}<
   }
   private renderRelations(projection: Projection): string {
     const { type } = this
-    // TODO: can be optimized, we're calling the filter two times
-    const relations = type.fields.filter((f) => f.outputType.location === 'outputObjectTypes')
-    if (relations.length === 0 && projection === Projection.include) {
-      return ''
+
+    const relationsProjectionChoice = {
+      // For select, a "relation"" can be a model or a composite
```
Comment (Jolg42) [inline packages/client/src/generation/TSClient/Payload.ts:50]:
```suggestion
      // For select, a "relation" can be a model or a composite
```
nit

File: packages/react-prisma/package.json [hunk 6]
```diff
@@ -14,15 +14,15 @@
...
+    "@types/jest": "28.1.7",
     "@types/node": "16.11.56",
     "esbuild": "0.15.6",
     "jest": "29.0.1",
     "jest-junit": "14.0.1",
     "react": "18.2.0",
-    "typescript": "4.8.2",
-    "@swc/core": "1.2.245",
-    "@swc/jest": "0.2.22"
+    "typescript": "4.8.2"
```
Comment (Jolg42) [inline packages/react-prisma/package.json:25]: This change is unexpected, looks like a merge went wrong

File: packages/instrumentation/package.json [hunk 7]
```diff
@@ -14,14 +14,14 @@
...
-    "typescript": "4.7.4",
     "jest": "28.1.3",
-    "jest-junit": "14.0.1",
-    "@types/jest": "28.1.8"
+    "jest-junit": "14.0.0",
+    "@types/jest": "28.1.7"
   },
   "dependencies": {
-    "@opentelemetry/instrumentation": "^0.32.0",
+    "@opentelemetry/instrumentation": "^0.31.0",
```
Comment (Jolg42) [inline packages/instrumentation/package.json:24]: This change is unexpected, looks like a merge went wrong

File: packages/internals/src/index.ts [hunk 8]
```diff
@@ -59,9 +60,8 @@ export { getEnvPaths } from './utils/getEnvPaths'
 export { version } from './utils/getVersionFromPackageJson'
 export { handlePanic } from './utils/handlePanic'
 export { isCi } from './utils/isCi'
-export { isInteractive } from './utils/isInteractive'
-export { canPrompt } from './utils/canPrompt'
 export { isCurrentBinInstalledGlobally } from './utils/isCurrentBinInstalledGlobally'
+export { isInteractive } from './utils/isInteractive'
```
Comment (Jolg42) [inline packages/internals/src/index.ts:64]: This change is unexpected, looks like a merge went wrong

File: packages/internals/src/utils/canPrompt.ts [hunk 9]
```diff
@@ -1,4 +1,5 @@
 import prompt from 'prompts'
+
```
Comment (Jolg42) [inline packages/internals/src/utils/canPrompt.ts:2]: This change is unexpected, looks like a merge went wrong

Comment (millsp) [reply packages/internals/src/utils/canPrompt.ts:2]: This one is the linting doing this.

File: packages/internals/src/index.ts (hunk 8 above)
Comment (millsp) [reply packages/internals/src/index.ts:64]: Resolved: the linting did this
