### PR TITLE
fix(adapter-pg): historical dates

### LINKED ISSUE #28192: Bug: PgAdapter corrupts historical dates with 2-digit years (00-99 AD)
### Bug description

When using `@prisma/adapter-pg`, historical dates with 2-digit years are incorrectly interpreted, causing data corruption and runtime errors.

**Affected years:**
- Years 31: Throws `RangeError: Invalid time value`
- Years 32-49: Incorrectly converted to 20xx (e.g., 32 AD → 2032 AD)
- Years 50-99: Incorrectly converted to 19xx (e.g., 50 AD → 1950 AD)
- Years 100+: Work correctly

**Important:** This bug only affects PgAdapter. Traditional Prisma connections handle these dates correctly.

**Reproduction:**
Repository with complete Docker setup: [kboshold/bug-reproduction-prisma-date](https://github.com/kboshold/bug-reproduction-prisma-date)

Run with: `docker compose up`

**Test output:**

🔍 Prisma Date Bug Reproduction Test

### Testing with PgAdapter
```


Testing 0031-01-01:
 ❌ CREATE 0031-01-01T00:00:00.000Z => Error: RangeError: Invalid time value
 ❌ UPDATE 0031-01-01T00:00:00.000Z => Error: RangeError: Invalid time value

Testing 0032-01-01:
 ❌ CREATE 0032-01-01T00:00:00.000Z => 2032-01-01T00:00:00.000Z (32 -> 2032)
 ❌ UPDATE 0032-01-01T00:00:00.000Z => 2032-01-01T00:00:00.000Z (32 -> 2032)

Testing 0040-01-01:
 ❌ CREATE 0040-01-01T00:00:00.000Z => 2040-01-01T00:00:00.000Z (40 -> 2040)
 ❌ UPDATE 0040-01-01T00:00:00.000Z => 2040-01-01T00:00:00.000Z (40 -> 2040)

Testing 0050-01-01:
 ❌ CREATE 0050-01-01T00:00:00.000Z => 1950-01-01T00:00:00.000Z (50 -> 1950)
 ❌ UPDATE 0050-01-01T00:00:00.000Z => 1950-01-01T00:00:00.000Z (50 -> 1950)

Testing 0120-01-01:
 ✅ CREATE 0120-01-01T00:00:00.000Z => 0120-01-01T00:00:00.000Z (120 -> 120)
 ✅ UPDATE 0120-01-01T00:00:00.000Z => 0120-01-01T00:00:00.000Z (120 -> 120)
```

###  Testing with Traditional Connection

```
Testing 0031-01-01:
 ✅ CREATE 0031-01-01T00:00:00.000Z => 0031-01-01T00:00:00.000Z (31 -> 31)
 ✅ UPDATE 0031-01-01T00:00:00.000Z => 0031-01-01T00:00:00.000Z (31 -> 31)

Testing 0032-01-01:
 ✅ CREATE 0032-01-01T00:00:00.000Z => 0032-01-01T00:00:00.000Z (32 -> 32)
 ✅ UPDATE 0032-01-01T00:00:00.000Z => 0032-01-01T00:00:00.000Z (32 -> 32)

Testing 0040-01-01:
 ✅ CREATE 0040-01-01T00:00:00.000Z => 0040-01-01T00:00:00.000Z (40 -> 40)
 ✅ UPDATE 0040-01-01T00:00:00.000Z => 0040-01-01T00:00:00.000Z (40 -> 40)

Testing 0050-01-01:
 ✅ CREATE 0050-01-01T00:00:00.000Z => 0050-01-01T00:00:00.000Z (50 -> 50)
 ✅ UPDATE 0050-01-01T00:00:00.000Z => 0050-01-01T00:00:00.000Z (50 -> 50)

Testing 0120-01-01:
 ✅ CREATE 0120-01-01T00:00:00.000Z => 0120-01-01T00:00:00.000Z (120 -> 120)
 ✅ UPDATE 0120-01-01T00:00:00.000Z => 0120-01-01T00:00:00.000Z (120 -> 120)
```

**Environment:**
- Prisma: 6.16.2
- @prisma/adapter-pg: 6.16.2
- Node.js: 24
- PostgreSQL: 17

**Impact:**
This affects applications dealing with historical data, genealogy, archaeology, or legacy system migrations. The silent data corruption is particularly dangerous as it may go unnoticed.

### Severity

🚨 Critical: Data loss, app crash, security issue

### Reproduction

See [kboshold/bug-reproduction-prisma-date](https://github.com/kboshold/bug-reproduction-prisma-date)

### Expected vs. Actual Behavior

Current behaviour: 
```
Testing 0031-01-01:
 ❌ CREATE 0031-01-01T00:00:00.000Z => Error: RangeError: Invalid time value
 ❌ UPDATE 0031-01-01T00:00:00.000Z => Error: RangeError: Invalid time value

Testing 0032-01-01:
 ❌ CREATE 0032-01-01T00:00:00.000Z => 2032-01-01T00:00:00.000Z (32 -> 2032)
 ❌ UPDATE 0032-01-01T00:00:00.000Z => 2032-01-01T00:00:00.000Z (32 -> 2032)

Testing 0040-01-01:
 ❌ CREATE 0040-01-01T00:00:00.000Z => 2040-01-01T00:00:00.000Z (40 -> 2040)
 ❌ UPDATE 0040-01-01T00:00:00.000Z => 2040-01-01T00:00:00.000Z (40 -> 2040)

Testing 0050-01-01:
 ❌ CREATE 0050-01-01T00:00:00.000Z => 1950-01-01T00:00:00.000Z (50 -> 1950)
 ❌ UPDATE 0050-01-01T00:00:00.000Z => 1950-01-01T00:00:00.000Z (50 -> 1950)

Testing 0120-01-01:
 ✅ CREATE 0120-01-01T00:00:00.000Z => 0120-01-01T00:00:00.000Z (120 -> 120)
 ✅ UPDATE 0120-01-01T00:00:00.000Z => 0120-01-01T00:00:00.000Z (120 -> 120)
```

Expected behaviour:
```
Testing 0031-01-01:
✅ CREATE 0031-01-01T00:00:00.000Z => 0031-01-01T00:00:00.000Z (31 -> 31)
✅ UPDATE 0031-01-01T00:00:00.000Z => 0031-01-01T00:00:00.000Z (31 -> 31)

Testing 0032-01-01:
✅ CREATE 0032-01-01T00:00:00.000Z => 0032-01-01T00:00:00.000Z (32 -> 32)
✅ UPDATE 0032-01-01T00:00:00.000Z => 0032-01-01T00:00:00.000Z (32 -> 32)

Testing 0040-01-01:
✅ CREATE 0040-01-01T00:00:00.000Z => 0040-01-01T00:00:00.000Z (40 -> 40)
✅ UPDATE 0040-01-01T00:00:00.000Z => 0040-01-01T00:00:00.000Z (40 -> 40)

Testing 0050-01-01:
✅ CREATE 0050-01-01T00:00:00.000Z => 0050-01-01T00:00:00.000Z (50 -> 50)
✅ UPDATE 0050-01-01T00:00:00.000Z => 0050-01-01T00:00:00.000Z (50 -> 50)

Testing 0120-01-01:
✅ CREATE 0120-01-01T00:00:00.000Z => 0120-01-01T00:00:00.000Z (120 -> 120)
✅ UPDATE 0120-01-01T00:00:00.000Z => 0120-01-01T00:00:00.000Z (120 -> 120)
```

### Frequency

Consistently reproducible

### Does this occur in development or production?

Both development and production

### Is this a regression?

- It does work without PgAdapter.

### Workaround

- Remove PgAdapter.

### Prisma Schema & Queries

See [kboshold/bug-reproduction-prisma-date](https://github.com/kboshold/bug-reproduction-prisma-date)

```prisma
generator client {
  provider   = "prisma-client"
  output     = "./prisma/client"
  engineType = "library"
}

datasource db {
  provider  = "postgres"
  url       = env("DATABASE_URL")
  directUrl = env("DIRECT_DATABASE_URL")
}

model TestData {
  id   String    @id @default(uuid())
  date DateTime?
}
```
```ts
const adapter = new PrismaPg({ connectionString })
const prisma = new PrismaClient({ adapter })

// Throws an error:
const record = await prisma.testData.create({
  data: { date: new Date('0031-01-01T00:00:00.000Z') }
})
```

### Prisma Config

Does not exist.

### Logs & Debug Info

```
// Debug logs here
```

### Environment & Setup

- OS: Docker / Linux
- PostgreSQL: 17|
- Node.js: 24

### Prisma Version

```
- Prisma: 6.16.2
- @prisma/adapter-pg: 6.16.2
```

### PR DESCRIPTION
**Pull request by jkomyno**
This PR:
- closes [TML-1476](https://linear.app/prisma-company/issue/TML-1476/pgadapter-corrupts-historical-dates-with-2-digit-years)
- closes https://github.com/prisma/prisma/issues/28192

### CODE REVIEW

File: packages/adapter-pg/src/conversion.ts [hunk 1]
```diff
@@ -299,11 +298,72 @@ function normalize_date(date: string): string {
  */
 
 function normalize_timestamp(time: string): string {
```
Comment (jacek-prisma) [inline packages/adapter-pg/src/conversion.ts:300]: I think there's a problem with putting the parsing logic in here, since this function is not invoked when `relationJoins = true`,
The only date parsing function we can rely on is `normalizeDateTime` in `packages/client-engine-runtime/src/interpreter/data-mapper.ts` when relationJoins are enabled

Comment (jacek-prisma) [reply packages/adapter-pg/src/conversion.ts:300]: That said, we should still ensure that this function doesn't mess up the date time string, because the output of this affects the input to the data mapper and the output of raw queries

Comment (jacek-prisma) [reply packages/adapter-pg/src/conversion.ts:300]: The reason this needs to do anything at all is that raw query tests depend on this 🤔 I'd be tempted to make all these functions no-ops and move all logic to raw query serialization and the data mapper, but not sure if we can do that easily without breaking the query engine

File: packages/adapter-pg/src/conversion.ts [hunk 2]
```diff
@@ -299,11 +298,72 @@ function normalize_date(date: string): string {
...
+      parseInt(hour, 10),
+      parseInt(minute, 10),
+      parseInt(second, 10),
+      parseInt(ms, 10),
+    ),
+  )
+  date.setUTCFullYear(parseInt(year, 10))
+  date.setUTCMinutes(date.getUTCMinutes() - offsetMinutes)
+
+  return date.toISOString().replace(/(\.000)?Z$/, '+00:00')
```
Comment (jacek-prisma) [inline packages/adapter-pg/src/conversion.ts]: I think things might work if we replace all of this with just `return time.replace(/[+-]\d{2}(:\d{2})?$/`

File: packages/client-engine-runtime/src/interpreter/data-mapper.ts [hunk 3]
```diff
@@ -329,5 +329,55 @@ function normalizeDateTime(dt: string): string {
     return `1970-01-01T${dtWithTz}`
   }
 
+  // Handle 2-digit year interpretation issues for historical dates
+  // JavaScript's Date constructor interprets 2-digit years as 1900-1999
+  // We need to extract the year and handle it explicitly if it's less than 100
+  const yearMatch = dtWithTz.match(/^(\d{1,4})-/)
```
Comment (jacek-prisma) [inline packages/client-engine-runtime/src/interpreter/data-mapper.ts]: at this point we know it's a date, so we could maybe just do `.split("-", 1)` and check the length of the first part
it'd probably be much more efficient than using a regex

File: packages/adapter-pg/src/__tests__/conversion.test.ts [hunk 4]
```diff
@@ -39,3 +43,118 @@ describe('mapArg', () => {
     expect(result).toBe('0099-12-31 23:59:59.999')
   })
 })
+
+describe('customParsers', () => {
+  describe('TIMESTAMP parser (normalize_timestamp)', () => {
```
Comment (jacek-prisma) [inline packages/adapter-pg/src/__tests__/conversion.test.ts]: it'd be much more valuable to have functional client tests rather than these, especially since parsing done in the adapter cannot be relied on

File: packages/client-engine-runtime/src/interpreter/data-mapper.ts [hunk 5]
```diff
@@ -329,5 +329,55 @@ function normalizeDateTime(dt: string): string {
...
+        )
+        date.setUTCFullYear(parseInt(yearStr, 10))
+
+        // Apply timezone offset
+        if (offsetMinutes !== 0) {
+          date.setUTCMinutes(date.getUTCMinutes() - offsetMinutes)
+        }
+
+        return date.toISOString()
+      }
```
Comment (jacek-prisma) [inline packages/client-engine-runtime/src/interpreter/data-mapper.ts]: is the goal of all of this just to pad the year with zeros? if so, why parse the entire string and not just pad the first part with zeroes?

Comment (jkomyno) [reply packages/client-engine-runtime/src/interpreter/data-mapper.ts]: No, this isn't just about "padding the year with zeros". We also need to handle timezone conversion with date arithmetics whenever Postgres returns a date with an offset

Comment (jacek-prisma) [reply packages/client-engine-runtime/src/interpreter/data-mapper.ts]: @jkomyno I think after padding out the year we could just call `new Date`, which should automatically handle the offset?

**Comment by jacek-prisma** [comment]
Added a simplified implementation and tested it manually against QE @jkomyno

File: packages/client-engine-runtime/src/interpreter/data-mapper.ts [hunk 6]
```diff
@@ -219,6 +219,7 @@ function mapValue(
       return { $type: 'Decimal', value }
 
     case 'datetime': {
+      console.log('Mapping datetime value:', { columnName, value, valueType: typeof value })
```
Comment (aqrln) [inline packages/client-engine-runtime/src/interpreter/data-mapper.ts]: stray debug log
```suggestion
```

File: packages/client/tests/functional/issues/28192-pg-historical-dates/test.ts [hunk 7]
```diff
@@ -0,0 +1,39 @@
+import testMatrix from './_matrix'
+// @ts-ignore
+import type { PrismaClient } from './generated/prisma/client'
+
+declare let prisma: PrismaClient
+
+// See: https://github.com/prisma/prisma/issues/28192
+testMatrix.setupTestSuite(
+  () => {
+    describe('[pg] historical dates with 2-digit years (00-99 AD)', () => {
```
Comment (aqrln) [inline packages/client/tests/functional/issues/28192-pg-historical-dates/test.ts]: nit: the full generated test suite name will already contain `postgresql` so adding `[pg]` here seems superfluous

Comment (aqrln) [reply packages/client/tests/functional/issues/28192-pg-historical-dates/test.ts]: also there's `pg` in the file name anyway

File: packages/client-engine-runtime/src/interpreter/data-mapper.ts (hunk 6 above)
Comment (jacek-prisma) [reply packages/client-engine-runtime/src/interpreter/data-mapper.ts]: good catch, removed

File: packages/client/tests/functional/issues/28192-pg-historical-dates/test.ts (hunk 7 above)
Comment (jacek-prisma) [reply packages/client/tests/functional/issues/28192-pg-historical-dates/test.ts]: updated

File: packages/client/tests/functional/issues/28192-pg-historical-dates/test.ts [hunk 8]
```diff
@@ -0,0 +1,39 @@
...
+        { label: '31 AD timestamp', timestampString: '0031-01-01T00:00:00.000Z' },
+        { label: '32 AD timestamp', timestampString: '0032-01-01T00:00:00.000Z' },
+        { label: '40 AD timestamp', timestampString: '0040-01-01T00:00:00.000Z' },
+        { label: '99 AD timestamp', timestampString: '0099-12-31T23:59:59.999Z' },
+        { label: '120 AD timestamp', timestampString: '0120-01-01T00:00:00+00:00' },
+        { label: 'timestamp with milliseconds', timestampString: '0040-06-15 12:30:45.123' },
+        { label: 'modern date timestamp', timestampString: '1999-12-31 23:59:59.999' },
+        { label: '3-digit year timestamp', timestampString: '0999-06-15 12:00:00' },
+        { label: 'timestamptz with milliseconds and timezone', timestampString: '0050-01-15 10:20:30.456+02' },
+      ] satisfies Array<{ label: string; timestampString: string }>
```
Comment (aqrln) [inline packages/client/tests/functional/issues/28192-pg-historical-dates/test.ts:21]: super nitpicky nit: this would be more appropriate as a type annotation (i.e. `const testData: Array<...> =`) and not `satisfies` since it's the exact type that we want to have and not a supertype constraint for type inference

**Review by aqrln — APPROVED** [review]

File: packages/client/tests/functional/issues/28192-pg-historical-dates/test.ts (hunk 8 above)
Comment (jkomyno) [reply packages/client/tests/functional/issues/28192-pg-historical-dates/test.ts:21]: This is very nitpicky :)
