### PR TITLE
fix(adapter-neon,adapter-pg): treat all custom types as text

### LINKED ISSUE #21807: Using `citext` fields with neon database driver causes conversion error
### Bug description

Using the postgres extension `Citext` on a field causes the error:

```
Error converting field "slug" of expected non-nullable type "String", found incompatible value of "someslug".
```

### How to reproduce

1. Use citext postgres extension on any field in a model
2. Fetch data from that model
3. See error:

```
Error converting field "slug" of expected non-nullable type "String", found incompatible value of "someslug".
```

Some debug logs:
```
  prisma:client  Prisma Client call: +670ms
  prisma:client  prisma.someModel.findMany({
  where: {
    slug: {
      equals: "someslug"
    }
  },
  select: {
    id: true,
    slug: true
  }
}) +0ms
  prisma:client  Generated request: +0ms
  prisma:client  {
  "modelName": "SomeModel",
  "action": "findMany",
  "query": {
    "arguments": {
      "where": {
        "slug": {
          "equals": "someslug"
        }
      }
    },
    "selection": {
      "id": true,
      "slug": true
    }
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: false +669ms
  prisma:client:engines:resolveEnginePath  enginePath /Users/markus/prisma/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/.prisma/client/libquery_engine-darwin-arm64.dylib.node +0ms
  prisma:client:libraryEngine  Using driver adapter: %O {
  errorRegistry: oc { registeredErrors: [] },
  queryRaw: [AsyncFunction (anonymous)],
  executeRaw: [AsyncFunction (anonymous)],
  flavour: 'postgres',
  startTransaction: [AsyncFunction: startTransaction],
  close: [AsyncFunction (anonymous)]
} +8ms
  prisma:client:libraryEngine  library starting +17ms
  prisma:client:libraryEngine  library started +2ms
  prisma:driver-adapter:neon [js::query_raw] {
  prisma:driver-adapter:neon   sql: 'SELECT "public"."SomeModel"."id", "public"."SomeModel"."slug" FROM "public"."SomeModel" WHERE "public"."SomeModel"."slug" = $1 OFFSET $2',
  prisma:driver-adapter:neon   args: [ 'someslug', 0 ]
  prisma:driver-adapter:neon } +0ms
  prisma:client:request_handler  PrismaClientKnownRequestError: Error converting field "slug" of expected non-nullable type "String", found incompatible value of "someslug".
    at Zt (/Users/markus/prisma/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:36:253)
    at mr.buildQueryError (/Users/markus/prisma/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:115:1216)
    at mr.request (/Users/markus/prisma/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:114:4091)
    at async Object.singleLoader (/Users/markus/prisma/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:123:5333)
    at async Cn.request (/Users/markus/prisma/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:123:5825)
    at async l (/Users/markus/prisma/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:128:9968)
    at async /Users/markus/prisma/script.ts:13:5 {
  code: 'P2032',
  clientVersion: '5.5.2',
  meta: { field: 'slug', expected_type: 'String', found: 'someslug' }
} +0ms
```

### Expected behavior

Prisma should correctly convert Citext fields to strings

### Prisma information

```prisma
datasource postgresql {
  url               = env("DATABASE_URL")
  shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
  provider          = "postgresql"
  directUrl         = env("DIRECT_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["driverAdapters"]
}

model SomeModel {
  id                                     String                 @id @default(cuid())
  slug                                   String                 @unique @default("") @postgresql.Citext
}
```

```ts
await prisma.someModel.findMany({
      where: {
        slug: {
          equals: 'someslug',
        },
      },
      select: {
        id: true,
        slug: true,
      },
    })
  );
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL v14
- Node.js version: v18

### Prisma Version

```
prisma                  : 5.5.2
@prisma/client          : 5.5.2
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at ../../node_modules/.pnpm/@prisma+engines@5.5.2/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at ../../node_modules/.pnpm/@prisma+engines@5.5.2/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.5.1-1.aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Default Engines Hash    : aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Studio                  : 0.494.0
Preview Features        : driverAdapters
```

### PR DESCRIPTION
**Pull request by aqrln**
Treat all custom Postgres types as text in the result set.

This is an alternative to https://github.com/prisma/prisma/pull/21918.

Thanks to driver adapters using Postgres text protocol, unlike our native driver that uses the binary protocol, we can get away with treating all unknown extension types as text if we want to expose them to users as such — we (or the driver) don't need to know how to decode them and convert to strings if they are already strings in the first place.

However, we cannot distinguish between known types added by extensions and enums without querying the catalog for type names. This may look like a problem at first, but in reality we can get away with treating enums as text in result set too, the response IR layer in the query engine uses the query schema to know it's an enum, not the type hint that comes from `quaint::Value`/`PrismaValue`. If the output type in the query schema says it's an enum, it will treat `PrismaValue::String` and `PrismaValue::Enum` equally: https://github.com/prisma/prisma-engines/blob/12d71c4263690f3990d590fbff611b2a24ef2dbc/query-engine/core/src/response_ir/internal.rs#L813. So mapping Postgres enums to `quaint::ValueType::Text` is fine, and is already supported by QE.

Engines test suite passing: https://github.com/prisma/prisma-engines/pull/4531

Fixes: https://github.com/prisma/prisma/issues/21807
Closes: https://github.com/prisma/prisma/pull/21918

### CODE REVIEW

File: packages/adapter-neon/src/conversion.ts [hunk 1]
```diff
@@ -251,9 +251,9 @@ export function fieldToColumnType(fieldTypeId: number): ColumnType {
     case ArrayColumnType.OID_ARRAY:
       return ColumnTypeEnum.Int64Array
     default:
-      if (fieldTypeId >= 10000) {
+      if (fieldTypeId >= 10_000) {
         // Postgres Custom Types
```
Comment (janpio) [inline packages/adapter-neon/src/conversion.ts:255]: Is this a comment for the `>= 10_000` or for the line below what is returned?

File: packages/client/tests/functional/issues/21807-citext-neon/tests.ts [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+      const writtenRecord = await prisma.model.create({
+        data: {
+          slug: 'someslug',
+        },
+      })
+
+      const readRecords = await prisma.model.findMany({
+        where: {
+          slug: {
+            equals: 'someslug',
```
Comment (Jolg42) [inline packages/client/tests/functional/issues/21807-citext-neon/tests.ts:20]: Could be worth changing the casing here? It should not affect the test but shows that CITEXT is working as expected?

**Review by Jolg42 — APPROVED** [review]

**Comment by mmachatschek** [comment]
@aqrln or @janpio is there a pre release available to test this change?

**Comment by aqrln** [comment]
@mmachatschek yep, every commit to main is published. Just grab the latest `dev` of all packages.
