### PR TITLE
fix(sdk): enable dotenv debug only if prisma or * in cli,client,migrate

### LINKED ISSUE #5562: @prisma/client version 2.16.x spams [dotnev][DEBUG] logs
## Bug description

After upgrading to version 2.16.x `[dotenv][DEBUG]` logs started spamming the console with "did not match key" and "overwrite" warnings

```
[dotenv][DEBUG] did not match key and value when parsing line 32:
[dotenv][DEBUG] did not match key and value when parsing line 37:
[dotenv][DEBUG] did not match key and value when parsing line 40:
[dotenv][DEBUG] did not match key and value when parsing line 43:
[dotenv][DEBUG] did not match key and value when parsing line 47:
[dotenv][DEBUG] "NODE_ENV" is already defined in `process.env` and will not be overwritten
[dotenv][DEBUG] "BUILD_TARGET" is already defined in `process.env` and will not be overwritten
[dotenv][DEBUG] "PORT" is already defined in `process.env` and will not be overwritten
[dotenv][DEBUG] "LOG_LEVEL" is already defined in `process.env` and will not be overwritten
[dotenv][DEBUG] "LOG_DIFFERENCE" is already defined in `process.env` and will not be overwritten
[dotenv][DEBUG] "DEBUG" is already defined in `process.env` and will not be overwritten
...many more
```

## How to reproduce

Upgrade from 2.15.0 to 2.16.x
Have existing `DEBUG` env variable set to unrelated namespace
Logs spam during nexus schema generation and logs spam during server start

```
// .env

DEBUG="app*"
```

## Expected behavior

No logs

## Prisma information

```ts
"prisma": "2.16.1",
"@prisma/client": "2.16.1",
// or
"prisma": "2.16.0",
"@prisma/client": "2.16.0",
```

## Environment & setup

- OS: 
- Database: 
- Node.js version: 
- Prisma version:

```

```

### PR DESCRIPTION
**Pull request by Jolg42**
closes https://github.com/prisma/prisma/issues/5562

### CODE REVIEW

**Review by williamluke4 — APPROVED** [review]

**Review by timsuchanek — APPROVED** [review]

File: src/packages/sdk/src/utils/tryLoadEnvs.ts [hunk 1]
```diff
@@ -127,13 +127,21 @@ export function loadEnv(
   if (exists(envPath)) {
     debug(`Environment variables loaded from ${envPath}`)
 
+    const debugEnv = process.env.DEBUG
+
+    // Value needs to be null or undefined, false is truthy
+    // https://github.com/motdotla/dotenv/blob/7301ac9be0b2c766f865bbe24280bf82586d25aa/lib/main.js#L89-L91
+    let enableDebug: true | undefined = undefined
+
+    if (debugEnv && (debugEnv.includes('prisma') || debugEnv === '*')) {
```
Comment (timsuchanek) [inline src/packages/sdk/src/utils/tryLoadEnvs.ts:136]:
```suggestion
    if (debugEnv && (debugEnv.startsWith('prisma') || debugEnv === '*')) {
```

To not match if people use the word `prisma` somewhere in their debugging

Comment (Jolg42) [reply src/packages/sdk/src/utils/tryLoadEnvs.ts:136]: Yes sounds good!
