### PR TITLE
fix(client): throw values as errors in itx

### LINKED ISSUE #12663: Interactive Transactions: fatal when throwing string instead of Error() since 3.10.0
### Bug description

works in 3.9.2, fatals as of 3.10.0:

```
await prisma.$transaction((prisma) => { throw "abort transaction"; }) // throwing string, not new Error()
```

error since 3.10.0: `TypeError: Cannot create property 'clientVersion' on string "abort transaction"`

### How to reproduce

^- code above, this one seems straightforward but just let me know if reproduction repo required

### Expected behavior

able to throw an expression of type as an error, as accepted by Typescript compiler
(yes I do typically follow best practice re: `Error`s 😉 ; this broke a unit test that was rolling back a transaction where there wasn't need for a full `Error`)

### Prisma information

N/A

### Environment & setup

- OS: Mac OS
- Database: Postgres
- Node.js version: 14

### Prisma Version

worked in versions up to + including `3.9.2`, fails in `3.10.0` and `3.11.1`

### PR DESCRIPTION
**Pull request by millsp**
closes https://github.com/prisma/prisma/issues/12663

### CODE REVIEW

File: packages/client/src/runtime/getPrismaClient.ts [hunk 1]
```diff
@@ -998,7 +998,6 @@ new PrismaClient({
         // it went bad, then we rollback the transaction
         await this._engine.transaction('rollback', headers, info).catch(() => {})
 
-        e.clientVersion = this._clientVersion
```
Comment (aqrln) [inline packages/client/src/runtime/getPrismaClient.ts:1001]: Should we do something like

```ts
if (typeof e === 'object' && e !== null) {
  e.clientVersion = this._clientVersion
}
```

or was it never intended to be set here in the first place?

File: packages/client/tests/functional/interactive-transactions/tests.ts [hunk 2]
```diff
@@ -113,6 +115,27 @@ testMatrix.setupTestSuite(({ provider }) => {
...
+      await prisma.user.create({
+        data: {
+          email: 'user_1@website.com',
+        },
+      })
+
+      throw 'you better rollback now'
+    })
+
+    await expect(result).rejects.toMatchInlineSnapshot(`you better rollback now`)
```
Comment (SevInf) [inline packages/client/tests/functional/interactive-transactions/tests.ts:132]:
```suggestion
    await expect(result).rejects.toBe(`you better rollback now`)
```

So we could be sure we caught a thrown string and not, for example, `Error` object with the same message.

File: packages/client/tests/functional/interactive-transactions/tests.ts [hunk 3]
```diff
@@ -196,19 +219,21 @@ testMatrix.setupTestSuite(({ provider }) => {
...
     })
 
-    1
     await expect(result).rejects.toMatchObject({
       message: expect.stringContaining('Transaction API error: Transaction already closed'),
+      code: 'P2028',
+      clientVersion: '0.0.0',
     })
+
     await expect(result).rejects.toThrowErrorMatchingInlineSnapshot(`
```
Comment (SevInf) [inline packages/client/tests/functional/interactive-transactions/tests.ts:228]:
```suggestion
    await expect(result).rejects.toMatchPrismaErrorInlineSnapshot(`
```

My bad, missed this in my sanitation PR, but it will help with the diff.

File: packages/client/src/runtime/getPrismaClient.ts (hunk 1 above)
Comment (aqrln) [reply packages/client/src/runtime/getPrismaClient.ts:1001]: (Looking at the new tests — apparently never intended to be set here; if the error was meant to have this field, it would have had it already set before re-throwing, if my understanding is correct. Marking the comment as resolved.)

**Review by aqrln — APPROVED** [review]
LGTM pending @SevInf's comments.
