### PR TITLE
fix(client, cli): client auto-install for pnpm

### LINKED ISSUE #5340: `prisma generate` fails when using pnpm workspaces because it tries to install prisma dependencies with npm or yarn
## Bug description

`prisma migrate dev` appears to be running npm to install `@prisma/cli` but it fails since my project is a pnpm project.

## How to reproduce

1. Set up your repo to use pnpm workspaces and `workspace:` protocol in package.json (see https://pnpm.js.org/en/workspaces)
2. Write a schema.
3. Run the initial migration: `pnpx prisma migrate dev --name init --preview-feature`  

I get the following error:
```
myapp (master *) $ pnpx prisma migrate dev --name init --preview-feature
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "dev.db" at "file:./dev.db"

SQLite database dev.db created at file:./dev.db

The following migration(s) have been created and applied from new schema changes:

migrations/
  └─ 20210129014823_init/
    └─ migration.sql

Running generate... (Use --skip-generate to skip the generators)
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:^0.4.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jkim/.npm/_logs/2021-01-29T01_48_26_656Z-debug.log
Error: Command failed with exit code 1: npm install -D @prisma/cli@2.15.0
```

## Expected behavior

No error

## Environment & setup

- OS: MacOS
- Database: SQLite
- Node.js version: v10.22.0
- Prisma version: 2.15.0

### LINKED ISSUE #9848: pnpm: Can not `prisma generate` when `@prisma/client` is not installed in project
### Bug description

image

### How to reproduce

Just add Prisma to pnpm workspace

### Expected behavior

_No response_

### Prisma information

package.json

```json
{
  "name": "adonis",
  "type": "module",
  "license": "MIT",
  "engines": {
    "node": ">=16.0.0"
  },
  "scripts": {
    "clean": "pnpm dlx rimraf \"**/{node_modules,dist,lib,lib-types}\"",
    "build": "bob-esbuild tsc && pnpm prepack -r",
    "test": "pnpm build && pnpm --prefix packages/ai start",
    "lint": "eslint \"./**/*.{ts,tsx}\"",
    "run": "node --experimental-specifier-resolution=node --loader ts-node/esm",
    "prisma": "cross-env NODE_ENV=${NODE_ENV:-development} dotenv-flow -- prisma",
    "migrate:dev": "pnpm prisma migrate dev",
    "migrate:dev:create": "pnpm prisma migrate dev --create-only",
    "migrate:deploy": "pnpm prisma migrate deploy",
    "migrate:reset": "pnpm prisma migrate reset",
    "migrate:resolve": "pnpm prisma migrate resolve",
    "prisma:generate": "pnpm prisma generate",
    "prisma:generate:watch": "pnpm prisma generate --watch",
    "prisma:seed": "pnpm prisma db seed",
    "prisma:studio": "pnpm prisma studio"
  },
  "devDependencies": {
    "@types/node": "^16.11.1",
    "@typescript-eslint/eslint-plugin": "^5.1.0",
    "@typescript-eslint/parser": "^5.1.0",
    "cross-env": "^7.0.3",
    "dotenv-flow-cli": "^1.0.0",
    "esbuild": "^0.13.8",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "prettier": "^2.4.1",
    "prisma": "^3.2.1",
    "ts-node": "^10.3.0",
    "typescript": "^4.5.0-dev.20211018"
  },
  "dependencies": {
    "bob-esbuild": "^2.0.1",
    "bob-esbuild-cli": "^2.0.0"
  }
}

```

### Environment & setup

- OS: MacOS
- Database: PostgreSQL
- Node.js version: 16.11.1

### Prisma Version

```
prisma                  : 3.3.0
@prisma/client          : 3.3.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 33838b0f78f1fe9052cf9a00e9761c9dc097a63c (at node_modules/.pnpm/@prisma+engines@3.3.0-30.33838b0f78f1fe9052cf9a00e9761c9dc097a63c/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 33838b0f78f1fe9052cf9a00e9761c9dc097a63c (at node_modules/.pnpm/@prisma+engines@3.3.0-30.33838b0f78f1fe9052cf9a00e9761c9dc097a63c/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 33838b0f78f1fe9052cf9a00e9761c9dc097a63c (at node_modules/.pnpm/@prisma+engines@3.3.0-30.33838b0f78f1fe9052cf9a00e9761c9dc097a63c/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 33838b0f78f1fe9052cf9a00e9761c9dc097a63c (at node_modules/.pnpm/@prisma+engines@3.3.0-30.33838b0f78f1fe9052cf9a00e9761c9dc097a63c/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 33838b0f78f1fe9052cf9a00e9761c9dc097a63c
Studio                  : 0.437.0
```

### LINKED ISSUE #11791: Docker with `pnpm install` hangs on `@prisma/client` postinstall
### Bug description

See https://github.com/pnpm/pnpm/discussions/4329 and below

### How to reproduce

Create an empty directory with a `Dockerfile`
```
FROM node:16

WORKDIR /usr/src/app

RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

RUN pnpm init -y

RUN --mount=type=cache,id=pnpm-store,target=/root/.pnpm-store\
    pnpm add @prisma/client

CMD ["echo", "end"]
```

Run `docker build . --progress=plain --no-cache`

### Expected behavior

It should produce a Docker build.

### Environment & setup

pnpm 6.30.1

### LINKED ISSUE #14401: Automatic installation of missing dependencies isn't compatible with pnpm
### Bug description

PNPM: https://pnpm.io

When I follow the getting started guide but use PNPM instead of NPM, `pnpx` fails at the migrate step:

```
$ pnpx prisma migrate dev --name init
```

### How to reproduce

1. Follow the steps here, but using PNPM instead of NPM: https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/relational-databases-typescript-postgres
2. The `migrate` step fails:

```
PS C:\Users\Behrang\Documents\Projects\github.com\behrangsa\xyz-doodles\doodle-5> pnpx prisma migrate dev --name init
.../Local/pnpm/store/v3/tmp/dlx-24148    |   +2 +
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: C:\Users\Behrang\AppData\Local\pnpm\store\v3
  Virtual store is at:             ../../../../../../AppData/Local/pnpm/store/v3/tmp/dlx-24148/node_modules/.pnpm
.../Local/pnpm/store/v3/tmp/dlx-24148    | Progress: resolved 2, reused 2, downloaded 0, added 2, done
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": PostgreSQL database "mydb", schema "public" at "localhost:49154"

PostgreSQL database mydb created at localhost:49154

Applying migration `20220720081027_init`

The following migration(s) have been created and applied from new schema changes:

migrations/
  └─ 20220720081027_init/
    └─ migration.sql

Your database is now in sync with your schema.

Running generate... (Use --skip-generate to skip the generators)
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm ERR! Cannot read properties of null (reading 'isDescendantOf')

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Behrang\scoop\persist\nodejs\cache\_logs\2022-07-20T08_10_30_080Z-debug-0.log
Error: Command failed with exit code 1: npm install @prisma/client@4.1.0
 ERROR  Command failed with exit code 1: C:\Users\Behrang\AppData\Local\pnpm\store\v3\tmp\dlx-24148\node_modules\.bin\prisma.CMD migrate dev --name init
```

[2022-07-20T08_10_30_080Z-debug-0.log](https://github.com/prisma/prisma/files/9147914/2022-07-20T08_10_30_080Z-debug-0.log)

### Expected behavior

Prisma to work with PNPM.

### Prisma information

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Post {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  title     String   @db.VarChar(255)
  content   String?
  published Boolean  @default(false)
  author    User     @relation(fields: [authorId], references: [id])
  authorId  Int
}

model Profile {
  id     Int     @id @default(autoincrement())
  bio    String?
  user   User    @relation(fields: [userId], references: [id])
  userId Int     @unique
}

model User {
  id      Int      @id @default(autoincrement())
  email   String   @unique
  name    String?
  posts   Post[]
  profile Profile?
}
```

### Environment & setup

- OS: Windows 11
- Database: PostgreSQL
- Node.js version: v18.4.0

### Prisma Version

```
.../Local/pnpm/store/v3/tmp/dlx-33356    |   +2 +
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: C:\Users\Behrang\AppData\Local\pnpm\store\v3
  Virtual store is at:             ../../../../../../AppData/Local/pnpm/store/v3/tmp/dlx-33356/node_modules/.pnpm
.../Local/pnpm/store/v3/tmp/dlx-33356    | Progress: resolved 2, reused 2, downloaded 0, added 2, done
Environment variables loaded from .env
prisma                  : 4.1.0
@prisma/client          : Not found
Current platform        : windows
Query Engine (Node-API) : libquery-engine 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at ..\..\..\..\..\..\AppData\Local\pnpm\store\v3\tmp\dlx-33356\node_modules\.pnpm\@prisma+engines@4.1.0\node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at ..\..\..\..\..\..\AppData\Local\pnpm\store\v3\tmp\dlx-33356\node_modules\.pnpm\@prisma+engines@4.1.0\node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at ..\..\..\..\..\..\AppData\Local\pnpm\store\v3\tmp\dlx-33356\node_modules\.pnpm\@prisma+engines@4.1.0\node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at ..\..\..\..\..\..\AppData\Local\pnpm\store\v3\tmp\dlx-33356\node_modules\.pnpm\@prisma+engines@4.1.0\node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 8d8414deb360336e4698a65aa45a1fbaf1ce13d8
Studio                  : 0.467.0
```

### LINKED ISSUE #14816: Prisma generate throws dependency error karma-chai
### Bug description

prisma generate throws a dep resolution error when you are using PNPM

My setup: Docker container 

Docker image base: FROM node:18
Host: MacBook Pro 2021 M1 Pro  

Running command from inside the container. 

Here is what I tried:

- Install as dev dep 
- Install as normal dep
- Use pnpx 
- Use npx 

```bash
root@64a9e9c2102a:/app# pnpx prisma generate 
.pnpm-store/v3/tmp/dlx-1446              |   +2 +
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /app/.pnpm-store/v3
  Virtual store is at:             .pnpm-store/v3/tmp/dlx-1446/node_modules/.pnpm
.pnpm-store/v3/tmp/dlx-1446              | Progress: resolved 2, reused 2, downloaded 0, added 2, done
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @eslint/eslintrc@1.3.0
npm WARN Found: peer eslint-plugin-jsdoc@">=22.1.0" from eslint-config-eslint@7.0.0
npm WARN node_modules/.pnpm/@eslint+eslintrc@1.3.0/node_modules/@eslint/eslintrc/node_modules/eslint-config-eslint
npm WARN   dev eslint-config-eslint@"^7.0.0" from @eslint/eslintrc@1.3.0
npm WARN   node_modules/.pnpm/@eslint+eslintrc@1.3.0/node_modules/@eslint/eslintrc
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer eslint-plugin-jsdoc@">=22.1.0" from eslint-config-eslint@7.0.0
npm WARN node_modules/.pnpm/@eslint+eslintrc@1.3.0/node_modules/@eslint/eslintrc/node_modules/eslint-config-eslint
npm WARN   dev eslint-config-eslint@"^7.0.0" from @eslint/eslintrc@1.3.0
npm WARN   node_modules/.pnpm/@eslint+eslintrc@1.3.0/node_modules/@eslint/eslintrc
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: accepts@1.3.8
npm WARN Found: peer eslint-plugin-import@">=2.18.0" from eslint-config-standard@14.1.1
npm WARN node_modules/.pnpm/accepts@1.3.8/node_modules/accepts/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"14.1.1" from accepts@1.3.8
npm WARN   node_modules/.pnpm/accepts@1.3.8/node_modules/accepts
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer eslint-plugin-import@">=2.18.0" from eslint-config-standard@14.1.1
npm WARN node_modules/.pnpm/accepts@1.3.8/node_modules/accepts/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"14.1.1" from accepts@1.3.8
npm WARN   node_modules/.pnpm/accepts@1.3.8/node_modules/accepts
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: accepts@1.3.8
npm WARN Found: peer eslint-plugin-standard@">=4.0.0" from eslint-config-standard@14.1.1
npm WARN node_modules/.pnpm/accepts@1.3.8/node_modules/accepts/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"14.1.1" from accepts@1.3.8
npm WARN   node_modules/.pnpm/accepts@1.3.8/node_modules/accepts
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer eslint-plugin-standard@">=4.0.0" from eslint-config-standard@14.1.1
npm WARN node_modules/.pnpm/accepts@1.3.8/node_modules/accepts/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"14.1.1" from accepts@1.3.8
npm WARN   node_modules/.pnpm/accepts@1.3.8/node_modules/accepts
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: async-retry@1.3.3
npm WARN Found: peer eslint-plugin-import@"^2.22.1" from eslint-config-airbnb@18.2.1
npm WARN node_modules/.pnpm/async-retry@1.3.3/node_modules/async-retry/node_modules/eslint-config-airbnb
npm WARN   dev eslint-config-airbnb@"18.2.1" from async-retry@1.3.3
npm WARN   node_modules/.pnpm/async-retry@1.3.3/node_modules/async-retry
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer eslint-plugin-import@"^2.22.1" from eslint-config-airbnb@18.2.1
npm WARN node_modules/.pnpm/async-retry@1.3.3/node_modules/async-retry/node_modules/eslint-config-airbnb
npm WARN   dev eslint-config-airbnb@"18.2.1" from async-retry@1.3.3
npm WARN   node_modules/.pnpm/async-retry@1.3.3/node_modules/async-retry
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: async-retry@1.3.3
npm WARN Found: peer eslint-plugin-jsx-a11y@"^6.4.1" from eslint-config-airbnb@18.2.1
npm WARN node_modules/.pnpm/async-retry@1.3.3/node_modules/async-retry/node_modules/eslint-config-airbnb
npm WARN   dev eslint-config-airbnb@"18.2.1" from async-retry@1.3.3
npm WARN   node_modules/.pnpm/async-retry@1.3.3/node_modules/async-retry
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer eslint-plugin-jsx-a11y@"^6.4.1" from eslint-config-airbnb@18.2.1
npm WARN node_modules/.pnpm/async-retry@1.3.3/node_modules/async-retry/node_modules/eslint-config-airbnb
npm WARN   dev eslint-config-airbnb@"18.2.1" from async-retry@1.3.3
npm WARN   node_modules/.pnpm/async-retry@1.3.3/node_modules/async-retry
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: async-retry@1.3.3
npm WARN Found: peer eslint-plugin-react@"^7.21.5" from eslint-config-airbnb@18.2.1
npm WARN node_modules/.pnpm/async-retry@1.3.3/node_modules/async-retry/node_modules/eslint-config-airbnb
npm WARN   dev eslint-config-airbnb@"18.2.1" from async-retry@1.3.3
npm WARN   node_modules/.pnpm/async-retry@1.3.3/node_modules/async-retry
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer eslint-plugin-react@"^7.21.5" from eslint-config-airbnb@18.2.1
npm WARN node_modules/.pnpm/async-retry@1.3.3/node_modules/async-retry/node_modules/eslint-config-airbnb
npm WARN   dev eslint-config-airbnb@"18.2.1" from async-retry@1.3.3
npm WARN   node_modules/.pnpm/async-retry@1.3.3/node_modules/async-retry
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: body-parser@1.20.0
npm WARN Found: peer eslint-plugin-import@">=2.18.0" from eslint-config-standard@14.1.1
npm WARN node_modules/.pnpm/body-parser@1.20.0/node_modules/body-parser/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"14.1.1" from body-parser@1.20.0
npm WARN   node_modules/.pnpm/body-parser@1.20.0/node_modules/body-parser
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer eslint-plugin-import@">=2.18.0" from eslint-config-standard@14.1.1
npm WARN node_modules/.pnpm/body-parser@1.20.0/node_modules/body-parser/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"14.1.1" from body-parser@1.20.0
npm WARN   node_modules/.pnpm/body-parser@1.20.0/node_modules/body-parser
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: body-parser@1.20.0
npm WARN Found: peer eslint-plugin-standard@">=4.0.0" from eslint-config-standard@14.1.1
npm WARN node_modules/.pnpm/body-parser@1.20.0/node_modules/body-parser/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"14.1.1" from body-parser@1.20.0
npm WARN   node_modules/.pnpm/body-parser@1.20.0/node_modules/body-parser
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer eslint-plugin-standard@">=4.0.0" from eslint-config-standard@14.1.1
npm WARN node_modules/.pnpm/body-parser@1.20.0/node_modules/body-parser/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"14.1.1" from body-parser@1.20.0
npm WARN   node_modules/.pnpm/body-parser@1.20.0/node_modules/body-parser
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: content-disposition@0.5.4
npm WARN Found: peer eslint-plugin-import@">=2.18.0" from eslint-config-standard@13.0.1
npm WARN node_modules/.pnpm/content-disposition@0.5.4/node_modules/content-disposition/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"13.0.1" from content-disposition@0.5.4
npm WARN   node_modules/.pnpm/content-disposition@0.5.4/node_modules/content-disposition
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer eslint-plugin-import@">=2.18.0" from eslint-config-standard@13.0.1
npm WARN node_modules/.pnpm/content-disposition@0.5.4/node_modules/content-disposition/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"13.0.1" from content-disposition@0.5.4
npm WARN   node_modules/.pnpm/content-disposition@0.5.4/node_modules/content-disposition
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: content-disposition@0.5.4
npm WARN Found: peer eslint-plugin-standard@">=4.0.0" from eslint-config-standard@13.0.1
npm WARN node_modules/.pnpm/content-disposition@0.5.4/node_modules/content-disposition/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"13.0.1" from content-disposition@0.5.4
npm WARN   node_modules/.pnpm/content-disposition@0.5.4/node_modules/content-disposition
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer eslint-plugin-standard@">=4.0.0" from eslint-config-standard@13.0.1
npm WARN node_modules/.pnpm/content-disposition@0.5.4/node_modules/content-disposition/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"13.0.1" from content-disposition@0.5.4
npm WARN   node_modules/.pnpm/content-disposition@0.5.4/node_modules/content-disposition
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: debug@2.6.9
npm ERR! Found: dev karma-chai@"^0.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev karma-chai@"^0.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-08-15T16_05_23_187Z-debug-0.log
Error: Command failed with exit code 1: npm install @prisma/client@4.2.1
```

### How to reproduce

1. Init prisma
2. Setup DB connection
3. Run npx prisma generate

### Expected behavior

_No response_

### Prisma information

NA

### Environment & setup

- OS: macOS 12.4
- Database: PostgreSQL
- Node.js version: v18.7.0

### Prisma Version

```bash
root@64a9e9c2102a:/app# npx prisma -v
Environment variables loaded from .env
prisma                  : 4.2.1
@prisma/client          : Not found
Current platform        : linux-arm64-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/.pnpm/@prisma+engines@4.2.1/node_modules/@prisma/engines/libquery_engine-linux-arm64-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/.pnpm/@prisma+engines@4.2.1/node_modules/@prisma/engines/migration-engine-linux-arm64-openssl-1.1.x)
Introspection Engine    : introspection-core 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/.pnpm/@prisma+engines@4.2.1/node_modules/@prisma/engines/introspection-engine-linux-arm64-openssl-1.1.x)
Format Binary           : prisma-fmt 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/.pnpm/@prisma+engines@4.2.1/node_modules/@prisma/engines/prisma-fmt-linux-arm64-openssl-1.1.x)
Default Engines Hash    : 2920a97877e12e055c1333079b8d19cee7f33826
Studio                  : 0.469.0
```

### LINKED ISSUE #14944: Postinstall script fails with PNPM workspaces due to npm ERR! Cannot read properties of null (reading 'matches')
### Bug description

When running `pnpm install` in a monorepo, with this structure
```
packages
    server
         prisma
               schema.prisma
    shared-utils
         package.json
    web
         package.json
pnpm-workspace.yaml
package.json
```

I get this error:
```
#0 2.239
#0 2.239 > @hub/shared-utils@1.0.0 generate /app/packages/shared-utils
#0 2.239 > pnpm prisma generate
#0 2.239
#0 36.80 Prisma schema loaded from ../server/prisma/schema.prisma
#0 451.1 npm ERR! Cannot read properties of null (reading 'matches')
#0 451.2
#0 451.2 npm ERR! A complete log of this run can be found in:
#0 451.2 npm ERR!     /root/.npm/_logs/2022-08-23T02_34_57_814Z-debug-0.log
#0 451.2 Error: Command failed with exit code 1: npm install -D prisma@3.15.2
#0 451.3 undefined
#0 451.3 /app/packages/shared-utils:
#0 451.3  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @hub/shared-utils@1.0.0 generate: `pnpm prisma generate`
#0 451.3 Exit status 1
```

my package `shared-utils` installs `prisma`, `web` depends on `shared-utils`

`shared-utils` has a custom `postinstall` script, which generates Prisma client from custom location(from `server` package).
This is `package.json` of `shared-utils`
```
{
  "name": "@example/shared-utils",
  "version": "1.0.0",
  "main": "dist/src/index.js",
  "types": "dist/src/index.d.ts",
  "private": true,
  "license": "MIT",
  "scripts": {
    "build": "rm -rf dist && tsc --build",
    "test": "jest",
    "precommit": "eslint --ext .ts \"*/**/*\" --fix && prettier --write .",
    "postinstall": "pnpm prisma generate"
  },
  "dependencies": {
    "currency.js": "^2.0.4",
    "@prisma/client": "3.15.2",
    "date-fns": "^2.28.0"
  },
  "devDependencies": {
    "@example/eslint-config": "1.0.0",
    "@example/prettier-config": "1.0.0",
    "prisma": "3.15.2"
  },
  "prisma": {
    "schema": "../server/prisma/schema.prisma"
  },
  "prettier": "@example/prettier-config",
  "jest": {
    "preset": "ts-jest",
    "roots": [
      "src"
    ],
    "modulePaths": [
      "src"
    ],
    "moduleDirectories": [
      "node_modules"
    ]
  }
}

```

### How to reproduce

1. Go to project root.
2. Run `pnpm install`
3. See error

### Expected behavior

`pnpm install` installs packages, and Prisma schema is generated automatically

### Environment & setup

- OS: Mac OS,
- Database: PostgreSQL
- Node.js version: 16.13.1

### Prisma Version

```
3.15.2
```

### LINKED ISSUE #18238: Using Prisma with pnpm results in inability to call database related commands
### Bug description

I am using pnpm with Prisma in my app, but whenever I try running `prisma migrate dev` or `prisma generate`, the program hangs for about 10 minutes before returning an error.

```
Running generate... (Use --skip-generate to skip the generators)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @eslint/eslintrc@2.0.0
npm WARN Found: peer eslint-plugin-jsdoc@">=22.1.0" from eslint-config-eslint@7.0.0
npm WARN node_modules/.pnpm/@eslint+eslintrc@2.0.0/node_modules/@eslint/eslintrc/node_modules/eslint-config-eslint
npm WARN   dev eslint-config-eslint@"^7.0.0" from @eslint/eslintrc@2.0.0
npm WARN   node_modules/.pnpm/@eslint+eslintrc@2.0.0/node_modules/@eslint/eslintrc
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer eslint-plugin-jsdoc@">=22.1.0" from eslint-config-eslint@7.0.0
npm WARN node_modules/.pnpm/@eslint+eslintrc@2.0.0/node_modules/@eslint/eslintrc/node_modules/eslint-config-eslint
npm WARN   dev eslint-config-eslint@"^7.0.0" from @eslint/eslintrc@2.0.0
npm WARN   node_modules/.pnpm/@eslint+eslintrc@2.0.0/node_modules/@eslint/eslintrc
npm ERR! Cannot read properties of null (reading 'matches')

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-03-06T21_07_48_240Z-debug-0.log
Error: Command failed with exit code 1: npm install @prisma/client@4.11.0
```

### How to reproduce

1. Install Prisma using pnpm
2. Write some models in the Prisma schema
3. Run `pnpm prisma migrate dev` or `pnpm prisma generate`

### Expected behavior

I expected Prisma to play nicely with the pnpm format, but it didn't. It seems like the problem might be a mismatch between the usage of `pnpm` and `npm` when installing `@prisma/client`, because even on my pnpm project, it still says that `npm install @prisma/client` was used. 

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model User {
  id Int @id @default(autoincrement())
  username String @unique
  password String
  
}
```

### Environment & setup

- OS: WSL
- Database: SQLite
- Node.js version: 18.12.1

### Prisma Version

```
4.11.0
```

### PR DESCRIPTION
**Pull request by millsp**
Fixes https://github.com/prisma/prisma/issues/5340
Fixes https://github.com/prisma/prisma/issues/9848
Fixes https://github.com/prisma/prisma/issues/14944
Fixes https://github.com/prisma/prisma/issues/11791
Fixes https://github.com/prisma/prisma/issues/14401
Fixes https://github.com/prisma/prisma/issues/14816
Fixes https://github.com/prisma/prisma/issues/18238
...likely to close yarn issues, but more tests are needed

Do not spend too much time on reviewing `@prisma/ni`, this package is temporary and is a port of my PR https://github.com/antfu/ni/pull/151 until it gets merged. You can review that PR too, if you find it useful.

For the reviewer, please also review https://github.com/prisma/ecosystem-tests/pull/3469

### CODE REVIEW

File: packages/internals/src/get-generators/generatorResolvers/prisma-client-js/check-dependencies/checkTypeScriptVersion.ts [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+import { logger } from '../../../..'
+import { resolvePkg } from './resolve'
+import { semverLt } from './semverLt'
+
+const debug = Debug('prisma:generator')
+
+// TODO: This is not well tested
+
+/**
+ * Warn, if typescript is below `4.1.0` and is install locally Because Template
```
Comment (janpio) [inline packages/internals/src/get-generators/generatorResolvers/prisma-client-js/check-dependencies/checkTypeScriptVersion.ts:15]:
```suggestion
 * Warn, if typescript is below `4.1.0` and is installed locally Because Template
```

File: packages/internals/src/get-generators/generatorResolvers/prisma-client-js/check-dependencies/checkYarnVersion.ts [hunk 2]
```diff
@@ -0,0 +1,47 @@
+import chalk from 'chalk'
+
+import { logger } from '../../../..'
+import { semverLt } from './semverLt'
+
+// TODO: Is this well tested?
+
+/**
+ * Warn, if yarn is older than 1.19.2 Because Yarn used to remove all dot
```
Comment (janpio) [inline packages/internals/src/get-generators/generatorResolvers/prisma-client-js/check-dependencies/checkYarnVersion.ts:9]:
```suggestion
 * Warn, if yarn is older than 1.19.2 because Yarn used to remove all dot
```

File: packages/internals/src/get-generators/generatorResolvers/prisma-client-js/check-dependencies/resolve.ts [hunk 3]
```diff
@@ -1,6 +1,14 @@
 import path from 'path'
 import { default as _resolve } from 'resolve'
 
+/**
+ * Alternative to resolve that returns undefined instead of throwing. It also
+ * enables preserving symlinks, which is not possible with the original resolve.
```
Comment (janpio) [inline packages/internals/src/get-generators/generatorResolvers/prisma-client-js/check-dependencies/resolve.ts:6]:
```suggestion
 * Alternative to 'resolve' that returns undefined instead of throwing. It also
 * enables preserving symlinks, which is not possible with the original 'resolve'.
```

File: packages/internals/src/get-generators/generatorResolvers/prisma-client-js/check-dependencies/resolve.ts [hunk 4]
```diff
@@ -1,6 +1,14 @@
...
+ * This variant will find the entrypoint of a package.
```
Comment (janpio) [inline packages/internals/src/get-generators/generatorResolvers/prisma-client-js/check-dependencies/resolve.ts:7]:
```suggestion
 * This variant will find the _entrypoint_ of a package.
```

File: packages/internals/src/get-generators/generatorResolvers/prisma-client-js/check-dependencies/resolve.ts [hunk 5]
```diff
@@ -13,6 +21,14 @@ async function resolve(id: string, options: _resolve.AsyncOpts) {
   }) as Promise<string | undefined>
 }
 
+/**
+ * Alternative to resolve that returns undefined instead of throwing. It also
+ * enables preserving symlinks, which is not possible with the original resolve.
+ * This variant will find the root of a package.
```
Comment (janpio) [inline packages/internals/src/get-generators/generatorResolvers/prisma-client-js/check-dependencies/resolve.ts:27]:
```suggestion
 * Alternative to 'resolve' that returns undefined instead of throwing. It also
 * enables preserving symlinks, which is not possible with the original 'resolve'.
 * This variant will find the _root_ of a package.
```

File: packages/internals/src/get-generators/generatorResolvers/prisma-client-js/prismaClientResolver.ts [hunk 6]
```diff
@@ -0,0 +1,114 @@
...
+import { runPackageCmd } from './auto-installation/runPackageCmd'
+import { checkTypeScriptVersion } from './check-dependencies/checkTypeScriptVersion'
+import { checkYarnVersion } from './check-dependencies/checkYarnVersion'
+import { isYarnUsed } from './check-dependencies/isYarnUsed'
+import { resolvePkg } from './check-dependencies/resolve'
+
+export const debug = Debug('prisma:generator')
+
+/**
+ * Client generator resolver. The generator is shipped with the Client, so f the
```
Comment (janpio) [inline packages/internals/src/get-generators/generatorResolvers/prisma-client-js/prismaClientResolver.ts:17]:
```suggestion
 * Client generator resolver. The generator is shipped with the Client, so if the
```

File: packages/internals/src/get-generators/generatorResolvers/prisma-client-js/prismaClientResolver.ts [hunk 7]
```diff
@@ -0,0 +1,114 @@
...
+    const prismaCliDir = await resolvePkg('prisma', { basedir: baseDir })
+
+    // Automatically installing the packages with Yarn on Windows won't work because
+    // Yarn will try to unlink the Query Engine DLL, which is currently being used.
+    // See https://github.com/prisma/prisma/issues/9184
+    if (process.platform === 'win32' && isYarnUsed(baseDir)) {
+      const hasCli = (s: string) => (prismaCliDir !== undefined ? s : '')
+      const missingCli = (s: string) => (prismaCliDir === undefined ? s : '')
+
+      throw new Error(
```
Comment (janpio) [inline packages/internals/src/get-generators/generatorResolvers/prisma-client-js/prismaClientResolver.ts:64]:
```suggestion
      // Error message automatically includes CLI as well if it is missing
      throw new Error(
```

**Comment by millsp** [comment]
@SocketSecurity ignore

File: helpers/compile/build.ts [hunk 8]
```diff
@@ -124,7 +124,7 @@ async function dependencyCheck(options: BuildOptions) {
   const buildPromise = esbuild.build({
     entryPoints: glob.sync('**/*.{j,t}s', {
       // We don't check dependencies in ecosystem tests because tests are isolated from the build.
-      ignore: ['./src/__tests__/**/*', './tests/e2e/**/*'],
+      ignore: ['./src/__tests__/**/*', './tests/e2e/**/*', './dist/**/*'],
```
Comment (millsp) [inline helpers/compile/build.ts:127]: Unrelated changes, prevents false positives by no checking dependencies in compiled code.

**Comment by millsp** [comment]
@SocketSecurity ignore esbuild@0.17.16
@SocketSecurity ignore esbuild@0.17.5

File: helpers/compile/plugins/fill-plugin/fillers/fs.ts [hunk 9]
```diff
@@ -2,13 +2,14 @@ export function existsSync() {
   return false
 }
 
+export const promises = {}
```
Comment (millsp) [inline helpers/compile/plugins/fill-plugin/fillers/fs.ts:5]: Needed for esbuild although code requiring this gets tree-shaken. Not an issue, but strange.

File: packages/client/tests/functional/jest.config.js [hunk 10]
```diff
@@ -14,7 +14,7 @@ module.exports = () => {
     // That includes all generated clients as well. So, unless we ignore them, they'd be kept in memory until test process
     // is finished, even though they are needed for 1 test only
     transformIgnorePatterns: [
-      '[\\/]node_modules[\\/]',
+      '.*[\\.]generated[\\/]@prisma[\\/]client[\\/].*',
```
Comment (millsp) [inline packages/client/tests/functional/jest.config.js:17]: This allows to transpile everything but the prisma clients.

File: packages/internals/src/get-generators/generatorResolvers/generatorResolvers.ts
Comment (millsp) [inline packages/internals/src/get-generators/generatorResolvers/generatorResolvers.ts:1]: Things weren't changed, this is mostly a cleanup.

File: packages/internals/src/get-generators/generatorResolvers/prisma-client-js/check-dependencies/semverLt.ts [hunk 11]
```diff
@@ -0,0 +1,36 @@
+/**
+ * Returns true, if semver version `a` is lower than `b`
+ * Note: This obviously doesn't support the full semver spec.
+ * @param {string} a
+ * @param {string} b
+ */
+export function semverLt(a, b) {
+  const [major1, minor1, patch1] = a.split('.')
+  const [major2, minor2, patch2] = b.split('.')
```
Comment (SevInf) [inline packages/internals/src/get-generators/generatorResolvers/prisma-client-js/check-dependencies/semverLt.ts:9]:
```suggestion
  const [major1, minor1, patch1] = a.split('.').map(Number)
  const [major2, minor2, patch2] = b.split('.').map(Number)
```

Otherwise, `'2' > '10'`

File: packages/internals/src/get-generators/generatorResolvers/prisma-client-js/prismaClientResolver.ts [hunk 12]
```diff
@@ -0,0 +1,115 @@
...
+  await checkTypeScriptVersion()
+
+  if (!prismaClientDir && !process.env.PRISMA_GENERATE_SKIP_AUTOINSTALL) {
+    // TODO: should this be relative to `baseDir` rather than `process.cwd()`?
+    if (
+      !fs.existsSync(path.join(process.cwd(), 'package.json')) &&
+      !fs.existsSync(path.join(process.cwd(), '../package.json'))
+    ) {
+      // Create default package.json
+      const defaultPackageJson = `{
```
Comment (SevInf) [inline packages/internals/src/get-generators/generatorResolvers/prisma-client-js/prismaClientResolver.ts:39]: Do you know why are we creating `package.json` outselves in this case?

**Review by SevInf — APPROVED** [review]
Left a question and pointed out one potential problem, otherwise LGTM

File: packages/internals/src/get-generators/generatorResolvers/photonjs/photonResolver.ts
Comment (janpio) [inline packages/internals/src/get-generators/generatorResolvers/photonjs/photonResolver.ts:1]: Let's completely drop this in Prisma 5.
Make a note in https://www.notion.so/prismaio/Prisma-5-ecaea07063da43b39537632bf448a5a6

File: packages/internals/src/get-generators/generatorResolvers/prisma-client-js/check-dependencies/checkTypeScriptVersion.ts [hunk 13]
```diff
@@ -0,0 +1,42 @@
...
+    if (typescriptPkg && fs.existsSync(typescriptPkg)) {
+      const pjson = require(typescriptPkg)
+      const currentVersion = pjson.version
+      if (semverLt(currentVersion, minVersion)) {
+        logger.warn(
+          `Prisma detected that your ${chalk.bold(
+            'TypeScript',
+          )} version ${currentVersion} is outdated. If you want to use Prisma Client with TypeScript please update it to version ${chalk.bold(
+            minVersion,
+          )} or ${chalk.bold('newer')}. ${chalk.dim(`TypeScript found in: ${chalk.bold(typescriptPath)}`)}`,
```
Comment (janpio) [inline packages/internals/src/get-generators/generatorResolvers/prisma-client-js/check-dependencies/checkTypeScriptVersion.ts:35]: Worth adding a link to https://www.prisma.io/docs/reference/system-requirements#software-requirements to surface that table more?

File: packages/internals/src/get-generators/generatorResolvers/prisma-client-js/check-dependencies/checkYarnVersion.ts [hunk 14]
```diff
@@ -0,0 +1,47 @@
...
+      if (agent === 'yarn' && major === 1) {
+        const currentYarnVersion = `${major}.${minor}.${patch}`
+        const minYarnVersion = '1.19.2'
+        if (semverLt(currentYarnVersion, minYarnVersion)) {
+          logger.warn(
+            `Your ${chalk.bold(
+              'yarn',
+            )} has version ${currentYarnVersion}, which is outdated. Please update it to ${chalk.bold(
+              minYarnVersion,
+            )} or ${chalk.bold('newer')} in order to use Prisma.`,
```
Comment (janpio) [inline packages/internals/src/get-generators/generatorResolvers/prisma-client-js/check-dependencies/checkYarnVersion.ts:28]: Worth linking to https://www.prisma.io/docs/reference/system-requirements#software-requirements?

File: packages/internals/src/get-generators/generatorResolvers/prisma-client-js/prismaClientResolver.ts (hunk 12 above)
Comment (janpio) [reply packages/internals/src/get-generators/generatorResolvers/prisma-client-js/prismaClientResolver.ts:39]: I think: `npm add` below will otherwise traverse up the tree to find a `package.json` where to put the dependencies - which might be outside of the project, leading to very funky behavior.

File: packages/ni/README.md
Comment (janpio) [inline packages/ni/README.md:1]: Why do we pull ni in completely?

Comment (janpio) [reply packages/ni/README.md:1]: Ah, I should read the PR description:
> Do not spend too much time on reviewing @prisma/ni, this package is temporary and is a port of my PR https://github.com/antfu/ni/pull/151 until it gets merged.

File: helpers/compile/plugins/tscPlugin.ts [hunk 15]
```diff
@@ -83,8 +84,11 @@ export const tscPlugin: (emitTypes?: boolean) => esbuild.Plugin = (emitTypes?: b
         const tsconfig = require(`${process.cwd()}/${options.tsconfig}`) // tsconfig
         const typeOutDir = tsconfig?.compilerOptions?.outDir ?? '.' // type out dir
         const entryPoint = options.entryPoints?.[0].replace(/\.ts$/, '')
-        const typeOutPath = `${typeOutDir}/${entryPoint.replace(/^src\//, '')}`
         const bundlePath = options.outfile!.replace(/\.js$/, '')
+        const typeOutPath = [
+          `${process.cwd()}/${typeOutDir}/${entryPoint}.d.ts`,
+          `${process.cwd()}/${typeOutDir}/${entryPoint.replace(/^src\//, '')}.d.ts`,
+        ].filter(fs.existsSync)[0]
```
Comment (aqrln) [inline helpers/compile/plugins/tscPlugin.ts:91]: Will it work in a clean checkout of the repo if this file doesn't exist yet?

File: packages/internals/src/get-generators/generatorResolvers/prisma-client-js/prismaClientResolver.ts (hunk 12 above)
Comment (millsp) [reply packages/internals/src/get-generators/generatorResolvers/prisma-client-js/prismaClientResolver.ts:39]: I haven't touched the package.json creation part which is also likely to be problematic too. But to answer your question, we also create a package.json for the user to init their project and for the reasons Jan pointed out. For reference, this is the file that we write, that already smells like an issue:

```sh
{"name":"my-prisma-project","version":"1.0.0","description":"","main":"index.js","scripts":{"test":"echo \"Error: no test specified\" && exit 1"},"keywords":[],"author":"","license":"ISC","devDependencies":{"prisma":"^4.13.0-integration-fix-use-ni-pm-detection.15"},"dependencies":{"@prisma/client":"^4.13.0-integration-fix-use-ni-pm-detection.15"}}
```

File: helpers/compile/plugins/tscPlugin.ts (hunk 15 above)
Comment (millsp) [reply helpers/compile/plugins/tscPlugin.ts:91]: I think it should as the previous step generated the necessary files. This piece of code specifically helps to find the output whether it is generated and contains the `src` root folder in `dist` or not. This is inconsistent in TS 4, in theory only one path should work, but I think it was fixed in TS 5.

File: packages/internals/src/get-generators/generatorResolvers/prisma-client-js/prismaClientResolver.ts (hunk 12 above)
Comment (millsp) [reply packages/internals/src/get-generators/generatorResolvers/prisma-client-js/prismaClientResolver.ts:39]: I haven't touched the package.json creation part which is also likely to be problematic too. But to answer your question, we also create a package.json for the user to init their project and for the reasons Jan pointed out. For reference, this is the file that we write, that already smells like an issue:

```sh
{"name":"my-prisma-project","version":"1.0.0","description":"","main":"index.js","scripts":{"test":"echo \"Error: no test specified\" && exit 1"},"keywords":[],"author":"","license":"ISC","devDependencies":{"prisma":"^4.13.0-integration-fix-use-ni-pm-detection.15"},"dependencies":{"@prisma/client":"^4.13.0-integration-fix-use-ni-pm-detection.15"}}
```

File: packages/internals/src/get-generators/generatorResolvers/photonjs/photonResolver.ts
Comment (millsp) [reply packages/internals/src/get-generators/generatorResolvers/photonjs/photonResolver.ts:1]: Done

File: packages/internals/src/get-generators/generatorResolvers/prisma-client-js/check-dependencies/semverLt.ts (hunk 11 above)
Comment (millsp) [reply packages/internals/src/get-generators/generatorResolvers/prisma-client-js/check-dependencies/semverLt.ts:9]: Good catch, this is code I split/moved around (like most of the PR), I'll create a an issue to fix this and test it.

Comment (millsp) [reply packages/internals/src/get-generators/generatorResolvers/prisma-client-js/check-dependencies/semverLt.ts:9]: https://github.com/prisma/prisma/issues/18751

File: helpers/compile/plugins/tscPlugin.ts (hunk 15 above)
Comment (aqrln) [reply helpers/compile/plugins/tscPlugin.ts:91]: Ah, I missed that part and was a bit confused, thank you!
