### PR TITLE
fix(client): returning never types on selections when extension enabled

### LINKED ISSUE #17767: Prisma.validator: with clientExtensions enabled, Typescript can no longer compute types
### Bug description

On the most basic schema, when Client Extensions are enabled, Typescript is no longer able to properly generate types for query results.  One does not need to implement any specific client extension - in fact, one doesn't have to use them at all.  Simply enabling Client Extensions completely renders any project uncompilable.

Please see the [sample repository](https://github.com/jove4015/special-umbrella) to reproduce.

### How to reproduce

Please see the [sample repository](https://github.com/jove4015/special-umbrella) with full reproduction instructions here:   https://github.com/jove4015/special-umbrella.

In the repo, you will see a very simple application that inserts one record into a basic table with all scalar fields and no relationships.   It runs correctly without client extensions enabled, but fails the second client extensions are turned on.

### Expected behavior

With client extensions enabled, Prisma should still be able to resolve types properly and compile.   Client Extensions should be usable.

### Prisma information

Schema:
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model TestTable {
  id          Int     @id @default(autoincrement())
  task_name   String?
  status      String?
  description String?
  notes       String?
}
```

Prisma version 4.9.0

### Environment & setup

- OS: MacOS or Debian Linux running in Docker
- Database: PostgreSQL
- Node.js version: v16.17.1

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 4.9.0
@prisma/client          : 4.9.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.9.0-42.ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5
Default Engines Hash    : ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5
Studio                  : 0.479.0
```

### LINKED ISSUE #19572: Type "never" returned from nested properties when using "select" after enabling data proxy + accelerate
### Bug description

I'm trying to enable Accelerate by following this documentation: https://prismaio.notion.site/prismaio/Accelerate-documentation-469a2162ab71487e9027403249d9b58f#e7abeabceaaa4af19eef587a8caa94fb

When I get to step 5, viz. enabling data proxy, a lot of the types in the app break. I managed to narrow it down to those queries which call methods that return select statements, e.g.:

```ts 
const selectStatement = { select: {
   id: true
}};

const selectStatement2 = {
   id: true
};

// this fails
prisma.query.findUnique({where: {id}, ...selectStatement}) 

// this also fails 
prisma.query.findUnique({where: {id}, select: selectStatement2}) 

// this works
prisma.query.findUnique({where: {id}, select: {id: true}})
```

**This does not happen on main, where data-proxy is not enabled.** 

If I go on `main` & **don't** install accelerate, but just add "clientExtensions" & run the data proxy command, the build **fails** with the same typing errors.

If I go on `main` & simply run the data proxy command `npx prisma generate --data-proxy`, the build **passes** with no errors. 

### Expected behavior

In the example above, the queries that call "external" select functions return all of the object's properties with type "never" 

Using the bug description example: 

If external select statement => return = {id: never} 
If select statement within prisma query itself => return = {id: number} 

### Prisma information

More concrete examples from prod

```prisma
datasource db {
  provider  = "postgresql"
  url       = env("DATABASE_URL")
  directUrl = env("DIRECT_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["extendedWhereUnique", "jsonProtocol", "clientExtensions"]
}
```

```ts
getApplicationForm = async (tenantId: number, id: number) =>
    prisma.application
      .findUniqueOrThrow({
        where: { tenantId_id: { tenantId, id } },
        select: {
          status: true,
          cycle: {
            select: {
              ...cycleSelectForDates(tenantId, CyclePhaseType.APPLICATIONS),
              appTemplate: {
                select: {
                  status: true,
                  sections: {
                    orderBy: { sortOrder: Prisma.SortOrder.asc },
                    ...formSectionSelect(id),
                  },
                },
              },
            },
          },
        },
      })
      .then(
        tap(({ cycle }) => {
          if (cycle.appTemplate.status !== FormTemplateStatus.PUBLISHED) {
            throw new TRPCError({
              message: 'Application Form not found',
              code: 'NOT_FOUND',
            });
          }
        }),
      )
      .then(({ status, cycle }) => ({
        status,
        dateStart: cycle.phases[0]?.dateStart ?? cycle.dateStart,
        dateEnd: cycle.phases[0]?.dateEnd ?? cycle.dateEnd,
        sections: cycle.appTemplate.sections ?? [],
      }));
```

```ts
const formSectionSelect = (applicationId: number) => ({
  select: {
    id: true,
    name: true,
    questions: {
      orderBy: {
        sortOrder: Prisma.SortOrder.asc,
      },
      select: {
        id: true,
        description: true,
        isRequired: true,
        text: true,
        type: true,
        applicationAnswers: {
          where: {
            applicationId,
          },
          select: {
            id: true,
            answer: true,
            choiceId: true,
          },
        },
        choices: {
          orderBy: {
            sortOrder: Prisma.SortOrder.asc,
          },
          select: {
            id: true,
            text: true,
            isDefault: true,
          },
        },
      },
    },
  },
});
```

This returns the following type 

```ts
(property) ApplicationsService.getApplicationForm: (tenantId: number, id: number) => Promise<{
    status: ApplicationStatus;
    dateStart: never;
    dateEnd: never;
    sections: {
        id: never;
        name: never;
        questions: {
            id: never;
            description: never;
            isRequired: never;
            text: never;
            type: never;
            applicationAnswers: {
                ...;
            }[];
            choices: {
                ...;
            }[];
        }[];
    }[];
}>
```

### Environment & setup

- OS: macOS
- Database: Supabase + Postgresql 
- Node.js version: v18.14.2

### Prisma Version

```
prisma                  : 4.15.0
@prisma/client          : 4.15.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 8fbc245156db7124f997f4cecdd8d1219e360944 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 8fbc245156db7124f997f4cecdd8d1219e360944 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.15.0-28.8fbc245156db7124f997f4cecdd8d1219e360944
Default Engines Hash    : 8fbc245156db7124f997f4cecdd8d1219e360944
Studio                  : 0.484.0
Preview Features        : clientExtensions, extendedWhereUnique, jsonProtocol
```

### PR DESCRIPTION
**Pull request by millsp**
closes https://github.com/prisma/prisma/issues/19572
closes https://github.com/prisma/prisma/issues/17767

Slack [thread](https://prisma-company.slack.com/archives/C016KUHB1R6/p1685727223766319?thread_ts=1685699415.404239&cid=C016KUHB1R6)

### CODE REVIEW

File: packages/client/src/runtime/core/types/GetResult.ts [hunk 1]
```diff
@@ -43,8 +43,15 @@ export type GetFindResult<P extends Payload, A> =
   | { include: infer S } & Record<string, unknown>
   ? {
       [K in keyof S as S[K] extends false | undefined | null ? never : K]:
-        S[K] extends true
+        S[K] extends object
```
Comment (millsp) [inline packages/client/src/runtime/core/types/GetResult.ts:46]: Flips the condition around, instead of checking if it's a boolean, we check if it's an object. This then has the side-effect of treating `true` and `boolean` the same. More details on what and why [here](https://prisma-company.slack.com/archives/C016KUHB1R6/p1685727223766319?thread_ts=1685699415.404239&cid=C016KUHB1R6).

File: packages/client/tests/functional/extensions/enabled/defineExtension.ts [hunk 2]
```diff
@@ -460,33 +460,55 @@ testMatrix.setupTestSuite(() => {
...
+    })
+
+    expectTypeOf<(typeof data1)['args']>().toEqualTypeOf<{ select: { email: true } }>()
+    expectTypeOf<(typeof data1)['payload']>().toMatchTypeOf<object>()
+    expectTypeOf<(typeof data1)['payload']['scalars']>().toHaveProperty('email').toEqualTypeOf<string>()
+    expectTypeOf<(typeof data1)['result'] & {}>().toHaveProperty('email').toEqualTypeOf<string>()
+
+    expectTypeOf<(typeof data2)['args']>().toEqualTypeOf<{ select: { email: boolean } }>()
+    expectTypeOf<(typeof data2)['payload']>().toMatchTypeOf<object>()
+    expectTypeOf<(typeof data2)['payload']['scalars']>().toHaveProperty('email').toEqualTypeOf<string>()
```
Comment (millsp) [inline packages/client/tests/functional/extensions/enabled/defineExtension.ts:482]: Previously, this resulted to `never`.

**Review by SevInf — APPROVED** [review]
So, I think I understood the problem and the fix and I think this is a way to go if we want to stay backward-compatible. 
Question for Prisma 5 or the future: should `{select: { relation: boolean }}` give you out `relation: SomeModel | undefined` instead? Or we've decided that it would be too inconvenient even for the future?
