### PR TITLE
fix: fix transaction manager race condition

### LINKED ISSUE #27660: Transaction API Error: "Closed transaction found in active transactions map" with Query Compiler and Driver Adapter
### Bug description

When using the query compiler with PrismaPg driver adapter, I'm encountering a transaction error on a specific query in production only.

### Error
```
Transaction API error: Internal Consistency Error: Closed transaction found in active transactions map
```

### Failing Query
```
const piecesOfInformation = await coreBypassRlsPrisma.pieceOfInformation.findMany({
  where: {
    processingStatus: 'PENDING'
  }
});
```

Other queries on the same table and all other tables work fine with the same client.

### Severity

🚨 Critical: Data loss, app crash, security issue

### Reproduction

The issue only happens in our production environment. I can't replicate this problem in my local dev and our test environment. Our test setup the same as production. The only difference is the data. 

The `findMany` should return 300 records. A SQL query on the table completes in less than 20ms, so the amount of data shouldn't be the issue either.

I also tried setting a timeout and wait time on the transaction, but the issue persists.

### Expected vs. Actual Behavior

Expected: That prisma returns the rows
Actual: Prisma client throws transaction error

### Frequency

Consistently reproducible

### Does this occur in development or production?

Only in production (e.g., query engine, generated client)

### Is this a regression?

No, the same issue persists with 6.10 as well.

### Workaround

Switching back to the Rust-based client resolves the issue:
```
// This works without errors
return new PrismaClientBase({ datasourceUrl: connectionString }).$extends(
  useExtendedPrismaModel()
);

### Prisma Schema & Queries

### Prisma Schema

```prisma
generator client {
  provider               = "prisma-client"
  output                 = "./generated"
  previewFeatures        = ["postgresqlExtensions", "relationJoins", "queryCompiler"]
  runtime                = "nodejs"
  moduleFormat           = "esm"
  generatedFileExtension = "ts"
  importFileExtension    = "ts"
}

generator json {
  provider  = "prisma-json-types-generator"
  output    = "./generated"
  namespace = "PrismaJson"
}

datasource db {
  provider   = "postgresql"
  url        = env("CORE_DATABASE_URL")
  directUrl  = env("CORE_DATABASE_DIRECT_URL")
  extensions = [pgsodium(schema: "pgsodium"), supabase_vault, uuid_ossp(map: "uuid-ossp", schema: "extensions"), pgvector(map: "vector")]
}

model PieceOfInformation {
  id String @id @default(dbgenerated("typeid_generate_text('infopiece'::text)"))

  ownedByOrganization   Organization @relation(fields: [ownedByOrganizationId], references: [id])
  ownedByOrganizationId String       @default(dbgenerated("current_organization_id()"))

  processingStatus PieceOfInformationProcessingStatus @default(PENDING)
  status           LifecycleStatus                    @default(ACTIVE)
  name             String

  createdOn DateTime @default(now())
  updatedOn DateTime @updatedAt

  @@index([ownedByOrganizationId])
  @@index([ownedByOrganizationId, status])
  @@index([ownedByOrganizationId, itemId])
  @@index([processingStatus])
}
```

### Client Initialization

```ts
const extendedPrismaClient = (connectionString: string) => {
  const pgAdapter = new PrismaPg({ connectionString });
  return new PrismaClientBase({ adapter: pgAdapter }).$extends(useExtendedPrismaModel());
};

const baseCoreByPassRlsPrisma = 
  globalThis.baseCoreByPassRlsPrisma ?? extendedPrismaClient(process.env.CORE_DATABASE_URL!);

export const coreBypassRlsPrisma = baseCoreByPassRlsPrisma.$extends(
  byPassRls()
) as unknown as CorePrismaClient;
```

### RLS Middleware (wraps all operations in transactions)

```ts
const rlsExtension = (claimSql: Prisma.Sql, user: SimpleAuthUser) => {
  const rlsStore = new AsyncLocalStorage<RlsStore>();

  return Prisma.defineExtension(client => {
    return client.$extends({
      name: 'rlsExtension',
      query: {
        $allModels: {
          async $allOperations({ args, query }) {
            const alreadyInRls = rlsStore.getStore()?.alreadyInRls;
            if (alreadyInRls) return query(args);

            const [, result] = await client.$transaction([
              client.$executeRaw(claimSql),
              query(args)
            ]);

            return result;
          }
        }
     }
   }
}
```

### Environment & Setup

- **OS:** Debian
- **Database:** PostgreSQL
- **Node.js version:** 22

### Prisma Version

```
 6.11
```

### PR DESCRIPTION
**Pull request by jacek-prisma**
Should fix https://github.com/prisma/prisma/issues/27660

The changes here ensure that we never have a closed transaction inside of `this.transactions` in between any `await` points, so users don't end up seeing `TransactionInternalConsistencyError`s.
Also adds a `closing` state that ensures we do not attempt to rollback multiple times.

### CODE REVIEW

File: packages/client-engine-runtime/src/transactionManager/TransactionManager.ts [hunk 1]
```diff
@@ -104,13 +105,17 @@ export class TransactionManager {
     // Transaction status might have changed to timed_out while waiting for transaction to start. => Check for it!
```
Comment (aqrln) [inline packages/client-engine-runtime/src/transactionManager/TransactionManager.ts]: nit:

```suggestion
    // Transaction status might have timed out while waiting for transaction to start. => Check for it!
```
since we're not actually doing that by checking for the state transition to `timed_out` in `case 'waiting'` anymore

**Review by aqrln — APPROVED** [review]
LGTM with a nit

**Comment by AjaniBilby** [comment]
I don't see a git tag for 6.12.1, did this merge make it into that update?
Or is this fix not published to npm yet?

Because I'm having this issue in production - and I'm trying to work out if I just need to get this patch into my system, or if possibly it's a new issue I need to investigate.

**Comment by AjaniBilby** [comment]
Sorry, never mind, there is no 6.12.1 - idk what I was thinking of.

**Comment by jacek-prisma** [comment]
@AjaniBilby it's currently fixed on dev, a new stable version with the fix will release next week
