### PR TITLE
fix(client): Fix #5616

### LINKED ISSUE #5616: $transaction doesn't rollback in case any transaction fails
## Bug description
I am trying to use Prisma transactions as specified [here](https://www.prisma.io/docs/guides/prisma-guides/prisma-client-transactions-guide/#can-i-perform-multiple-nested-writes---for-example-create-two-new-teams-and-assign-users). My transaction is not rolling back in case of an error.

**Example**
```ts
const txn1 = this.prisma.table1.create({
      data: {
        name: `Test 1`
      },
    });
const txn2 = this.prisma.table1.create({
  data: {
    name: undefined //`Test 2`,
  },
});
const transactionResults = await this.prisma.$transaction([txn1, txn2]);
```
`name` is a mandatory column so when I send undefined, `txn2` fails but `txn1` still creates a record in the table even though it should rollback as `txn2` failed.

## How to reproduce

Sample code shared above. Try to execute it with a test table.

## Expected behavior
Transaction 1 insert should rollback as transaction 2 failed.

## Environment & setup

- OS: MacOS Catalina 10.15.1, Running inside docker `node:14.15.4-alpine`
- Database: PostgreSQL 
- Node.js version: v14.15.4 
- Prisma version:

```
prisma               : 2.16.0
@prisma/client       : 2.16.0
Current platform     : linux-musl
Query Engine         : query-engine 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules/prisma/node_modules/@prisma/engines/query-engine-linux-musl)
Migration Engine     : migration-engine-cli 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules/prisma/node_modules/@prisma/engines/migration-engine-linux-musl)
Introspection Engine : introspection-core 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules/prisma/node_modules/@prisma/engines/introspection-engine-linux-musl)
Format Binary        : prisma-fmt 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-linux-musl)
Studio               : 0.346.0
Preview Features     : nativeTypes, createMany
```

### PR DESCRIPTION
**Pull request by timsuchanek**
We fix a situation where a mix of specific transactions would not roll back:
If you had an array of transactions and the first element would succeed, while the second would fails with a JavaScript runtime validation error, the first query would not be rolled back.
The solution is to do things in 2 steps: First the validation, then the query.
So that if the validation fails, we're not even sending the query anymore.
This is achieved in https://github.com/prisma/prisma/pull/5625/files#diff-fa9a06cd1e0a72798879057fc84c392b66c4cd06446619c74bc749f11aa152a1R1622 where we don't return the request Promise directly for transactions anymore, but rather a callback.
This callback is then being called with Promise.all in https://github.com/prisma/prisma/pull/5625/files#diff-fa9a06cd1e0a72798879057fc84c392b66c4cd06446619c74bc749f11aa152a1R908

### CODE REVIEW

File: src/packages/client/src/__tests__/integration/happy/mixed-transaction/test.ts [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+          email: undefined,
+        },
+      }),
+    ])
+  } catch (e) {
+    //
+    // console.error(e)
+  }
+
+  await new Promise<void>((r) => r())
```
Comment (williamluke4) [inline src/packages/client/src/__tests__/integration/happy/mixed-transaction/test.ts:28]: What in the world is this for?

**Review by williamluke4 — APPROVED** [review]

File: src/packages/client/src/__tests__/integration/happy/mixed-transaction/test.ts (hunk 1 above)
Comment (timsuchanek) [reply src/packages/client/src/__tests__/integration/happy/mixed-transaction/test.ts:28]: The problem is, that without this, the current "batch" is not dispatched in the error case.
