### PR TITLE
fix(client): Serialize all Floats in exponential notation

### LINKED ISSUE #12651: Cannot insert Floats (≥9.223372037e18 and <1e21) or (>-1e21 and ≤-9.223372037e18)
### Bug description

Trying to set fields defined as `Float` in the Schema to values ≥ `9.223372037e18` and < `1e21` fails with the following error:
```
Error parsing GraphQL query: query parse error: Parse error at 3:11
number too large to fit in target type
```
Additionally, trying to set values > `-1e21` and ≤ `-9.223372037e18` throws as well:
```
Error parsing GraphQL query: query parse error: Parse error at 3:11
number too small to fit in target type
```
I've first encountered this with postgresql, but it happens with sqlite as well.

I'm guessing there is something going wrong while parsing the generated GraphQL query.
Calling the reproduction script with `1e20` throws while trying to execute the following query that was generated by `prisma:client`:
```graphql
mutation {
  createOneTest(data: {
    test: 100000000000000000000
  }) {
    id
    test
  }
}
```

Running that same query manually through the `query-engine`'s GraphQL playground yields the same error, but when writing the value in exponential notation (`1e20`), the mutation works just fine.

### How to reproduce

1. clone https://github.com/cmd-johnson/prisma-bug-reproduction
2. install the project (either run `npm install` or `yarn install`)
    - The project's `postinstall` hook will automatically create a `test.db` sqlite DB and apply the only required migration
3. running `node index.js [number]` will attempt to insert the value you pass it as an argument into the database. Try it with:
    | value | result |
    |-------|--------|
    | `1e20` | error ("too large") |
    | `1e21` | ok |
    | `9.223372037e18` | error ("too large") |
    | `9.223372036e18` | ok |
    | `-1e20` | error ("too small") |
    | `-1e21` | ok |
    | `-9.223372037e18` | error ("too small") |
    | `-9.223372036e18` | ok |

This can also be reproduced when running the Prisma query-engine directly, with some key differences:
1. clone https://github.com/cmd-johnson/prisma-bug-reproduction
2. in the project directory, run `query-engine --datamodel-path ./schema.prisma -g`
3. go to http://localhost:4466/
    | value | result |
    |---|---|
    | `1e20` | ok |
    | `100000000000000000000` (== `1e20`, but written out) | error ("too large") |

### Expected behavior

All examples should work without throwing.

### Prisma information

Schema:
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  url = "file:./test.db"
  provider = "sqlite"
}

model Test {
  id Int @id @default(autoincrement())
  test Float
}
```

Code: (see [reproduction repo](https://github.com/cmd-johnson/prisma-bug-reproduction) for more)
```js
await prisma.test.create({ data: { test: 1e20 } })
```

### Environment & setup

- OS: Linux (Manjaro)
- Database: PostgreSQL or SQLite, others probably as well
- Node.js version: v17.8.0

### Prisma Version

```
prisma                  : 3.11.1
@prisma/client          : 3.11.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 1a2506facaf1a4727b7c26850735e88ec779dee9
Studio                  : 0.458.0
```

### LINKED ISSUE #13317: Always serialize float fields in exponent notation
Follow-up to this ticket: https://github.com/prisma/prisma/issues/12651
We should always serialize float field values in the generated GraphQL query to exponential notation, as the whole number serialization causes the value being parsed as a 64 bit signed integer, which limits the float range unnecessarily.

I consider this a bug as the user has a valid float to store, but the integer parsing prevents that.

### LINKED ISSUE #15551: Float values around 2^63 get interpreted as invalid intergers and throw a graphql error
### Bug description

Running the `create` method with any schema with a `Float` column with the value `2**64` fails.

After some digging, it seems that the graphql query stringifies the number to `18446744073709552000`, which graphql wrongly interprets as an integer. Passing values around `2**70` function as it seems they get serialized as `1.1805916207174113e+21`.

This means we cannot insert numbers from around ~`2**63` to ~`2**69` for our app. Can't insert them via prisma studio either.

I dont know the codebase much, but would this be fixed if ".0" was suffixed to numbers that the `e` notation doesn't have?

### How to reproduce

1. copy the schema below
2. run the provided js on it. it is a single create query
3. > Query parsing failure: A number used in the query does not fit into a 64 bit signed integer. Consider using `BigInt` as field type if you're trying to store large integers

### Expected behavior

The value `18446744073709552000` should be written to the database as a float. 

### Prisma information

`prisma/schema.prisma`
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:./test.db"
}

model Test {
  id    Int   @id @default(autoincrement())
  value Float
}
```
`test.mjs`
```js
import { PrismaClient } from '@prisma/client';

const client = new PrismaClient();

await client.test.create({
  data: {
    value: 2 ** 64,
  },
});
```

using `DEBUG=*` i found this graphql query
```graphql
mutation {
  createOneTest(data: {
    value: 18446744073709552000
  }) {
    id
    value
  }
}
```

the `value: n` is what im referring to above about the stringified value

### Environment & setup

- OS: Debian Docker running on NixOS
- Database: Sqlite
- Node.js version: 16.17.0

### Prisma Version

```
prisma                  : 4.3.1
@prisma/client          : 4.3.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/.pnpm/@prisma+engines@4.3.1/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/.pnpm/@prisma+engines@4.3.1/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/.pnpm/@prisma+engines@4.3.1/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/.pnpm/@prisma+engines@4.3.1/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.3.0-32.c875e43600dfe042452e0b868f7a48b817b9640b
Default Engines Hash    : c875e43600dfe042452e0b868f7a48b817b9640b
Studio                  : 0.473.0
```

### PR DESCRIPTION
**Pull request by cmd-johnson**
This should fix #12651, #13317 and #15551 by always serializing Float fields in GraphQL queries in exponential notation.

I added a unit test for the serialization and a integration test that verifies that large floats can now be inserted into the database and updated other tests that used floats to match the new serialization behavior.

In order to properly test this, I also had to change the regex used by the `jestSnapshotSerializer` in `normalizeMigrateTimestamps`, because it interfered with all long numbers in snapshots. E.g. `-9.007199254740991e+15` would get replaced with `-9.202012310000001e+15`, which made snapshots appear to test for a wrong value. I updated snapshots that had the same problem accordingly.

Fixes #12651
Fixes #13317
Fixes #15551

### CODE REVIEW

**Review by SevInf — APPROVED** [review]
Hi @cmd-johnson!
Thank you for the great contribution, especially adding both unit & integration tests!

I've made a couple of changes to the PR:
- converted intergration test to a [functional](https://github.com/prisma/prisma/blob/main/TESTING.md#functional-tests-for-the-client) one. This a newer, more powerful test suite and we generally add new tests there and consider integration suite to be a legacy.

Once CI is green, I'll merge your contribution. Then, it will be released as a part of prisma 4.6.0.

**Comment by aqrln** [comment]
Also fixes https://github.com/prisma/prisma/issues/15551

File: packages/internals/src/utils/jestSnapshotSerializer.js [hunk 1]
```diff
@@ -69,7 +69,8 @@ function normalizeBinaryFilePath(str) {
 }
 
 function normalizeMigrateTimestamps(str) {
-  return str.replace(/\d{14}/g, '20201231000000')
+  return str.replace(/(?<!\d)\d{14}(?!\d)/g, '20201231000000')
+  // return str.replace(/\d{14}/g, '20201231000000')
```
Comment (aqrln) [inline packages/internals/src/utils/jestSnapshotSerializer.js:73]:
```suggestion
```

**Review by aqrln — APPROVED** [review]
