### PR TITLE
fix(sdk): convertCredentials for SQLite when using file: & correct database name

### LINKED ISSUE #283: Create new SQL Database missing first char on name
Version: Preview19
Platform: Windows 10

Running `primsma2 lift save` when the DB doesn't exist prompts to create the DB but the db name doesn't include the first char (only in the message), it creates the DB with the correct name. See this image for reference:
image

Also, when you press YES, it hangs. I need to CTRL + C then run it again for it to work.

### PR DESCRIPTION
**Pull request by Jolg42**
Closes prisma/migrate#283

### CODE REVIEW

File: src/packages/sdk/src/convertCredentials.ts [hunk 1]
```diff
@@ -61,6 +62,13 @@ export function credentialsToUri(credentials: DatabaseCredentials): string {
     url.pathname = ''
   }
 
+  if (
+    credentials.type === 'sqlite' &&
+    credentials.uri?.indexOf('file:') === 0
```
Comment (timsuchanek) [inline src/packages/sdk/src/convertCredentials.ts:67]:
```suggestion
    credentials.uri?.startsWith('file:')
```

File: src/packages/sdk/src/convertCredentials.ts [hunk 2]
```diff
@@ -87,16 +95,24 @@ export function uriToCredentials(
 
   const { schema, socket, host, ...extraFields } = uri.query
 
+  let database: string | undefined = undefined
+  if (type === 'sqlite' && uri.pathname) {
+    if (uri.pathname.indexOf('file:') === 0) {
```
Comment (timsuchanek) [inline src/packages/sdk/src/convertCredentials.ts:100]:
```suggestion
    if (uri.pathname.startsWith('file:')) {
```
