### PR TITLE
fix(client): Allow to use `constructor` as a model name

### LINKED ISSUE #15615: Type error on query with select field (although query runs successfully)
### Bug description

I'm having the following query:

```
const seasonDrivers = await prisma.seasonEntrantDriver.findMany({
  select: {
    driver: {
      select: {
        id: true,
        name: true,
        nationality: {
          select: {
            alpha2Code: true,
          },
        },
      },
    },
  },
  where: {
    year: currentSeasonYear,
  },
})
```

and although the query returns the expected results like:

```
[
  {
    "driver": {
      "id": "valtteri-bottas",
      "name": "Valtteri Bottas",
      "nationality": {
        "alpha2Code": "FI"
      }
    }
  },
  ..
]
```

I get a type error in Visual Studio Code on the top `select` part stating:

```
Type '{ driver: { select: { id: true; name: true; nationality: { select: { alpha2Code: true; }; }; }; }; }' is not assignable to type 'SeasonEntrantDriverSelect'.
  Types of property 'constructor' are incompatible.
    Type 'Function' is not assignable to type 'boolean | ConstructorArgs'.ts(2322)
```

which results in more type errors downstream as the `seasonDrivers` var cannot be typed anymore; which also means auto-completion is not working anymore.

Probably it is related to the `constructor` name used as field.
Note that however I can query my constructor table without any problems like 
`const constructors = await prisma.constructor.findMany({..})`
so it is not a general problem to use the name `constructor`.

Even a similar query using a nested `constructor` field like below gives no type error at all:

```
const seasonConstructors = await prisma.seasonEntrantConstructor.findMany({
  select: {
    constructor: {
      select: {
        id: true,
        name: true,
        country: {
          select: {
            alpha2Code: true,
          },
        },
      },
    },
  },
  where: {
    year: currentSeasonYear,
  },
})
```

### How to reproduce

.

### Expected behavior

_No response_

### Prisma information

Here is a part of the Prisma schema.

If needed I can share the full schema.

```
model Season {
  year                                   Int                                     @map("year") @id
  seasonEntrants                         SeasonEntrant[]                         @relation("SeasonEntrantsBySeason")
  seasonEntrantConstructors              SeasonEntrantConstructor[]              @relation("SeasonEntrantConstructorsBySeason")
  seasonEntrantTyreManufacturers         SeasonEntrantTyreManufacturer[]         @relation("SeasonEntrantTyreManufacturersBySeason")
  seasonEntrantDrivers                   SeasonEntrantDriver[]                   @relation("SeasonEntrantDriversBySeason")
  @@map("season")
}

model SeasonEntrant {
  year                                   Int                                     @map("year")
  season                                 Season                                  @relation(name: "SeasonEntrantsBySeason", fields: [year], references: [year])
  entrantId                              String                                  @map("entrant_id")
  entrant                                Entrant                                 @relation(name: "SeasonEntrantsByEntrant", fields: [entrantId], references: [id])
  countryId                              String                                  @map("country_id")
  country                                Country                                 @relation(name: "SeasonEntrantsByCountry", fields: [countryId], references: [id])
  seasonEntrantConstructors              SeasonEntrantConstructor[]              @relation("SeasonEntrantConstructorsBySeasonEntrant")
  seasonEntrantTyreManufacturers         SeasonEntrantTyreManufacturer[]         @relation("SeasonEntrantTyreManufacturerBySeasonEntrant")
  seasonEntrantDrivers                   SeasonEntrantDriver[]                   @relation("SeasonEntrantDriversBySeasonEntrant")
  @@map("season_entrant")
  @@id([year, entrantId])
}

model SeasonEntrantConstructor {
  year                                   Int                                     @map("year")
  season                                 Season                                  @relation(name: "SeasonEntrantConstructorsBySeason", fields: [year], references: [year])
  entrantId                              String                                  @map("entrant_id")
  entrant                                Entrant                                 @relation(name: "SeasonEntrantConstructorsByEntrant", fields: [entrantId], references: [id])
  seasonEntrant                          SeasonEntrant                           @relation(name: "SeasonEntrantConstructorsBySeasonEntrant", fields: [year, entrantId], references: [year, entrantId])
  constructorId                          String                                  @map("constructor_id")
  constructor                            Constructor                             @relation(name: "SeasonEntrantConstructorsByConstructor", fields: [constructorId], references: [id])
  engineManufacturerId                   String                                  @map("engine_manufacturer_id")
  engineManufacturer                     EngineManufacturer                      @relation(name: "SeasonEntrantConstructorsByEngineManufacturer", fields: [engineManufacturerId], references: [id])
  seasonEntrantTyreManufacturers         SeasonEntrantTyreManufacturer[]         @relation("SeasonEntrantTyreManufacturersBySeasonEntrantConstructor")
  seasonEntrantDrivers                   SeasonEntrantDriver[]                   @relation("SeasonEntrantDriversBySeasonEntrantConstructor")
  @@map("season_entrant_constructor")
  @@id([year, entrantId, constructorId, engineManufacturerId])
}

model SeasonEntrantTyreManufacturer {
  year                                   Int                                     @map("year")
  season                                 Season                                  @relation(name: "SeasonEntrantTyreManufacturersBySeason", fields: [year], references: [year])
  entrantId                              String                                  @map("entrant_id")
  entrant                                Entrant                                 @relation(name: "SeasonEntrantTyreManufacturersByEntrant", fields: [entrantId], references: [id])
  seasonEntrant                          SeasonEntrant                           @relation(name: "SeasonEntrantTyreManufacturerBySeasonEntrant", fields: [year, entrantId], references: [year, entrantId])
  constructorId                          String                                  @map("constructor_id")
  constructor                            Constructor                             @relation(name: "SeasonEntrantTyreManufacturersByConstructor", fields: [constructorId], references: [id])
  engineManufacturerId                   String                                  @map("engine_manufacturer_id")
  engineManufacturer                     EngineManufacturer                      @relation(name: "SeasonEntrantTyreManufacturersByEngineManufacturer", fields: [engineManufacturerId], references: [id])
  seasonEntrantConstructor               SeasonEntrantConstructor                @relation(name: "SeasonEntrantTyreManufacturersBySeasonEntrantConstructor", fields: [year, entrantId, constructorId, engineManufacturerId], references: [year, entrantId, constructorId, engineManufacturerId])
  tyreManufacturerId                     String                                  @map("tyre_manufacturer_id")
  tyreManufacturer                       TyreManufacturer                        @relation(name: "SeasonEntrantTyreManufacturersByTyreManufacturer", fields: [tyreManufacturerId], references: [id])
  @@map("season_entrant_tyre_manufacturer")
  @@id([year, entrantId, constructorId, engineManufacturerId, tyreManufacturerId])
}

model SeasonEntrantDriver {
  year                                   Int                                     @map("year")
  season                                 Season                                  @relation(name: "SeasonEntrantDriversBySeason", fields: [year], references: [year])
  entrantId                              String                                  @map("entrant_id")
  entrant                                Entrant                                 @relation(name: "SeasonEntrantDriversByEntrant", fields: [entrantId], references: [id])
  seasonEntrant                          SeasonEntrant                           @relation(name: "SeasonEntrantDriversBySeasonEntrant", fields: [year, entrantId], references: [year, entrantId])
  constructorId                          String                                  @map("constructor_id")
  constructor                            Constructor                             @relation("SeasonEntrantDriversByConstructor", fields: [constructorId], references: [id])
  engineManufacturerId                   String                                  @map("engine_manufacturer_id")
  engineManufacturer                     EngineManufacturer                      @relation(name: "SeasonEntrantDriversByEngineManufacturer", fields: [engineManufacturerId], references: [id])
  seasonEntrantConstructor               SeasonEntrantConstructor                @relation(name: "SeasonEntrantDriversBySeasonEntrantConstructor", fields: [year, entrantId, constructorId, engineManufacturerId], references: [year, entrantId, constructorId, engineManufacturerId])
  driverId                               String                                  @map("driver_id")
  driver                                 Driver                                  @relation(name: "SeasonEntrantDriversByDriver", fields: [driverId], references: [id])
  @@map("season_entrant_driver")
  @@id([year, entrantId, constructorId, engineManufacturerId, driverId])
}

```

### Environment & setup

- OS: macOS
- Database: SQLite
- Node.js version: v18.4.0

### Prisma Version

```
prisma                  : 4.3.1
@prisma/client          : 4.3.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/prisma-fmt-darwin)
Format Wasm             : @prisma/prisma-fmt-wasm 4.3.0-32.c875e43600dfe042452e0b868f7a48b817b9640b
Default Engines Hash    : c875e43600dfe042452e0b868f7a48b817b9640b
Studio                  : 0.473.0
```

### PR DESCRIPTION
**Pull request by SevInf**
Mostly, it was a matter of replacing `Boolean(model[typeName])` with `hasOwnProperty(model, typeName)` since former works on `constructor` property from object prototype.
However, there were 2 other changes necessary.
For fluent clients, we have to change type declaration from class to interface because within a class, `get constructor()` declaration causes TS error, but it's fine within interface. Bunch of private properties were removed from a declaration as a result, but they were very outdated and did not correspond to runtime.

For `PrismaClient` class, we have the same problem, but we can't use the same solution - `PrismaClient` has to be a class with a usable constructor. So, there we switch from  `get constructor()`  to `get ["constructor"]()` declaration - this is enough to make both constructor and the model property work.

Fix #15615

### CODE REVIEW

File: packages/client/src/generation/utils.ts [hunk 1]
```diff
@@ -71,6 +71,9 @@ export function getFieldArgName(field: DMMF.SchemaField, modelName: string): str
   if (field.args.length) {
     return getModelFieldArgsName(field, modelName)
   }
+  if ((field.outputType.type as any).name === undefined) {
+    console.log(field.outputType.type)
+  }
```
Comment (Jolg42) [inline packages/client/src/generation/utils.ts:76]: What is this for? 👀

**Review by millsp — APPROVED** [review]

**Comment by marceloverdijk** [comment]
Unfortunately, I think this fix only solves it partially... see https://github.com/prisma/prisma/issues/15615#issuecomment-2360119584
