### PR TITLE
fix(cli): omit full path from `prisma --version`

### LINKED ISSUE #2882: Omit full path when running prisma --version
## Problem

Right now when I run `prisma --version`, I get the full path to the binaries.

```
@prisma/cli          : 2.0.0
Current platform     : darwin
Query Engine         : query-engine de2bc1cbdb5561ad73d2f08463fa2eec48993f56 (at /Users/m/Go/src/github.com/prisma/upgrade/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli de2bc1cbdb5561ad73d2f08463fa2eec48993f56 (at /Users/m/Go/src/github.com/prisma/upgrade/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core de2bc1cbdb5561ad73d2f08463fa2eec48993f56 (at /Users/m/Go/src/github.com/prisma/upgrade/node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt de2bc1cbdb5561ad73d2f08463fa2eec48993f56 (at /Users/m/Go/src/github.com/prisma/upgrade/node_modules/@prisma/cli/prisma-fmt-darwin)
```

On top of being unwieldy, this is also not copy & pastable.

## Suggested solution

I'd suggest we make those paths relative to our current working directory. 

Then we can adjust the github issue templates to ask users to run `prisma --version`, instead of:

```md
## Environment & setup

<!-- In which environment does the problem occur -->

- OS: <!--[e.g. Mac OS, Windows, Debian, CentOS, ...]-->
- Database: <!--[PostgreSQL, MySQL, MariaDB or SQLite]-->
- Prisma version: <!--[Run `prisma -v` to see your Prisma version]-->
- Node.js version: <!--[Run `node -v` to see your Node.js version]-->
```

### PR DESCRIPTION
**Pull request by Jolg42**
Closes #2882

```
@prisma/cli          : 2.2.0-dev.43
Current platform     : darwin
Query Engine         : query-engine 83ac782d5d93dcee37efeba8ccbeff596701148a (at ../../sdk/query-engine-darwin)
Migration Engine     : migration-engine-cli 83ac782d5d93dcee37efeba8ccbeff596701148a (at ../../sdk/migration-engine-darwin)
Introspection Engine : introspection-core 83ac782d5d93dcee37efeba8ccbeff596701148a (at ../../sdk/introspection-engine-darwin)
Format Binary        : prisma-fmt 83ac782d5d93dcee37efeba8ccbeff596701148a (at ../../sdk/prisma-fmt-darwin)
```

### CODE REVIEW

File: src/packages/cli/src/Version.ts [hunk 1]
```diff
@@ -56,9 +57,16 @@ export class Version implements Command {
...
-  private printBinaryInfo({ path, version, fromEnvVar }: BinaryInfo): string {
+  private printBinaryInfo({
+    path: absolutePath,
+    version,
+    fromEnvVar,
+  }: BinaryInfo): string {
     const resolved = fromEnvVar ? `, resolved by ${fromEnvVar}` : ''
-    return `${version} (at ${path}${resolved})`
+    return `${version} (at ${path.relative(
+      __dirname,
```
Comment (timsuchanek) [inline src/packages/cli/src/Version.ts:67]: Let's use `proces.cwd()` instead  here.

**Review by timsuchanek — CHANGES_REQUESTED** [review]

File: src/packages/cli/src/Version.ts (hunk 1 above)
Comment (Jolg42) [inline src/packages/cli/src/Version.ts:67]:
```suggestion
      process.cwd(),
```
