### PR TITLE
fix(client): deep chaining

### LINKED ISSUE #3267: Fluent API chaining seems to be broken as of 2.3.0
## Bug description

The query chaining part of the fluent API is throwing an error when chaining anything more than 1 relation, e.g.:
```
const customer = await prisma.booking
  .findOne({ where: { id: booking.id } })
  .property()
  .customer()
```

Throws:
```
  12 const customer = await prisma.booking
  13   .findOne({ where: { id: booking.id } })
  14   .property()
→ 15   .customer({
       where: {
         id: 'ckdprh4rp000092ch4d7pus08'
       },
       select: {
         property: {
         ~~~~~~~~
           select: {
             customer: true
           }
         },
     ?   id?: true,
     ?   customer?: true,
     ?   customerId?: true,
     ?   bookings?: true
       }
     })


Unknown field `property` for select statement on model Property. Available options are listed in green.
```

## How to reproduce

1. Create schema
```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Customer {
  id         String     @default(cuid()) @id
  // children
  properties Property[]
}

model Property {
  id         String    @default(cuid()) @id
  // parents
  customer   Customer  @relation(fields: [customerId], references: [id])
  customerId String
  // children
  bookings   Booking[]
}

model Booking {
  id         String   @default(cuid()) @id
  // parents
  property   Property @relation(fields: [propertyId], references: [id])
  propertyId String
}
```

2. Run this script:
```
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

const main = async () => {
  await prisma.executeRaw('TRUNCATE "Customer" CASCADE')
  
  const booking = await prisma.booking.create({
    data: { property: { create: { customer: { create: {} } } } }
  })

  const customer = await prisma.booking
    .findOne({ where: { id: booking.id } })
    .property()
    .customer()

  console.log(customer)
}

main().catch(err => console.log(err)).finally(async () => {
  await prisma.disconnect()
})

```

## Expected behavior

Should work as before v2.3+

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 14.5.0
- Prisma version:

```
2.4.1 (seems to be broken as of 2.3.0)
```

### PR DESCRIPTION
**Pull request by timsuchanek**
Closes #3267

### CODE REVIEW

File: src/packages/client/src/runtime/getPrismaClient.ts [hunk 1]
```diff
@@ -986,7 +986,7 @@ new PrismaClient({
                 /*
                  * necessary for user.posts() calls -> the original model name needs to be preserved
                  */
-                modelName: model.name,
+                modelName: modelName || model.name,
```
Comment (Jolg42) [inline src/packages/client/src/runtime/getPrismaClient.ts:989]: Literally a one line fix 😄
