### PR TITLE
fix(debug): stop relying on `process` (unavailable in Vercel Edge Functions) and `node:util`

### LINKED ISSUE #24346: `next build` shows warning about `@prisma/debug`: `A Node.js API is used (process.stdout at line: 68) which is not supported in the Edge Runtime.`
### Bug description

When deploying the following project https://github.com/prisma/ecosystem-tests/tree/dev/driver-adapters-wasm/planetscale-vercel-nextjs-edgemw here is the output from `next build` with 10 warnings about `@prisma/debug`

```
[14:03:38.532] > next build
[14:03:38.532] 
[14:03:39.214]   ▲ Next.js 14.2.3
[14:03:39.215] 
[14:03:39.215]    Linting and checking validity of types ...
[14:03:39.420]    Creating an optimized production build ...
[14:03:46.546]  ⚠ Compiled with warnings
[14:03:46.546] 
[14:03:46.547] ./node_modules/.pnpm/@prisma+debug@5.15.0-dev.50/node_modules/@prisma/debug/dist/index.js
[14:03:46.547] A Node.js API is used (process.stdout at line: 68) which is not supported in the Edge Runtime.
[14:03:46.547] Learn more: https://nextjs.org/docs/api-reference/edge-runtime
[14:03:46.547] 
[14:03:46.547] Import trace for requested module:
[14:03:46.547] ./node_modules/.pnpm/@prisma+debug@5.15.0-dev.50/node_modules/@prisma/debug/dist/index.js
[14:03:46.547] ./node_modules/.pnpm/@prisma+driver-adapter-utils@5.15.0-dev.50/node_modules/@prisma/driver-adapter-utils/dist/index.mjs
[14:03:46.547] ./node_modules/.pnpm/@prisma+adapter-planetscale@5.15.0-dev.50_@planetscale+database@1.18.0/node_modules/@prisma/adapter-planetscale/dist/index.mjs
[14:03:46.547] 
[14:03:46.547] ./node_modules/.pnpm/@prisma+debug@5.15.0-dev.50/node_modules/@prisma/debug/dist/index.js
[14:03:46.548] A Node.js API is used (process.stdout at line: 68) which is not supported in the Edge Runtime.
[14:03:46.548] Learn more: https://nextjs.org/docs/api-reference/edge-runtime
[14:03:46.548] 
[14:03:46.548] Import trace for requested module:
[14:03:46.548] ./node_modules/.pnpm/@prisma+debug@5.15.0-dev.50/node_modules/@prisma/debug/dist/index.js
[14:03:46.548] ./node_modules/.pnpm/@prisma+driver-adapter-utils@5.15.0-dev.50/node_modules/@prisma/driver-adapter-utils/dist/index.mjs
[14:03:46.548] ./node_modules/.pnpm/@prisma+adapter-planetscale@5.15.0-dev.50_@planetscale+database@1.18.0/node_modules/@prisma/adapter-planetscale/dist/index.mjs
[14:03:46.548] 
[14:03:46.548] ./node_modules/.pnpm/@prisma+debug@5.15.0-dev.50/node_modules/@prisma/debug/dist/index.js
[14:03:46.549] A Node.js API is used (process.stderr at line: 146) which is not supported in the Edge Runtime.
[14:03:46.549] Learn more: https://nextjs.org/docs/api-reference/edge-runtime
[14:03:46.549] 
[14:03:46.549] Import trace for requested module:
[14:03:46.549] ./node_modules/.pnpm/@prisma+debug@5.15.0-dev.50/node_modules/@prisma/debug/dist/index.js
[14:03:46.549] ./node_modules/.pnpm/@prisma+driver-adapter-utils@5.15.0-dev.50/node_modules/@prisma/driver-adapter-utils/dist/index.mjs
[14:03:46.549] ./node_modules/.pnpm/@prisma+adapter-planetscale@5.15.0-dev.50_@planetscale+database@1.18.0/node_modules/@prisma/adapter-planetscale/dist/index.mjs
[14:03:46.549] 
[14:03:46.549] ./node_modules/.pnpm/@prisma+debug@5.15.0-dev.50/node_modules/@prisma/debug/dist/index.js
[14:03:46.550] A Node.js API is used (process.stderr at line: 146) which is not supported in the Edge Runtime.
[14:03:46.550] Learn more: https://nextjs.org/docs/api-reference/edge-runtime
[14:03:46.550] 
[14:03:46.550] Import trace for requested module:
[14:03:46.550] ./node_modules/.pnpm/@prisma+debug@5.15.0-dev.50/node_modules/@prisma/debug/dist/index.js
[14:03:46.550] ./node_modules/.pnpm/@prisma+driver-adapter-utils@5.15.0-dev.50/node_modules/@prisma/driver-adapter-utils/dist/index.mjs
[14:03:46.550] ./node_modules/.pnpm/@prisma+adapter-planetscale@5.15.0-dev.50_@planetscale+database@1.18.0/node_modules/@prisma/adapter-planetscale/dist/index.mjs
[14:03:46.550] 
[14:03:46.551] ./node_modules/.pnpm/@prisma+debug@5.15.0-dev.50/node_modules/@prisma/debug/dist/index.js
[14:03:46.551] A Node.js API is used (process.stderr at line: 150) which is not supported in the Edge Runtime.
[14:03:46.551] Learn more: https://nextjs.org/docs/api-reference/edge-runtime
[14:03:46.551] 
[14:03:46.551] Import trace for requested module:
[14:03:46.551] ./node_modules/.pnpm/@prisma+debug@5.15.0-dev.50/node_modules/@prisma/debug/dist/index.js
[14:03:46.551] ./node_modules/.pnpm/@prisma+driver-adapter-utils@5.15.0-dev.50/node_modules/@prisma/driver-adapter-utils/dist/index.mjs
[14:03:46.552] ./node_modules/.pnpm/@prisma+adapter-planetscale@5.15.0-dev.50_@planetscale+database@1.18.0/node_modules/@prisma/adapter-planetscale/dist/index.mjs
[14:03:46.552] 
[14:03:50.097]  ✓ Compiled successfully
```

<details>
<summary>Full logs</summary>

```
[14:03:18.885] Running build in Washington, D.C., USA (East) – iad1
[14:03:19.092] Retrieving list of deployment files...
[14:03:20.271] Downloading 13 deployment files...
[14:03:27.162] Restored build cache
[14:03:27.303] Running "vercel build"
[14:03:28.249] Vercel CLI 34.2.3
[14:03:29.279] Detected `pnpm-lock.yaml` version 6 generated by pnpm 8
[14:03:29.324] Installing dependencies...
[14:03:31.002] Lockfile is up to date, resolution step is skipped
[14:03:31.373] Progress: resolved 1, reused 0, downloaded 0, added 0
[14:03:31.528] Packages: +8 -8
[14:03:31.533] ++++++++--------
[14:03:32.389] Progress: resolved 8, reused 0, downloaded 0, added 0
[14:03:33.110] Progress: resolved 8, reused 0, downloaded 8, added 8, done
[14:03:33.646] .../node_modules/@prisma/engines postinstall$ node scripts/postinstall.js
[14:03:34.710] .../node_modules/@prisma/engines postinstall: Done
[14:03:34.827] .../node_modules/prisma preinstall$ node scripts/preinstall-entry.js
[14:03:34.876] .../node_modules/prisma preinstall: Done
[14:03:34.928] .../node_modules/@prisma/client postinstall$ node scripts/postinstall.js
[14:03:35.549] .../node_modules/@prisma/client postinstall: Prisma schema loaded from prisma/schema.prisma
[14:03:35.900] .../node_modules/@prisma/client postinstall: ✔ Generated Prisma Client (v5.15.0-dev.50) to ./node_modules/.pnpm/@prisma+client@5.15.0-dev.50_prisma@5.15.0-dev.50/node_modules/@prisma/client in 36ms
[14:03:35.900] .../node_modules/@prisma/client postinstall: Start using Prisma Client
[14:03:35.901] .../node_modules/@prisma/client postinstall: ```
[14:03:35.901] .../node_modules/@prisma/client postinstall: import { PrismaClient } from '@prisma/client'
[14:03:35.901] .../node_modules/@prisma/client postinstall: const prisma = new PrismaClient()
[14:03:35.901] .../node_modules/@prisma/client postinstall: ```
[14:03:35.901] .../node_modules/@prisma/client postinstall: More information: https://pris.ly/d/client
[14:03:35.902] .../node_modules/@prisma/client postinstall: ┌─────────────────────────────────────────────────────────────┐
[14:03:35.902] .../node_modules/@prisma/client postinstall: │  Deploying your app to serverless or edge functions?        │
[14:03:35.902] .../node_modules/@prisma/client postinstall: │  Try Prisma Accelerate for connection pooling and caching.  │
[14:03:35.902] .../node_modules/@prisma/client postinstall: │  https://pris.ly/cli/--accelerate                           │
[14:03:35.903] .../node_modules/@prisma/client postinstall: └─────────────────────────────────────────────────────────────┘
[14:03:36.101] .../node_modules/@prisma/client postinstall: Done
[14:03:36.306] 
[14:03:36.306] dependencies:
[14:03:36.310] - @prisma/adapter-planetscale 5.15.0-dev.48
[14:03:36.311] + @prisma/adapter-planetscale 5.15.0-dev.50
[14:03:36.311] - @prisma/client 5.15.0-dev.48
[14:03:36.311] + @prisma/client 5.15.0-dev.50
[14:03:36.311] 
[14:03:36.311] devDependencies:
[14:03:36.311] - prisma 5.15.0-dev.48
[14:03:36.311] + prisma 5.15.0-dev.50
[14:03:36.312] 
[14:03:36.455] 
[14:03:36.456] > planetscale-vercel-nextjs-edgemw@ postinstall /vercel/path0
[14:03:36.456] > prisma generate
[14:03:36.456] 
[14:03:37.433] Prisma schema loaded from prisma/schema.prisma
[14:03:37.811] 
[14:03:37.811] ✔ Generated Prisma Client (v5.15.0-dev.50) to ./node_modules/.pnpm/@prisma+client@5.15.0-dev.50_prisma@5.15.0-dev.50/node_modules/@prisma/client in 36ms
[14:03:37.811] 
[14:03:37.811] Start using Prisma Client
[14:03:37.811] ```
[14:03:37.812] import { PrismaClient } from '@prisma/client'
[14:03:37.812] const prisma = new PrismaClient()
[14:03:37.812] ```
[14:03:37.812] 
[14:03:37.812] More information: https://pris.ly/d/client
[14:03:37.812] 
[14:03:37.812] ┌─────────────────────────────────────────────────────────────┐
[14:03:37.812] │  Deploying your app to serverless or edge functions?        │
[14:03:37.812] │  Try Prisma Accelerate for connection pooling and caching.  │
[14:03:37.812] │  https://pris.ly/cli/--accelerate                           │
[14:03:37.812] └─────────────────────────────────────────────────────────────┘
[14:03:37.812] 
[14:03:38.011] Done in 8.6s
[14:03:38.031] Detected Next.js version: 14.2.3
[14:03:38.040] Running "pnpm run build"
[14:03:38.531] 
[14:03:38.531] > planetscale-vercel-nextjs-edgemw@ build /vercel/path0
[14:03:38.532] > next build
[14:03:38.532] 
[14:03:39.214]   ▲ Next.js 14.2.3
[14:03:39.215] 
[14:03:39.215]    Linting and checking validity of types ...
[14:03:39.420]    Creating an optimized production build ...
[14:03:46.546]  ⚠ Compiled with warnings
[14:03:46.546] 
[14:03:46.547] ./node_modules/.pnpm/@prisma+debug@5.15.0-dev.50/node_modules/@prisma/debug/dist/index.js
[14:03:46.547] A Node.js API is used (process.stdout at line: 68) which is not supported in the Edge Runtime.
[14:03:46.547] Learn more: https://nextjs.org/docs/api-reference/edge-runtime
[14:03:46.547] 
[14:03:46.547] Import trace for requested module:
[14:03:46.547] ./node_modules/.pnpm/@prisma+debug@5.15.0-dev.50/node_modules/@prisma/debug/dist/index.js
[14:03:46.547] ./node_modules/.pnpm/@prisma+driver-adapter-utils@5.15.0-dev.50/node_modules/@prisma/driver-adapter-utils/dist/index.mjs
[14:03:46.547] ./node_modules/.pnpm/@prisma+adapter-planetscale@5.15.0-dev.50_@planetscale+database@1.18.0/node_modules/@prisma/adapter-planetscale/dist/index.mjs
[14:03:46.547] 
[14:03:46.547] ./node_modules/.pnpm/@prisma+debug@5.15.0-dev.50/node_modules/@prisma/debug/dist/index.js
[14:03:46.548] A Node.js API is used (process.stdout at line: 68) which is not supported in the Edge Runtime.
[14:03:46.548] Learn more: https://nextjs.org/docs/api-reference/edge-runtime
[14:03:46.548] 
[14:03:46.548] Import trace for requested module:
[14:03:46.548] ./node_modules/.pnpm/@prisma+debug@5.15.0-dev.50/node_modules/@prisma/debug/dist/index.js
[14:03:46.548] ./node_modules/.pnpm/@prisma+driver-adapter-utils@5.15.0-dev.50/node_modules/@prisma/driver-adapter-utils/dist/index.mjs
[14:03:46.548] ./node_modules/.pnpm/@prisma+adapter-planetscale@5.15.0-dev.50_@planetscale+database@1.18.0/node_modules/@prisma/adapter-planetscale/dist/index.mjs
[14:03:46.548] 
[14:03:46.548] ./node_modules/.pnpm/@prisma+debug@5.15.0-dev.50/node_modules/@prisma/debug/dist/index.js
[14:03:46.549] A Node.js API is used (process.stderr at line: 146) which is not supported in the Edge Runtime.
[14:03:46.549] Learn more: https://nextjs.org/docs/api-reference/edge-runtime
[14:03:46.549] 
[14:03:46.549] Import trace for requested module:
[14:03:46.549] ./node_modules/.pnpm/@prisma+debug@5.15.0-dev.50/node_modules/@prisma/debug/dist/index.js
[14:03:46.549] ./node_modules/.pnpm/@prisma+driver-adapter-utils@5.15.0-dev.50/node_modules/@prisma/driver-adapter-utils/dist/index.mjs
[14:03:46.549] ./node_modules/.pnpm/@prisma+adapter-planetscale@5.15.0-dev.50_@planetscale+database@1.18.0/node_modules/@prisma/adapter-planetscale/dist/index.mjs
[14:03:46.549] 
[14:03:46.549] ./node_modules/.pnpm/@prisma+debug@5.15.0-dev.50/node_modules/@prisma/debug/dist/index.js
[14:03:46.550] A Node.js API is used (process.stderr at line: 146) which is not supported in the Edge Runtime.
[14:03:46.550] Learn more: https://nextjs.org/docs/api-reference/edge-runtime
[14:03:46.550] 
[14:03:46.550] Import trace for requested module:
[14:03:46.550] ./node_modules/.pnpm/@prisma+debug@5.15.0-dev.50/node_modules/@prisma/debug/dist/index.js
[14:03:46.550] ./node_modules/.pnpm/@prisma+driver-adapter-utils@5.15.0-dev.50/node_modules/@prisma/driver-adapter-utils/dist/index.mjs
[14:03:46.550] ./node_modules/.pnpm/@prisma+adapter-planetscale@5.15.0-dev.50_@planetscale+database@1.18.0/node_modules/@prisma/adapter-planetscale/dist/index.mjs
[14:03:46.550] 
[14:03:46.551] ./node_modules/.pnpm/@prisma+debug@5.15.0-dev.50/node_modules/@prisma/debug/dist/index.js
[14:03:46.551] A Node.js API is used (process.stderr at line: 150) which is not supported in the Edge Runtime.
[14:03:46.551] Learn more: https://nextjs.org/docs/api-reference/edge-runtime
[14:03:46.551] 
[14:03:46.551] Import trace for requested module:
[14:03:46.551] ./node_modules/.pnpm/@prisma+debug@5.15.0-dev.50/node_modules/@prisma/debug/dist/index.js
[14:03:46.551] ./node_modules/.pnpm/@prisma+driver-adapter-utils@5.15.0-dev.50/node_modules/@prisma/driver-adapter-utils/dist/index.mjs
[14:03:46.552] ./node_modules/.pnpm/@prisma+adapter-planetscale@5.15.0-dev.50_@planetscale+database@1.18.0/node_modules/@prisma/adapter-planetscale/dist/index.mjs
[14:03:46.552] 
[14:03:50.097]  ✓ Compiled successfully
[14:03:50.098]    Collecting page data ...
[14:03:50.517]    Generating static pages (0/2) ...
[14:03:50.927]  ✓ Generating static pages (2/2)
[14:03:51.068]    Finalizing page optimization ...
[14:03:51.068]    Collecting build traces ...
[14:03:57.353] 
[14:03:57.373] Route (pages)                             Size     First Load JS
[14:03:57.374] ┌ ○ /404                                  180 B          78.3 kB
[14:03:57.374] └ ƒ /api                                  0 B            78.1 kB
[14:03:57.374] + First Load JS shared by all             78.1 kB
[14:03:57.374]   ├ chunks/framework-a85322f027b40e20.js  45.2 kB
[14:03:57.374]   ├ chunks/main-d0d7919c01510df0.js       32 kB
[14:03:57.374]   └ other shared chunks (total)           906 B
[14:03:57.375] 
[14:03:57.375] ƒ Middleware                              71.9 kB
[14:03:57.375] 
[14:03:57.375] ○  (Static)   prerendered as static content
[14:03:57.375] ƒ  (Dynamic)  server-rendered on demand
[14:03:57.375] 
[14:03:57.459] Traced Next.js server files in: 36.518ms
[14:03:57.496] Created all serverless functions in: 36.382ms
[14:03:57.708] Collected static files (public/, static/, .next/static): 2.745ms
[14:03:57.732] Build Completed in /vercel/output [29s]
[14:03:57.839] Deploying outputs...
[14:03:57.840] Injected preview comments into the build output, you can disable this in your project settings.
[14:04:06.237] 
[14:04:06.681] Deployment completed
[14:04:13.605] Uploading build cache [131.59 MB]...
[14:04:17.284] Build cache uploaded: 3.679s
```

</details>

### How to reproduce

- Deploy https://github.com/prisma/ecosystem-tests/tree/dev/driver-adapters-wasm/planetscale-vercel-nextjs-edgemw 
- Check the build logs on Vercel

### Expected behavior

No warning, or at least, less warnings.

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
prisma                  : 5.15.0-dev.50
@prisma/client          : 5.15.0-dev.50
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.14.0
Query Engine (Node-API) : libquery-engine 64bb6b95cbf89b742d0a4cbcbebffc973942e7ad (at node_modules/.pnpm/@prisma+engines@5.15.0-dev.50/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 64bb6b95cbf89b742d0a4cbcbebffc973942e7ad (at node_modules/.pnpm/@prisma+engines@5.15.0-dev.50/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.15.0-16.64bb6b95cbf89b742d0a4cbcbebffc973942e7ad
Default Engines Hash    : 64bb6b95cbf89b742d0a4cbcbebffc973942e7ad
Studio                  : 0.500.0
Preview Features        : driverAdapters
```

### PR DESCRIPTION
**Pull request by jkomyno**
This PR fixes https://github.com/prisma/prisma/issues/24346.

It replaces `process.stderr.write('SOME LOG STRING' + '\n')` with `console.warn('SOME LOG STRING')` (when `console.warn` is available) or with `console.log('SOME LOG STRING')` as a backup plan.

This is needed to avoid confusing warnings in Next.js (especially when using middlewares + Edge functions), due to:
- The lack of `process` / `node:process` support: https://nextjs.org/docs/pages/api-reference/edge
- The conservative warning emitted by Next.js when encountering `process` during the Webpack compilation: https://github.com/vercel/next.js/blob/303d155c08a343ca9c45c80be216417bbe7a0cc2/packages/next/src/build/webpack/plugins/middleware-plugin.ts#L368-L370

Moreover, in https://github.com/prisma/prisma/pull/24686/commits/9cd3e4b081e1c763df3027d8004bb28a1ec0a21c, I removed the need for `node:util`.

### CODE REVIEW

**Comment by jkomyno** [comment]
TODO: paste ecosystem-tests' action link of a Vercel build passing without warnings, once https://github.com/prisma/prisma/issues/24673 is fixed.

**Comment by jkomyno** [comment]
This is the `next build` output when combining this PR with https://github.com/prisma/prisma/pull/24711 (which fixes a Next regression + ecosystem-tests failures related to Next.js):

Screenshot 2024-07-05 at 15 19 58

This demonstrates that this PR indeed fixes https://github.com/prisma/prisma/issues/24346.

File: packages/debug/src/index.ts [hunk 1]
```diff
@@ -61,30 +60,20 @@ const topProps = {
...
-        } catch (e) {
-          logger = console.warn ?? console.log
-        }
+    const baseLogger = console.warn ?? console.log
+
+    const logWithFormatting = (() => {
+      try {
+        // TODO: try and see whether `require('node:util')` works in React Native.
+        const util = require(`${'util'}`)
+        return (...innerArgs: unknown[]) => baseLogger(`${util.format(...innerArgs)}`)
```
Comment (SevInf) [inline packages/debug/src/index.ts:69]: I think you don't need to manually call `util.format` if you are using `console` methods

**Review by SevInf — APPROVED** [review]
Good after checking if we can get rid of `util.format`

File: packages/debug/src/__tests__/debug.extended.test.ts [hunk 2]
```diff
@@ -1,5 +1,14 @@
+import * as useDebugImport from '../index'
+
+let Debug: typeof useDebugImport.default
```
Comment (SevInf) [inline packages/debug/src/__tests__/debug.extended.test.ts:3]: Do we need to be global or can `importDebug` simply return it?

Comment (SevInf) [reply packages/debug/src/__tests__/debug.extended.test.ts:3]: Alternatively, i think `importDebug` can be called in `beforeEach`?

Comment (jkomyno) [reply packages/debug/src/__tests__/debug.extended.test.ts:3]: I had to run a few iterations on that regard, but `importDebug` should be called after `beforeEach`, due to `process.env` shenanigans happening in the module scope, and each test mingling with `process.env` writes
