### PR TITLE
fix(client): 2.29.1 fixes

### LINKED ISSUE #128: Cannot find namespace 'debug' in 2.29.0
```
+ pnpm recursive run build
Scope: all 5 workspace projects
packages/engines-version build$ tsc -d
packages/get-platform build$ tsc -d
packages/engines-version build: Done
packages/get-platform build: Done
packages/fetch-engine build$ tsc -d
Error: packages/fetch-engine build: ../../node_modules/.pnpm/@prisma+debug@2.29.0/node_modules/@prisma/debug/dist/index.d.ts(2,44): error TS2503: Cannot find namespace 'debug'.
packages/fetch-engine build: Failed
undefined
/home/runner/work/engines-wrapper/engines-wrapper/packages/fetch-engine:
 ERROR  @prisma/fetch-engine@2.29.0-34.1be4cd60b89afa04b192acb1ef47758a39810f3a build: `tsc -d`
Exit status 2
```

### LINKED ISSUE #8717: Interactive transactions not working with `$queryRaw` and `$executeRaw` in 2.29.0
### Bug description

The `transactionId` cannot get passed down from the proxied client to `$queryRaw` and `$executeRaw`'s custom promises.

### Expected behavior

_No response_

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
2.29.0
```

### LINKED ISSUE #8718: Calling `.catch()` or `.finally()` on a prisma client model query does not fire the request in 2.29.0
### Bug description

await `prisma.user.create({data: {email: 'test@test.io'}}).catch(() => {})` doesn't fire the request anymore in `2.29.0`

### Expected behavior

_No response_

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
2.29.0
```

### PR DESCRIPTION
**Pull request by millsp**
Fixes https://github.com/prisma/engines-wrapper/issues/128
Fixes https://github.com/prisma/prisma/issues/8717
Fixes https://github.com/prisma/prisma/issues/8718

### CODE REVIEW

File: packages/client/src/runtime/getPrismaClient.ts [hunk 1]
```diff
@@ -1314,15 +1310,19 @@ new PrismaClient({
           plural: true,
           aggregate: true,
           groupBy: true,
+          count: true,
```
Comment (millsp) [inline packages/client/src/runtime/getPrismaClient.ts:1313]:
```suggestion
```

**Review by Jolg42 — APPROVED** [review]
Let's patch this!

**Comment by PabloSzx** [comment]
is 2.29.1 going to be released?
