### PR TITLE
fix: postinstall trigger in yarn workspace

### LINKED ISSUE #5299: Fix yarn workspace
Tracking issue for https://github.com/prisma/prisma/issues/5266#issuecomment-767656190

Clone blitz-js/blitz
```
yarn
yarn build
cd examples/auth
blitz start
# Open page in browser
# See Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
```

### PR DESCRIPTION
**Pull request by williamluke4**
closes https://github.com/prisma/prisma/issues/5299

### CODE REVIEW

File: src/packages/client/src/generation/generateClient.ts [hunk 1]
```diff
@@ -157,6 +160,8 @@ export async function generateClient({
     ? await getDotPrismaDir(outputDir)
     : outputDir
 
+  console.log({finalOutputDir, outputDir, generator});
```
Comment (timsuchanek) [inline src/packages/client/src/generation/generateClient.ts:163]:
```suggestion
  console.log({finalOutputDir, outputDir, generator});
```

**Review by timsuchanek — DISMISSED** [review]

File: src/packages/client/src/generation/generateClient.ts (hunk 1 above)
Comment (williamluke4) [inline src/packages/client/src/generation/generateClient.ts:163]:
```suggestion
```

Comment (williamluke4) [reply src/packages/client/src/generation/generateClient.ts]: Removed

**Comment by williamluke4** [comment]
Confirmed by Brandon that this worked

File: src/packages/cli/src/__tests__/generate.test.ts [hunk 2]
```diff
@@ -3,7 +3,7 @@ import { consoleContext, Context } from './__helpers__/context'
 
 const ctx = Context.new().add(consoleContext()).assemble()
 
-it('should work with a custom output dir', async () => {
+it.skip('should work with a custom output dir', async () => {
```
Comment (timsuchanek) [inline src/packages/cli/src/__tests__/generate.test.ts:6]: Please remove

File: src/packages/cli/src/__tests__/generate.test.ts [hunk 3]
```diff
@@ -16,7 +16,7 @@ it('should work with a custom output dir', async () => {
   await expect(main()).resolves.toMatchSnapshot()
 }, 10000)
 
-it('should error with exit code 1 with incorrect schema', async () => {
+it.skip('should error with exit code 1 with incorrect schema', async () => {
```
Comment (timsuchanek) [inline src/packages/cli/src/__tests__/generate.test.ts:19]: Please remove

File: src/packages/client/src/generation/generateClient.ts [hunk 4]
```diff
@@ -110,6 +110,9 @@ export async function buildClient({
 }
 
 async function getDotPrismaDir(outputDir: string): Promise<string> {
+  if(outputDir.endsWith('node_modules/@prisma/client')){
```
Comment (timsuchanek) [inline src/packages/client/src/generation/generateClient.ts:113]: Please use prettier

File: src/packages/client/scripts/postinstall.js [hunk 5]
```diff
@@ -9,6 +10,25 @@ const copyFile = promisify(fs.copyFile)
...
+  if (process.env.DEBUG && process.env.DEBUG.includes('postinstall')) {
+    console.log(message, ...optionalParams)
+  }
+}
+
+/**
+ * This replicates the exception of `fs.mkdir` with native the
+ * `recusive` option when run on an invalid drive under Windows.
+ **/
+function permissionError(pth) {
```
Comment (timsuchanek) [inline src/packages/client/scripts/postinstall.js:23]: Can this be cleaned up?

File: src/packages/client/scripts/postinstall.js [hunk 6]
```diff
@@ -9,6 +10,12 @@ const copyFile = promisify(fs.copyFile)
 const mkdir = promisify(fs.mkdir)
 const stat = promisify(fs.stat)
 
+function debug(message, ...optionalParams) {
+  if (process.env.DEBUG && process.env.DEBUG.includes('postinstall')) {
```
Comment (Jolg42) [inline src/packages/client/scripts/postinstall.js:14]:
```suggestion
  if (process.env.DEBUG && process.env.DEBUG === 'prisma:postinstall') {
```

File: src/packages/client/scripts/postinstall.js [hunk 7]
```diff
@@ -22,7 +29,18 @@ async function main() {
 
   // this is needed, so that the Generate command does not fail in postinstall
   process.env.PRISMA_GENERATE_IN_POSTINSTALL = 'true'
-
+  if (localPath) {
+    // localPath = xxxx/custom-server/node_modules/prisma/build/index.js
+    // packageRoot = xxxx/custom-server/
+    const packageRoot = localPath && path.join(localPath, '../../../../')
```
Comment (Jolg42) [inline src/packages/client/scripts/postinstall.js:35]: this should always be the value "true"?

localPath if checked just before in the if

path.join(localPath, '../../../../') is noop, returns a truthy string.

so `PRISMA_GENERATE_IN_POSTINSTALL = packageRoot` means = true? Is that intended like this?

Comment (williamluke4) [reply src/packages/client/scripts/postinstall.js]: So I have made some changes to this logic. I just realized that if people are still using `@prisma/cli` this would not resolve the correct path. Might be worth using some logic from `pkg-up` here.

Comment (williamluke4) [reply src/packages/client/scripts/postinstall.js]: I will implement that when I get in tomorrow morning

Comment (Jolg42) [reply src/packages/client/scripts/postinstall.js]: Ok 💯

**Comment by williamluke4** [comment]
@Jolg42 Just tested this again locally in the blitz repo and it looks good to go.

**Comment by williamluke4** [comment]
Let's wait on this https://github.com/prisma/e2e-tests/actions/runs/613449058

**Review by Jolg42 — APPROVED** [review]
Nice! Thanks for the new pass!

**Review by Jolg42 — DISMISSED** [review]
Looks like it’s broken in codesandbox e2e test https://github.com/prisma/e2e-tests/runs/2011990612?check_suite_focus=true

```
Error: FetchError: invalid json response body at 0nilk.sse.codesandbox.io reason: Unexpected token < in JSON at position 0
    at /home/runner/work/e2e-tests/e2e-tests/platforms/codesandbox/deploy.ts:49:11
    at step (/home/runner/work/e2e-tests/e2e-tests/platforms/codesandbox/deploy.ts:44:23)
    at Object.throw (/home/runner/work/e2e-tests/e2e-tests/platforms/codesandbox/deploy.ts:25:53)
    at rejected (/home/runner/work/e2e-tests/e2e-tests/platforms/codesandbox/deploy.ts:17:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Sleeping for 5 sec
```

`Unexpected token < in JSON at position 0` is likely a timeout error page from Cloudflare (what I got when I opened the page in my browser after a while)

**Comment by Jolg42** [comment]
Passing now in https://github.com/prisma/e2e-tests/runs/2012799937?check_suite_focus=true after rebase in e2e repo
